import type { RichArticle } from './article-data';

type Topic = {
  slug: string; title: string; description: string; focus: string; decision: string;
  failure: string; example: string; check: string; owner: string; question: string;
};

const source = { name: 'International Labour Organization: Decent work and the care economy', url: 'https://www.ilo.org/topics-and-sectors/care-economy', note: 'Context for clear responsibilities and accountable work arrangements.' };

const topics: Topic[] = [
  { slug: 'august23-philippines-hr-employee-file-access-review', title: 'Philippines HR employee files: review access before the first handoff', description: 'Review employee-file access for a Philippines-based HR support lane so routine administration stays useful without giving the support role an undefined view of sensitive records.', focus: 'employee-file access review', decision: 'which records a support role may view, edit, or route', failure: 'granting broad access because the queue is inconvenient to split', example: 'a coordinator who needs one approved onboarding form but can also browse unrelated employee files', check: 'the access list matches the task list, named account, reviewer, and expiry or review date', owner: 'the company HR or security owner', question: 'Which exact record does the task require, and what is the smallest view that permits the work?' },
  { slug: 'august23-philippines-hr-offer-letter-version-control', title: 'Philippines HR offer letters: control the version before sending', description: 'Control offer-letter versions in a Philippines-based recruiting support workflow while the hiring owner retains authority over terms, approvals, and candidate communication.', focus: 'offer-letter version control', decision: 'which approved terms and message may be sent to a candidate', failure: 'treating the newest attachment as approved simply because it has a recent timestamp', example: 'a draft with a corrected start date beside an older file that still contains the approved signature block', check: 'the source, version, approver, recipient, and send permission are visible together', owner: 'the hiring owner and authorized HR reviewer', question: 'What evidence shows that this exact version, for this candidate, is approved for release?' },
  { slug: 'august23-philippines-hr-leave-balance-reconciliation', title: 'Philippines HR leave balances: reconcile the source before answering', description: 'Reconcile leave-balance inputs in a Philippines-based HR support lane without turning a spreadsheet comparison into an eligibility or policy decision.', focus: 'leave-balance reconciliation', decision: 'which balance and rule the authorized HR owner should use', failure: 'answering from a familiar spreadsheet while the system of record has changed', example: 'a balance that differs because an approved leave entry and a payroll cutoff belong to different windows', check: 'the period, source, adjustment, reviewer, and unresolved difference are recorded', owner: 'the company HR or payroll owner', question: 'Which period and approved source control this answer, and what remains uncertain?' },
  { slug: 'august23-philippines-hr-employee-survey-response-routing', title: 'Philippines HR employee surveys: route responses without exposing the record', description: 'Route employee-survey responses through a narrow, privacy-conscious workflow while qualified owners decide what requires follow-up and what should remain aggregated.', focus: 'employee-survey response routing', decision: 'which owner should receive a concern and what information is necessary', failure: 'copying a detailed response into a broad queue for convenience', example: 'a small-team comment that appears anonymous but includes enough context to identify the writer', check: 'the response is minimized, access-limited, and routed with an explicit reason', owner: 'the HR owner responsible for the survey and any sensitive follow-up', question: 'What is the least information needed for the named owner to act responsibly?' },
  { slug: 'august23-philippines-hr-new-hire-paperwork-exception-log', title: 'Philippines HR new-hire paperwork: use an exception log that owners can act on', description: 'Build a new-hire paperwork exception log for a Philippines-based HR support lane that separates missing evidence from an owner decision about what to do next.', focus: 'new-hire paperwork exception logging', decision: 'whether a missing item can wait, needs correction, or requires an owner decision', failure: 'marking a packet complete because most fields look filled in', example: 'a signed form whose identity field does not match the approved hiring record', check: 'each exception names the missing evidence, risk, owner, due time, and permitted next step', owner: 'the hiring and HR owners', question: 'Is this a missing document, a data mismatch, or a decision that the support role cannot make?' },
  { slug: 'august23-philippines-hr-manager-absence-handoff', title: 'Philippines HR manager absence handoffs: make temporary ownership explicit', description: 'Prepare a manager-absence handoff for Philippines-based HR support without allowing a temporary delegate to inherit decisions that were never assigned.', focus: 'manager-absence handoff', decision: 'who may approve, answer, or escalate each HR workstream during an absence', failure: 'using an out-of-office message as if it transferred every HR authority', example: 'a routine calendar request arriving beside a sensitive complaint while the usual manager is away', check: 'the delegate, scope, start and end time, backup owner, and excluded decisions are written down', owner: 'the company manager or HR authority assigning the coverage', question: 'Which authority moved, for how long, and which questions still require the original owner?' },
  { slug: 'august23-philippines-hr-policy-change-acknowledgment', title: 'Philippines HR policy changes: track acknowledgment without interpreting the rule', description: 'Track policy-change acknowledgments in a Philippines-based HR workflow while the company keeps responsibility for policy meaning, rollout decisions, and exceptions.', focus: 'policy-change acknowledgment tracking', decision: 'which version applies and how an employee response should be handled', failure: 'using a reminder tracker as proof that an employee understood or accepted a policy', example: 'two acknowledgments tied to different versions after a policy page was updated', check: 'the version, audience, delivery record, response, and exception owner are distinct fields', owner: 'the company HR or policy owner', question: 'Are we proving delivery, receipt, acknowledgment, or something stronger that requires an owner judgment?' },
  { slug: 'august23-philippines-hr-recruiting-requisition-intake', title: 'Philippines HR recruiting requisitions: check the intake before opening the queue', description: 'Prepare recruiting requisitions through a complete intake in a Philippines-based support lane while hiring owners retain headcount, role, and selection authority.', focus: 'recruiting requisition intake', decision: 'whether the requisition is approved, complete, and ready for recruiting work', failure: 'starting outreach from a request that has no confirmed owner or approved role scope', example: 'a forwarded manager note that names a title but omits the hiring plan, location, or approval path', check: 'the requisition has a named owner, approved role brief, intake date, and explicit next action', owner: 'the hiring manager and company recruiting owner', question: 'What authorizes this requisition, and who can change its scope after work begins?' },
  { slug: 'august23-philippines-hr-payroll-cutoff-checklist', title: 'Philippines HR payroll cutoffs: separate preparation from approval', description: 'Prepare a payroll-cutoff checklist for a Philippines-based HR support workflow without letting reconciliation work become a payroll or compensation decision.', focus: 'payroll-cutoff preparation', decision: 'which changes are approved for the payroll run and which require correction', failure: 'silently fixing a mismatch so a deadline appears to have been met', example: 'a manager change arriving after the cutoff beside a time record that uses the prior manager', check: 'the cutoff, source, proposed change, approver, exception, and final release owner are visible', owner: 'the company payroll and HR owners', question: 'What changed, when did it become effective, and who approved inclusion in this run?' },
  { slug: 'august23-philippines-hr-employee-contact-update', title: 'Philippines HR employee contact updates: preserve the old value and the source', description: 'Route employee contact updates with provenance and effective dates in a Philippines-based HR administration lane while the owner controls the authoritative record.', focus: 'employee contact-update routing', decision: 'whether a requested contact change is authorized and when it becomes effective', failure: 'overwriting a phone number or address without preserving the source and prior value', example: 'a request from a personal email that conflicts with a recent approved form', check: 'the old value, proposed value, source, identity check, effective date, and approver are recorded', owner: 'the company HR records owner', question: 'What proves the requester is authorized, and what date should the approved change take effect?' },
  { slug: 'august23-philippines-hr-employee-complaint-intake-minimization', title: 'Philippines HR complaint intake: minimize the record before routing', description: 'Design a careful complaint-intake lane for Philippines-based HR support that preserves the signal needed by the right owner without investigating or deciding the complaint.', focus: 'complaint-intake minimization', decision: 'which qualified owner should receive the concern and what immediate safeguard applies', failure: 'asking a support coordinator to investigate because the first message lacks context', example: 'a short complaint that includes health, family, or identity details unrelated to the first routing decision', check: 'the intake captures the route, urgency, essential facts, and owner without unnecessary narrative', owner: 'the designated HR, employee-relations, or safeguarding owner', question: 'What must the receiving owner know now, and what detail should not be copied further?' },
  { slug: 'august23-philippines-hr-people-ops-weekly-review', title: 'Philippines HR people operations: run a weekly review from named sources', description: 'Run a weekly people-operations review for a Philippines-based support lane with defined source fields, visible exceptions, and an owner who explains the result.', focus: 'weekly people-operations review', decision: 'which snapshot and definitions control the review conversation', failure: 'explaining a trend before the period, population, and source records are frozen', example: 'a headcount change that appears to be a hiring result but is actually a late status update', check: 'each number has a source, period, definition, reviewer, and unresolved exception', owner: 'the company people-operations or HR reporting owner', question: 'What exactly does this number count, and what source or exception could change the interpretation?' }
];

const paragraph = (t: Topic, n: number): string => [
  `A Philippines-based HR support role can handle ${t.focus} when the company defines the queue as preparation and control rather than delegated judgment. Begin with the business question: ${t.question} The answer should be visible in the role brief before anyone receives a live record. A useful brief names the approved intake channel, the records the worker may consult, the output expected from the worker, the person who reviews it, and the point where work stops. This level of detail matters because routine HR administration often sits next to employment, privacy, payroll, recruiting, or security decisions. The support role can make the path easier to follow, but it should not quietly become the authority for the decision at the end of the path.`,
  `The first control is a source map. List each system, form, message, calendar, or document that may be used for ${t.focus}, then state whether it is authoritative, supporting, or only a lead to investigate. Record the source date and the person responsible for changing it. A recent file is not automatically the controlling record, and a familiar sender is not proof of authority. For ${t.focus}, the company should decide how to handle a conflict rather than asking the coordinator to choose the most plausible version. The coordinator can preserve the conflict, label it clearly, and send a short question to ${t.owner}. That keeps an uncertain item visible instead of allowing an unrecorded guess to enter the employee file or queue history.`,
  `Use a narrow status vocabulary for ${t.focus}. Received means the item arrived. Ready means the required information is present for the support step. Waiting means a named person must respond. Escalated means the question crossed the role boundary or carries a defined risk. Closed means the approved action and its evidence are recorded. These labels prevent a reminder from looking like an approval and prevent a prepared draft from looking like a completed decision. Add the received time, next due time, current owner, and approved destination to every item. If the item is missing information, describe the gap without blaming the requester. The record should help the next reviewer understand what happened without repeating sensitive detail that does not affect the next action.`,
  `The central risk in this lane is ${t.failure}. The control is not a longer checklist by itself. It is a separation between what the Philippines team prepares and what ${t.owner} decides. The team may compare values, identify a missing field, draft an approved reminder, assemble a packet, and report an exception. It should not interpret a policy from memory, promise an outcome, investigate a complaint, choose a candidate, approve compensation, change a status, or give legal advice. Put these stop rules in the queue instructions and practice them with redacted examples. A worker who stops at the right point has completed the assigned control, even when the item remains open for an owner decision.`,
  `A realistic test for ${t.focus} should include ${t.example}. Add a complete ordinary item, a duplicate, a late change, a conflicting source, and a message that contains more personal information than the task requires. Ask the reviewer to identify the source, permitted preparation, stop point, recipient, and closeout proof for each example. Do not score the worker only on speed or the number of items closed. Score whether the item reached the right owner, whether the source remained intact, whether the notes were minimized, and whether the final state can be reconstructed. If two reviewers would route the same example differently, the operating rule needs clarification before volume increases.`,
  `Access should follow the smallest useful task. For ${t.focus}, a worker may need a queue view, a controlled folder, a calendar, or a redacted report. That does not imply a need to browse every employee file, export a full directory, edit an authoritative record, or administer a system. Use named accounts, approved storage, and a review date for access. If the work expands to a new record type or a new tool, pause for an access decision. Keep training examples redacted and do not paste employee narratives into unapproved drafting tools. The owner should know who can view the item, where a draft is stored, how a correction is made, and when an access need ends.`,
  `Close ${t.focus} with a proof statement that is narrower than a marketing claim. Say what source was checked, what comparison or preparation occurred, who approved the next step, where the result was stored, and when the item changed status. Do not claim compliance, fairness, eligibility, accuracy, employee satisfaction, hiring quality, or legal sufficiency unless an authorized owner has made that separate conclusion from suitable evidence. For this company’s HR outsourcing guidance, practical detail is useful only when the boundary is honest. A record that says “missing approval routed to the HR owner at 14:00” is stronger than “approved and complete” when the owner has not yet answered.`,
  `Review the first pilot of ${t.focus} with the owner who will live with its consequences. Count wrong destinations, missing evidence, duplicate work, late responses, unnecessary access, and correct stops. Then change the form, queue label, example, or escalation note that caused the repeat issue. Do not solve a weak process by broadening the support role without review. A Philippines-based team can make recurring HR administration steadier when the company gives it a clear lane and a dependable handoff. Employers use different systems, policies, privacy practices, and approval chains, so the final role brief must be checked against the company’s own records and qualified advice.`,
  `The practical starting point is small: one queue, one named reviewer, one approved destination, and a short set of redacted examples. For ${t.focus}, agree on how quickly the owner responds, what happens when the owner is unavailable, and who receives an urgent exception. Put the answer in the workflow rather than leaving it in a private conversation. After the review window, the company can decide whether to expand the queue, narrow it, or hand the work back. That decision belongs to the company. The support role supplies evidence about the workflow; it does not decide that the workflow is safe, lawful, or complete on its own.`
][n];

function makeArticle(t: Topic, index: number): RichArticle {
  const sections = [
    { heading: `Define ${t.focus} as a bounded lane`, paragraphs: [paragraph(t, 0), paragraph(t, 1)] },
    { heading: 'Give the queue statuses that match reality', paragraphs: [paragraph(t, 2), paragraph(t, 3)] },
    { heading: 'Test the exceptions before adding volume', paragraphs: [paragraph(t, 4), paragraph(t, 5)] },
    { heading: 'Close with evidence and review the boundary', paragraphs: [paragraph(t, 6), paragraph(t, 7)] }
  ];
  return {
    slug: t.slug, title: t.title, description: t.description, published: '2026-08-23', updated: '2026-08-23', minutes: 12,
    revision: `2026-08-23-${t.slug}`, directAnswer: [
      `A Philippines-based support role can prepare and track ${t.focus}, but ${t.decision} should remain with ${t.owner}.`,
      `Start with a named source, narrow access, a reviewer, and proof for each approved handoff. Escalate uncertainty instead of turning an incomplete record into an answer.`
    ],
    takeaways: [`Define the input and output for ${t.focus}.`, 'Keep the decision owner named in every queue item.', 'Use source records and approved wording.', 'Minimize sensitive information in working notes.', 'Close only when the action and evidence are visible.'],
    taskRows: [
      { lane: 'Intake', philippinesTeam: `Receive and label ${t.focus} items from the approved channel.`, owner: 'Set priority, scope, and accountable decision maker.', check: 'Source, date, owner, and risk are recorded' },
      { lane: 'Preparation', philippinesTeam: 'Check required fields and preserve conflicting versions.', owner: 'Approve exceptions and any change to the standard path.', check: 'Prepared work traces to a source' },
      { lane: 'Handoff', philippinesTeam: 'Route a precise question and send approved reminders.', owner: 'Make the decision and approve sensitive communication.', check: 'Recipient and due time are visible' },
      { lane: 'Quality', philippinesTeam: 'Review a sample and list wrong routes or missing proof.', owner: 'Accept corrections and update the operating rule.', check: 'Correction has an owner and date' },
      { lane: 'Closeout', philippinesTeam: 'Record the approved result and destination.', owner: 'Confirm retention, access, and final status.', check: 'No item closes without evidence' }
    ],
    pilotStats: [
      { value: '1', label: 'Starting queue', note: 'Keep the first lane narrow and observable.' },
      { value: '5', label: 'Test cases', note: 'Include complete, missing, duplicate, late, and conflicting inputs.' },
      { value: '1', label: 'Named reviewer', note: 'Give the sample one accountable quality owner.' },
      { value: '30', label: 'Review window', note: 'Use a defined period before changing scope.' }
    ],
    sections, scripts: [
      { label: 'Provider question', text: `Show how a Philippines-based assistant would handle ${t.focus}, including ${t.example}. What is prepared, what stops, who decides, and what proof remains?` },
      { label: 'Assistant stop rule', text: `Prepare ${t.focus} from approved sources. Stop before deciding ${t.decision}; route the question to ${t.owner}.` }
    ],
    workflow: [
      { step: '01', title: 'Map the source', text: `List inputs, authority, access, and required fields for ${t.focus}.` },
      { step: '02', title: 'Run redacted examples', text: 'Test an ordinary item and several exceptions with the owner present.' },
      { step: '03', title: 'Prepare and route', text: 'Do the permitted work, preserve uncertainty, and send precise escalations.' },
      { step: '04', title: 'Review evidence', text: 'Check source, destination, notes, access, and proof in a sample.' },
      { step: '05', title: 'Decide scope', text: 'Expand, narrow, or hand back the lane using the review record.' }
    ],
    faqs: [
      { question: `What can a Philippines-based assistant do for ${t.focus}?`, answer: `The assistant can receive, organize, compare, prepare, remind, and route approved ${t.focus} work. ${t.owner} retains the decision and exceptions.` },
      { question: 'What should stay with the company owner?', answer: `The company should retain ${t.decision}, policy interpretation, legal questions, sensitive employee conversations, and exceptions.` },
      { question: 'How should the pilot be checked?', answer: 'Review ordinary and exception cases, verify access and evidence, record corrections, and hold a scope decision at the end of the review window.' },
      { question: 'What makes the item complete?', answer: 'The source, permitted action, owner, approval, status, date, destination, and evidence should be visible in the approved system.' },
      { question: 'How should sensitive information be handled?', answer: 'Use named accounts, least-privilege access, approved storage, redacted examples, and an escalation path that minimizes the record.' }
    ],
    related: [{ title: 'HR operations support', href: '/services/operations-support', note: 'Review the matching support lane.' }, { title: 'HR reporting and QA', href: '/services/reporting-and-qa', note: 'Plan owner review and evidence.' }, { title: 'HR outsourcing planning guide', href: '/blog/human-resources-outsourced-planning', note: 'Compare task and owner boundaries.' }],
    sources: [source], heroImage: undefined
  };
}

export const august23Articles: Record<string, RichArticle> = Object.fromEntries(topics.map((topic, index) => [topic.slug, makeArticle(topic, index)]));
export const august23BlogPosts = topics.map(({ slug, title, description }) => ({ slug, title, excerpt: description, minutes: 12 }));
export const august23Manifest = topics.map(({ slug }) => ({ route: `/blog/${slug}`, sourcePath: 'app/blog/august23-batch.ts', sourcePaths: ['app/blog/august23-batch.ts'] }));
export const august23PromptReceipts = topics.map(({ slug, title, focus }) => ({ route: `/blog/${slug}`, imagePath: null, prompt: `Gemini unavailable in this workspace for ${title}; no image generated or substituted. Intended focus: ${focus}.`, status: 'blocked-provider-unavailable' }));
