import type { RichArticle } from './article-data';

export type August18BlogSeed = {
  slug: string; title: string; description: string; focus: string;
  sourceDate: '2026-08-18';
  sections: Array<[string, string, string]>;
};

const source = { name: 'National Privacy Commission of the Philippines: Data Privacy Act resources', url: 'https://privacy.gov.ph/data-privacy-act/', note: 'Context for limiting access to personal information and keeping an accountable administrative record.' };

const makeSeedSections = (focus: string, headings: string[]): Array<[string, string, string]> => headings.map((heading) => [heading, `${heading} is the first control for ${focus}. Write down the source, the action that is allowed, the person who reviews uncertainty, and the evidence that closes the task. In a Philippines-based HR support lane, the coordinator can prepare facts, check required fields, maintain status, and remind an owner. That role should not turn an incomplete record into a confident employment, pay, legal, policy, medical, or eligibility conclusion. A short boundary is useful: routine preparation continues; an exception stops and goes to the named owner.`, `For ${focus}, use a concrete example before live work begins. Show the original request, the approved system, the exact handoff, and the point where the coordinator must wait. Keep personal information in the restricted source rather than copying a narrative into a broad queue. When a date, value, identity, or instruction conflicts, preserve both sources and route the difference. This makes the record useful to an HR owner who was not present for the first conversation and prevents a tidy status field from hiding an unresolved decision.`]);

// Each entry owns its date and its article-specific editorial angles. The page
// layout is shared, but the guidance, examples, stop points, and questions are
// written for the individual HR operating problem.
const august18Raw = [
  ['philippines-hr-employee-file-retention-review', 'Philippines HR employee-file retention reviews: decide what needs attention', 'Build a review lane for employee-file retention dates, source records, and owner decisions without treating an administrative checklist as legal advice.', 'employee-file retention reviews', ['Start with the record inventory', 'Separate retention facts from legal interpretation', 'Use a restricted exception queue', 'Review access before archiving', 'Close with owner evidence', 'Test a mixed sample', 'Measure decisions, not deletion volume']],
  ['philippines-hr-new-hire-identity-access-handoff', 'Philippines HR new-hire identity and access handoffs: make the dependency visible', 'Coordinate approved identity, HR, and access tasks for a new hire while system owners retain control of provisioning and exceptions.', 'new-hire identity and access handoffs', ['Map the identity source', 'Separate HR readiness from access approval', 'Sequence dependent owners', 'Protect credentials and documents', 'Reconcile every system acknowledgement', 'Handle a late start date', 'Review the handoff record']],
  ['philippines-hr-employee-complaint-intake-routing', 'Philippines HR employee complaint intake: route the concern without rewriting it', 'Create a narrow complaint-intake route that preserves the employee’s wording, limits visibility, and sends decisions to an authorized HR owner.', 'employee complaint intake routing', ['Preserve the original concern', 'Use minimum necessary routing data', 'Define the urgent path', 'Keep intake separate from investigation', 'Track acknowledgement carefully', 'Test sensitive examples', 'Review the queue for exposure']],
  ['philippines-recruiting-candidate-reference-check-coordination', 'Philippines recruiting reference-check coordination: protect consent and source evidence', 'Coordinate approved reference-check requests, consent evidence, and follow-up without interpreting references or deciding a candidate outcome.', 'candidate reference-check coordination', ['Confirm consent before contact', 'Use the approved question set', 'Keep source and response separate', 'Route adverse or unclear material', 'Control follow-up timing', 'Reconcile the hiring record', 'Review fairness and access']],
  ['philippines-hr-benefits-enrollment-deadline-reconciliation', 'Philippines HR benefits enrollment deadlines: reconcile status without deciding eligibility', 'Track enrollment deadlines, missing documents, and carrier acknowledgements while benefits owners decide eligibility, exceptions, and advice.', 'benefits enrollment deadline reconciliation', ['Define each deadline event', 'Distinguish submitted from accepted', 'Keep eligibility with the plan owner', 'Protect dependent information', 'Reconcile carrier responses', 'Handle a missed deadline', 'Review recurring gaps']],
  ['philippines-hr-training-completion-evidence-audit', 'Philippines HR training completion evidence audits: show the gap without inventing completion', 'Audit training assignments and evidence with a source-backed checklist while managers and compliance owners decide remediation.', 'training completion evidence audits', ['Name the authoritative completion source', 'Separate assignment from completion', 'Flag exceptions neutrally', 'Restrict sensitive course details', 'Route remediation decisions', 'Test evidence variations', 'Close the audit trail']],
  ['philippines-hr-employee-master-data-change-log', 'Philippines HR employee master-data change logs: make corrections traceable', 'Maintain a change log for approved employee master-data updates with old values, sources, approvers, and downstream confirmations.', 'employee master-data change logs', ['Capture the request before editing', 'Keep old and new values distinct', 'Verify the approver', 'Map downstream systems', 'Limit copied personal data', 'Handle conflicting sources', 'Reconcile and close']],
  ['philippines-hr-leave-balance-reconciliation-support', 'Philippines HR leave-balance reconciliation: surface differences for the owner', 'Compare approved leave records with balance reports and route differences without deciding entitlement or changing balances by assumption.', 'leave-balance reconciliation support', ['Define the comparison period', 'Use approved leave as the source', 'Separate arithmetic from entitlement', 'Protect employee visibility', 'Route disputed balances', 'Document corrections', 'Review the reconciliation sample']],
  ['philippines-hr-employee-survey-response-routing', 'Philippines HR employee survey response routing: protect anonymity and action ownership', 'Route employee survey themes and urgent responses according to an approved privacy design while HR leaders decide interpretation and action.', 'employee survey response routing', ['Understand the survey promise', 'Keep identity out of broad reports', 'Define the safety escalation', 'Separate theme coding from conclusions', 'Assign action owners', 'Test small-group risk', 'Review the reporting boundary']],
  ['philippines-hr-hris-permission-review-cycle', 'Philippines HRIS permission review cycles: prove access was reviewed', 'Coordinate recurring HRIS access reviews with role lists, owner attestations, and removal evidence without granting or revoking access by assumption.', 'HRIS permission review cycles', ['Inventory roles and owners', 'Compare need with assigned access', 'Separate review from change', 'Route privileged exceptions', 'Record removal evidence', 'Handle inactive accounts', 'Set the next review']],
  ['philippines-recruiting-offer-letter-approval-routing', 'Philippines recruiting offer-letter approval routing: keep the approved terms authoritative', 'Prepare offer-letter routing from approved role and candidate inputs while recruiters and authorized leaders control terms, exceptions, and release.', 'offer-letter approval routing', ['Start from the approved requisition', 'Separate draft from approved terms', 'Protect candidate information', 'Route exceptions before release', 'Track version and delivery', 'Handle a changed start date', 'Reconcile the hiring file']],
  ['philippines-hr-employee-relocation-record-coordination', 'Philippines HR employee relocation records: coordinate updates without deciding obligations', 'Track approved relocation-related record changes and owner questions while HR, payroll, tax, and legal owners decide obligations and advice.', 'employee relocation record coordination', ['Define the request scope', 'Map affected records and owners', 'Separate logistics from advice', 'Restrict location information', 'Track effective dates', 'Route cross-border questions', 'Review the final record']],
  ['philippines-hr-disciplinary-record-access-control', 'Philippines HR disciplinary-record access controls: keep the queue narrow', 'Design a restricted administrative route for approved disciplinary records with clear viewers, sources, and escalation boundaries.', 'disciplinary-record access controls', ['Define the restricted case source', 'Use minimum routing labels', 'Keep judgment with HR', 'Control copies and exports', 'Track owner acknowledgement', 'Handle an access mistake', 'Review permissions and retention']],
  ['philippines-hr-employee-beneficiary-update-routing', 'Philippines HR beneficiary-update routing: verify the request before filing', 'Route beneficiary-update requests from an approved source to the right owner while keeping identity evidence and plan decisions separate.', 'employee beneficiary-update routing', ['Preserve the request and date', 'Use the approved verification path', 'Separate filing from eligibility', 'Protect family information', 'Track carrier or plan confirmation', 'Handle conflicting submissions', 'Close with evidence']],
  ['philippines-hr-manager-headcount-request-reconciliation', 'Philippines HR manager headcount requests: reconcile demand with approval', 'Prepare a manager headcount request record from role, timing, and business inputs while leaders retain budget and hiring approval.', 'manager headcount request reconciliation', ['Capture the requested role', 'Separate demand from authorization', 'Check the source budget record', 'Map recruiting dependencies', 'Route unclear assumptions', 'Track approval versions', 'Review the request register']],
  ['philippines-recruiting-candidate-accommodation-routing', 'Philippines recruiting candidate accommodation routing: make the handoff respectful', 'Coordinate accommodation requests with restricted details, approved contacts, and timely owner handoffs without making medical or hiring judgments.', 'candidate accommodation routing', ['Preserve the candidate request', 'Limit who sees sensitive detail', 'Use a qualified owner', 'Keep scheduling flexible', 'Track the agreed adjustment', 'Handle a last-minute request', 'Review the candidate experience']],
  ['philippines-hr-employee-record-access-request-log', 'Philippines HR employee-record access requests: define scope before retrieval', 'Log employee-record access requests with identity, purpose, scope, and approval fields before a qualified owner decides what may be released.', 'employee-record access request logs', ['Verify requester and purpose', 'Define the record scope', 'Separate retrieval from release', 'Protect third-party information', 'Track review and delivery', 'Handle an overbroad request', 'Close with a disclosure record']],
  ['philippines-hr-payroll-bank-detail-change-routing', 'Philippines HR payroll bank-detail changes: use a high-control handoff', 'Route bank-detail change requests through approved verification and separate review while payroll and finance owners control the actual change and payment risk.', 'payroll bank-detail change routing', ['Treat the request as high risk', 'Use independent verification', 'Separate preparation from approval', 'Avoid email-only confirmation', 'Reconcile the effective cycle', 'Handle a suspicious request', 'Review control evidence']],
  ['philippines-hr-policy-version-control-register', 'Philippines HR policy version-control registers: keep guidance current', 'Maintain a policy register that shows owner, version, effective date, and communication status without interpreting policy for employees or managers.', 'policy version-control registers', ['Identify the authoritative copy', 'Record version and effective date', 'Separate publication from interpretation', 'Route obsolete references', 'Track acknowledgement work', 'Handle an urgent update', 'Review the register monthly']],
  ['philippines-hr-employee-return-of-property-coordination', 'Philippines HR return-of-property coordination: reconcile custody and exceptions', 'Track approved property-return instructions, custody evidence, and open exceptions while company owners decide recovery, replacement, and dispute handling.', 'employee return-of-property coordination', ['Inventory property from the source', 'Record custody without assumptions', 'Use approved return instructions', 'Separate tracking from dispute decisions', 'Reconcile receipts and condition', 'Handle missing property', 'Close the handback record']],
  ['philippines-hr-recruiting-background-check-status-routing', 'Philippines recruiting background-check status routing: separate status from outcome', 'Track consent, vendor status, and missing steps without interpreting a report or making a hiring decision.', 'background-check status routing', ['Confirm the authorized request', 'Track status states precisely', 'Restrict report content', 'Route adverse information', 'Keep the candidate message approved', 'Handle a delayed vendor result', 'Review completion evidence']],
  ['philippines-hr-employee-hris-offboarding-reconciliation', 'Philippines HRIS offboarding reconciliation: prove the record and handback agree', 'Reconcile approved offboarding records across HRIS, access, payroll, and owner checklists without deciding the departure or changing dates by assumption.', 'HRIS offboarding reconciliation', ['Start from the approved notice', 'Compare effective dates carefully', 'Map system owners', 'Protect the departure record', 'Route mismatches immediately', 'Handle a reopened task', 'Document final handback']],
] as const;

export const august18BlogSeeds: August18BlogSeed[] = august18Raw.map(([slug, title, description, focus, headings]) => ({
  slug, title, description, focus,
  sourceDate: '2026-08-18',
  sections: headings.map((heading) => {
    const first = `${heading} is the first control for ${focus}. Write down the source, the action that is allowed, the person who reviews uncertainty, and the evidence that closes the task. In a Philippines-based HR support lane, the coordinator can prepare facts, check required fields, maintain status, and remind an owner. That role should not turn an incomplete record into a confident employment, pay, legal, policy, medical, or eligibility conclusion. A short boundary is useful: routine preparation continues; an exception stops and goes to the named owner.`;
    const second = `For ${focus}, use a concrete example before live work begins. Show the original request, the approved system, the exact handoff, and the point where the coordinator must wait. Keep personal information in the restricted source rather than copying a narrative into a broad queue. When a date, value, identity, or instruction conflicts, preserve both sources and route the difference. This makes the record useful to an HR owner who was not present for the first conversation and prevents a tidy status field from hiding an unresolved decision.`;
    return [heading, first, second] as [string, string, string];
  })
}));

const related = (seed: August18BlogSeed) => [
  { title: seed.title, href: `/blog/${seed.slug}`, note: 'This guide.' },
  { title: 'HR operations support', href: '/services/operations-support', note: 'Review the matching support lane.' },
  { title: 'HR reporting and QA', href: '/services/reporting-and-qa', note: 'Plan review and evidence.' },
  { title: 'Plan Philippines-based HR support', href: '/contact-us', note: 'Bring a redacted workflow to a staffing discussion.' }
];

export const august18Articles: Record<string, RichArticle> = Object.fromEntries(august18BlogSeeds.map((seed, index) => [seed.slug, {
  slug: seed.slug, title: seed.title, description: seed.description, published: seed.sourceDate, updated: seed.sourceDate, minutes: 12, revision: `${seed.sourceDate}-${seed.slug}`,
  directAnswer: [`A Philippines-based HR coordinator can prepare and track ${seed.focus}, check approved inputs, and route exceptions. The company’s qualified HR, recruiting, payroll, finance, legal, or system owner should retain the decision, interpretation, sensitive conversation, and final approval.`, `Start with one narrow queue, a named source, a restricted destination, an owner review, and proof of completion. Expand only when the owner can distinguish a checked administrative item from a decision that still needs authority.`],
  takeaways: seed.sections.slice(0, 5).map(([h]) => h),
  taskRows: seed.sections.slice(0, 5).map(([h, , p], i) => ({ lane: h, philippinesTeam: `Prepare and track the approved ${seed.focus} work for this stage.`, owner: i === 0 ? 'Set scope, authority, and the accountable decision maker.' : 'Review exceptions and approve the business or HR decision.', check: p.slice(0, 78) })),
  pilotStats: [{ value: '1', label: 'Starting lane', note: 'Keep the first review narrow and observable.' }, { value: '2', label: 'Review passes', note: 'Check preparation and the owner handoff.' }, { value: '3', label: 'Escalation tiers', note: 'Routine, owner review, and urgent routing.' }, { value: '30', label: 'Pilot days', note: 'Use a defined window before expanding scope.' }],
  sections: seed.sections.map(([heading, first, second]) => ({ heading, paragraphs: [first, second] })),
  scripts: [{ label: 'Owner handoff', text: `The ${seed.focus} record is prepared from [source]. Open questions: [list]. Please confirm the approved next action and owner.` }, { label: 'Stop rule', text: `I can check and route ${seed.focus} from approved sources. I will stop before making a decision or answering an exception.` }],
  workflow: [{ step: '01', title: 'Map the source', text: `Identify the authoritative input and required fields for ${seed.focus}.` }, { step: '02', title: 'Set the boundary', text: 'Name the allowed preparation, the reviewer, and the stop conditions.' }, { step: '03', title: 'Run the lane', text: 'Prepare routine work, preserve sources, and route uncertainty.' }, { step: '04', title: 'Review evidence', text: 'Compare a representative sample with the written workflow.' }, { step: '05', title: 'Choose scope', text: 'Expand, narrow, or hand back the work using the review record.' }],
  faqs: [{ question: `What can support staff do for ${seed.focus}?`, answer: 'They can organize, check, remind, prepare, and route approved work. Owners retain decisions, exceptions, sensitive messages, and final approval.' }, { question: 'What should stay with the company owner?', answer: 'Employment outcomes, policy interpretation, legal questions, pay and benefits decisions, investigations, complaints, and sensitive exceptions.' }, { question: 'What makes the record complete?', answer: 'The source, scope, action, owner, status, date, approval where needed, and evidence are visible in the approved system.' }, { question: 'How should uncertainty be handled?', answer: 'Preserve the original facts, mark the issue clearly, and route it to a named qualified owner rather than guessing.' }],
  related: related(seed), sources: [source],
  banners: [{ eyebrow: 'First task', title: 'Write the queue before assigning it.', text: `Define inputs, outputs, access, owners, and stop rules for ${seed.focus}.`, href: '/services/operations-support', linkLabel: 'Review HR operations support' }, { eyebrow: 'Quality check', title: 'Review a representative sample.', text: 'Look for missing sources, wrong routing, and approvals that were assumed.', href: '/services/reporting-and-qa', linkLabel: 'See HR reporting and QA' }, { eyebrow: 'Plan the role', title: 'Keep judgment with the owner.', text: 'Bring a redacted example to a staffing discussion before expanding the lane.', href: '/contact-us', linkLabel: 'Discuss HR support' }]
} as RichArticle]));

export const august18BlogPosts = august18BlogSeeds.map(({ slug, title, description }) => ({ slug, title, excerpt: description, minutes: 12 }));
