import type { RichArticle } from './article-data';

type Topic = { slug:string; title:string; description:string; focus:string; decision:string; image:string; distinct:string[] };
const source = { name: 'International Labour Organization: Decent work and the care economy', url: 'https://www.ilo.org/topics-and-sectors/care-economy', note: 'General context for accountable work arrangements and clear responsibilities.' };
const topics: Topic[] = [
 {slug:'august21-philippines-hr-absence-calendar-version-reconciliation',title:'Philippines HR absence calendars: reconcile versions before publishing coverage',description:'Reconcile absence calendars in a Philippines-based HR support lane while managers retain approval authority and the final coverage decision.',focus:'absence-calendar reconciliation',decision:'whether an absence is approved and how coverage should be changed',image:'/blog-heroes/august21-philippines-hr-absence-calendar-version-reconciliation.png',distinct:['Compare the approved request, calendar entry, and published coverage as three separate records.','A coordinator can identify a date mismatch and preserve both versions; a manager decides whether the request is approved, corrected, or escalated.','Test overlapping leave, a half-day, a withdrawn request, and a manager who is unavailable.']},
 {slug:'august21-philippines-hr-employee-change-request-routing',title:'Philippines HR employee changes: route requests with evidence',description:'Route employee change requests through source checks and named approvals in a Philippines-based HR administration workflow.',focus:'employee-change request routing',decision:'whether a status, manager, address, or schedule change is authorized',image:'/blog-heroes/august21-philippines-hr-employee-change-request-routing.png',distinct:['Treat the request as a proposed change, not as permission to edit the master record.','Capture the old value, proposed value, source, effective date, and approving owner before preparation.','Test a forwarded email, a duplicate request, a late effective date, and a request with missing identity evidence.']},
 {slug:'august21-philippines-hr-benefits-enrollment-document-control',title:'Philippines HR benefits enrollment: control documents without deciding eligibility',description:'Control benefits enrollment documents with completeness checks and careful escalation while qualified owners retain eligibility decisions.',focus:'benefits-enrollment document control',decision:'whether an employee is eligible and which benefits response is authorized',image:'/blog-heroes/august21-philippines-hr-benefits-enrollment-document-control.png',distinct:['Separate receipt and completeness from eligibility and advice.','A support role can flag a missing form or signature but should not interpret a plan rule from memory.','Test a late election, a changed dependent, an unreadable attachment, and an employee asking what choice is best.']},
 {slug:'august21-philippines-hr-new-hire-access-activation-proof',title:'Philippines HR new-hire access: prove activation without granting authority',description:'Track new-hire access requests and activation evidence in a Philippines-based HR handoff while system owners control permissions.',focus:'new-hire access activation proof',decision:'which systems a new hire may use and when access should be active',image:'/blog-heroes/august21-philippines-hr-new-hire-access-activation-proof.png',distinct:['Match every requested system to the approved role, start date, and system owner.','The coordinator can assemble the request and collect confirmation; a system owner grants, limits, or refuses access.','Test an early start, a changed manager, a sensitive system, and a request outside the approved channel.']},
 {slug:'august21-philippines-hr-people-ops-month-end-close',title:'Philippines people ops month-end close: reconcile the packet before review',description:'Prepare a people-ops month-end packet from named sources and unresolved exceptions without presenting administrative checks as business results.',focus:'people-ops month-end reconciliation',decision:'which definitions, exceptions, and corrections belong in the approved report',image:'/blog-heroes/august21-philippines-hr-people-ops-month-end-close.png',distinct:['Tie every count to a source, period, definition, and extraction note.','The support role can compare records and list differences; the reporting owner decides treatment and explanation.','Test a late correction, a changed population, a missing source, and a metric whose definition changed mid-month.']},
 {slug:'august21-philippines-hr-complaint-intake-routing',title:'Philippines HR complaint intake: route concerns without investigating them',description:'Create a restrained complaint-intake route for Philippines-based HR support that acknowledges concerns and protects the investigation boundary.',focus:'complaint-intake routing',decision:'how the employer should investigate, respond, protect privacy, and decide next steps',image:'/blog-heroes/august21-philippines-hr-complaint-intake-routing.png',distinct:['Record receipt and urgency without deciding whether an allegation is true.','Use approved acknowledgment language and send the concern to a qualified owner with restricted access.','Test an anonymous concern, an urgent safety message, a manager named in the complaint, and a request for an outcome.']},
 {slug:'august21-philippines-hr-training-completion-reconciliation',title:'Philippines HR training records: reconcile completion without overstating compliance',description:'Reconcile training completion records with source evidence in a Philippines-based HR support lane while owners interpret requirements.',focus:'training-completion reconciliation',decision:'whether a training requirement is satisfied and what exception response is needed',image:'/blog-heroes/august21-philippines-hr-training-completion-reconciliation.png',distinct:['Compare the roster, attendance evidence, learning-system status, and approved exception list.','A coordinator can identify a missing completion record; the owner decides whether alternative evidence counts.','Test a duplicate learner, a late upload, an expired course, and an accommodation question.']},
 {slug:'august21-philippines-hr-manager-request-authentication',title:'Philippines HR manager requests: authenticate before preparing the work',description:'Authenticate manager requests before a Philippines-based HR assistant prepares records, reminders, or employee communications.',focus:'manager-request authentication',decision:'whether the requester is authorized and whether the requested action is permitted',image:'/blog-heroes/august21-philippines-hr-manager-request-authentication.png',distinct:['Verify requester, source channel, employee scope, effective date, and required approval.','A familiar name is not enough evidence for a sensitive change or employee message.','Test a forwarded request, an urgent request, a substitute manager, and a request that conflicts with the current record.']},
 {slug:'august21-philippines-hr-candidate-communication-approval',title:'Philippines HR candidate messages: keep approval visible before sending',description:'Prepare routine candidate communications from approved copy while a Philippines-based recruiting support role avoids hiring judgment.',focus:'candidate-communication approval',decision:'what the candidate should be told and whether the process should continue',image:'/blog-heroes/august21-philippines-hr-candidate-communication-approval.png',distinct:['Separate scheduling and approved status messages from rejection, offer, compensation, and feedback decisions.','Keep the message version, recipient, requisition, approver, and send status together.','Test a candidate asking for feedback, a delayed interviewer, an offer change, and an accommodation request.']},
 {slug:'august21-philippines-hr-termination-checklist-evidence',title:'Philippines HR termination checklists: preserve evidence and decision boundaries',description:'Track termination checklist evidence in a Philippines-based HR support lane while company owners retain employment, access, pay, and communication decisions.',focus:'termination-checklist evidence',decision:'whether employment ends, when access changes, and what the employee is told',image:'/blog-heroes/august21-philippines-hr-termination-checklist-evidence.png',distinct:['A checklist records an approved decision; it must never become the mechanism that makes it.','Collect confirmations for property, access, records, payroll handoff, and approved communication.','Test an immediate closeout, a missing device, an open complaint, and an employee question about final pay.']},
 {slug:'august21-philippines-hr-employee-file-index-provenance-map',title:'Philippines HR employee-file indexes: map provenance without creating a shadow file',description:'Build a source-of-truth map for employee records in a Philippines-based HR support workflow without copying sensitive files into an uncontrolled index.',focus:'employee-file provenance mapping',decision:'which approved record controls when sources disagree',image:'/blog-heroes/august21-philippines-hr-employee-file-index-provenance-map.png',distinct:['Use the index as a finding aid with source, owner, effective date, and access group.','Preserve conflicting references and route the field-level decision rather than choosing the newest-looking file.','Test duplicate addresses, corrected dates, a scanned form, and a record in the wrong repository.']},
 {slug:'august21-philippines-hr-interview-feedback-integrity',title:'Philippines HR interview feedback: protect scorecard integrity before collection',description:'Collect interview feedback with version control and neutral reminders in a Philippines-based recruiting support lane without influencing selection.',focus:'interview-feedback integrity',decision:'how the authorized panel evaluates evidence and reaches a candidate disposition',image:'/blog-heroes/august21-philippines-hr-interview-feedback-integrity.png',distinct:['Freeze the scorecard version, interview stage, interviewer, and submission state before reminders begin.','Preserve original responses when a panel member changes a score; do not normalize unlike forms.','Test a late scorecard, duplicate submission, rubric change, and request for a recommendation.']}
];

const common = (t:Topic, i:number): RichArticle => {
 const paragraphs = [
  `A Philippines-based HR support role can organize ${t.focus} from approved sources, but the role must not become the decision maker. Start by naming the input, the permitted output, the owner, and the evidence that closes the task. The queue should show what arrived, where it came from, what was checked, what remains uncertain, and who must act next. This makes a routine handoff understandable across working hours and prevents a coordinator from filling an authority gap with a reasonable guess.`,
  `The central boundary is ${t.decision}. That choice belongs with the company’s qualified owner, not with a checklist, reminder, or calendar entry. A coordinator can compare fields, prepare a neutral summary, send owner-approved wording, and request a missing confirmation. They should stop before interpreting policy, weighing employee circumstances, changing a sensitive record, or promising an outcome. A written stop rule is part of the workflow, not an admission that the workflow is incomplete.`,
  ...t.distinct.map((x)=>`${x} Keep the source and the proposed action next to one another. If the evidence is incomplete, label the gap plainly and route a question to the named owner. Do not convert a pending item into a completed one because a deadline is close. The point of ${t.focus} is a traceable handoff that makes the next decision easier to make, not a faster way to hide uncertainty.`),
  `Build the first queue from the systems the company actually uses. Identify the approved inbox, HRIS, file store, calendar, learning system, recruiting workspace, or case channel involved in this lane. Give each source a stable label and record the time zone, review window, backup owner, and restricted audience. A Philippines-based team may prepare work outside the owner’s working hours, so the handoff should say exactly what was checked and what still needs a response rather than implying that silence is approval.`,
  `Minimum necessary access matters because administrative work often sits beside sensitive employee information. Give the role only the fields and systems needed for the stated task. Use a named account, avoid broad exports, keep training examples redacted, and define where evidence belongs. If the task expands to a new system or new category of personal information, pause for an access review. A safe workflow in one queue does not automatically authorize the same access in another.`,
  `Use a small pilot with an ordinary case and deliberate exceptions. Include a complete item, a missing field, a duplicate, a late change, a conflicting record, and a restricted question. For each example, record the source, action, stop point, owner, response, and closeout proof. Review the sample with the owner before adding volume. The review should assess accuracy and restraint: did the role do the allowed preparation, and did it avoid the decision that was not delegated?`,
  `Neutral language keeps the public process useful. Say that the coordinator received, checked, prepared, reminded, or routed the item when that is what happened. Do not say that the workflow proved compliance, fairness, eligibility, employee satisfaction, or hiring quality unless the approved evidence supports that separate conclusion. Administrative completeness is a process observation. It is not a promise about the underlying employment result.`,
  `A useful exception note is short and specific: “I checked [source] for [field]. The record shows [fact], while the request says [different fact]. I have not changed the record or answered the substantive question. Please confirm [decision], owner, and effective date.” This format gives the company enough context to act without spreading unnecessary personal detail. It also leaves a clear audit trail for the next reviewer.`,
  `Review the lane at the end of the pilot. Count missing sources, wrong destinations, duplicate items, late handoffs, and cases that stopped correctly. Treat those as workflow observations rather than performance claims about a person or location. When the same exception recurs, revise the source instruction, form, or escalation path. Do not solve a process weakness by silently granting the support role broader authority.`,
  `The company should revisit the role brief whenever the work changes. If a request now needs investigation, negotiation, legal interpretation, employee counseling, pay judgment, candidate evaluation, or a sensitive disclosure, route it to the qualified owner. If a preparation step repeats safely, document the example, confirm the access, and approve a controlled expansion. Scope should follow evidence and authority, not pressure to move more work.`,
  `This guide is public operational guidance, not a substitute for the employer’s HR, privacy, security, payroll, recruiting, or legal advice. Different employers use different systems, calendars, records, and approval rules. A practical staffing discussion starts with a redacted example, a source list, permitted outputs, restricted questions, review timing, and the person who owns the first correction.`,
  `Close each item by comparing the requested action with the evidence actually returned. A reminder is not an approval, a received form is not an eligibility decision, an activated account is not proof that the role was authorized, and a collected scorecard is not a hiring disposition. Those distinctions keep ${t.focus} honest. They let Philippines-based HR support make recurring work more orderly while company owners retain judgment, accountability, and the final say.`
 ];
 return {slug:t.slug,title:t.title,description:t.description,published:'2026-08-21',updated:'2026-08-21',minutes:14,revision:`2026-08-21-${t.slug}`,heroImage:t.image,
  directAnswer:[`A Philippines-based HR support role can prepare and track ${t.focus} from approved sources. The company owner retains ${t.decision}, sensitive questions, exceptions, and final approval.`,`Start with one narrow queue, minimum necessary access, a named reviewer, and proof for every close.`],
  takeaways:[`Define ${t.focus} as a bounded queue.`,`Keep ${t.decision} with the qualified owner.`,`Preserve source and effective-date evidence.`,`Use a visible stop rule for exceptions.`,`Review representative work before expanding.`],
  taskRows:[{lane:'Intake',philippinesTeam:`Receive and classify ${t.focus} from the approved channel.`,owner:'Set scope, priority, and accountable owner.',check:'Source, date, and privacy level are visible'},{lane:'Preparation',philippinesTeam:'Check fields and prepare the permitted packet or reminder.',owner:'Approve changes, exceptions, and sensitive wording.',check:'Every output traces to a source'},{lane:'Handoff',philippinesTeam:'Route the open question and record acknowledgement.',owner:'Make the substantive decision.',check:'Recipient and due time are named'},{lane:'Review',philippinesTeam:'Assemble a representative sample and note misses.',owner:'Confirm quality and update the rule.',check:'Correction is recorded'},{lane:'Closeout',philippinesTeam:'Save status and evidence in the approved system.',owner:'Confirm completion and retention.',check:'No inference is presented as fact'}],
  pilotStats:[{value:'1',label:'Starting lane',note:'Keep the first queue narrow.'},{value:'2',label:'Review passes',note:'Check preparation and handoff.'},{value:'3',label:'Stop conditions',note:'Routine, owner review, restricted.'},{value:String(6+i),label:'Test cases',note:'Use varied redacted examples.'}],
  sections:[{heading:`Define ${t.focus} before assigning it`,paragraphs:paragraphs.slice(0,2)},{heading:'Test the real exceptions',paragraphs:paragraphs.slice(2,5)},{heading:'Set sources, access, and handoffs',paragraphs:paragraphs.slice(5,7)},{heading:'Pilot with evidence',paragraphs:paragraphs.slice(7,9)},{heading:'Use bounded public language',paragraphs:paragraphs.slice(9,11)},{heading:'Choose the next scope deliberately',paragraphs:paragraphs.slice(11)}],
  scripts:[{label:'Owner handoff',text:`This ${t.focus} item is prepared from [source]. I checked [fields] and found [open question]. Please confirm [decision], owner, and effective date.`},{label:'Stop rule',text:`I can prepare and route ${t.focus} from approved sources. I will stop before making a decision, interpreting policy, or answering a restricted question.`}],
  workflow:[{step:'01',title:'Map the source',text:'Name the approved input, required fields, owner, and destination.'},{step:'02',title:'Test the edge',text:'Walk ordinary, missing, conflicting, late, and restricted cases.'},{step:'03',title:'Run the lane',text:'Prepare routine work and preserve evidence.'},{step:'04',title:'Review the sample',text:'Check routing, access, privacy, and stop points.'},{step:'05',title:'Choose scope',text:'Expand, narrow, or hand back based on the review.'}],
  faqs:[{question:`What can support staff do for ${t.focus}?`,answer:'They can organize, check, prepare, remind, and route approved work. Owners retain decisions, sensitive communications, exceptions, and final approval.'},{question:'What should stay with the company?',answer:'Employment outcomes, policy interpretation, legal questions, pay and benefits decisions, investigations, complaints, and sensitive exceptions.'},{question:'How should conflicting records be handled?',answer:'Preserve the sources, describe the difference, and route the decision to a named qualified owner.'},{question:'What makes the queue complete?',answer:'A source, allowed action, owner, status, date, approval where needed, and evidence are visible.'},{question:'When should the role stop?',answer:'Stop when the request requires judgment, sensitive questioning, policy interpretation, or an unsupported decision.'}],
  related:[{title:'HR operations support',href:'/services/operations-support',note:'Review the matching support lane.'},{title:'HR reporting and QA',href:'/services/reporting-and-qa',note:'Plan owner review and evidence.'},{title:'HR outsourcing planning guide',href:'/blog/human-resources-outsourced-planning',note:'Keep the role boundary visible.'}],sources:[source],
  banners:[{eyebrow:'First task',title:'Write the queue before assigning it.',text:`Define inputs, outputs, access, owners, and stop rules for ${t.focus}.`,href:'/services/operations-support',linkLabel:'Review HR operations support'},{eyebrow:'Quality check',title:'Review a representative sample.',text:'Look for missing sources, wrong routing, and assumed approvals.',href:'/services/reporting-and-qa',linkLabel:'See HR reporting and QA'},{eyebrow:'Plan the role',title:'Keep judgment with the owner.',text:'Bring a redacted workflow to a staffing discussion.',href:'/contact-us',linkLabel:'Discuss HR support'}]};
};
export const august21Articles: Record<string, RichArticle> = Object.fromEntries(topics.map((t,i)=>[t.slug,common(t,i)]));
export const august21BlogPosts = topics.map(({slug,title,description})=>({slug,title,excerpt:description,minutes:14}));
export const august21Manifest = topics.map(({slug,image})=>({route:`/blog/${slug}`,sourcePath:'app/blog/august21-batch.ts',sourcePaths:['app/blog/august21-batch.ts'],imagePath:`public${image}`}));
export const august21PromptReceipts = topics.map(({slug,title,focus})=>({route:`/blog/${slug}`,prompt:`Distinct Gemini-generated editorial hero for ${title}; visual focus: ${focus}; landscape; no readable text, logos, watermark, or stock look.`}));
