import type { RichArticle } from './article-data';

type Topic = { slug:string; title:string; description:string; focus:string; record:string; exception:string };
const date = '2026-08-31';
const source = { name:'NIST Privacy Framework', url:'https://www.nist.gov/privacy-framework', note:'Official guidance for data processing, access, and accountability controls.' };
const topics: Topic[] = [
['employment-verification-intake','Employment verification intake: a controlled Philippines HR support lane','Set up employment verification intake so a Philippines-based coordinator can check authorization and route responses without disclosing unapproved employee data.','employment verification intake','requester identity, authorization, requested fields, response owner, and delivery channel','a requester seeks salary, performance, or departure details outside the approved response'],
['return-to-work-document-tracking','Return-to-work document tracking without medical judgment','Track return-to-work documents and deadlines while qualified owners retain medical, accommodation, leave, and fitness decisions.','return-to-work document tracking','received document, restricted location, field check, qualified owner, and next checkpoint','a document contains a restriction or diagnosis that requires qualified review'],
['probation-review-scheduling','Probation review scheduling: keep the deadline separate from the decision','Coordinate probation review dates, forms, and reminders without allowing an administrative status to imply an employment decision.','probation review scheduling','start date, review date, manager, form version, reminders, and owner decision','the manager misses the review date or asks the coordinator to record an outcome'],
['employee-referral-tracking','Employee referral tracking: connect candidates, rules, and approvals','Maintain an employee referral register that preserves candidate consent, program version, hiring status, and reward approval.','employee referral tracking','referrer, candidate authorization, requisition, program version, status source, and reward approver','two employees claim the same referral or a reward rule changed'],
['shift-change-request-routing','Shift change request routing with a visible approval trail','Route shift changes through manager, scheduling, payroll, and employee confirmations without treating a calendar edit as approval.','shift change request routing','requested shift, effective date, coverage impact, approval, payroll notice, and employee confirmation','the calendar and payroll cut-off disagree about the effective date'],
['employee-name-change-records','Employee name change records: reconcile identity fields safely','Coordinate employee name changes across approved systems while keeping identity evidence restricted and preserving prior record links.','employee name change coordination','employee request, evidence location, affected systems, field owner, effective date, and proof','one system cannot accept the approved name format or evidence does not match'],
['job-description-version-control','Job description version control before recruiting starts','Keep job descriptions tied to an approved owner, version, location, and requisition before candidate outreach begins.','job description version control','role identifier, owner, version, approval date, requisition, destinations, and superseded copy','a recruiter receives different duties or requirements from two managers'],
['interview-panel-readiness','Interview panel readiness: confirm access, roles, and evidence','Prepare interview panels with approved materials, clear roles, accessibility checks, and a route for conflicts or missing reviewers.','interview panel readiness','consent boundary, panel roster, interview plan, scorecard version, access check, and conflicts','a panelist lacks the approved scorecard or reports a potential conflict'],
['contractor-conversion-checklist','Contractor conversion administration: a boundary-first checklist','Coordinate conversion paperwork and system tasks while company owners decide classification, terms, compensation, and employment status.','contractor conversion administration','approved decision, effective date, agreement owner, system changes, payroll handoff, and access review','the requested start date arrives before approved terms or classification review'],
['employee-survey-distribution','Employee survey distribution without exposing response identity','Administer survey invitations, delivery exceptions, and reporting thresholds while protecting respondent identity and response content.','employee survey distribution','approved audience, survey version, delivery event, identity boundary, suppression rule, and report owner','a small group result could identify a respondent'],
['mandatory-training-exemption-routing','Training exemption routing: track the request, not the judgment','Route mandatory training exemption requests and due dates without allowing support staff to approve eligibility or sensitive exceptions.','training exemption request routing','course, due date, request receipt, restricted reason location, decision owner, and interim status','the request cites medical, religious, legal, or accessibility grounds'],
['emergency-contact-data-review','Emergency contact data review with least-necessary access','Run a narrow emergency contact review that checks completeness and freshness without copying personal details into broad reports.','emergency contact data review','employee confirmation, last-reviewed date, field status, restricted system, correction owner, and audit result','an employee reports a safety concern or asks who may use the information'],
].map(([slug,title,description,focus,record,exception]) => ({slug:`august31-philippines-hr-${slug}`,title,description,focus,record,exception}));

export const august31BlogPosts = topics.map(t => ({slug:t.slug,title:t.title,excerpt:t.description,minutes:10,published:date}));
export const august31Articles: Record<string, RichArticle> = Object.fromEntries(topics.map((t) => [t.slug, {
 slug:t.slug,title:t.title,description:t.description,published:date,updated:date,minutes:10,revision:`${date}-${t.slug}`,heroImage:'/blog-heroes/august31-hr-operations-field-guide.svg',
 directAnswer:[`A Philippines-based coordinator can administer ${t.focus} when the company defines sources, permitted actions, and stop points. The role can check, prepare, remind, and route, but should not make employment, medical, legal, pay, privacy, or policy decisions.`,`Start with one controlled queue and retain ${t.record}. An accountable company owner approves the outcome and every exception.`],
 takeaways:[`Write the source and owner for every ${t.focus} item.`,'Limit access to the fields and systems needed for the task.','Keep preparation separate from approval and judgment.',`Escalate when ${t.exception}.`,'Close work only after the owner response and destination are recorded.'],
 taskRows:[{lane:'Intake',philippinesTeam:`Receive ${t.focus} through the approved channel and check required fields.`,owner:'Define scope, authority, privacy rules, and priority.',check:'Requester, source, and received time are present'},{lane:'Reconciliation',philippinesTeam:`Compare ${t.record} without overwriting a conflict.`,owner:'Resolve conflicting sources and approve corrections.',check:'Old and proposed values remain distinguishable'},{lane:'Exception',philippinesTeam:`Pause and route the item when ${t.exception}.`,owner:'Make the substantive decision and approve wording.',check:'Recipient, question, due time, and privacy boundary are explicit'},{lane:'Closeout',philippinesTeam:'Record the approved action, destination, date, and remaining work.',owner:'Confirm the outcome and retention treatment.',check:'Status has an owner response or system evidence'}],
 pilotStats:[{value:'1',label:'Controlled queue',note:'Use one intake channel during the pilot'},{value:'2',label:'Named owners',note:'One process owner and one exception owner'},{value:'5',label:'Test cases',note:'Include complete, missing, duplicate, conflict, and sensitive items'},{value:'10',label:'Review days',note:'Inspect every item before expanding'}],
 sections:[
  {heading:`Define the ${t.focus} record`,paragraphs:[`A workable lane begins with a record that an owner can reconstruct. Retain ${t.record}. Store only what the process needs, and keep sensitive evidence in its approved restricted location.`,'Status words should describe events such as received, checked, waiting for owner, returned for correction, and completed. A convenient label must never substitute for evidence.']},
  {heading:'Draw the authority line before granting access',paragraphs:[`The coordinator may compare approved inputs, prepare neutral wording, identify a missing field, and route a precise question. The coordinator must stop when ${t.exception}.`,'The company owner retains policy interpretation, employee decisions, legal conclusions, sensitive conversations, pay treatment, and exception approval. Put this boundary in the playbook and handoff template.']},
  {heading:'Reconcile sources without rewriting history',paragraphs:['Keep the request, controlling record, and completion evidence separate. If they disagree, preserve both values and ask the named owner which one controls. Do not treat the newest timestamp or most senior sender as automatic authority.',`For ${t.focus}, record the source location and effective date next to the proposed action. This gives the owner a short question instead of a cleaned-up record that hides the conflict.`]},
  {heading:'Test ordinary work and uncomfortable exceptions',paragraphs:[`Test a complete item, a missing field, a duplicate, a conflicting source, and the case where ${t.exception}. Record the permitted preparation and exact stop point for each.`,'Review whether the handoff reached someone with authority, private details stayed in the proper system, and the final status can be proven. Fix the route before adding volume.']},
  {heading:'Use a narrow closeout statement',paragraphs:['A good closeout names the source checked, action prepared, owner response, approved destination, and completion time. If the owner has not responded, the item remains pending with a checkpoint and escalation path.','Review errors by type: wrong destination, missing evidence, late response, duplicate record, excess access, or premature closure. Those counts improve the workflow without claiming legal sufficiency.']},
  {heading:'Questions to ask a provider',paragraphs:[`Ask the provider to demonstrate ${t.focus} with a redacted normal example and an exception. Have them show the fields they need, the decision they will not make, and the evidence returned to your owner.`,'Ask how access is removed, drafts are deleted, unresolved items are handed back, and the playbook changes after an error. Specific answers are more useful than broad promises.']}
 ],
 scripts:[{label:'Owner handoff',text:`I checked the approved sources for ${t.focus}. The unresolved point is in the restricted item. Please confirm the controlling value and approved next action.`},{label:'Stop rule',text:`I can prepare and route this item, but I cannot approve the outcome because ${t.exception}. I sent it to the named owner and recorded the next checkpoint.`}],
 workflow:[{step:'01',title:'Open the record',text:'Capture the request, source, owner, due time, and privacy level.'},{step:'02',title:'Check the evidence',text:'Compare required fields while preserving source differences.'},{step:'03',title:'Route the exception',text:'Send one precise question to the qualified owner.'},{step:'04',title:'Record the decision',text:'Apply only the action the owner approved.'},{step:'05',title:'Close and review',text:'Save proof, return open work, and sample the lane for defects.'}],
 faqs:[{question:`Can outsourced staff own ${t.focus}?`,answer:'They can own defined administrative steps and queue hygiene. A qualified company owner retains decisions, exceptions, and sensitive communication.'},{question:'What access should the coordinator receive?',answer:'Use named accounts and the smallest useful view of the approved queue, source fields, and destination. Do not provide broad exports by default.'},{question:'What happens when records conflict?',answer:'Preserve both sources, identify the difference, and route the decision to the accountable owner. Do not overwrite the earlier record.'},{question:'How should quality be reviewed?',answer:'Test normal and exception cases, then sample source accuracy, routing, privacy handling, and closeout evidence.'},{question:'Does this workflow provide legal advice?',answer:'No. It is an administrative control pattern. Use qualified owners for legal, policy, medical, pay, and employment decisions.'}],
 related:[{title:'HR operations support',href:'/services/operations-support',note:'Review the related administrative lane.'},{title:'HR reporting and QA',href:'/services/reporting-and-qa',note:'Plan source checks and owner review.'},{title:'Plan Philippines-based HR support',href:'/contact-us',note:'Bring a redacted workflow to a staffing discussion.'}],sources:[source],
 banners:[{eyebrow:'Start with the record',title:`Map ${t.focus} before granting access.`,text:'Name the inputs, owner, stop point, and completion proof.',href:'/services/operations-support',linkLabel:'Review HR operations support'},{eyebrow:'Check the lane',title:'Sample evidence before adding volume.',text:'Review sources, exceptions, access, and closeout records with the owner.',href:'/services/reporting-and-qa',linkLabel:'See reporting and QA'},{eyebrow:'Scope the role',title:'Keep judgment with the company owner.',text:'Use a redacted example to define the work and its authority boundary.',href:'/contact-us',linkLabel:'Discuss HR support'}]
} as RichArticle]));
