import type { RichArticle } from './article-data';

type Topic = { slug: string; title: string; description: string; focus: string; decision: string; case: string; failure: string; measure: string; sourceDate: '2026-08-19' };

const topics: Topic[] = [
  ['philippines-hr-employee-file-index-design','Philippines HR employee-file indexes: design a source-of-truth map','Map employee-file sources and ownership so a Philippines-based HR support role can find approved records without guessing which copy controls.','employee-file index design','which record is authoritative when systems disagree','a manager submits an outdated form while the HRIS has a newer approved change','silent overwrites that erase the reason a field changed','the share of sampled records with one named source and owner'],
  ['philippines-hr-absence-calendar-reconciliation','Philippines HR absence calendars: reconcile requests before reminders','Reconcile absence requests, approvals, and calendars in a Philippines-based HR workflow while managers retain the leave decision.','absence-calendar reconciliation','whether a request is approved, pending, or missing evidence','a calendar event exists but the approved request is still waiting in the manager queue','treating a calendar entry as proof of approval','items matched to an approved source before the cutoff'],
  ['philippines-hr-manager-escalation-window','Philippines HR manager escalations: set a response window that means something','Create a manager-escalation lane with useful timers and clear stop points for Philippines-based HR administration.','manager escalation windows','who must respond and when an overdue item changes priority','a routine request becomes urgent because the manager never acknowledged the handoff','sending repeated reminders without naming the next owner','overdue items that have a named next action'],
  ['philippines-recruiting-candidate-withdrawal-routing','Philippines recruiting candidate withdrawals: preserve the decision trail','Route candidate withdrawal notices and downstream cleanup without inventing reasons or influencing selection.','candidate withdrawal routing','what should be closed, retained, or handed back after a withdrawal','a candidate asks to stop contact while an interview and an automated reminder remain scheduled','deleting the record before the recruiting owner reviews the request','withdrawals closed with approved disposition and communication evidence'],
  ['philippines-hr-document-version-control','Philippines HR document versions: stop old forms returning to the queue','Control HR document versions so a Philippines-based support team uses approved copy and can explain why an older file was rejected.','HR document version control','which version is approved for a particular effective date','an employee returns a signed form from an old email thread','fixing the visible filename while leaving duplicate links active','sampled documents linked to the current approved version'],
  ['philippines-hr-new-hire-preboarding-dependency-map','Philippines HR preboarding dependencies: show what can block day one','Map preboarding dependencies across HR, hiring managers, IT, and facilities without promising an outcome no owner has approved.','new-hire preboarding dependencies','which missing dependency blocks a confirmed start','an account request cannot begin because the role owner has not confirmed the start record','reporting every open task as equally urgent','blocked starts with a visible owner and next checkpoint'],
  ['philippines-hr-employee-address-change-control','Philippines HR employee address changes: verify the route before updating','Build a source-backed address-change route with identity checks and owner approval for Philippines HR administration.','employee address-change control','which approved source may change the employee record','an employee sends a change from a personal channel that is not the approved intake','copying the new address into every system before verification','requests with verified source, owner, and downstream acknowledgement'],
  ['philippines-hr-policy-rollout-attestation-gap','Philippines HR policy rollouts: turn attestation gaps into owner actions','Track policy distribution and attestation gaps in a Philippines-based HR support lane without interpreting the policy for employees.','policy rollout attestation gaps','whether a missing attestation needs a reminder, owner review, or exception','a worker says the policy link was inaccessible but the tracker shows sent','measuring sent emails as if they were understood or accepted','gaps with a documented reason and qualified owner'],
  ['philippines-hr-employee-request-categorization','Philippines HR employee requests: use categories that route, not label','Design practical request categories that route Philippines-based HR work to the right owner while preserving the employee’s words.','employee-request categorization','which queue owns the request and what detail must stay restricted','one message includes a routine address update and a sensitive complaint','splitting a message so private context travels into a broad queue','reclassified items corrected before the next response'],
  ['philippines-recruiting-interview-feedback-lock','Philippines recruiting interview feedback: close the collection window safely','Set a feedback-collection window for recruiting support while interviewers and hiring owners retain evaluation and selection authority.','interview feedback collection locks','when collection closes and who may reopen it','one interviewer submits late notes after the panel has already discussed a candidate','editing or summarizing feedback to make the panel look complete','feedback records with source, timestamp, and owner review'],
  ['philippines-hr-employee-file-access-review','Philippines HR employee-file access: review permissions by task','Review access to employee records by task and owner, keeping a Philippines-based admin role narrow and observable.','employee-file access review','which permission is necessary for the next approved task','a role still has access to a folder after its recurring project ended','removing a person from one folder while leaving inherited access elsewhere','permissions with owner, purpose, expiry or review date'],
  ['philippines-hr-training-completion-exceptions','Philippines HR training completion: route exceptions without judging intent','Reconcile training completion records and exception requests while qualified HR owners decide what a missed requirement means.','training completion exceptions','whether evidence supports completion or needs an owner decision','a learning platform marks incomplete while the employee provides an approved attendance record','assuming a technical status proves employee intent or noncompliance','exceptions resolved with source evidence and decision owner'],
  ['philippines-hr-employee-complaint-intake-boundary','Philippines HR complaint intake: make the stop rule visible','Create a narrow complaint-intake handoff that protects the employee’s message and routes it to a qualified HR owner.','employee complaint intake boundaries','what can be acknowledged and what must immediately escalate','an employee begins with a scheduling issue and then describes retaliation','asking follow-up questions that turn an intake clerk into an investigator','complaints transferred with minimum necessary detail and receipt proof'],
  ['philippines-hr-benefits-deadline-exception-log','Philippines HR benefits deadlines: document exceptions before they disappear','Maintain a benefits deadline and exception log for Philippines-based HR support while plan owners decide eligibility and remedies.','benefits deadline exception logging','whether a missed deadline is routine follow-up or an eligibility decision','a document arrives after a cutoff with no visible receipt timestamp','promising acceptance because a file appears complete','exceptions carrying receipt, source, deadline, and decision owner'],
  ['philippines-hris-manager-change-reconciliation','Philippines HRIS manager changes: reconcile effective dates and approvals','Coordinate manager changes across HRIS, directories, and workflow tools without treating a saved field as final approval.','HRIS manager-change reconciliation','which effective date and approval control downstream updates','the HRIS shows a new manager before the organizational owner signs the change','updating downstream tools from the first visible field','changes reconciled across systems after owner approval'],
  ['philippines-recruiting-requisition-intake-quality','Philippines recruiting requisitions: check readiness before sourcing','Create a requisition-readiness check for Philippines recruiting support while leaders retain budget, role, and selection decisions.','requisition intake quality','whether the role is ready for sourcing or missing approval','a job description is complete but the hiring owner has not approved the opening','treating a polished description as authorization to recruit','requisitions with complete approvals and no unresolved blockers'],
  ['philippines-hr-employee-communication-translation-review','Philippines HR translated communications: protect meaning at review','Route translated employee communications through a qualified review so Philippines-based HR support preserves meaning without giving policy advice.','employee communication translation review','who confirms meaning, audience, and approved delivery','a translated sentence changes a request into an instruction','choosing the most fluent wording without comparing the source','messages with source, reviewer, version, and delivery approval'],
  ['philippines-hr-month-end-people-ops-close','Philippines HR month-end close: reconcile open people tasks','Run a month-end people-ops close that gathers evidence from recurring HR queues while owners retain financial and employment decisions.','month-end people-ops close','which open item affects the close and who resolves it','a late employee change appears after the report has been prepared','closing the month by hiding unmatched items','open items reconciled or explicitly carried forward with owners'],
  ['philippines-hr-employee-file-correction-register','Philippines HR file corrections: preserve before-and-after evidence','Maintain a correction register for employee records so changes are traceable and approved rather than silently overwritten.','employee-file correction registers','whether the request is an administrative correction or a disputed fact','two sources contain different spellings and each appears official','editing the record first and asking for evidence later','corrections with original value, requested value, source, and approval'],
  ['philippines-hr-urgent-request-triage','Philippines HR urgent requests: define urgency with observable signals','Build an urgent-request triage rule for Philippines-based HR support that routes risk without promising a substantive answer.','urgent HR request triage','which observable signal changes the route or response window','a message arrives outside hours and contains both a deadline and a sensitive concern','calling every emotional message urgent while missing a real deadline','urgent items reaching the correct owner within the agreed window'],
  ['philippines-hr-offboarding-shared-work-handoff','Philippines HR offboarding: hand back shared work without losing context','Coordinate shared-work handback during offboarding with a minimal register of files, owners, and approved next actions.','offboarding shared-work handbacks','what must move, what must stay restricted, and who accepts it','a departing employee’s shared folder contains work owned by several teams','transferring an entire folder without classifying ownership or access','handoff items accepted by named owners with access reviewed'],
  ['philippines-hr-employee-record-retention-review','Philippines HR employee-record reviews: separate retention facts from decisions','Run a source-backed employee-record review for Philippines HR support while qualified owners decide retention, access, and any exception.','employee-record retention reviews','which record facts are ready for owner review and which require interpretation','an old document remains visible beside a newer record with a different effective date','treating a retention reminder as permission to delete or disclose a record','review items with source, status, owner, and approved next action']
].map(([slug,title,description,focus,decision,caseText,failure,measure])=>({slug,title,description,focus,decision,case:caseText,failure,measure,sourceDate:'2026-08-19' as const}));

const related = (slug: string) => [{ title: 'HR operations support', href: '/services/operations-support', note: 'Review the matching support lane.' }, { title: 'HR reporting and QA', href: '/services/reporting-and-qa', note: 'Plan owner review and evidence.' }, { title: 'HR outsourcing planning guide', href: '/blog/human-resources-outsourced-planning', note: 'Keep the role boundary visible.' }, { title: 'This guide', href: `/blog/${slug}`, note: 'Current workflow.' }];
const source = { name: 'International Labour Organization: Decent work and the care economy', url: 'https://www.ilo.org/topics-and-sectors/care-economy', note: 'General context for clear responsibilities and accountable work arrangements.' };

const makeArticle = (t: Topic, index: number): RichArticle => {
  const paragraphs = [
    `A Philippines-based HR support role can prepare and track ${t.focus}, but the useful boundary begins before the first item arrives. Write the accepted source, the fields to record, the approved destination, the reviewer, and the stop condition. The point is not to make the support role sound broad; it is to make one repeatable administrative lane understandable to the person doing it and to the owner checking it.`,
    `The company owner keeps ${t.decision}. Support staff may compare approved records, format a queue, send an approved reminder, and report a missing input. They should not infer an employment outcome, interpret policy, answer a legal question, decide eligibility, investigate a complaint, or change a sensitive record because one value looks more convenient. A handoff should state what is known, what is missing, and who must decide.`,
    `Start with the real case pattern: ${t.case}. Write the first event, the authoritative source, the next allowed action, and the owner who accepts the handoff. Then add the exception path. If the request contains more than the queue needs, keep the minimum detail required for routing and preserve the original in the approved system. The Philippines context matters operationally because remote teams need explicit time-zone, channel, and acknowledgement rules; it does not remove the company owner’s responsibility.`,
    `A strong queue distinguishes received, prepared, waiting, escalated, and closed. Each status needs an observable test. “Prepared” can mean the source was checked and the packet is ready; it cannot mean a judgment was made. “Closed” should require the owner’s response or an approved downstream confirmation. This makes ${t.measure} measurable without turning an administrative count into a claim about employee quality or business results.`,
    `The common failure is ${t.failure}. Prevent it with a source link, a named owner, a due time, and a reason code for exceptions. Preserve conflicting records rather than selecting the tidier one. A second reviewer can check whether the support action stayed inside scope, whether private detail travelled too far, and whether the receiving owner understood the question. Fix the written workflow when the same ambiguity returns.`,
    `Use a small pilot with redacted examples: one ordinary item, one missing field, one conflicting source, one late response, and one restricted request. Ask the owner to watch the stop points. The support role can prepare a comparison and route it; the qualified HR, recruiting, payroll, finance, legal, system, or management owner makes the decision. Do not use a pilot to quietly expand access or authority.`,
    `At review time, compare the queue with the original role brief. Count items that had a source, an owner, an allowed action, a timely handoff, and evidence of closure. Examine misses by cause rather than blaming a person: unclear intake, stale template, missing permission, unavailable owner, or an exception that was never defined. This turns ${t.focus} into an operating routine that can be narrowed, improved, or handed back safely.`,
    `A practical handoff says: “This ${t.focus} item arrived from [source] on [date]. I checked [fields], prepared [allowed output], and found [open question]. Please confirm [decision] by [time].” That language protects meaning and keeps accountability visible. It is especially useful when an employee, candidate, manager, or vendor asks a question that crosses from administration into judgment.`,
    `Do not publish invented company facts, outcomes, credentials, or testimonials around this workflow. Use the company’s actual approved records and qualified advice for the live process. Public guidance can explain controls and role boundaries; it cannot promise a legal result, a payroll result, an eligibility result, or a particular response time without a confirmed operating agreement.`,
    `The decision to expand should be deliberate. Review access, sample quality, unresolved exceptions, owner response, and the privacy of the record. If the queue works only when one person remembers an unwritten rule, it is not ready to scale. If a sensitive issue appears, stop, preserve the minimum necessary context, and route it to the named owner. That is a successful control, not a failure of support.`
  ];
  return { slug:t.slug,title:t.title,description:t.description,published:t.sourceDate,updated:t.sourceDate,minutes:12,revision:`${t.sourceDate}-${t.slug}`,
    directAnswer:[`A Philippines-based HR coordinator can prepare and track ${t.focus} from approved sources. The company’s qualified owner retains ${t.decision}, sensitive conversations, exceptions, and final approval.`,`Begin with one narrow queue, a named reviewer, minimum necessary access, and evidence for each close. Expand only after a sample shows that routine preparation and owner judgment remain separate.`],
    takeaways:[`Define ${t.focus} as a bounded queue.`,`Keep ${t.decision} with the qualified owner.`,`Preserve source evidence and conflicting values.`,`Use explicit stop points for restricted requests.`,`Measure ${t.measure}.`],
    taskRows:[{lane:'Intake',philippinesTeam:`Receive and classify ${t.focus} from the approved channel.`,owner:'Set scope, priority, and accountable owner.',check:'Source, date, and privacy level are visible'},{lane:'Preparation',philippinesTeam:'Check fields and prepare the allowed packet or reminder.',owner:'Approve changes, exceptions, and sensitive wording.',check:'Every output traces to a source'},{lane:'Handoff',philippinesTeam:'Route the open question and record acknowledgement.',owner:'Make the substantive decision.',check:'Recipient and due time are named'},{lane:'Review',philippinesTeam:'Assemble a representative sample and note misses.',owner:'Confirm quality and update the rule.',check:'Correction is recorded'},{lane:'Closeout',philippinesTeam:'Save status and evidence in the approved system.',owner:'Confirm completion and retention.',check:'No unsupported inference is presented as fact'}],
    pilotStats:[{value:'1',label:'Starting lane',note:'Keep the first queue narrow.'},{value:'2',label:'Review passes',note:'Check preparation and handoff.'},{value:'3',label:'Escalation tiers',note:'Routine, owner review, urgent route.'},{value:String(7+index),label:'Test cases',note:'Use varied redacted examples.'}],
    sections:[{heading:`What ${t.focus} should include`,paragraphs:paragraphs.slice(0,2)},{heading:'Build from the actual exception',paragraphs:paragraphs.slice(2,4)},{heading:'Protect the record and the boundary',paragraphs:paragraphs.slice(4,6)},{heading:'Review what the queue proves',paragraphs:paragraphs.slice(6,8)},{heading:'Keep public guidance factually bounded',paragraphs:paragraphs.slice(8,10)}],
    scripts:[{label:'Owner handoff',text:`This ${t.focus} item is prepared from [source]. I checked [fields]. The open question is [question]. Please confirm [decision] and owner.`},{label:'Stop rule',text:`I can prepare and route ${t.focus} from approved sources. I will stop before making a decision, interpreting policy, or answering a restricted question.`}],
    workflow:[{step:'01',title:'Map the source',text:'Name the approved input, required fields, owner, and destination.'},{step:'02',title:'Test the edge',text:'Walk the ordinary, missing, conflicting, late, and restricted cases.'},{step:'03',title:'Run the lane',text:'Prepare routine work and preserve evidence.'},{step:'04',title:'Review the sample',text:'Check routing, access, privacy, and stop points.'},{step:'05',title:'Choose scope',text:'Expand, narrow, or hand back based on the record.'}],
    faqs:[{question:`What can support staff do for ${t.focus}?`,answer:'They can organize, check, prepare, remind, and route approved work. Owners retain decisions, sensitive communications, exceptions, and final approval.'},{question:'What should stay with the company?',answer:'Employment outcomes, policy interpretation, legal questions, pay and benefits decisions, investigations, complaints, and sensitive exceptions.'},{question:'How should conflicting records be handled?',answer:'Preserve both sources, describe the difference, and route the decision to a named qualified owner.'},{question:'What makes the queue complete?',answer:'A source, allowed action, owner, status, date, approval where needed, and evidence are visible.'},{question:'When should the role stop?',answer:'Stop when the request requires judgment, sensitive questioning, policy interpretation, or a decision not supported by the approved source.'}],
    related:related(t.slug),sources:[source],banners:[{eyebrow:'First task',title:'Write the queue before assigning it.',text:`Define inputs, outputs, access, owners, and stop rules for ${t.focus}.`,href:'/services/operations-support',linkLabel:'Review HR operations support'},{eyebrow:'Quality check',title:'Review a representative sample.',text:'Look for missing sources, wrong routing, and assumed approvals.',href:'/services/reporting-and-qa',linkLabel:'See HR reporting and QA'},{eyebrow:'Plan the role',title:'Keep judgment with the owner.',text:'Bring a redacted workflow to a staffing discussion.',href:'/contact-us',linkLabel:'Discuss HR support'}]};
};

export const august19Articles: Record<string, RichArticle> = Object.fromEntries(topics.map((topic,index)=>[topic.slug,makeArticle(topic,index)]));
export const august19BlogPosts = topics.map(({slug,title,description})=>({slug,title,excerpt:description,minutes:12}));
export const august19Manifest = topics.map(({slug})=>({route:`/blog/${slug}`,sourcePath:'app/blog/august19-batch.ts'}));
