export type DailySeed = { slug: string; title: string; description: string; focus: string };

export const dailySeeds: DailySeed[] = [
  ['philippines-hr-case-intake-routing','Philippines HR case intake routing: protect the first handoff','Create a controlled HR case intake lane with minimum-necessary details, priority tags, and named escalation owners.','HR case intake routing'],
  ['philippines-employee-file-audit-workflow','Philippines employee file audit workflow: find gaps safely','Review employee files for completeness and route missing evidence without changing records outside an approved process.','employee file audits'],
  ['philippines-hr-knowledge-base-maintenance','Philippines HR knowledge base maintenance: keep answers current','Maintain approved HR help content with source dates, owner review, and a clear path for policy questions.','HR knowledge base maintenance'],
  ['philippines-recruiting-requisition-administration','Philippines recruiting requisition administration: control the request','Keep role requests, approvals, status changes, and hiring-owner decisions visible in one recruiting workflow.','recruiting requisition administration'],
  ['philippines-reference-check-coordination','Philippines reference check coordination: document the boundary','Coordinate approved reference-check steps while keeping consent, interpretation, and hiring decisions with the owner.','reference check coordination'],
  ['philippines-hr-survey-administration','Philippines HR survey administration: protect response handling','Set up survey distribution, reminders, and response tracking without exposing unnecessary employee information.','HR survey administration'],
  ['philippines-employee-letter-preparation','Philippines employee letter preparation: use an approval gate','Prepare routine employee letters from approved templates and route exceptions before anything is issued.','employee letter preparation'],
  ['philippines-hr-absence-tracking-support','Philippines HR absence tracking support: make status visible','Track absence records and follow-ups using approved sources while managers retain approval and accommodation decisions.','absence tracking support'],
  ['philippines-hr-org-chart-maintenance','Philippines HR org chart maintenance: prevent stale reporting lines','Maintain organizational data from approved changes with version checks and owner signoff.','org chart maintenance'],
  ['philippines-hr-new-manager-support-workflow','Philippines new manager HR support: build a safe workflow','Give new managers repeatable administrative support with clear escalation for employee, policy, and performance questions.','new manager HR support'],
  ['philippines-hr-training-invitation-coordination','Philippines HR training invitation coordination: close the loop','Coordinate training invitations, attendance, reminders, and completion evidence with an accountable program owner.','training invitation coordination'],
  ['philippines-hr-document-retention-review','Philippines HR document retention review: route the decision','Prepare a retention review queue with source records, dates, and owner decisions instead of deleting records by assumption.','HR document retention review'],
  ['philippines-hr-employee-announcement-workflow','Philippines employee announcement workflow: approve before sending','Draft and route routine employee announcements from approved copy while sensitive messages stay with HR leadership.','employee announcement workflow'],
  ['philippines-hr-people-analytics-data-preparation','Philippines people analytics data preparation: check the source','Prepare aggregated people data with clear definitions, access limits, and review before reporting.','people analytics data preparation'],
  ['philippines-hr-policy-update-implementation','Philippines HR policy update implementation: track the handoff','Coordinate policy update tasks, acknowledgements, and questions without interpreting policy for employees.','HR policy update implementation'],
  ['philippines-hr-employee-feedback-routing','Philippines employee feedback routing: make escalation explicit','Collect and route employee feedback using approved channels, confidentiality boundaries, and named owners.','employee feedback routing'],
  ['philippines-hr-employee-directory-cleanup','Philippines HR employee directory cleanup: verify before changing','Clean approved directory fields through evidence checks, change logs, and owner review.','employee directory cleanup'],
  ['philippines-hr-offer-document-coordination','Philippines HR offer document coordination: keep approvals separate','Coordinate offer document preparation and status while compensation, terms, and final approval remain with authorized owners.','offer document coordination'],
  ['philippines-hr-employee-status-reporting','Philippines HR employee status reporting: define the source of truth','Prepare recurring status reports from approved records and route discrepancies before publication.','employee status reporting'],
  ['philippines-hr-policy-question-escalation','Philippines HR policy question escalation: stop at interpretation','Sort routine policy questions from requests that require qualified HR or legal review.','HR policy question escalation'],
  ['philippines-hr-employee-recognition-administration','Philippines employee recognition administration: keep the process fair','Coordinate recognition nominations and records from approved criteria without making eligibility or employment decisions.','employee recognition administration'],
  ['philippines-hr-return-to-work-coordination','Philippines return-to-work coordination: protect sensitive handoffs','Track approved return-to-work logistics and route medical, accommodation, and policy questions to the right owner.','return-to-work coordination'],
  ['philippines-hr-people-operations-calendar','Philippines people operations calendar: build one reliable cadence','Run a shared people-operations calendar with owners, deadlines, reminders, and completion evidence.','people operations calendar'],
  ['philippines-hr-process-exception-log','Philippines HR process exception log: turn surprises into controls','Maintain an exception log that shows what stopped, who decided, and what the playbook should learn.','HR process exception logging'],
  ['philippines-hr-employee-milestone-tracking','Philippines HR employee milestone tracking: make follow-up reliable','Track approved employee milestones and reminders with a clear owner, source record, and escalation path.','employee milestone tracking']
].map(([slug, title, description, focus]) => ({ slug, title, description, focus }));

export const dailyBlogPosts = dailySeeds.map(({ slug, title, description }) => ({ slug, title, excerpt: description, minutes: 9 }));
