export type August11BlogSeed = {
  slug: string;
  title: string;
  description: string;
  focus: string;
  sourceDate: '2026-08-11';
};

// Each record owns its publication date so the batch remains auditable at source.
export const august11BlogSeeds: August11BlogSeed[] = [
  { slug: 'philippines-hr-onboarding-owner-matrix', title: 'Philippines HR onboarding owner matrix: prevent dropped handoffs', description: 'Build an onboarding owner matrix that shows who prepares, approves, and confirms each employee setup task.', focus: 'onboarding owner matrices', sourceDate: '2026-08-11' },
  { slug: 'philippines-hr-employee-data-change-approvals', title: 'Philippines HR employee data changes: use an approval trail', description: 'Route employee data changes through source evidence, named approval, and a visible record of what changed.', focus: 'employee data change approvals', sourceDate: '2026-08-11' },
  { slug: 'philippines-hr-new-hire-first-week-checklist', title: 'Philippines new-hire first-week checklist: make ownership visible', description: 'Coordinate first-week HR tasks with a practical checklist for introductions, documents, access, and follow-up.', focus: 'new-hire first-week checklists', sourceDate: '2026-08-11' },
  { slug: 'philippines-hr-candidate-availability-coordination', title: 'Philippines candidate availability coordination: protect the schedule', description: 'Keep candidate availability, interviewer calendars, and changes aligned without taking hiring judgment away from the hiring owner.', focus: 'candidate availability coordination', sourceDate: '2026-08-11' },
  { slug: 'philippines-hr-interview-feedback-follow-up', title: 'Philippines interview feedback follow-up: close the evidence gap', description: 'Collect interview feedback on time, identify missing inputs, and route decisions to the authorized hiring owner.', focus: 'interview feedback follow-up', sourceDate: '2026-08-11' },
  { slug: 'philippines-hr-employee-document-expiry-tracking', title: 'Philippines HR document expiry tracking: create an early-warning queue', description: 'Track document review dates and reminders while qualified owners decide what an expired or incomplete record means.', focus: 'employee document expiry tracking', sourceDate: '2026-08-11' },
  { slug: 'philippines-hr-employee-request-status-updates', title: 'Philippines HR request status updates: keep employees informed', description: 'Use approved status messages and clear ownership to reduce silent waits in recurring employee requests.', focus: 'employee request status updates', sourceDate: '2026-08-11' },
  { slug: 'philippines-hr-manager-onboarding-brief', title: 'Philippines manager onboarding brief: give new leaders a usable start', description: 'Prepare a manager onboarding brief with key contacts, recurring responsibilities, and escalation boundaries.', focus: 'manager onboarding briefs', sourceDate: '2026-08-11' },
  { slug: 'philippines-hr-employee-event-coordination', title: 'Philippines HR employee event coordination: separate logistics from decisions', description: 'Coordinate invitations, attendance, materials, and reminders while HR owners handle sensitive participation questions.', focus: 'employee event coordination', sourceDate: '2026-08-11' },
  { slug: 'philippines-hr-training-roster-reconciliation', title: 'Philippines HR training roster reconciliation: resolve mismatches safely', description: 'Compare training rosters with approved records and route mismatches before completion reporting is finalized.', focus: 'training roster reconciliation', sourceDate: '2026-08-11' },
  { slug: 'philippines-hr-employee-contact-preferences', title: 'Philippines HR contact preferences: verify before updating', description: 'Maintain employee contact preferences from approved requests with verification and an accountable change owner.', focus: 'employee contact preference updates', sourceDate: '2026-08-11' },
  { slug: 'philippines-hr-people-ops-weekly-review', title: 'Philippines people operations weekly review: turn open work into decisions', description: 'Prepare a weekly people-operations review that distinguishes completed work, blockers, risks, and owner decisions.', focus: 'people operations weekly reviews', sourceDate: '2026-08-11' },
  { slug: 'philippines-hr-employee-anniversary-reminders', title: 'Philippines HR employee anniversary reminders: make recognition reliable', description: 'Coordinate anniversary reminders from approved employee records without making assumptions about recognition or eligibility.', focus: 'employee anniversary reminders', sourceDate: '2026-08-11' },
  { slug: 'philippines-hr-recruiting-interview-packet-control', title: 'Philippines recruiting interview packets: control the source version', description: 'Prepare consistent interview packets from approved materials and keep outdated versions from reaching panel members.', focus: 'recruiting interview packet control', sourceDate: '2026-08-11' },
  { slug: 'philippines-hr-candidate-status-reconciliation', title: 'Philippines candidate status reconciliation: find stalled handoffs', description: 'Compare candidate status across approved recruiting records and surface stalled or conflicting next steps.', focus: 'candidate status reconciliation', sourceDate: '2026-08-11' },
  { slug: 'philippines-hr-employee-policy-resource-index', title: 'Philippines HR policy resource index: make approved answers findable', description: 'Build an indexed set of approved policy resources with owners, review dates, and escalation paths.', focus: 'HR policy resource indexes', sourceDate: '2026-08-11' },
  { slug: 'philippines-hr-employee-case-document-check', title: 'Philippines HR case document checks: organize without investigating', description: 'Check case files for required documents and route gaps while investigation and employment judgments stay with qualified owners.', focus: 'HR case document checks', sourceDate: '2026-08-11' },
  { slug: 'philippines-hr-employee-leave-calendar-support', title: 'Philippines HR leave calendar support: keep dates and owners aligned', description: 'Maintain an approved leave calendar and route conflicts or sensitive questions to the right HR owner.', focus: 'employee leave calendar support', sourceDate: '2026-08-11' },
  { slug: 'philippines-hr-employee-acknowledgement-reminders', title: 'Philippines HR acknowledgement reminders: track completion fairly', description: 'Coordinate acknowledgement reminders from approved materials and report exceptions without pressuring employees or interpreting policy.', focus: 'employee acknowledgement reminders', sourceDate: '2026-08-11' },
  { slug: 'philippines-hr-recruiting-rejection-approval-routing', title: 'Philippines recruiting rejection routing: keep the decision with the owner', description: 'Prepare approved candidate status communications and route rejection decisions through the authorized hiring owner.', focus: 'recruiting rejection approval routing', sourceDate: '2026-08-11' },
  { slug: 'philippines-hr-employee-handbook-question-log', title: 'Philippines employee handbook question log: show what needs review', description: 'Capture handbook questions, link them to approved sources, and escalate interpretation requests instead of guessing.', focus: 'employee handbook question logs', sourceDate: '2026-08-11' },
  { slug: 'philippines-hr-people-ops-month-end-checklist', title: 'Philippines people operations month-end checklist: close the loop', description: 'Prepare a month-end checklist for open HR administration, evidence, owner review, and the next reporting cycle.', focus: 'people operations month-end checklists', sourceDate: '2026-08-11' },
];

export const august11BlogPosts = august11BlogSeeds.map(({ slug, title, description }) => ({ slug, title, excerpt: description, minutes: 10 }));
