export type August14BlogSeed = {
  slug: string;
  title: string;
  description: string;
  focus: string;
  sourceDate: '2026-08-14';
};

// Each article owns its publication date in this source record.
export const august14BlogSeeds: August14BlogSeed[] = [
  { slug: 'philippines-hr-employee-file-source-map', title: 'Philippines HR employee-file source maps: make records easier to find', description: 'Create a consistent employee-file source map with source labels, approved locations, and clear handling for missing or sensitive records.', focus: 'employee-file source maps', sourceDate: '2026-08-14' },
  { slug: 'philippines-hr-new-hire-first-week-check-ins', title: 'Philippines HR first-week check-ins: coordinate the follow-up', description: 'Coordinate new-hire check-ins, collect approved notes, and route concerns while managers retain responsibility for the employee experience.', focus: 'new-hire first-week check-ins', sourceDate: '2026-08-14' },
  { slug: 'philippines-hr-employee-address-change-administration', title: 'Philippines HR address-change administration: keep the record traceable', description: 'Route employee address changes from an approved request to the right systems with a visible source and owner review.', focus: 'employee address-change administration', sourceDate: '2026-08-14' },
  { slug: 'philippines-hr-annual-review-evidence-collection', title: 'Philippines HR annual-review evidence collection: protect manager judgment', description: 'Collect review-cycle evidence and missing inputs without rewriting feedback or making performance decisions.', focus: 'annual-review evidence collection', sourceDate: '2026-08-14' },
  { slug: 'philippines-hr-employee-emergency-contact-updates', title: 'Philippines HR emergency-contact updates: check the handoff', description: 'Track emergency-contact update requests with identity checks, approved storage, and a clear path for sensitive questions.', focus: 'emergency-contact updates', sourceDate: '2026-08-14' },
  { slug: 'philippines-hr-training-enrollment-coordination', title: 'Philippines HR training enrollment coordination: track seats and exceptions', description: 'Coordinate approved training enrollment, reminders, and completion evidence while owners decide eligibility and exceptions.', focus: 'training enrollment coordination', sourceDate: '2026-08-14' },
  { slug: 'philippines-hr-employee-status-letter-preparation', title: 'Philippines HR status-letter preparation: keep the source approved', description: 'Prepare routine employment-status letters from approved inputs while qualified owners control wording, review, and release.', focus: 'employee status-letter preparation', sourceDate: '2026-08-14' },
  { slug: 'philippines-hr-hris-duplicate-record-review', title: 'Philippines HRIS duplicate-record review: separate evidence from correction', description: 'Find possible duplicate employee records and route evidence to the system owner without merging or deleting records by assumption.', focus: 'HRIS duplicate-record review', sourceDate: '2026-08-14' },
  { slug: 'philippines-hr-employee-portal-access-requests', title: 'Philippines HR employee-portal access requests: verify before routing', description: 'Organize employee-portal access requests with identity, system ownership, and completion evidence.', focus: 'employee-portal access requests', sourceDate: '2026-08-14' },
  { slug: 'philippines-hr-leave-calendar-coordination', title: 'Philippines HR leave-calendar coordination: keep dates and owners clear', description: 'Coordinate approved leave dates and reminders without deciding eligibility, changing balances, or answering policy exceptions.', focus: 'leave-calendar coordination', sourceDate: '2026-08-14' },
  { slug: 'philippines-hr-employee-file-correction-routing', title: 'Philippines HR employee-file corrections: route the request safely', description: 'Track requests to correct employee records with the original source, requested change, approver, and final confirmation.', focus: 'employee-file correction routing', sourceDate: '2026-08-14' },
  { slug: 'philippines-hr-manager-people-data-review', title: 'Philippines HR manager people-data reviews: prepare a clean exception list', description: 'Prepare manager review lists from approved HR data and surface gaps without exposing unrelated employee information.', focus: 'manager people-data reviews', sourceDate: '2026-08-14' },
  { slug: 'philippines-hr-employee-handbook-question-routing', title: 'Philippines HR handbook question routing: link answers to the right source', description: 'Route handbook questions to current approved material while HR owners handle interpretation and exceptions.', focus: 'employee handbook question routing', sourceDate: '2026-08-14' },
  { slug: 'philippines-hr-employee-communication-acknowledgement', title: 'Philippines HR communication acknowledgements: distinguish delivery from understanding', description: 'Track delivery and acknowledgement evidence for approved employee communications without treating a missing signal as agreement.', focus: 'employee communication acknowledgements', sourceDate: '2026-08-14' },
  { slug: 'philippines-hr-recruiting-interview-packet-preparation', title: 'Philippines recruiting interview packets: prepare consistent materials', description: 'Assemble approved interview materials and schedules while hiring owners retain evaluation and selection responsibility.', focus: 'recruiting interview packet preparation', sourceDate: '2026-08-14' },
  { slug: 'philippines-hr-candidate-withdrawal-administration', title: 'Philippines candidate withdrawal administration: close the loop carefully', description: 'Record candidate withdrawal notices, update approved stages, and route follow-up without inventing reasons or changing hiring decisions.', focus: 'candidate withdrawal administration', sourceDate: '2026-08-14' },
  { slug: 'philippines-hr-employee-file-audit-preparation', title: 'Philippines HR employee-file audit preparation: show what needs attention', description: 'Prepare a focused employee-file review from approved criteria and route missing or sensitive items to the responsible owner.', focus: 'employee-file audit preparation', sourceDate: '2026-08-14' },
  { slug: 'philippines-hr-people-ops-calendar-inventory', title: 'Philippines HR people-ops calendar inventory: find recurring commitments', description: 'Inventory recurring people-ops dates, owners, and source records so deadlines are visible before they become urgent.', focus: 'people-ops calendar inventory', sourceDate: '2026-08-14' },
  { slug: 'philippines-hr-employee-document-signature-tracking', title: 'Philippines HR document-signature tracking: keep completion evidence intact', description: 'Track approved document signature requests and completed files without changing terms or treating silence as consent.', focus: 'employee document-signature tracking', sourceDate: '2026-08-14' },
  { slug: 'philippines-hr-hris-field-definition-register', title: 'Philippines HRIS field-definition registers: reduce inconsistent updates', description: 'Maintain a plain-language field register with source ownership, allowed updates, and escalation points for HR data work.', focus: 'HRIS field-definition registers', sourceDate: '2026-08-14' },
  { slug: 'philippines-hr-employee-request-progress-notes', title: 'Philippines HR employee-request progress notes: say what is actually known', description: 'Prepare accurate progress notes from the request record while sensitive explanations and final decisions stay with HR owners.', focus: 'employee-request progress notes', sourceDate: '2026-08-14' },
  { slug: 'philippines-hr-people-ops-handoff-notes', title: 'Philippines HR people-ops handoff notes: make open work usable', description: 'Write concise handoff notes that show status, owner, next action, and evidence without copying unnecessary employee detail.', focus: 'people-ops handoff notes', sourceDate: '2026-08-14' },
];

export const august14BlogPosts = august14BlogSeeds.map(({ slug, title, description }) => ({ slug, title, excerpt: description, minutes: 10 }));
