export type August13BlogSeed = {
  slug: string;
  title: string;
  description: string;
  focus: string;
  sourceDate: '2026-08-13';
};

// Each article owns its publication date in this source record.
export const august13BlogSeeds: August13BlogSeed[] = [
  { slug: 'philippines-hr-workforce-planning-intake', title: 'Philippines HR workforce planning intake: turn requests into a clear brief', description: 'Organize workforce planning requests with source notes, decision owners, and a practical handoff for Philippines-based HR support.', focus: 'workforce planning intake', sourceDate: '2026-08-13' },
  { slug: 'philippines-hr-performance-cycle-calendar-support', title: 'Philippines HR performance-cycle calendar support: keep reviews on track', description: 'Coordinate review dates, reminders, and missing inputs while managers retain responsibility for feedback and performance decisions.', focus: 'performance-cycle calendar support', sourceDate: '2026-08-13' },
  { slug: 'philippines-hr-recognition-nomination-tracking', title: 'Philippines HR recognition nomination tracking: make the handoff visible', description: 'Track recognition nominations from approved submissions and route eligibility or sensitive questions to the right owner.', focus: 'recognition nomination tracking', sourceDate: '2026-08-13' },
  { slug: 'philippines-hris-integration-issue-log', title: 'Philippines HRIS integration issue logs: give every mismatch an owner', description: 'Maintain a useful HRIS issue log with affected records, evidence, next actions, and clear escalation boundaries.', focus: 'HRIS integration issue logging', sourceDate: '2026-08-13' },
  { slug: 'philippines-hr-accommodation-document-routing', title: 'Philippines HR accommodation document routing: protect the sensitive handoff', description: 'Route accommodation documentation through approved channels while qualified HR owners handle confidential decisions and communications.', focus: 'accommodation document routing', sourceDate: '2026-08-13' },
  { slug: 'philippines-hr-benefits-enrollment-exception-tracking', title: 'Philippines HR benefits enrollment exceptions: track gaps without guessing', description: 'Track missing enrollment inputs and carrier questions while benefits owners decide eligibility, corrections, and employee advice.', focus: 'benefits enrollment exception tracking', sourceDate: '2026-08-13' },
  { slug: 'philippines-hr-employee-lifecycle-checklist', title: 'Philippines HR employee lifecycle checklist: connect the handoffs', description: 'Use one lifecycle checklist to connect hiring, onboarding, changes, leave, and exit administration without losing ownership.', focus: 'employee lifecycle checklists', sourceDate: '2026-08-13' },
  { slug: 'philippines-hr-meeting-agenda-preparation', title: 'Philippines HR meeting agenda preparation: make owner decisions easier', description: 'Prepare concise HR meeting agendas from open work, evidence, and decisions that need an accountable owner.', focus: 'HR meeting agenda preparation', sourceDate: '2026-08-13' },
  { slug: 'philippines-hr-policy-review-calendar', title: 'Philippines HR policy review calendars: keep review dates useful', description: 'Track policy review dates, source versions, and owners without asking support staff to interpret or rewrite policy.', focus: 'HR policy review calendars', sourceDate: '2026-08-13' },
  { slug: 'philippines-hr-candidate-reference-check-coordination', title: 'Philippines candidate reference-check coordination: control the follow-up', description: 'Coordinate approved reference-check requests and responses while hiring owners retain consent, evaluation, and selection decisions.', focus: 'candidate reference-check coordination', sourceDate: '2026-08-13' },
  { slug: 'philippines-hr-onboarding-buddy-coordination', title: 'Philippines HR onboarding buddy coordination: support the first connection', description: 'Coordinate buddy assignments, introductions, and reminders from an approved plan with a named onboarding owner.', focus: 'onboarding buddy coordination', sourceDate: '2026-08-13' },
  { slug: 'philippines-hr-service-catalog-maintenance', title: 'Philippines HR service catalog maintenance: make help easier to route', description: 'Maintain an HR service catalog with request types, owners, source links, and escalation rules for recurring employee support.', focus: 'HR service catalog maintenance', sourceDate: '2026-08-13' },
  { slug: 'philippines-hr-manager-action-tracking', title: 'Philippines HR manager action tracking: close the loop after meetings', description: 'Track approved manager actions, dates, and evidence so HR follow-up does not disappear between meetings.', focus: 'manager action tracking', sourceDate: '2026-08-13' },
  { slug: 'philippines-hr-employee-survey-response-routing', title: 'Philippines HR employee survey response routing: separate themes from cases', description: 'Organize survey responses and route urgent or personal matters without treating anonymous feedback as an employee case.', focus: 'employee survey response routing', sourceDate: '2026-08-13' },
  { slug: 'philippines-hr-document-translation-coordination', title: 'Philippines HR document translation coordination: preserve the source version', description: 'Coordinate approved HR document translations with source control, reviewer ownership, and a visible status trail.', focus: 'HR document translation coordination', sourceDate: '2026-08-13' },
  { slug: 'philippines-hr-compensation-cycle-administration', title: 'Philippines HR compensation-cycle administration: protect the approval boundary', description: 'Prepare compensation-cycle files and reminders from approved inputs while leaders retain decisions, access, and employee communications.', focus: 'compensation-cycle administration', sourceDate: '2026-08-13' },
  { slug: 'philippines-hr-absence-certification-tracking', title: 'Philippines HR absence certification tracking: flag missing records carefully', description: 'Track approved absence documentation and deadlines while qualified owners handle medical, legal, and eligibility questions.', focus: 'absence certification tracking', sourceDate: '2026-08-13' },
  { slug: 'philippines-hr-organization-change-communication-prep', title: 'Philippines HR organization-change communication prep: keep the source approved', description: 'Prepare logistics and approved drafts for organization changes without announcing decisions or inventing employee details.', focus: 'organization-change communication preparation', sourceDate: '2026-08-13' },
  { slug: 'philippines-hr-new-manager-question-routing', title: 'Philippines HR new-manager question routing: build a dependable first stop', description: 'Capture new-manager questions, connect them to approved resources, and route policy interpretation to the right HR owner.', focus: 'new-manager question routing', sourceDate: '2026-08-13' },
  { slug: 'philippines-hr-records-access-request-log', title: 'Philippines HR records access request logs: show who should act', description: 'Track employee-record access requests with identity, scope, approval, and completion evidence while owners control disclosure.', focus: 'HR records access request logging', sourceDate: '2026-08-13' },
  { slug: 'philippines-hr-handbook-version-control', title: 'Philippines HR handbook version control: stop outdated answers', description: 'Keep handbook versions, approval dates, and approved links visible so support staff can route questions to current sources.', focus: 'HR handbook version control', sourceDate: '2026-08-13' },
  { slug: 'philippines-hr-interview-debrief-logistics', title: 'Philippines HR interview debrief logistics: prepare the room for decisions', description: 'Coordinate debrief schedules, scorecard reminders, and approved materials while interviewers retain candidate judgments.', focus: 'interview debrief logistics', sourceDate: '2026-08-13' },
];

export const august13BlogPosts = august13BlogSeeds.map(({ slug, title, description }) => ({ slug, title, excerpt: description, minutes: 10 }));
