export type August17BlogSeed = {
  slug: string;
  title: string;
  description: string;
  focus: string;
  sourceDate: '2026-08-17';
};

// Each August 17 article owns its publication date in this source record.
export const august17BlogSeeds: August17BlogSeed[] = [
  { slug: 'philippines-hr-after-hours-inbox-escalation', title: 'Philippines HR after-hours inbox escalation: define the handoff', description: 'Set a clear after-hours route for Philippines-based HR support so urgent messages reach an authorized owner without turning every message into an emergency.', focus: 'after-hours inbox escalation', sourceDate: '2026-08-17' },
  { slug: 'philippines-hr-start-date-change-coordination', title: 'Philippines HR start-date changes: keep onboarding records aligned', description: 'Coordinate approved start-date changes across calendars, checklists, and onboarding records while the hiring owner controls the decision and communication.', focus: 'start-date change coordination', sourceDate: '2026-08-17' },
  { slug: 'philippines-hr-payroll-cutoff-calendar-support', title: 'Philippines HR payroll cutoff calendars: track inputs without approving pay', description: 'Maintain a payroll-input calendar with source records, cutoff reminders, and exception owners while payroll and HR leaders approve the final data.', focus: 'payroll cutoff calendar support', sourceDate: '2026-08-17' },
  { slug: 'philippines-hr-manager-request-intake-design', title: 'Philippines HR manager request intake: ask for the facts first', description: 'Design a manager request intake that captures the issue, requested outcome, source record, and owner without inviting unsupported employment judgments.', focus: 'manager request intake', sourceDate: '2026-08-17' },
  { slug: 'philippines-recruiting-interview-reschedule-control', title: 'Philippines recruiting interview reschedules: protect candidate communication', description: 'Handle interview changes with approved messages, calendar checks, and a visible owner for conflicts or candidate concerns.', focus: 'interview reschedule control', sourceDate: '2026-08-17' },
  { slug: 'philippines-hr-employee-name-correction-routing', title: 'Philippines HR employee name corrections: preserve the original request', description: 'Route name-correction requests from an approved source to the right system owner while keeping identity checks and change evidence together.', focus: 'employee name-correction routing', sourceDate: '2026-08-17' },
  { slug: 'philippines-hr-confidential-case-routing', title: 'Philippines HR confidential case routing: minimize what the queue reveals', description: 'Build a narrow routing record for sensitive HR matters so support staff can move the handoff without copying private case detail into a broad queue.', focus: 'confidential case routing', sourceDate: '2026-08-17' },
  { slug: 'philippines-hr-return-to-work-coordination-planning', title: 'Philippines HR return-to-work coordination: track steps, not medical conclusions', description: 'Coordinate approved return-to-work logistics and checkpoints while qualified owners handle medical information, accommodations, and employment decisions.', focus: 'return-to-work coordination', sourceDate: '2026-08-17' },
  { slug: 'philippines-hr-benefits-life-event-intake', title: 'Philippines HR benefits life-event intake: separate documents from eligibility', description: 'Collect and route benefits life-event documents with a source checklist while plan owners decide eligibility, deadlines, and employee advice.', focus: 'benefits life-event intake', sourceDate: '2026-08-17' },
  { slug: 'philippines-hr-manager-self-service-catalog', title: 'Philippines HR manager self-service catalogs: make the first request easier', description: 'Create a manager-facing HR request catalog with plain-language categories, required fields, current sources, and escalation boundaries.', focus: 'manager self-service catalogs', sourceDate: '2026-08-17' },
  { slug: 'philippines-hr-policy-exception-evidence-packet', title: 'Philippines HR policy exceptions: prepare an evidence packet without deciding', description: 'Assemble the source, request, policy version, and open questions for a policy exception while the authorized HR owner makes the decision.', focus: 'policy exception evidence packets', sourceDate: '2026-08-17' },
  { slug: 'philippines-hr-probation-review-reminders', title: 'Philippines HR probation review reminders: keep the decision with the manager', description: 'Track probation review dates, missing inputs, and approved reminders without writing performance conclusions or deciding an employee outcome.', focus: 'probation review reminders', sourceDate: '2026-08-17' },
  { slug: 'philippines-hr-exit-property-custody-log', title: 'Philippines HR exit property custody logs: reconcile each handoff', description: 'Track company property through an employee exit with custody, receipt, inspection, and exception fields that keep the responsible owner visible.', focus: 'exit property custody logs', sourceDate: '2026-08-17' },
  { slug: 'philippines-hr-employment-verification-routing', title: 'Philippines HR employment verification requests: verify the requester and source', description: 'Route employment verification requests through identity, authorization, and approved-source checks while the employer controls what may be disclosed.', focus: 'employment verification routing', sourceDate: '2026-08-17' },
  { slug: 'philippines-hr-employee-data-export-request', title: 'Philippines HR employee data export requests: define scope before retrieval', description: 'Prepare employee data export requests with a declared scope, source list, access boundary, and review owner before any response is released.', focus: 'employee data export requests', sourceDate: '2026-08-17' },
  { slug: 'philippines-recruiting-requisition-approval-packet', title: 'Philippines recruiting requisition approval packets: show what is ready', description: 'Prepare a requisition packet from approved role information, budget authority, and hiring steps while leaders retain approval and selection decisions.', focus: 'requisition approval packets', sourceDate: '2026-08-17' },
  { slug: 'philippines-recruiting-candidate-profile-duplicate-review', title: 'Philippines recruiting duplicate candidate profiles: compare evidence before merging', description: 'Flag possible duplicate candidate records and route the evidence without merging profiles or guessing which record should remain authoritative.', focus: 'duplicate candidate profile review', sourceDate: '2026-08-17' },
  { slug: 'philippines-recruiting-interview-panel-availability', title: 'Philippines recruiting interview-panel availability: set rules for conflicts', description: 'Coordinate panel availability with defined priority rules, owner confirmation, and candidate-safe communication when schedules collide.', focus: 'interview-panel availability', sourceDate: '2026-08-17' },
  { slug: 'philippines-hris-effective-date-change-queue', title: 'Philippines HRIS effective-date changes: distinguish entry from effect', description: 'Track HRIS changes by requested date, entry date, approval, and downstream acknowledgment so a saved field is not mistaken for an effective change.', focus: 'HRIS effective-date change queues', sourceDate: '2026-08-17' },
  { slug: 'philippines-hr-new-hire-equipment-request-routing', title: 'Philippines HR new-hire equipment requests: route the dependency chain', description: 'Coordinate approved equipment requests across HR, IT, and the manager with clear dependencies, dates, and exception ownership.', focus: 'new-hire equipment request routing', sourceDate: '2026-08-17' },
  { slug: 'philippines-hr-employee-language-support-routing', title: 'Philippines HR employee language-support requests: route without rewriting meaning', description: 'Coordinate language-support requests with the original message, qualified reviewer, and approved delivery channel while preserving the employee’s meaning.', focus: 'employee language-support routing', sourceDate: '2026-08-17' },
  { slug: 'philippines-hr-open-case-handoff-register', title: 'Philippines HR open-case handoff registers: make ownership visible', description: 'Create a minimal handoff register for open HR work with status, next action, owner, and approved evidence, without duplicating sensitive case narratives.', focus: 'open-case handoff registers', sourceDate: '2026-08-17' },
];

export const august17BlogPosts = august17BlogSeeds.map(({ slug, title, description }) => ({ slug, title, excerpt: description, minutes: 10 }));
