export type DailySeed = { slug: string; title: string; description: string; focus: string };

export const dailySeeds: DailySeed[] = [
  ['philippines-hr-case-intake-routing','Philippines HR case intake routing: protect the first handoff','Create a controlled HR case intake lane with minimum-necessary details, priority tags, and named escalation owners.','HR case intake routing'],
  ['philippines-employee-file-audit-workflow','Philippines employee file audit workflow: find gaps safely','Review employee files for completeness and route missing evidence without changing records outside an approved process.','employee file audits'],
  ['philippines-hr-knowledge-base-maintenance','Philippines HR knowledge base maintenance: keep answers current','Maintain approved HR help content with source dates, owner review, and a clear path for policy questions.','HR knowledge base maintenance'],
  ['philippines-recruiting-requisition-administration','Philippines recruiting requisition administration: control the request','Keep role requests, approvals, status changes, and hiring-owner decisions visible in one recruiting workflow.','recruiting requisition administration'],
  ['philippines-reference-check-coordination','Philippines reference check coordination: document the boundary','Coordinate approved reference-check steps while keeping consent, interpretation, and hiring decisions with the owner.','reference check coordination'],
  ['philippines-hr-survey-administration','Philippines HR survey administration: protect response handling','Set up survey distribution, reminders, and response tracking without exposing unnecessary employee information.','HR survey administration'],
  ['philippines-employee-letter-preparation','Philippines employee letter preparation: use an approval gate','Prepare routine employee letters from approved templates and route exceptions before anything is issued.','employee letter preparation'],
  ['philippines-hr-absence-tracking-support','Philippines HR absence tracking support: make status visible','Track absence records and follow-ups using approved sources while managers retain approval and accommodation decisions.','absence tracking support'],
  ['philippines-hr-org-chart-maintenance','Philippines HR org chart maintenance: prevent stale reporting lines','Maintain organizational data from approved changes with version checks and owner signoff.','org chart maintenance'],
  ['philippines-hr-new-manager-support-workflow','Philippines new manager HR support: build a safe workflow','Give new managers repeatable administrative support with clear escalation for employee, policy, and performance questions.','new manager HR support'],
  ['philippines-hr-training-invitation-coordination','Philippines HR training invitation coordination: close the loop','Coordinate training invitations, attendance, reminders, and completion evidence with an accountable program owner.','training invitation coordination'],
  ['philippines-hr-document-retention-review','Philippines HR document retention review: route the decision','Prepare a retention review queue with source records, dates, and owner decisions instead of deleting records by assumption.','HR document retention review'],
  ['philippines-hr-employee-announcement-workflow','Philippines employee announcement workflow: approve before sending','Draft and route routine employee announcements from approved copy while sensitive messages stay with HR leadership.','employee announcement workflow'],
  ['philippines-hr-people-analytics-data-preparation','Philippines people analytics data preparation: check the source','Prepare aggregated people data with clear definitions, access limits, and review before reporting.','people analytics data preparation'],
  ['philippines-hr-policy-update-implementation','Philippines HR policy update implementation: track the handoff','Coordinate policy update tasks, acknowledgements, and questions without interpreting policy for employees.','HR policy update implementation'],
  ['philippines-hr-employee-feedback-routing','Philippines employee feedback routing: make escalation explicit','Collect and route employee feedback using approved channels, confidentiality boundaries, and named owners.','employee feedback routing'],
  ['philippines-hr-employee-directory-cleanup','Philippines HR employee directory cleanup: verify before changing','Clean approved directory fields through evidence checks, change logs, and owner review.','employee directory cleanup'],
  ['philippines-hr-offer-document-coordination','Philippines HR offer document coordination: keep approvals separate','Coordinate offer document preparation and status while compensation, terms, and final approval remain with authorized owners.','offer document coordination'],
  ['philippines-hr-employee-status-reporting','Philippines HR employee status reporting: define the source of truth','Prepare recurring status reports from approved records and route discrepancies before publication.','employee status reporting'],
  ['philippines-hr-policy-question-escalation','Philippines HR policy question escalation: stop at interpretation','Sort routine policy questions from requests that require qualified HR or legal review.','HR policy question escalation'],
  ['philippines-hr-employee-recognition-administration','Philippines employee recognition administration: keep the process fair','Coordinate recognition nominations and records from approved criteria without making eligibility or employment decisions.','employee recognition administration'],
  ['philippines-hr-return-to-work-coordination','Philippines return-to-work coordination: protect sensitive handoffs','Track approved return-to-work logistics and route medical, accommodation, and policy questions to the right owner.','return-to-work coordination'],
  ['philippines-hr-people-operations-calendar','Philippines people operations calendar: build one reliable cadence','Run a shared people-operations calendar with owners, deadlines, reminders, and completion evidence.','people operations calendar'],
  ['philippines-hr-process-exception-log','Philippines HR process exception log: turn surprises into controls','Maintain an exception log that shows what stopped, who decided, and what the playbook should learn.','HR process exception logging'],
  ['philippines-hr-employee-milestone-tracking','Philippines HR employee milestone tracking: make follow-up reliable','Track approved employee milestones and reminders with a clear owner, source record, and escalation path.','employee milestone tracking']
  ,['philippines-hr-job-description-maintenance','Philippines HR job description maintenance: control the source','Keep job descriptions current through owner approval, version history, and a clear route for changes.','job description maintenance']
  ,['philippines-hr-candidate-consent-records','Philippines candidate consent records: track the evidence','Track candidate consent records from approved sources and escalate missing or unclear permissions.','candidate consent record tracking']
  ,['philippines-hr-background-check-coordination','Philippines background check coordination: keep the handoff clear','Coordinate approved background-check steps while qualified owners handle consent, interpretation, and decisions.','background check coordination']
  ,['philippines-hr-interview-panel-preparation','Philippines interview panel preparation: make the setup repeatable','Prepare interview panels, schedules, packets, and reminders without influencing candidate evaluation.','interview panel preparation']
  ,['philippines-hr-new-hire-equipment-tracking','Philippines new hire equipment tracking: close the logistics loop','Track approved equipment requests, delivery status, and handoff evidence with a named owner.','new hire equipment tracking']
  ,['philippines-hr-onboarding-access-request-routing','Philippines onboarding access requests: route least-privilege setup','Route new-hire access requests from approved records and flag missing approvals before provisioning.','onboarding access request routing']
  ,['philippines-hr-benefits-deadline-reminders','Philippines benefits deadline reminders: use an owner-approved cadence','Coordinate benefits reminders and completion tracking while eligibility and advice remain with qualified owners.','benefits deadline reminders']
  ,['philippines-hr-employee-survey-follow-up','Philippines employee survey follow-up: protect the response boundary','Coordinate survey reminders and aggregate follow-up without exposing unnecessary response details.','employee survey follow-up']
  ,['philippines-hr-manager-forms-support','Philippines manager HR forms support: check before routing','Help managers complete approved HR forms with required-field checks and escalation for judgment calls.','manager HR forms support']
  ,['philippines-hr-performance-cycle-administration','Philippines performance cycle administration: track the process','Track review deadlines, meeting logistics, and completion evidence while managers own performance judgments.','performance cycle administration']
  ,['philippines-hr-learning-records-administration','Philippines learning records administration: reconcile completion evidence','Maintain approved learning records, attendance evidence, and reminders without deciding employee eligibility.','learning records administration']
  ,['philippines-hr-employee-handbook-version-control','Philippines employee handbook version control: prevent stale copies','Track handbook versions, approvals, acknowledgements, and distribution so employees receive current material.','employee handbook version control']
  ,['philippines-hr-policy-inbox-triage','Philippines HR policy inbox triage: route with context','Sort policy questions by topic, source, urgency, and owner without interpreting policy or giving legal advice.','policy inbox triage']
  ,['philippines-hr-employee-complaint-intake-support','Philippines employee complaint intake support: protect the first response','Record and route complaint intake from approved channels while investigations and employee communications remain with qualified owners.','employee complaint intake support']
  ,['philippines-hr-absence-document-follow-up','Philippines absence document follow-up: track without overreaching','Track approved absence documentation and reminders while medical, accommodation, and leave decisions stay with the right owner.','absence document follow-up']
  ,['philippines-hr-employee-address-change-workflow','Philippines employee address change workflow: verify before updating','Route employee address changes through source checks, owner approval, and a visible change record.','employee address change workflow']
  ,['philippines-hr-employee-manager-change-log','Philippines employee manager change log: preserve the handoff','Record approved reporting-line changes and notify affected workflow owners without making organizational decisions.','employee manager change logging']
  ,['philippines-hr-hris-data-reconciliation','Philippines HRIS data reconciliation: compare before correcting','Compare approved HR records across systems, flag discrepancies, and route corrections to authorized owners.','HRIS data reconciliation']
  ,['philippines-hr-recruiting-source-tracking','Philippines recruiting source tracking: keep attribution usable','Maintain recruiting source fields and campaign notes from approved data without overstating hiring performance.','recruiting source tracking']
  ,['philippines-hr-candidate-interview-reminders','Philippines candidate interview reminders: keep communication approved','Coordinate candidate reminders and confirmations with approved templates and escalation for changes or sensitive questions.','candidate interview reminders']
  ,['philippines-hr-offer-approval-tracking','Philippines offer approval tracking: separate preparation from decision','Track offer approvals, document status, and handoffs while compensation, terms, and final decisions remain with authorized owners.','offer approval tracking']
  ,['philippines-hr-employee-file-indexing','Philippines employee file indexing: make records findable','Index approved employee records by source, type, date, and owner without changing content or retention decisions.','employee file indexing']
  ,['philippines-hr-employee-record-correction-routing','Philippines employee record correction routing: verify the request','Route employee record correction requests with source evidence, owner review, and a clear audit trail.','employee record correction routing']
].map(([slug, title, description, focus]) => ({ slug, title, description, focus }));

export const dailyBlogPosts = dailySeeds.map(({ slug, title, description }) => ({ slug, title, excerpt: description, minutes: 9 }));
