import { buildBlogBatch, type BlogBatchTopic } from './september22-batch';

// Cycle label only. Reconcile this value to each route's actual first-live UTC date
// immediately before the sole combined production push.
export const october2CycleDate = '2026-10-02';
const prefix = 'october2-hr-';

export const october2Topics: BlogBatchTopic[] = [
  { slug: 'employee-name-change-system-sequence', title: 'Sequence an Employee Name Change Across HR Systems', description: 'Build an evidence-led name-change queue that keeps identity, payroll, benefits, directory, and access records synchronized without letting support staff decide legal sufficiency.', workflow: 'employee name change system sequencing', trigger: 'an authenticated employee submits the employer-required change evidence through an approved channel', owner: 'the employer HR, payroll, benefits, security, privacy, and legal owners', stop: 'identity, required evidence, effective date, tax treatment, benefits treatment, system authority, or conflicting names are unclear', proof: 'the HR owner approves the controlling identity record and each required destination acknowledges the same authorized value or a documented exception', service: 'employee-records-administration', example: 'The HRIS accepts a new surname while payroll rejects it and the company directory updates before the employee chooses how the change should be displayed', source: { name: 'Social Security Administration — Employer W-2 Filing Instructions', url: 'https://www.ssa.gov/employer/', note: 'Official employer resources concerning names and Social Security wage reporting.' } },
  { slug: 'manager-access-transfer-checklist', title: 'Transfer Manager Access Without Copying Sensitive HR Permissions', description: 'Coordinate reporting-line changes, approvals, delegated work, and access reviews without cloning a former manager’s full HR visibility.', workflow: 'manager access transfer coordination', trigger: 'the authorized HR owner releases an approved manager change with an effective time and affected population', owner: 'the employer HRIS, security, privacy, HR, payroll, and application owners', stop: 'reporting scope, effective timing, confidential cases, inherited groups, segregation of duties, or a temporary delegation needs judgment', proof: 'each application owner confirms the approved role assignment and removal, with restricted cases reassigned by their qualified owner', service: 'employee-records-administration', example: 'A new manager needs timecard approvals on Monday but should not inherit access to an open employee-relations case held by the prior manager', source: { name: 'NIST Cybersecurity Framework 2.0', url: 'https://www.nist.gov/cyberframework', note: 'Official framework supporting governed identity and access control practices.' } },
  { slug: 'candidate-withdrawal-record-handoff', title: 'Handle Candidate Withdrawals Without Erasing Recruiting Evidence', description: 'Record a candidate-directed withdrawal, stop future activity, and preserve the required recruiting history without rewriting prior stages.', workflow: 'candidate withdrawal record handoff', trigger: 'a candidate submits an authenticated withdrawal or an authorized recruiter records the candidate’s clear instruction', owner: 'the employer recruiting, privacy, HR, legal, and hiring owners', stop: 'identity, withdrawal scope, pending offer, accommodation, complaint, deletion request, agency ownership, or retention treatment is unclear', proof: 'recruiting confirms the candidate is no longer active, scheduled actions are cancelled, and the retained record accurately preserves the source and disposition', service: 'interview-coordination', example: 'A candidate withdraws from one role while asking to remain under consideration for another opening handled by a different recruiter', source: { name: 'EEOC Recordkeeping Requirements', url: 'https://www.eeoc.gov/employers/recordkeeping-requirements', note: 'Official overview of federal employment recordkeeping requirements.' } },
  { slug: 'new-hire-start-date-change-control', title: 'Control a New Hire Start-Date Change Across Dependent Tasks', description: 'Move an approved start date through payroll, benefits, access, equipment, orientation, and manager calendars while preserving the original offer record.', workflow: 'new hire start-date change control', trigger: 'the authorized hiring or HR owner releases a dated start-date change for an identified accepted candidate', owner: 'the employer hiring, HR, payroll, benefits, IT, security, facilities, and legal owners', stop: 'offer terms, employee classification, eligibility, screening, work authorization, pay timing, location, or candidate agreement is uncertain', proof: 'the hiring and HR owners approve the new controlling date and every required dependency records a matching disposition or visible exception', service: 'onboarding-coordination', example: 'A manager moves a start by one week after a laptop ships and payroll has already created the worker for the original cycle', source: { name: 'USCIS Form I-9 Central', url: 'https://www.uscis.gov/i-9-central', note: 'Official employer resources for Form I-9 timing and responsibilities.' } },
  { slug: 'payroll-duplicate-employee-record-review', title: 'Review Duplicate Employee Records Before Payroll Processing', description: 'Detect and route possible duplicate worker records without merging identities, deleting history, or changing pay on an administrative assumption.', workflow: 'payroll duplicate employee record review', trigger: 'an approved payroll or HRIS control flags two records sharing defined identity or payment attributes', owner: 'the employer payroll, HRIS, HR, security, privacy, tax, and legal owners', stop: 'identity, rehire status, concurrent employment, entity, tax profile, bank account, pay history, or record ownership is uncertain', proof: 'the authorized owners document whether the records are distinct or approve a controlled correction, and payroll reconciles the affected cycle totals', service: 'payroll-preparation-support', example: 'A returning employee appears under a new worker ID while an older record remains active in a second employing entity', source: { name: 'U.S. Department of Labor Recordkeeping', url: 'https://www.dol.gov/general/topic/workhours/hoursrecordkeeping', note: 'Official federal overview of employer wage and hour recordkeeping responsibilities.' } },
  { slug: 'benefits-qualifying-event-document-status', title: 'Track Benefits Qualifying-Event Documents Without Deciding Eligibility', description: 'Run a dated document and carrier-status queue while the plan owner retains eligibility, coverage, deadline, and exception decisions.', workflow: 'benefits qualifying-event document status tracking', trigger: 'an authenticated participant or authorized plan owner opens a qualifying-event case through the approved benefits channel', owner: 'the employer plan administrator, benefits, payroll, privacy, carrier, and legal owners', stop: 'event type, eligibility, acceptable evidence, coverage tier, effective date, deadline, privacy, or plan terms require interpretation', proof: 'the plan owner records the authorized disposition and the carrier or system confirms the matching coverage action or documented rejection', service: 'benefits-administration-support', example: 'A participant reports a marriage before the plan deadline but uploads a document whose names do not match the current HR record', source: { name: 'U.S. Department of Labor — Health Plans and Benefits', url: 'https://www.dol.gov/general/topic/health-plans', note: 'Official resources concerning employer health plans and participant protections.' } },
  { slug: 'interview-no-show-recovery-workflow', title: 'Build a Fair Interview No-Show Recovery Workflow', description: 'Separate calendar failures, candidate communication, accommodation signals, and recruiter decisions before closing an application.', workflow: 'interview no-show recovery', trigger: 'the approved interview window ends without a verified candidate arrival or completed interview record', owner: 'the employer recruiter, hiring, accessibility, HR, privacy, and legal owners', stop: 'delivery failure, time-zone error, accommodation, emergency, recruiter delay, interviewer absence, candidate identity, or disposition needs judgment', proof: 'the authorized recruiter records the candidate-facing next step and the scheduling history identifies whether the event was completed, rescheduled, withdrawn, or closed', service: 'interview-coordination', example: 'A candidate misses a video interview after replying to an invitation with a captioning request that never reached the interviewer', source: { name: 'EEOC — Disability Discrimination and Employment Decisions', url: 'https://www.eeoc.gov/disability-discrimination-and-employment-decisions', note: 'Official EEOC information relevant to disability and employment processes.' } },
  { slug: 'policy-translation-review-handoff', title: 'Control the Review Handoff for Translated HR Policies', description: 'Coordinate translation versions, reviewer questions, publication, and acknowledgments while qualified owners retain legal and policy meaning.', workflow: 'translated HR policy review handoff', trigger: 'the policy owner releases an approved source version, target language, audience, translator, and review path', owner: 'the employer policy, legal, HR, communications, accessibility, and local-language reviewers', stop: 'source meaning, legal terminology, jurisdiction, audience literacy, accessibility, employee rights, or conflicting versions are unclear', proof: 'the policy owner approves the source and translated versions as a paired release and the publication record identifies the version each employee received', service: 'hr-help-desk-support', example: 'A translated leave policy uses a familiar local phrase that changes who appears eligible under the approved source text', source: { name: 'EEOC — National Origin Discrimination', url: 'https://www.eeoc.gov/national-origin-discrimination', note: 'Official EEOC information concerning national-origin discrimination, including language-related employment practices.' } },
  { slug: 'employee-survey-anonymity-operations', title: 'Protect Survey Anonymity During HR Survey Operations', description: 'Prepare rosters, reminders, exports, and reporting thresholds without exposing who responded or implying anonymity the system cannot provide.', workflow: 'employee survey anonymity operations', trigger: 'the authorized survey owner releases a defined audience, approved questions, privacy notice, platform configuration, and reporting rules', owner: 'the employer survey, privacy, HR, legal, analytics, and communications owners', stop: 'identity fields, small groups, free text, manager access, response tracing, retention, consent, or reporting thresholds are uncertain', proof: 'the survey owner approves the configured collection and final report, and the output follows the promised identity and minimum-group rules', service: 'reporting-and-qa', example: 'A manager asks for response status by name so the team can reach a participation target advertised as anonymous', source: { name: 'NIST Privacy Framework', url: 'https://www.nist.gov/privacy-framework', note: 'Official framework for identifying and managing privacy risk.' } },
  { slug: 'employee-refund-reimbursement-status', title: 'Track Employee Reimbursements Without Approving Expenses', description: 'Maintain receipt, approval, payment, rejection, and follow-up evidence while budget and payroll owners decide policy and tax treatment.', workflow: 'employee reimbursement status tracking', trigger: 'an authenticated employee submits an expense through the approved reimbursement channel with a case reference', owner: 'the employer finance, manager, payroll, tax, HR, and policy owners', stop: 'business purpose, receipt sufficiency, policy exception, approval authority, taxability, currency, duplicate payment, or wage treatment is unclear', proof: 'the authorized owner records approval or rejection and the payment destination confirms the matching amount, currency, employee, and cycle', service: 'payroll-preparation-support', example: 'An employee submits a home-office purchase after a manager approved it in chat but the expense system has no policy category for the item', source: { name: 'IRS Publication 15-B', url: 'https://www.irs.gov/publications/p15b', note: 'Official IRS guide to employer tax treatment of fringe benefits.' } },
  { slug: 'disciplinary-meeting-record-routing', title: 'Route Disciplinary Meeting Records Without Expanding Access', description: 'Coordinate approved notices, attendance, acknowledgment, restricted filing, and follow-up while managers and HR retain every substantive decision.', workflow: 'disciplinary meeting record routing', trigger: 'the authorized HR or employee-relations owner opens a restricted case with approved participants, timing, and documents', owner: 'the employer manager, HR, employee-relations, privacy, legal, labor, and security owners', stop: 'facts, discipline, representation, accommodation, leave, retaliation, safety, protected activity, signature refusal, or communication content needs judgment', proof: 'the authorized case owner records the meeting disposition, approved document version, acknowledgment status, and restricted record location', service: 'performance-review-administration', example: 'An employee refuses to sign a notice and tells the coordinator the action followed a safety complaint', source: { name: 'OSHA — Whistleblower Protections', url: 'https://www.whistleblowers.gov/', note: 'Official resources concerning protected reports and anti-retaliation provisions administered by OSHA.' } },
  { slug: 'hr-vendor-contact-change-verification', title: 'Verify HR Vendor Contact Changes Before Sensitive Handoffs', description: 'Authenticate new vendor contacts and delivery instructions before releasing employee data, approving access, or redirecting payments.', workflow: 'HR vendor contact change verification', trigger: 'an approved vendor or company owner requests a contact, domain, portal, destination, or authorized-recipient change', owner: 'the employer procurement, security, privacy, HR, finance, legal, and vendor owners', stop: 'identity, authority, contract scope, domain, bank details, data destination, permission, or urgency conflicts with the trusted record', proof: 'the company owner verifies the change through a pre-established channel and each affected access, transfer, or payment workflow records the approved destination', service: 'operations-support', example: 'A benefits vendor email asks HR to upload a census to a new file-sharing domain before the normal monthly cutoff', source: { name: 'FTC — Start with Security', url: 'https://www.ftc.gov/business-guidance/resources/start-security-guide-business', note: 'Official business guidance concerning access controls, data handling, and service-provider oversight.' } },
];

export const october2BlogPosts = october2Topics.map(({ slug, title, description }) => ({
  slug: `${prefix}${slug}`,
  title,
  excerpt: description,
  minutes: 12,
  published: october2CycleDate,
}));

// This first draft deliberately centralizes schema-complete content. Each article's
// sections receive a topic-specific qualitative rewrite before the combined gate.
export const october2Articles = buildBlogBatch(october2CycleDate, prefix, october2Topics);
