import type { RichArticle } from './article-data';
import { october5BlogDate } from './october5-blog-batch';

const slug = 'compare-hr-outsourcing-proposals-scope-controls-cost';
export const october5ProposalPost = { slug, title: 'How to Compare HR Outsourcing Proposals Beyond the Headline Price', excerpt: 'Normalize scope, workload assumptions, decision boundaries, controls, transition effort, and exit obligations before comparing HR outsourcing fees.', minutes: 16, published: october5BlogDate } as const;

const sections: RichArticle['sections'] = [
  { heading: 'Convert each proposal into the same unit of work', paragraphs: [
    'Two providers can use the same service label while pricing different work. One onboarding package may cover checklist tracking and reminders; another may include document preparation, system entry, orientation scheduling, and first-week follow-up. Rewrite every proposal as observable tasks with an intake event, permitted action, destination, company decision owner, frequency, and completion evidence. Mark exclusions and optional services beside the task rather than in a separate notes column. Only then can a buyer see whether a lower fee reflects efficiency or a smaller obligation.',
    'Choose comparison units that match actual demand. Employee count alone may be poor for a company with seasonal hiring, multiple payroll cycles, frequent job changes, or many manager questions. Use recent volumes for hires, exits, interviews, record changes, benefit inquiries, payroll inputs, policy acknowledgments, and help-desk contacts. Add peaks and deadlines, not just monthly averages. If reliable history is missing, label the estimate and ask every bidder to price the same low, expected, and high scenarios rather than letting each provider choose a favorable assumption.'
  ]},
  { heading: 'Price the ownership boundary, not just coordinator time', paragraphs: [
    'A proposal should state which actions the provider prepares, performs, recommends, or refuses without company approval. This matters because an inexpensive administrative service may still require substantial time from internal HR, payroll, benefits, privacy, security, managers, or counsel. Map every recurring handoff and estimate the company effort required to review it. A provider should not imply that routine coordination includes employment decisions, policy interpretation, legal advice, compensation approval, benefit eligibility, investigations, or exceptions unless the contract and qualified ownership genuinely support that scope.',
    'Use a worked example such as a late manager request to change a new hire’s start date. Identify who confirms candidate agreement, approves the date, moves system tasks, evaluates payroll and benefit timing, changes access activation, reschedules orientation, and sends the final message. Compare how each bidder allocates those steps. The exercise exposes hidden internal work and vague phrases such as full-service onboarding. It also shows whether the provider understands when to stop rather than treating quick completion as permission to make a company decision.'
  ]},
  { heading: 'Normalize charges that appear outside the base fee', paragraphs: [
    'List implementation, configuration, migration, training, dedicated staffing, minimum volume, after-hours coverage, language support, custom reporting, integrations, background services, postage, travel, software licenses, storage, archive retrieval, and termination assistance. Ask what event triggers each fee and whether it is one-time, recurring, usage-based, or pass-through. Do not assume that included means unlimited. A service may include a help desk while charging separately for contacts above a threshold or for every request routed to a specialist.',
    'Model a full operating period with the same scenarios for all proposals. Keep vendor-specific taxes, currencies, billing periods, and price adjustments visible. If exchange rates affect the budget, assign that assumption to the company model rather than asking one provider to absorb it silently. Avoid inventing a precise total when volumes are uncertain; show ranges and the variables that move them. The goal is not to predict every invoice but to reveal which operational event can change cost and who controls that event.'
  ]},
  { heading: 'Evaluate control evidence as a deliverable', paragraphs: [
    'Ask bidders to demonstrate how access is approved, reviewed, and removed; how sensitive requests leave a general queue; how source documents and later corrections remain distinguishable; how dependencies and employee updates are tracked; and how mistakes are investigated. A policy statement is useful context, but an operating sample is stronger. Review a redacted case record, access request, exception report, and closure evidence. The FTC advises businesses to control access and oversee service providers; the buyer still needs to translate that principle into the systems and data placed in scope.',
    'Compare incident and continuity responsibilities without asking providers to promise impossible prevention. Who detects a failed integration, unavailable queue, misdirected attachment, or unauthorized access? Who must be notified, through what channel, with what evidence, and who decides the response? Test backup contacts and service restoration assumptions. A cheaper proposal can become expensive if company staff must continuously discover defects, reconstruct status, or chase evidence that the service design never required the provider to retain.'
  ]},
  { heading: 'Separate service measurement from sales promises', paragraphs: [
    'Replace broad claims about responsiveness or accuracy with request-specific measures. Define acknowledgment, authorized progress, company decision, employee update, destination completion, and evidence-backed closure. Ask how pauses are recorded and how total employee waiting time remains visible. Compare quality sampling, reopened cases, duplicate work, rejected updates, missed cutoffs, and aging dependencies alongside speed. A single average can be dominated by easy requests and hide the few cases where delay has the greatest employee consequence.',
    'Request references or examples only within permissions and treat anecdotes as limited evidence, not guaranteed results. Unsupported testimonials, savings claims, or perfect accuracy figures should not enter the decision model. During a supervised pilot, score providers against the same redacted scenarios and rubric. Record where instructions were unclear so the company does not penalize a bidder for an ambiguity it created. A fair comparison measures the proposed operating system, not the confidence of the presentation team.'
  ]},
  { heading: 'Include transition and exit before selecting a winner', paragraphs: [
    'Estimate company work required to launch: process mapping, source cleanup, access provisioning, employee communication, migration testing, owner training, and parallel operation. Ask who produces each artifact and what acceptance evidence closes implementation. Then examine exit obligations with equal care. The proposal should address open-case handoff, export format, record provenance, access removal, return or deletion evidence, transition assistance, final billing, and the time allowed to retrieve company information. These are service costs even when they do not appear in the monthly fee.',
    'Finish with a decision record that preserves normalized scope, assumptions, scenarios, controls, company effort, unresolved questions, evaluated risks, and approval. Weight criteria according to the company’s needs rather than copying a generic procurement scorecard. The reader outcome is a comparison that management can defend later: each proposal was evaluated against the same work and demand, authority stayed visible, control evidence mattered, and the selected commercial model did not conceal implementation or exit obligations.'
  ]}
];

export const october5ProposalArticles: Record<string, RichArticle> = { [slug]: {
  slug, title: october5ProposalPost.title, description: october5ProposalPost.excerpt, published: october5BlogDate, updated: october5BlogDate, minutes: 16, revision: '2026-10-05-compare-hr-outsourcing-proposals-draft-1', heroImage: '/hr-team.jpg',
  directAnswer: ['Compare HR outsourcing proposals only after translating them into the same tasks, demand scenarios, ownership boundaries, company effort, control evidence, implementation work, and exit obligations. Headline monthly fees are not comparable when scope differs.', 'Use recent volumes and peak scenarios, identify every decision the company retains, model conditional charges, and score providers with the same evidence-based rubric. Preserve assumptions so leaders can understand what could change the result.'],
  takeaways: sections.map(section=>section.heading), sections,
  taskRows: sections.map((section,index)=>({lane:section.heading,philippinesTeam:`Provide operating evidence for comparison area ${index+1}.`,owner:`Set assumptions and approve weighting for area ${index+1}.`,check:'Normalize task, volume, authority, company effort, fee trigger, and proof.'})),
  pilotStats: [{value:'3',label:'Demand scenarios',note:'Low, expected, and peak.'},{value:'1',label:'Common task map',note:'Applied to every proposal.'},{value:'2',label:'Lifecycle edges',note:'Implementation and exit.'},{value:'0',label:'Hidden assumptions',note:'Target for the decision record.'}],
  scripts: [{label:'Scope clarification',text:'For this named task and demand scenario, state the included action, excluded action, company decision required, completion evidence, and any fee trigger.'},{label:'Control demonstration',text:'Please show a redacted operating example of the access, exception, employee-update, and closure evidence described in the proposal.'}],
  workflow: sections.map((section,index)=>({step:String(index+1).padStart(2,'0'),title:section.heading,text:section.paragraphs[0].split('. ')[0]+'.'})),
  faqs: [{question:'Is price per employee a fair comparison?',answer:'Only when included tasks, volume assumptions, minimums, retained company work, controls, and conditional fees are equivalent.'},{question:'How should uncertain demand be priced?',answer:'Give every bidder the same low, expected, and peak scenarios and preserve the assumptions.'},{question:'Should controls affect the score?',answer:'Yes. Ask for operating evidence rather than relying only on policy or marketing statements.'},{question:'Why review exit terms before selection?',answer:'Record export, open-case handoff, access removal, deletion evidence, assistance, and final charges can materially affect total effort and risk.'}],
  related: [{title:'HR operations support',href:'/services/operations-support',note:'Break recurring administration into comparable tasks.'},{title:'HR reporting and QA',href:'/services/reporting-and-qa',note:'Define evidence-based service review.'},{title:'Onboarding coordination',href:'/services/onboarding-coordination',note:'Use a complete workflow as a comparison case.'},{title:'Compare HR support options',href:'/contact-us',note:'Discuss scope, volumes, owners, controls, and handoffs.'}],
  sources: [{name:'FTC — Start with Security',url:'https://www.ftc.gov/business-guidance/resources/start-security-guide-business',note:'Official guidance on access controls and service-provider oversight.'},{name:'NIST Cybersecurity Framework 2.0',url:'https://www.nist.gov/cyberframework',note:'Official framework supporting governed risk and supplier responsibilities.'}], banners: []
} };
