import type { RichArticle } from './article-data';
import { october5BlogDate } from './october5-blog-batch';

const slug = 'employee-file-migration-acceptance-testing-outsourced-hr';
export const october5FileMigrationPost = { slug, title: 'Acceptance-Test an Employee File Migration Before HR Takes Over', excerpt: 'Use record classes, custody evidence, exception sampling, and employee-facing tests to decide whether a migrated HR file set is ready for outsourced administration.', minutes: 16, published: october5BlogDate } as const;

const sections: RichArticle['sections'] = [
  { heading: 'Define the record population before counting files', paragraphs: [
    'A migration cannot pass merely because the destination contains the same number of objects as the export. Define the population by employing entity, worker status, date range, record class, source system, and approved exclusions. Separate current employees, former workers, candidates, contractors, and dependents when their records follow different rules. List expected classes such as identity and tax forms, signed policies, job changes, benefit elections, performance records, leave material, payroll support, and offboarding evidence. The inventory gives reviewers a denominator and prevents a large volume of harmless documents from hiding missing high-consequence records.',
    'Document the authoritative source for each class and what the destination is expected to preserve. A scanned personnel folder, HRIS field, benefits portal acknowledgment, and payroll result may all describe the same event without being interchangeable. Name the system or artifact that controls the operational decision. If duplicates or conflicting versions already exist, do not silently choose one during transfer. Record the conflict, retain provenance, and route the decision to the qualified company owner. Migration staff move approved information; they do not rewrite employment history.'
  ]},
  { heading: 'Translate custody into observable evidence', paragraphs: [
    'For each exported package, retain the source location, export time, operator, applied filters, item count, format, and integrity evidence appropriate to the tool. At import, record the destination batch, result, rejected objects, changed names, and person who reviewed the outcome. A content hash can show whether a file changed, but it cannot prove that the correct file was selected or attached to the correct employee. Pair technical integrity with a business-key reconciliation using the approved employee identifier, record class, effective date, and source reference.',
    'Keep the transfer log outside the ordinary employee-facing folder if it reveals system paths or operational details employees do not need. Restrict migration reports because filenames and rejection messages can contain personal information. The outsourced HR team may prepare reconciliations and investigate mechanical failures under approved access. Company record, privacy, security, payroll, benefits, or legal owners decide unresolved custody, retention, disclosure, and correction questions. That boundary should appear in the acceptance plan before anyone begins moving production files.'
  ]},
  { heading: 'Sample for consequence rather than convenience', paragraphs: [
    'Random sampling is useful, but a purely random sample can miss rare records that matter most. Build a risk-based layer that deliberately selects new hires, recent terminations, employees with job or manager changes, benefit events, active leave, payroll corrections, duplicate names, long service histories, restricted cases, and documents near a retention event. Add ordinary records so the test still represents routine administration. For every sample, trace from the source through the transfer log to the destination and then through the workflow that will use the record.',
    'Write acceptance assertions before looking at results. Examples include: the signed version is present, the effective date matches the controlling event, access is limited to the approved group, prior versions remain distinguishable, a search finds the person using the authorized identifiers, the document opens completely, and the related workflow points to the correct destination record. Predetermined assertions reduce the temptation to explain defects away after discovery. A missing signature page is not a cosmetic issue simply because the first page renders correctly.'
  ]},
  { heading: 'Test permissions from both allowed and denied views', paragraphs: [
    'A migration changes exposure as well as storage. Test with role-appropriate accounts for HR coordinators, managers, payroll users, benefits owners, system administrators, and people who should have no access. Confirm which employees, fields, attachments, search results, previews, exports, audit events, and notifications each role can reach. Check inherited folders, shared links, report subscriptions, and cached exports, because access can persist outside the main application role. Use redacted or controlled test cases where a live restricted record is not necessary.',
    'Negative tests are essential. A manager should not discover another team’s file through search, an ordinary coordinator should not preview medical material, and a departing migration user should not retain export rights after the acceptance window. Record the attempted action and actual response rather than writing permission looks correct. If the platform cannot enforce the intended separation, name the interim control, owner, review frequency, and expiry. Do not approve the migration based on a future configuration change with no accountable due date.'
  ]},
  { heading: 'Exercise real HR tasks against migrated records', paragraphs: [
    'Run supervised tasks that the outsourced team will perform after handoff. Retrieve an onboarding acknowledgment, prepare a manager change, confirm a payroll-support document, locate a benefits election, assemble an offboarding checklist, and answer an employee request for a record correction. Observe whether staff can identify the controlling version, understand its context, follow access rules, and update the proper destination without reconstructing history from filenames. A technically complete repository can still be unusable if metadata, relationships, or search behavior were lost.',
    'Include awkward cases: a worker with two employment periods, a changed legal name, documents in multiple languages, a corrected effective date, a source attachment that fails to open, and two people with similar identifiers. The test outcome should distinguish a migration defect from a training gap, source-data problem, product limitation, or unresolved company decision. Assign the right owner rather than making the outsourced coordinator invent a workaround. Retest the corrected path from its beginning so a local fix does not hide a broken downstream result.'
  ]},
  { heading: 'Accept with a residual register, not a vague exception', paragraphs: [
    'Classify every defect by affected population, record class, consequence, root cause, owner, correction method, and retest deadline. Define which defects block takeover: missing required populations, wrong employee associations, unreadable critical documents, uncontrolled restricted access, unreliable search, or unexplained count differences may justify a stop. Lower-consequence naming or display defects may enter a residual register if the company explicitly accepts the interim control. The acceptance authority must belong to the company, not the provider whose delivery is being evaluated.',
    'Close only when the signed acceptance record states the tested scope, evidence, passed assertions, remaining exceptions, owners, and review dates. Preserve source exports according to the approved rollback and retention plan until the company authorizes disposition. Tell employees how to report a missing or incorrect record without exposing migration mechanics. The reader outcome is a defensible handoff: the new HR support team can find and use the right evidence, restricted material stays restricted, and unresolved defects remain visible to people empowered to fix them.'
  ]}
];

export const october5FileMigrationArticles: Record<string, RichArticle> = { [slug]: {
  slug, title: october5FileMigrationPost.title, description: october5FileMigrationPost.excerpt, published: october5BlogDate, updated: october5BlogDate, minutes: 16, revision: '2026-10-05-employee-file-migration-draft-1', heroImage: '/hr-team.jpg',
  directAnswer: ['Acceptance-test an employee-file migration against a defined population, record classes, custody evidence, permissions, and real HR tasks. Matching object counts alone cannot prove that the correct records are complete, usable, and attached to the right people.', 'Use both representative and consequence-based samples. Keep unresolved retention, privacy, payroll, benefits, legal, and correction decisions with qualified company owners while the outsourced team prepares evidence and retests approved fixes.'],
  takeaways: sections.map(section=>section.heading), sections,
  taskRows: sections.map((section,index)=>({lane:section.heading,philippinesTeam:`Prepare migration evidence and execute approved test ${index+1}.`,owner:`Decide acceptance and exceptions for test ${index+1}.`,check:'Trace source, custody, destination, access, use, and retest result.'})),
  pilotStats: [{value:'2',label:'Sampling layers',note:'Representative and consequence-based.'},{value:'2-sided',label:'Permission testing',note:'Allowed and denied views.'},{value:'1',label:'Controlling source',note:'Named for each record class.'},{value:'0',label:'Unowned defects',note:'Every residual item needs accountable closure.'}],
  scripts: [{label:'Migration defect',text:'The sampled record failed the stated acceptance assertion. Preserve the source and destination evidence, classify the consequence, and route the correction decision to the named owner.'},{label:'Employee correction route',text:'We received your record concern and will verify it against the approved source. Please use the secure channel provided for any supporting document.'}],
  workflow: sections.map((section,index)=>({step:String(index+1).padStart(2,'0'),title:section.heading,text:section.paragraphs[0].split('. ')[0]+'.'})),
  faqs: [{question:'Is matching the file count enough?',answer:'No. Counts do not prove correct identity, completeness, readability, provenance, permissions, metadata, or workflow usability.'},{question:'Should sampling be random?',answer:'Use random or representative sampling plus deliberate selection of rare, restricted, changed, and high-consequence records.'},{question:'Who approves exceptions?',answer:'A named company authority should accept residual risk. The provider should not approve its own unresolved delivery defects.'},{question:'When can source exports be deleted?',answer:'Only after the company applies its approved rollback, retention, legal, security, and privacy rules.'}],
  related: [{title:'Employee records administration',href:'/services/employee-records-administration',note:'Review the outsourced file-support lane.'},{title:'HR reporting and QA',href:'/services/reporting-and-qa',note:'Plan sampling and reconciliation evidence.'},{title:'Onboarding coordination',href:'/services/onboarding-coordination',note:'Test a document-dependent employee journey.'},{title:'Plan an HR records handoff',href:'/contact-us',note:'Discuss scope, access, ownership, and acceptance.'}],
  sources: [{name:'NIST Privacy Framework',url:'https://www.nist.gov/privacy-framework',note:'Official framework for managing privacy risk and data processing.'},{name:'National Archives — Records Management',url:'https://www.archives.gov/records-mgmt',note:'Official records-management resources supporting governed record custody and disposition.'}], banners: []
} };
