import type { RichArticle } from './article-data';
import { october5BlogDate } from './october5-blog-batch';

const slug = 'what-to-put-in-hr-outsourcing-kickoff-packet';
export const october5KickoffPost = { slug, title: 'What to Put in an HR Outsourcing Kickoff Packet', excerpt: 'Give an outsourced HR team enough operating context to start safely without dumping every policy, file, password, and unresolved decision into one folder.', minutes: 15, published: october5BlogDate } as const;

const sections: RichArticle['sections'] = [
  { heading: 'Begin with outcomes and boundaries, not a document dump', paragraphs: [
    'A useful kickoff packet explains what the company wants the support lane to accomplish during its first operating period. Name the employee populations, business units, working hours, channels, systems, and request types in scope. Describe observable outcomes such as maintaining an onboarding checklist, preparing approved record updates, coordinating interviews, or tracking payroll inputs to a cutoff. Then state what remains with company owners: employment decisions, policy interpretation, legal advice, pay approval, benefit eligibility, investigations, exceptions, and access administration. This prevents a new coordinator from treating possession of a file as authority to act.',
    'Do not begin by copying an entire HR drive. Extra material creates privacy exposure and makes current instructions harder to identify. Build the packet from the approved work backward. For each task, ask which source, field, template, contact, deadline, and evidence the coordinator actually needs. Link to the controlled source instead of attaching a convenience copy when practical. Mark information-only references separately from operating instructions. If a document is unresolved or obsolete, keep it out of the active packet and record the company owner who must decide its status.'
  ]},
  { heading: 'Create a service map employees and managers can follow', paragraphs: [
    'List the approved intake channels and explain who may use each one. A shared mailbox may accept general employee questions, while a secure form receives identity documents and a restricted route receives sensitive concerns. Include authentication steps, expected acknowledgment, escalation triggers, and what the coordinator may say before a company decision. Managers need a parallel map for approvals, job changes, interview feedback, and urgent issues. The packet should make routing predictable without forcing employees to understand internal department names or provider contracts.',
    'Add several realistic examples. An employee asking when a submitted address change will appear can receive a status after authentication. A manager requesting an unapproved pay change must be routed to the compensation or payroll owner. A message mentioning medical information should leave the general queue and enter the protected path without a public summary. Examples teach boundaries better than labels such as basic and complex. They also reveal whether a route lacks an owner before live work exposes the gap.'
  ]},
  { heading: 'Name sources of truth and effective-date rules', paragraphs: [
    'For every supported process, identify the controlling system or approved artifact. The HRIS may control the employee’s current manager, payroll may control a processed payment result, a signed plan election may control a benefits instruction, and an applicant system may control interview status. Explain how the coordinator handles disagreements between sources. The safe default is to preserve both values, pause the affected update, and send the conflict to the named owner. The provider should not select the most recent-looking value or overwrite history to make systems agree.',
    'Effective dates need their own instructions. State where a requested date comes from, who approves it, which cutoffs or dependencies apply, and what proof shows the destination accepted it. Include time zone and holiday assumptions. A manager email sent after a payroll cutoff may be valid as a request but too late for the current cycle. The coordinator can log and escalate the timing issue; the company owner decides treatment. This distinction keeps administrative support from quietly becoming policy or pay authority.'
  ]},
  { heading: 'Provide contacts as an ownership matrix', paragraphs: [
    'A contact list is not enough. Create an ownership matrix by decision or destination: onboarding approval, payroll cutoff, benefit question, system access, employee record correction, leave document, candidate issue, privacy concern, and after-hours escalation. Give a primary role, backup role, approved channel, expected response, and evidence the coordinator must provide. Use roles where possible so the packet survives staffing changes, but identify the current people responsible for receiving work. Confirm that backups know they are listed before launch.',
    'Show the provider what to do when nobody answers. The fallback might be an on-call leader, a documented delay notice to the employee, or a stop rule that protects the record until the owner returns. It should never be an invitation to make the decision. Test the matrix with a scenario that crosses departments, such as a new hire whose start date moves after equipment ships but before payroll creation. The exercise reveals whether each dependency has one acting owner and whether handoffs preserve context.'
  ]},
  { heading: 'Grant access through a separate controlled record', paragraphs: [
    'The kickoff packet may describe required systems, but it should not contain passwords or shared credentials. Maintain an access register showing the user, task, system, employee population, permission, approver, activation time, review date, and removal trigger. Provision named accounts wherever supported. Ask system owners to test both permitted work and denied areas, including searches, attachments, exports, reports, delegated calendars, and notifications. A role name alone does not prove what the user can see.',
    'Include practical data-handling rules: approved devices, download limits, secure transfer methods, local-file restrictions, printing, incident reporting, and disposal of working copies. The NIST Privacy Framework can help owners consider how personal data is processed and protected, while actual company instructions must reflect its systems and obligations. If the provider cannot meet a requirement, record the exception and company decision before access begins. Do not normalize an informal workaround during a rushed kickoff.'
  ]},
  { heading: 'Turn the packet into a tested operating baseline', paragraphs: [
    'Run a tabletop using representative requests before launch. Ask the coordinator to authenticate intake, locate the right source, prepare an authorized step, route a decision, protect an attachment, update an employee, and retain closure evidence. Include a duplicate request, unavailable owner, conflicting effective date, and sensitive message sent to the wrong channel. Record questions and correct the packet itself rather than relying on verbal answers that future team members cannot see. The exercise should end with clear changes, owners, and a retest date.',
    'Version the packet and keep a short change log for processes, contacts, systems, templates, and boundaries. Name a company owner who approves changes and a provider owner who confirms receipt. Review it after the pilot and whenever a material workflow changes. The reader outcome is a concise operating baseline: the outsourced HR team knows what work to perform, where trusted information lives, when to stop, who decides, and what evidence lets the company verify that support was delivered safely.'
  ]}
];

export const october5KickoffArticles: Record<string, RichArticle> = { [slug]: {
  slug, title: october5KickoffPost.title, description: october5KickoffPost.excerpt, published: october5BlogDate, updated: october5BlogDate, minutes: 15, revision: '2026-10-05-hr-outsourcing-kickoff-packet-draft-1', heroImage: '/hr-team.jpg',
  directAnswer: ['An HR outsourcing kickoff packet should define supported outcomes, employee populations, channels, sources of truth, deadlines, decision owners, escalation paths, and proof of completion. Include only the records needed for approved tasks.', 'Keep credentials in controlled access systems and keep employment, pay, benefits, privacy, legal, and exception decisions with company owners. Test the packet with realistic employee and manager requests before launch.'],
  takeaways: sections.map(section=>section.heading), sections,
  taskRows: sections.map((section,index)=>({lane:section.heading,philippinesTeam:`Prepare and test kickoff checkpoint ${index+1}.`,owner:`Approve boundaries and decisions for checkpoint ${index+1}.`,check:'Confirm source, owner, access, stop rule, destination, and evidence.'})),
  pilotStats: [{value:'1',label:'Controlling source',note:'Named for every supported process.'},{value:'2',label:'Owner levels',note:'Primary and confirmed backup.'},{value:'0',label:'Passwords in packet',note:'Credentials stay in access systems.'},{value:'1',label:'Approved baseline',note:'Versioned and tested before launch.'}],
  scripts: [{label:'Owner question',text:'The source values conflict and the supported procedure does not authorize a choice. Here are both records, effective dates, affected deadline, and the decision required.'},{label:'Employee status',text:'We received your request and completed the authorized preparation step. The named company owner is reviewing the remaining decision, with the next update due at the stated time.'}],
  workflow: sections.map((section,index)=>({step:String(index+1).padStart(2,'0'),title:section.heading,text:section.paragraphs[0].split('. ')[0]+'.'})),
  faqs: [{question:'Should the packet include every HR policy?',answer:'No. Include or link only current approved material needed for supported work, and identify the controlling source.'},{question:'Can passwords go in the packet?',answer:'No. Use approved credential and access-management processes with named accounts where supported.'},{question:'Who updates the packet?',answer:'A company owner approves changes and a provider owner confirms receipt and operational adoption.'},{question:'How should the packet be tested?',answer:'Use representative, conflicting, sensitive, duplicate, and after-hours scenarios before live launch.'}],
  related: [{title:'HR operations support',href:'/services/operations-support',note:'Review the core outsourced operations lane.'},{title:'Onboarding coordination',href:'/services/onboarding-coordination',note:'Map a deadline-dependent workflow.'},{title:'HR help desk support',href:'/services/hr-help-desk-support',note:'Design employee intake and routing.'},{title:'Plan your HR kickoff',href:'/contact-us',note:'Discuss scope, owners, access, and evidence.'}],
  sources: [{name:'NIST Privacy Framework',url:'https://www.nist.gov/privacy-framework',note:'Official framework for managing privacy risk in data processing.'},{name:'FTC — Start with Security',url:'https://www.ftc.gov/business-guidance/resources/start-security-guide-business',note:'Official business guidance on access and service-provider data handling.'}], banners: []
} };
