import type { RichArticle } from './article-data';

// Cycle label only. Reconcile this to the actual UTC first-publication date before the sole push.
export const october5BlogDate = '2026-10-06';
const slug = 'hr-outsourcing-provider-transition-without-losing-employee-context';
export const october5BlogPosts = [{ slug, title: 'How to Change HR Outsourcing Providers Without Losing Employee Context', excerpt: 'Plan a controlled HR support transition that preserves open cases, records, access boundaries, employee expectations, and decision ownership.', minutes: 15, published: october5BlogDate }] as const;

const sections: RichArticle['sections'] = [
  { heading: 'Inventory the work people depend on now', paragraphs: [
    'A provider transition starts with active obligations, not a folder count. List open onboarding steps, payroll inputs, benefit questions, leave documents, interviews, employee-record corrections, policy acknowledgments, offboarding tasks, manager requests, and reporting deadlines. For each item, capture the employee or candidate reference, purpose, current status, next action, due date, company decision owner, provider coordinator, source evidence, and approved destination. That produces a service inventory another authorized reviewer can reconcile. A drive with thousands of files cannot show which employee is waiting for an answer tomorrow morning.',
    'Separate routine requests from restricted cases. A general status question can use the normal queue, while a complaint, medical document, accommodation discussion, investigation, wage dispute, or legal hold may require a qualified internal owner and narrower transfer path. Do not summarize sensitive facts into the migration tracker merely to simplify handoff. Use a case identifier, access classification, custodian, and checkpoint. The transition team can then preserve continuity without expanding who may view the underlying material or inviting the new provider to interpret unresolved facts.'
  ]},
  { heading: 'Require usable context from the outgoing provider', paragraphs: [
    'Ask for structured handoff packages instead of an undifferentiated export. Each package should identify the authoritative record, later corrections, unanswered questions, approvals already received, messages already sent, and the next person expected to act. Historical notes must remain distinguishable from current instructions. If a payroll input was rejected twice, the incoming team needs the rejection response and reviewing owner; another copy of the original spreadsheet will repeat the failure. When the old provider cannot explain a status, mark it unresolved rather than converting uncertainty into a confident migration label.',
    'Agree on formats before delivery. Dates, identifiers, naming conventions, time zones, status values, attachment references, and redaction rules should be tested with representative cases. Preserve original timestamps and authorship where the record system supports them. A controlled export report or content hash can show that delivered files did not change in transit, but technical integrity is only one test. A company owner must still confirm that the package is complete for its business purpose and that restricted records reached only the approved location.'
  ]},
  { heading: 'Rebuild access from duties rather than cloning accounts', paragraphs: [
    'Create an access matrix for the incoming provider by task, system, employee population, data field, permitted action, approver, start time, and review date. Begin with the minimum access needed for tested work. Copying an outgoing account can preserve obsolete permissions, one-off exceptions, mailbox rules, report subscriptions, delegated calendars, or access to people the new team does not support. NIST defines least privilege around access necessary for assigned tasks. That principle gives a transition owner a practical test for every requested permission without assuming that an old configuration was correct.',
    'Plan removal as carefully as provisioning. Record when outgoing users lose interactive access, API credentials, shared links, forwarding rules, local exports, and scheduled reports. Name the company system owner who performs or verifies each action. The incoming provider should never use a departing user’s credentials during overlap. If a platform cannot meet the desired timing, document the temporary safeguard, authorized users, expiry, and monitoring step. Test what both groups can actually reach after the effective time; a closed access ticket is not proof that side channels disappeared.'
  ]},
  { heading: 'Rehearse employee journeys before changing the front door', paragraphs: [
    'Test the transition from the employee’s point of view. Send a redacted onboarding document, ask a benefits-status question, submit a record correction, raise a payroll-cutoff issue, reschedule an interview, and route a message requiring immediate escalation. Confirm that the incoming team can authenticate the request, locate the controlling record, protect attachments, identify the company decision owner, meet the agreed response target, and deliver an approved answer. Include a duplicate message and an out-of-scope request. Those tests expose parallel cases and invented answers when ownership is unclear.',
    'Keep employee communication concrete. State when the contact route changes, which requests it accepts, how identity will be checked, what information should not be sent through ordinary email, expected acknowledgment timing, and where urgent or sensitive concerns go. Do not imply that the provider becomes the employer or final decision maker. Managers need separate instructions covering approvals and escalation. If the public address stays the same, document the internal routing change so messages do not disappear into an unattended rule owned by the departing team.'
  ]},
  { heading: 'Use overlap to compare outcomes, not create duplicate owners', paragraphs: [
    'A short overlap can reveal missing context, but every task still needs one acting coordinator and one company decision owner. Define which provider handles new intake, which finishes named legacy cases, and how misrouted work returns. Do not ask both providers to process the same requests as a safety measure. Duplicate replies, conflicting status changes, and repeated requests for documents damage employee trust and make the final record harder to reconcile. Hold a daily exception review for aged cases, rejected updates, missing evidence, disputed ownership, and deadlines inside the cutover window.',
    'Measure continuity with operational evidence: acknowledgment time, cases accepted with a named next action, missed deadlines, duplicate records, access exceptions, contacts repeated because context was missing, and items returned for a company decision. Trace a sample from source request through response and destination record. Aggregate dashboards can look healthy while a leave document or payroll correction remains stranded. These measures support the transition review; they are not unsupported promises about either provider’s general performance.'
  ]},
  { heading: 'Close only when the residual queue has accountable owners', paragraphs: [
    'Create a residual register for anything the incoming provider did not accept cleanly: unreadable exports, unresolved decisions, records without a destination, cases awaiting employee confirmation, vendor rejections, and access defects. Every entry needs an owner, due date, evidence location, and disposition. Completion does not require pretending that every case is solved on cutover day. It requires proving that nothing is ownerless and that employees know where to obtain an update. Keep contractual record-return or deletion obligations on a separate evidence trail controlled by the company.',
    'Finish with a company-led review of access, record custody, open obligations, employee communications, service reporting, and lessons. Confirm that old intake paths are closed or redirected, temporary permissions expired, and retained records follow the company schedule. The practical reader outcome is a transition dossier another authorized reviewer can follow: what moved, what did not, who owns each exception, which employee journeys passed, and which destination acknowledgments support final sign-off.'
  ]}
];

export const october5BlogArticles: Record<string, RichArticle> = { [slug]: {
  slug, title: october5BlogPosts[0].title, description: october5BlogPosts[0].excerpt, published: october5BlogDate, updated: october5BlogDate, minutes: 15, revision: '2026-10-05-provider-transition-draft-1', heroImage: '/hr-team.jpg',
  directAnswer: ['Change HR outsourcing providers through a controlled service transition, not a bulk file transfer. Define the requests, deadlines, records, permissions, and pending decisions in scope, then assign a company owner to every category.', 'Use a case inventory, task-limited access, employee-facing continuity rules, and an overlap period with explicit boundaries. The company retains employment decisions, policy interpretation, approvals, and exceptions.'],
  takeaways: sections.map(section => section.heading), sections,
  taskRows: sections.map((section,index)=>({lane:section.heading,philippinesTeam:`Prepare and route evidence for checkpoint ${index+1}.`,owner:`Approve decisions and access for checkpoint ${index+1}.`,check:`Retain source, destination, owner, and outcome for checkpoint ${index+1}.`})),
  pilotStats: [{value:'1',label:'Coordinator per task',note:'Overlap does not mean duplicate ownership.'},{value:'6',label:'Evidence checkpoints',note:'Each addresses a different transition risk.'},{value:'2-sided',label:'Access test',note:'Verify both grants and removals.'},{value:'0',label:'Ownerless exceptions',note:'The residual-queue closeout target.'}],
  scripts: [{label:'Outgoing-provider handoff',text:'For every active item, provide the authoritative source, corrections, current status, approvals, next action, deadline, company owner, and approved evidence location. Mark uncertainty explicitly.'},{label:'Employee cutover notice',text:'Beginning on the approved date, use this route for the listed HR administration requests. The company remains responsible for employment decisions and exceptions.'}],
  workflow: sections.map((section,index)=>({step:String(index+1).padStart(2,'0'),title:section.heading,text:section.paragraphs[0].split('. ')[0]+'.'})),
  faqs: [{question:'How long should two providers overlap?',answer:'Base overlap on tested workflows, deadline risk, access, and unresolved cases. Keep one acting coordinator for every task.'},{question:'Should every historical HR file move?',answer:'No. Transfer records according to purpose, authorization, retention rules, and task need.'},{question:'Who approves unresolved employee cases?',answer:'The employer’s designated qualified owner makes the relevant decision. The provider organizes evidence and routes the question.'},{question:'What proves continuity?',answer:'Use case acceptance, employee-journey tests, destination acknowledgments, access verification, deadline results, and a residual register.'}],
  related: [{title:'HR operations support',href:'/services/operations-support',note:'Review the outsourced administration lane.'},{title:'Employee records administration',href:'/services/employee-records-administration',note:'Plan controlled records custody.'},{title:'HR reporting and QA',href:'/services/reporting-and-qa',note:'Build continuity checks.'},{title:'Plan an HR support transition',href:'/contact-us',note:'Discuss tasks, ownership, access, and handoffs.'}],
  sources: [{name:'NIST CSRC — least privilege',url:'https://csrc.nist.gov/glossary/term/least_privilege',note:'Official definition supporting task-limited access.'},{name:'FTC — Start with Security',url:'https://www.ftc.gov/business-guidance/resources/start-security-guide-business',note:'Official guidance on access, data handling, and service providers.'}], banners: []
} };
