import type { RichArticle } from './article-data';
import { october5BlogDate } from './october5-blog-batch';

const slug = 'set-hr-help-desk-service-levels-before-outsourcing';
export const october5HelpDeskPost = { slug, title: 'Set HR Help Desk Service Levels Before You Outsource', excerpt: 'Turn vague responsiveness promises into request-specific intake, ownership, escalation, update, and closure rules employees can rely on.', minutes: 15, published: october5BlogDate } as const;

const sections: RichArticle['sections'] = [
  { heading: 'Measure the employee journey instead of the inbox', paragraphs: [
    'A service level should describe what happens to a real request. Start when an employee reaches an approved channel and define when the clock begins, what proves receipt, and which events can pause it. An unread-email count is not a service measure. A useful case record connects the request category, received time, authentication status, assigned coordinator, company decision owner, next promised update, final outcome, and destination system. This distinguishes a quick acknowledgment from an actual answer and prevents a provider from closing a ticket simply because it forwarded the message.',
    'Map several employee journeys before choosing targets. A mailing-address correction, missing-pay concern, benefits-card question, interview reschedule, policy request, and sensitive complaint should not share one timer. Each has different consequences, evidence, and owners. Ask what the employee needs at each stage: confirmation that the request arrived, instructions for safe document delivery, an expected update time, and a clear escalation route. Include candidates, former workers, managers, and people without ordinary system access when those audiences are expected to use the desk.'
  ]},
  { heading: 'Build categories around required action and consequence', paragraphs: [
    'Categories should tell the coordinator what to do next. Payroll is usually too broad because it can mean a routine statement request, late time input, bank-detail change, or report that expected wages are missing. Define categories with entry criteria, required authentication, permitted provider actions, company owner, destination, normal update interval, and emergency escalation. Keep the list short enough for consistent use, then put unusual cases in a visible exception lane instead of forcing them into the nearest reporting bucket and hiding the decision they require.',
    'Sensitive subjects need discreet routing without asking an employee to diagnose a legal issue. Offer neutral options such as confidential workplace concern, health or leave document, suspected account misuse, or urgent pay problem. The provider can confirm receipt and protect material while qualified company owners determine substance. Do not require allegations or medical details in an ordinary subject line. A category works when it directs a request safely even if the employee does not know which policy, plan, law, or internal team applies.'
  ]},
  { heading: 'Separate acknowledgment, progress, decision, and closure', paragraphs: [
    'One response-time promise hides four events. Acknowledgment tells the sender the request arrived. Progress means a coordinator completed an authorized step or obtained new evidence. A decision comes from the employer or another qualified owner when judgment is needed. Closure means the answer reached the employee and the controlling record or destination reflects the outcome. Set expectations for each event that matters. An automatic reply within a minute helps only when the request is then authenticated, owned, and advanced within a meaningful interval.',
    'Define pause rules narrowly. A case may wait for an employee document, manager approval, carrier response, payroll calculation, or legal review, but the provider should record the dependency, responsible person, request time, and next follow-up. Pausing must not erase the duty to update the employee. If a vendor misses its target, the employee still needs honest status from the desk. Track elapsed provider work separately from total employee waiting time so a service review does not reward administrative pauses while requests continue aging.'
  ]},
  { heading: 'Design escalation around a named person and action', paragraphs: [
    'Escalate to HR is not an operating rule. Name the role or on-call owner for each trigger, approved channel, evidence to include, response expected, and fallback if that person is unavailable. Triggers can include an imminent payroll cutoff, inability to access a required system, suspected privacy incident, safety threat, time-sensitive accommodation signal, repeated vendor rejection, or a case nearing maximum age. The outsourced coordinator reports facts and protects the record; the company owner decides the substantive response.',
    'Test escalation after normal business hours and across holidays or time zones. A Philippines-based team may be available while a domestic owner is not, but availability does not transfer authority. Decide what the provider may acknowledge, which accounts it may secure, whom it contacts, and when it must stop. Avoid personal messaging accounts that leave no durable case history. The escalation record should show trigger, time, recipient, evidence delivered, acknowledgment, decision owner, and instructions returned.'
  ]},
  { heading: 'Audit answer quality alongside speed', paragraphs: [
    'Fast incorrect answers create repeat work and employee harm. Review a sample for authentication, category choice, owner assignment, source use, tone, privacy, destination update, and proof of closure. Compare the public answer with the company policy, plan document, payroll record, or approved instruction in effect at that time. Do not score coordinators on outcomes they cannot control, such as whether an exception is approved. Score whether they gathered the required evidence, stayed inside their authority, and kept the employee informed.',
    'Look for recontacts, reopened cases, transfers, duplicate tickets, stale dependencies, and changes made in the wrong system. These signals explain more than an average response time. Segment results by request type and consequence so a high volume of simple confirmations does not hide a small set of aging pay or leave cases. Employee comments may reveal confusing instructions, but protect anonymity and do not present a tiny voluntary sample as a reliable satisfaction statistic.'
  ]},
  { heading: 'Pilot the rules before attaching contractual remedies', paragraphs: [
    'Run proposed service levels against redacted historical requests and a supervised live pilot. Include straightforward work, ambiguous messages, missing identity evidence, duplicate contacts, a provider outage, an absent company owner, and a request that changes category after review. Record where the timer, ownership rule, or escalation path becomes unclear. Adjust definitions before using results to reward or penalize a provider. Otherwise teams may optimize ticket labels and pause codes rather than improving the experience of people who need HR support.',
    'Publish a concise operating sheet for coordinators and owners, plus plain-language expectations for employees. Review targets when channels, staffing, systems, vendors, policies, or business hours change. The final deliverable is not a table of impressive percentages. It is a service design that tells employees when they will hear back, tells the provider what it may do, tells company owners when they must decide, and leaves evidence showing whether the request reached the right destination with a usable answer.'
  ]}
];

export const october5HelpDeskArticles: Record<string, RichArticle> = { [slug]: {
  slug, title: october5HelpDeskPost.title, description: october5HelpDeskPost.excerpt, published: october5BlogDate, updated: october5BlogDate, minutes: 15, revision: '2026-10-05-help-desk-service-levels-draft-1', heroImage: '/hr-team.jpg',
  directAnswer: ['Set outsourced HR help desk service levels by request type and employee consequence. Define acknowledgment, progress, decision, update, escalation, and closure separately because one average response-time target conceals whether a request was answered correctly.', 'Keep employment, payroll, benefits, privacy, legal, and exception decisions with named company owners. The provider authenticates intake, prepares authorized work, tracks dependencies, communicates approved status, and preserves evidence.'],
  takeaways: sections.map(section => section.heading), sections,
  taskRows: sections.map((section,index)=>({lane:section.heading,philippinesTeam:`Operate and document checkpoint ${index+1}.`,owner:`Approve scope and exceptions for checkpoint ${index+1}.`,check:'Sample source, timestamps, owner, destination, and employee update.'})),
  pilotStats: [{value:'4',label:'Distinct service events',note:'Acknowledgment, progress, decision, and closure.'},{value:'1',label:'Acting owner',note:'Every open request needs accountability.'},{value:'2',label:'Time views',note:'Provider work and employee waiting time.'},{value:'0',label:'Silent pauses',note:'Every dependency needs an update rule.'}],
  scripts: [{label:'Dependency update',text:'Your request is waiting for the named decision or destination response. The next follow-up is scheduled for the stated time, and you do not need to resend documents already received.'},{label:'Owner escalation',text:'This case met the documented escalation trigger. Here are the authenticated source, deadline, completed steps, open decision, and next employee update time.'}],
  workflow: sections.map((section,index)=>({step:String(index+1).padStart(2,'0'),title:section.heading,text:section.paragraphs[0].split('. ')[0]+'.'})),
  faqs: [{question:'Is first-response time enough?',answer:'No. Track acknowledgment separately from progress, owner decision, employee updates, destination completion, and evidence-backed closure.'},{question:'Should every request use the same target?',answer:'No. Group work by required action, consequence, evidence, and owner.'},{question:'Can a provider pause a case?',answer:'Only under defined rules preserving the dependency, responsible party, follow-up, employee update, and total waiting time.'},{question:'Who handles urgent requests?',answer:'The provider follows approved intake and protection steps, then a named qualified company owner decides the substantive response.'}],
  related: [{title:'HR help desk support',href:'/services/hr-help-desk-support',note:'Review the employee-request support lane.'},{title:'HR reporting and QA',href:'/services/reporting-and-qa',note:'Plan service sampling and evidence.'},{title:'Payroll preparation support',href:'/services/payroll-preparation-support',note:'Map cutoff-sensitive requests.'},{title:'Scope outsourced HR support',href:'/contact-us',note:'Discuss channels, owners, controls, and coverage.'}],
  sources: [{name:'NIST Cybersecurity Framework 2.0',url:'https://www.nist.gov/cyberframework',note:'Official framework supporting governed responsibilities, response, and recovery.'},{name:'U.S. Department of Labor — recordkeeping',url:'https://www.dol.gov/general/topic/workhours/hoursrecordkeeping',note:'Official overview relevant to payroll and work-time records.'}], banners: []
} };
