import { buildBlogBatch, type BlogBatchTopic } from './september22-batch';

// Cycle label only. Reconcile this value to each route's actual first-live UTC date
// immediately before the sole combined production push.
export const october2CycleDate = '2026-10-02';
const prefix = 'october2-hr-';

export const october2Topics: BlogBatchTopic[] = [
  { slug: 'employee-name-change-system-sequence', title: 'Sequence an Employee Name Change Across HR Systems', description: 'Build an evidence-led name-change queue that keeps identity, payroll, benefits, directory, and access records synchronized without letting support staff decide legal sufficiency.', workflow: 'employee name change system sequencing', trigger: 'an authenticated employee submits the employer-required change evidence through an approved channel', owner: 'the employer HR, payroll, benefits, security, privacy, and legal owners', stop: 'identity, required evidence, effective date, tax treatment, benefits treatment, system authority, or conflicting names are unclear', proof: 'the HR owner approves the controlling identity record and each required destination acknowledges the same authorized value or a documented exception', service: 'employee-records-administration', example: 'The HRIS accepts a new surname while payroll rejects it and the company directory updates before the employee chooses how the change should be displayed', source: { name: 'Social Security Administration — Employer W-2 Filing Instructions', url: 'https://www.ssa.gov/employer/', note: 'Official employer resources concerning names and Social Security wage reporting.' } },
  { slug: 'manager-access-transfer-checklist', title: 'Transfer Manager Access Without Copying Sensitive HR Permissions', description: 'Coordinate reporting-line changes, approvals, delegated work, and access reviews without cloning a former manager’s full HR visibility.', workflow: 'manager access transfer coordination', trigger: 'the authorized HR owner releases an approved manager change with an effective time and affected population', owner: 'the employer HRIS, security, privacy, HR, payroll, and application owners', stop: 'reporting scope, effective timing, confidential cases, inherited groups, segregation of duties, or a temporary delegation needs judgment', proof: 'each application owner confirms the approved role assignment and removal, with restricted cases reassigned by their qualified owner', service: 'employee-records-administration', example: 'A new manager needs timecard approvals on Monday but should not inherit access to an open employee-relations case held by the prior manager', source: { name: 'NIST Cybersecurity Framework 2.0', url: 'https://www.nist.gov/cyberframework', note: 'Official framework supporting governed identity and access control practices.' } },
  { slug: 'candidate-withdrawal-record-handoff', title: 'Handle Candidate Withdrawals Without Erasing Recruiting Evidence', description: 'Record a candidate-directed withdrawal, stop future activity, and preserve the required recruiting history without rewriting prior stages.', workflow: 'candidate withdrawal record handoff', trigger: 'a candidate submits an authenticated withdrawal or an authorized recruiter records the candidate’s clear instruction', owner: 'the employer recruiting, privacy, HR, legal, and hiring owners', stop: 'identity, withdrawal scope, pending offer, accommodation, complaint, deletion request, agency ownership, or retention treatment is unclear', proof: 'recruiting confirms the candidate is no longer active, scheduled actions are cancelled, and the retained record accurately preserves the source and disposition', service: 'interview-coordination', example: 'A candidate withdraws from one role while asking to remain under consideration for another opening handled by a different recruiter', source: { name: 'EEOC Recordkeeping Requirements', url: 'https://www.eeoc.gov/employers/recordkeeping-requirements', note: 'Official overview of federal employment recordkeeping requirements.' } },
  { slug: 'new-hire-start-date-change-control', title: 'Control a New Hire Start-Date Change Across Dependent Tasks', description: 'Move an approved start date through payroll, benefits, access, equipment, orientation, and manager calendars while preserving the original offer record.', workflow: 'new hire start-date change control', trigger: 'the authorized hiring or HR owner releases a dated start-date change for an identified accepted candidate', owner: 'the employer hiring, HR, payroll, benefits, IT, security, facilities, and legal owners', stop: 'offer terms, employee classification, eligibility, screening, work authorization, pay timing, location, or candidate agreement is uncertain', proof: 'the hiring and HR owners approve the new controlling date and every required dependency records a matching disposition or visible exception', service: 'onboarding-coordination', example: 'A manager moves a start by one week after a laptop ships and payroll has already created the worker for the original cycle', source: { name: 'USCIS Form I-9 Central', url: 'https://www.uscis.gov/i-9-central', note: 'Official employer resources for Form I-9 timing and responsibilities.' } },
  { slug: 'payroll-duplicate-employee-record-review', title: 'Review Duplicate Employee Records Before Payroll Processing', description: 'Detect and route possible duplicate worker records without merging identities, deleting history, or changing pay on an administrative assumption.', workflow: 'payroll duplicate employee record review', trigger: 'an approved payroll or HRIS control flags two records sharing defined identity or payment attributes', owner: 'the employer payroll, HRIS, HR, security, privacy, tax, and legal owners', stop: 'identity, rehire status, concurrent employment, entity, tax profile, bank account, pay history, or record ownership is uncertain', proof: 'the authorized owners document whether the records are distinct or approve a controlled correction, and payroll reconciles the affected cycle totals', service: 'payroll-preparation-support', example: 'A returning employee appears under a new worker ID while an older record remains active in a second employing entity', source: { name: 'U.S. Department of Labor Recordkeeping', url: 'https://www.dol.gov/general/topic/workhours/hoursrecordkeeping', note: 'Official federal overview of employer wage and hour recordkeeping responsibilities.' } },
  { slug: 'benefits-qualifying-event-document-status', title: 'Track Benefits Qualifying-Event Documents Without Deciding Eligibility', description: 'Run a dated document and carrier-status queue while the plan owner retains eligibility, coverage, deadline, and exception decisions.', workflow: 'benefits qualifying-event document status tracking', trigger: 'an authenticated participant or authorized plan owner opens a qualifying-event case through the approved benefits channel', owner: 'the employer plan administrator, benefits, payroll, privacy, carrier, and legal owners', stop: 'event type, eligibility, acceptable evidence, coverage tier, effective date, deadline, privacy, or plan terms require interpretation', proof: 'the plan owner records the authorized disposition and the carrier or system confirms the matching coverage action or documented rejection', service: 'benefits-administration-support', example: 'A participant reports a marriage before the plan deadline but uploads a document whose names do not match the current HR record', source: { name: 'U.S. Department of Labor — Health Plans and Benefits', url: 'https://www.dol.gov/general/topic/health-plans', note: 'Official resources concerning employer health plans and participant protections.' } },
  { slug: 'interview-no-show-recovery-workflow', title: 'Build a Fair Interview No-Show Recovery Workflow', description: 'Separate calendar failures, candidate communication, accommodation signals, and recruiter decisions before closing an application.', workflow: 'interview no-show recovery', trigger: 'the approved interview window ends without a verified candidate arrival or completed interview record', owner: 'the employer recruiter, hiring, accessibility, HR, privacy, and legal owners', stop: 'delivery failure, time-zone error, accommodation, emergency, recruiter delay, interviewer absence, candidate identity, or disposition needs judgment', proof: 'the authorized recruiter records the candidate-facing next step and the scheduling history identifies whether the event was completed, rescheduled, withdrawn, or closed', service: 'interview-coordination', example: 'A candidate misses a video interview after replying to an invitation with a captioning request that never reached the interviewer', source: { name: 'EEOC — Disability Discrimination and Employment Decisions', url: 'https://www.eeoc.gov/disability-discrimination-and-employment-decisions', note: 'Official EEOC information relevant to disability and employment processes.' } },
  { slug: 'policy-translation-review-handoff', title: 'Control the Review Handoff for Translated HR Policies', description: 'Coordinate translation versions, reviewer questions, publication, and acknowledgments while qualified owners retain legal and policy meaning.', workflow: 'translated HR policy review handoff', trigger: 'the policy owner releases an approved source version, target language, audience, translator, and review path', owner: 'the employer policy, legal, HR, communications, accessibility, and local-language reviewers', stop: 'source meaning, legal terminology, jurisdiction, audience literacy, accessibility, employee rights, or conflicting versions are unclear', proof: 'the policy owner approves the source and translated versions as a paired release and the publication record identifies the version each employee received', service: 'hr-help-desk-support', example: 'A translated leave policy uses a familiar local phrase that changes who appears eligible under the approved source text', source: { name: 'EEOC — National Origin Discrimination', url: 'https://www.eeoc.gov/national-origin-discrimination', note: 'Official EEOC information concerning national-origin discrimination, including language-related employment practices.' } },
  { slug: 'employee-survey-anonymity-operations', title: 'Protect Survey Anonymity During HR Survey Operations', description: 'Prepare rosters, reminders, exports, and reporting thresholds without exposing who responded or implying anonymity the system cannot provide.', workflow: 'employee survey anonymity operations', trigger: 'the authorized survey owner releases a defined audience, approved questions, privacy notice, platform configuration, and reporting rules', owner: 'the employer survey, privacy, HR, legal, analytics, and communications owners', stop: 'identity fields, small groups, free text, manager access, response tracing, retention, consent, or reporting thresholds are uncertain', proof: 'the survey owner approves the configured collection and final report, and the output follows the promised identity and minimum-group rules', service: 'reporting-and-qa', example: 'A manager asks for response status by name so the team can reach a participation target advertised as anonymous', source: { name: 'NIST Privacy Framework', url: 'https://www.nist.gov/privacy-framework', note: 'Official framework for identifying and managing privacy risk.' } },
  { slug: 'employee-refund-reimbursement-status', title: 'Track Employee Reimbursements Without Approving Expenses', description: 'Maintain receipt, approval, payment, rejection, and follow-up evidence while budget and payroll owners decide policy and tax treatment.', workflow: 'employee reimbursement status tracking', trigger: 'an authenticated employee submits an expense through the approved reimbursement channel with a case reference', owner: 'the employer finance, manager, payroll, tax, HR, and policy owners', stop: 'business purpose, receipt sufficiency, policy exception, approval authority, taxability, currency, duplicate payment, or wage treatment is unclear', proof: 'the authorized owner records approval or rejection and the payment destination confirms the matching amount, currency, employee, and cycle', service: 'payroll-preparation-support', example: 'An employee submits a home-office purchase after a manager approved it in chat but the expense system has no policy category for the item', source: { name: 'IRS Publication 15-B', url: 'https://www.irs.gov/publications/p15b', note: 'Official IRS guide to employer tax treatment of fringe benefits.' } },
  { slug: 'disciplinary-meeting-record-routing', title: 'Route Disciplinary Meeting Records Without Expanding Access', description: 'Coordinate approved notices, attendance, acknowledgment, restricted filing, and follow-up while managers and HR retain every substantive decision.', workflow: 'disciplinary meeting record routing', trigger: 'the authorized HR or employee-relations owner opens a restricted case with approved participants, timing, and documents', owner: 'the employer manager, HR, employee-relations, privacy, legal, labor, and security owners', stop: 'facts, discipline, representation, accommodation, leave, retaliation, safety, protected activity, signature refusal, or communication content needs judgment', proof: 'the authorized case owner records the meeting disposition, approved document version, acknowledgment status, and restricted record location', service: 'performance-review-administration', example: 'An employee refuses to sign a notice and tells the coordinator the action followed a safety complaint', source: { name: 'OSHA — Whistleblower Protections', url: 'https://www.whistleblowers.gov/', note: 'Official resources concerning protected reports and anti-retaliation provisions administered by OSHA.' } },
  { slug: 'hr-vendor-contact-change-verification', title: 'Verify HR Vendor Contact Changes Before Sensitive Handoffs', description: 'Authenticate new vendor contacts and delivery instructions before releasing employee data, approving access, or redirecting payments.', workflow: 'HR vendor contact change verification', trigger: 'an approved vendor or company owner requests a contact, domain, portal, destination, or authorized-recipient change', owner: 'the employer procurement, security, privacy, HR, finance, legal, and vendor owners', stop: 'identity, authority, contract scope, domain, bank details, data destination, permission, or urgency conflicts with the trusted record', proof: 'the company owner verifies the change through a pre-established channel and each affected access, transfer, or payment workflow records the approved destination', service: 'operations-support', example: 'A benefits vendor email asks HR to upload a census to a new file-sharing domain before the normal monthly cutoff', source: { name: 'FTC — Start with Security', url: 'https://www.ftc.gov/business-guidance/resources/start-security-guide-business', note: 'Official business guidance concerning access controls, data handling, and service-provider oversight.' } },
];

export const october2BlogPosts = october2Topics.map(({ slug, title, description }) => ({
  slug: `${prefix}${slug}`,
  title,
  excerpt: description,
  minutes: 12,
  published: october2CycleDate,
}));

type SectionBrief = { heading: string; focus: string };

const firstRewritePass: readonly (readonly SectionBrief[])[] = [
  [
    { heading: 'Choose the identity anchor before editing a field', focus: 'Separate the authenticated request, the employer’s controlling HR record, payroll reporting identity, preferred display name, and the evidence required by each destination. A name is not one universal field, and a directory preference must not silently overwrite a tax or benefits record.' },
    { heading: 'Order destinations by consequence and dependency', focus: 'Map HRIS, payroll, benefits, retirement, timekeeping, identity provider, email, badges, directories, learning, and vendor portals. Update downstream systems only after their approved source is ready, and record rejections instead of repeatedly forcing a value through validation.' },
    { heading: 'Protect the employee during the transition window', focus: 'Plan for mixed-name search, email delivery, paycheck access, benefits service, travel or badge checks, and confidential display preferences. Give the employee one status contact while restricting supporting evidence to staff who actually need it.' },
    { heading: 'Reconcile the completed change rather than trusting tickets', focus: 'Compare the approved value and effective date with destination acknowledgments. Distinguish completed, intentionally different, pending, rejected, and not-applicable systems so one green master ticket cannot conceal a failed payroll or access update.' },
  ],
  [
    { heading: 'Start from approved reporting scope, not the predecessor’s account', focus: 'Define the employee population, effective instant, temporary or permanent status, and business duties that create access needs. Copying a former manager’s groups can expose complaints, compensation, medical material, investigations, and workers outside the new manager’s remit.' },
    { heading: 'Split operational approvals from confidential case ownership', focus: 'List timecards, leave workflow, schedule changes, recruiting actions, performance tasks, analytics, and employee-relations cases separately. Each application owner should grant the smallest role that supports the approved duty instead of treating manager as a single permission bundle.' },
    { heading: 'Stage the handover around the effective time', focus: 'Identify approvals that must finish before the change, tasks that can transfer at the effective time, and restricted work that HR must reassign manually. Prevent both a gap in routine approvals and an overlap in sensitive access.' },
    { heading: 'Test access from both sides of the reporting change', focus: 'Validate visible teams, available actions, delegated queues, exports, notifications, and removed permissions. Review orphaned tasks and inherited subscriptions because access can persist through reports and alerts even after the primary role changes.' },
  ],
  [
    { heading: 'Record exactly what the candidate withdrew from', focus: 'Capture the candidate’s own words, authenticated channel, received time, role or requisition, and whether the instruction covers one application or all recruiting contact. Do not turn silence, a missed interview, or a recruiter assumption into a candidate-authored withdrawal.' },
    { heading: 'Stop future activity without rewriting the past', focus: 'Cancel interviews, reminders, assessments, background steps, and hiring tasks that no longer have a valid purpose. Preserve prior stages, communications, scorecards, and source history under the employer’s retention rules instead of deleting evidence to make the pipeline tidy.' },
    { heading: 'Separate withdrawal from privacy and complaint requests', focus: 'A candidate may withdraw and separately ask for deletion, correction, accommodation follow-up, or review of treatment. Route each request to its qualified owner; a pipeline status change cannot decide record rights or close a concern.' },
    { heading: 'Close linked workflows with a truthful disposition', focus: 'Check calendars, agency submissions, referral records, offer documents, hiring-manager queues, and candidate messaging. The final record should show what stopped, what remains retained, who approved any exception, and whether another active application continues.' },
  ],
  [
    { heading: 'Establish the new date and preserve the original commitment', focus: 'Keep the accepted offer and original start date intact, then attach the candidate-agreed change, reason category, approver, effective time, and controlling version. A calendar edit alone cannot establish that both parties accepted changed timing.' },
    { heading: 'Move dependencies in a deliberate sequence', focus: 'Recalculate screening checkpoints, work-authorization tasks, payroll setup, benefits eligibility, equipment delivery, accounts, workspace, orientation, training, buddy meetings, and manager availability. Some tasks should move, while secure preparation may remain valid.' },
    { heading: 'Find consequences that a one-week shift can create', focus: 'Test pay-cycle entry, benefit waiting periods, holiday closures, expiring checks, equipment custody, travel, relocation, notice periods, and system activation rules. Route decisions instead of presenting the date shift as administratively neutral.' },
    { heading: 'Run a readiness review against the revised date', focus: 'Ask each dependency owner for a dated ready, blocked, changed, or not-applicable response. Send the candidate only approved updates, and keep unresolved internal details out of general onboarding messages.' },
  ],
];

const secondRewritePass: readonly (readonly SectionBrief[])[] = [
  [
    { heading: 'Treat a duplicate signal as a hypothesis', focus: 'Compare worker IDs, names, contact details, government identifiers, employing entities, rehire links, assignments, and effective periods without assuming a match proves duplication. Shared addresses, changed names, concurrent jobs, and data-entry errors can create false positives.' },
    { heading: 'Freeze risky changes while payroll remains observable', focus: 'Prevent unsupervised merge, deletion, direct-deposit change, tax-profile replacement, or status closure. Record affected payroll runs and let authorized payroll owners choose a controlled hold or processing path rather than losing the audit trail.' },
    { heading: 'Reconstruct how both records were created', focus: 'Trace recruiting, onboarding, HRIS, integration, import, vendor, and manual events. Identify which record each destination treats as authoritative and where pay, deductions, balances, access, or reporting has already accumulated.' },
    { heading: 'Resolve identity and reconcile financial effects separately', focus: 'Document whether the records represent one worker, a rehire, concurrent employment, or two people. After that identity decision, reconcile gross-to-net totals, taxes, benefits, time, general-ledger output, and retained history through approved corrections.' },
  ],
  [
    { heading: 'Open the case around the participant’s event statement', focus: 'Record the participant, event they reported, event date, received time, requested coverage change, plan, and approved source channel. Intake staff may describe missing fields but must not promise eligibility or a coverage date.' },
    { heading: 'Use a document-status map instead of an eligibility verdict', focus: 'Track requested, received, unreadable, identity mismatch, owner review, carrier submission, rejected, supplemented, and confirmed states. Keep sensitive supporting material in the restricted benefits system rather than copying it into reminder notes.' },
    { heading: 'Protect deadlines without manufacturing certainty', focus: 'Show plan deadlines, internal review targets, carrier cutoffs, payroll freezes, and the next owner action. If evidence or terms are disputed, preserve the submission time and escalate; do not alter an event date to make processing easier.' },
    { heading: 'Reconcile coverage, deductions, and carrier response', focus: 'Compare the plan owner’s disposition with coverage tier, covered people, effective interval, carrier acknowledgment, payroll deductions, credits, and employee communication. Leave the case open when those outcomes disagree.' },
  ],
  [
    { heading: 'Verify what failed before labeling a no-show', focus: 'Check the invitation version, accepted time, timezone, meeting link, delivery status, candidate reply, interviewer attendance, lobby records, and approved accommodation path. A failed calendar or host process should not become an adverse candidate label.' },
    { heading: 'Route signals that scheduling staff should not interpret', focus: 'Escalate disability or accommodation language, emergencies, complaints, identity concerns, technology barriers, recruiter promises, and disputed timing. Preserve the candidate’s message accurately without adding a diagnosis or credibility judgment.' },
    { heading: 'Offer a bounded recovery path', focus: 'Use recruiter-approved wording for confirmation, one rescheduling opportunity, response deadline, available formats, and contact route. Apply the employer’s stated process consistently while allowing qualified owners to approve a different response.' },
    { heading: 'Measure preventable failures as well as candidate outcomes', focus: 'Separate candidate absence from interviewer absence, link failure, timezone mismatch, delivery failure, late change, and unresolved request. Review patterns by process stage without using operational defects as candidate-quality evidence.' },
  ],
  [
    { heading: 'Freeze one approved source version for translation', focus: 'Give the translator a version identifier, publication owner, defined audience, jurisdiction, effective date, glossary, and context notes. Changes to the source after translation begins must create a visible revision rather than silent line edits.' },
    { heading: 'Review meaning where literal equivalence is unsafe', focus: 'Flag leave, discipline, reporting, benefits, safety, complaint, confidentiality, and acknowledgment terms for qualified review. Ask reviewers to explain ambiguities and employee actions, not merely proofread spelling.' },
    { heading: 'Test the document with its intended readers and format', focus: 'Check reading order, headings, links, tables, forms, contact routes, screen-reader behavior, and mobile display. Confirm that examples and date or number conventions remain clear without introducing new policy promises.' },
    { heading: 'Publish paired versions with one change history', focus: 'Link source and translation versions, approval evidence, distribution list, superseded files, acknowledgments, and correction notices. Employees should be able to identify the current document and a route for questions in the relevant language.' },
  ],
  [
    { heading: 'Define the anonymity promise in operational terms', focus: 'Specify which platform fields exist, who can see raw data, whether links or devices are traceable, how free text is treated, and the smallest reportable group. Avoid claiming anonymity when administrators can identify individual responses.' },
    { heading: 'Build a roster that supports invitations without entering analysis', focus: 'Use the minimum fields required to distribute approved invitations and reminders. Keep participation status away from line managers when the stated promise or collection purpose does not support named follow-up.' },
    { heading: 'Control small groups, filters, comments, and exports', focus: 'Test whether combinations of location, team, tenure, role, demographics, timestamps, or narrative details can reveal a respondent. Suppress, combine, redact, or route outputs under the owner’s approved rules.' },
    { heading: 'Report limitations beside every conclusion', focus: 'Show response population, response rate, excluded groups, threshold rules, missingness, weighting choices, and survey period. Do not present a voluntary snapshot as a complete workforce finding or expose comments to create a more dramatic report.' },
  ],
  [
    { heading: 'Keep receipt, business purpose, and approval as separate facts', focus: 'Record the claimant, expense date, merchant, amount, currency, category, receipt, submitted purpose, project, and named approver. A complete packet does not establish that an item is allowable, reimbursable, or non-taxable.' },
    { heading: 'Route exceptions without coaching the desired answer', focus: 'Pause duplicates, missing receipts, late submissions, unusual merchants, personal components, foreign exchange, disputed policy, manager conflicts, and payroll questions. Send the evidence and one bounded question to the correct owner.' },
    { heading: 'Track the approved amount through the payment path', focus: 'Distinguish submitted, approved, adjusted, rejected, exported, scheduled, paid, returned, and cancelled states. Preserve both claimed and approved amounts so a downstream payment does not erase the reason for a difference.' },
    { heading: 'Close from destination evidence and employee-facing clarity', focus: 'Match employee, amount, currency, payment reference, cycle, and destination response. Use approved wording to explain status and owner decisions, and leave bank, tax, wage, or policy disputes with qualified staff.' },
  ],
  [
    { heading: 'Open the restricted case from an authorized instruction', focus: 'Confirm the case owner, approved notice version, participants, meeting purpose, delivery method, representation process, timing, and restricted record location. Scheduling access does not confer access to the underlying investigation or decision file.' },
    { heading: 'Coordinate logistics without editing the decision', focus: 'Prepare invitations, approved documents, acknowledgments, interpreter or accessibility arrangements, private rooms, and attendance evidence. Route requests to change allegations, findings, consequences, or employee rights back to HR or legal owners.' },
    { heading: 'Treat new disclosures as a stop event', focus: 'Escalate safety reports, protected activity, leave, accommodation, discrimination, retaliation, pay, medical facts, threats, representation questions, and factual disputes. Do not bury them in meeting notes or promise an outcome.' },
    { heading: 'Record disposition without treating signature as agreement', focus: 'Distinguish delivery, attendance, receipt, signature, refusal, comments, appeal or review request, and assigned follow-up. File only the approved version and keep general trackers free of sensitive narrative.' },
  ],
  [
    { heading: 'Compare the requested change with the trusted vendor record', focus: 'Identify the contract entity, service, current contacts, approved domains, portals, data routes, account owners, payment details, and verification channels. A familiar logo or urgent email is not proof of authority.' },
    { heading: 'Verify authority outside the requesting message', focus: 'Use an established portal, known telephone contact, contract owner, or independently retrieved directory. Require separate review when a change affects bank instructions, employee data, credentials, administrators, or encryption keys.' },
    { heading: 'Stage access and transfers at the narrowest scope', focus: 'Test a non-sensitive acknowledgment or controlled account update before releasing live files. Limit recipient, dataset, period, purpose, expiry, download, and onward sharing according to approved terms.' },
    { heading: 'Reconcile every workflow touched by the new contact', focus: 'Review scheduled exports, shared links, mailbox rules, support tickets, invoices, access groups, integrations, and emergency contacts. Remove superseded access and retain evidence of verification, approval, first successful use, and any rejected destination.' },
  ],
];

const expandBrief = (topic: BlogBatchTopic, brief: SectionBrief, position: number) => {
  const openings = [
    `The most important design choice in this part of ${topic.workflow} is the source of authority.`,
    `This checkpoint fails when speed is allowed to stand in for evidence.`,
    `A useful operating record must explain both what changed and what deliberately did not change.`,
    `Treat this stage as a dependency decision rather than a clerical update.`,
  ];
  return [
    `${openings[position % openings.length]} ${brief.focus} Record the source event, observed value, accountable owner, effective time, and next checkpoint in terms a second reviewer can reconstruct. The support role may gather, compare, and route facts; it may not convert an incomplete or conflicting record into an approved outcome. That boundary matters because the apparent simplicity of a field, calendar item, or queue status says nothing about its downstream consequence.`,
    `For “${brief.heading.toLowerCase()},” use this redacted case in a tabletop review: ${topic.example}. Identify the first fact that prevents routine handling, the system or person that controls that fact, and the deadline that remains visible while the case is paused. The escalation should contain the relevant source and one bounded question for ${topic.owner}. It should not propose a legal, employment, pay, benefit, privacy, security, or candidate decision merely to keep the service target green.`,
    `Translate “${brief.heading.toLowerCase()}” into explicit states rather than a free-text note. Preserve submitted, source, approved, and destination values separately; attach restricted links instead of copying sensitive material; and record rejection or non-response as its own event. Stop when ${topic.stop}. If the owner supplies a new instruction, retain the prior state and add the dated decision so a later reviewer can see why the workflow changed direction.`,
    `Close “${brief.heading.toLowerCase()}” from destination evidence. For this workflow, ${topic.proof}. A reminder, sent email, successful upload, or checked box proves activity, not the authoritative result. Review rejected and reopened cases weekly, because they reveal weak source data, ambiguous ownership, integration defects, or an unrealistic cutoff. Improve the access design and playbook instead of asking the coordinator to assume authority the role does not have.`,
  ];
};

const baseOctober2Articles = buildBlogBatch(october2CycleDate, prefix, october2Topics);

export const october2Articles = Object.fromEntries(Object.entries(baseOctober2Articles).map(([slug, article], articleIndex) => [slug, {
  ...article,
  heroImage: '/hr-team.jpg',
  ...((firstRewritePass[articleIndex] ?? secondRewritePass[articleIndex - firstRewritePass.length]) ? {
    minutes: 15,
    sections: (firstRewritePass[articleIndex] ?? secondRewritePass[articleIndex - firstRewritePass.length]).map((brief, sectionIndex) => ({
      heading: brief.heading,
      paragraphs: expandBrief(october2Topics[articleIndex], brief, sectionIndex),
    })),
  } : {}),
}]));
