import type { RichArticle } from './article-data';
import { october5BlogDate } from './october5-blog-batch';

const slug = 'design-30-day-outsourced-hr-administration-pilot';
export const october5PilotPost = { slug, title: 'Design a 30-Day Outsourced HR Administration Pilot', excerpt: 'Test a bounded mix of real HR work, retained owner effort, employee experience, controls, and failure recovery before expanding outsourced support.', minutes: 16, published: october5BlogDate } as const;

const sections: RichArticle['sections'] = [
  { heading: 'Write the pilot question before selecting the work', paragraphs: [
    'A useful pilot answers a decision the company is prepared to make. Examples include whether an outsourced coordinator can keep onboarding dependencies visible, whether a help desk can route employee requests safely, or whether interview scheduling can move without increasing manager effort. Write the question, proposed scope, decision date, approver, and evidence required. Avoid a broad goal such as see how it goes. Without a decision rule, ordinary startup friction and sales enthusiasm can both be mistaken for proof.',
    'Set boundaries around employee populations, systems, channels, hours, and tasks. Keep employment decisions, policy interpretation, legal questions, compensation approval, benefit eligibility, investigations, sensitive exceptions, and access administration with named company owners. State which actions the provider may prepare or complete and which require approval. A small scope is not a weak test when it contains the full handoffs of a real workflow. It is stronger than giving the provider scattered low-risk errands that reveal nothing about operating discipline.'
  ]},
  { heading: 'Establish a baseline that shows current burden', paragraphs: [
    'Before launch, sample recent work using the same definitions planned for the pilot. Record volume, peaks, acknowledgment, elapsed time, owner touches, rework, duplicate contacts, rejected updates, missing evidence, employee follow-ups, and destination completion. Note where the company lacks reliable data instead of manufacturing precision. The baseline should expose internal effort: a request finished in one day may still require five manager messages and manual reconstruction by HR. That burden matters when assessing whether outsourcing creates capacity.',
    'Preserve context around unusual weeks. A holiday, payroll calendar, hiring surge, system outage, or benefit deadline can make one period unrepresentative. Use ranges and case narratives alongside aggregates. Do not compare the provider’s carefully selected pilot week with an unexplained annual average. The purpose is to understand what changed, not to produce a flattering percentage. If the baseline reveals an unsafe process, correct the immediate risk rather than requiring the provider to reproduce it for experimental consistency.'
  ]},
  { heading: 'Choose cases that exercise the complete operating loop', paragraphs: [
    'Build a case mix containing routine, ambiguous, deadline-sensitive, duplicate, and restricted-routing scenarios. For onboarding, include an ordinary hire, changed start date, missing document, absent manager, and system rejection. For employee support, include a status request, record correction, payroll concern, sensitive message in the wrong channel, and question outside scope. Use real supervised work when appropriate and redacted simulations when live exposure is unnecessary. Each case should test intake, authentication, source selection, authorized action, decision routing, employee update, destination evidence, and closure.',
    'Do not pad the pilot with easy volume. A hundred template acknowledgments cannot demonstrate whether the provider recognizes a conflict or protects an attachment. At the same time, do not design only traps. The provider needs enough ordinary work to establish a stable routine and show how it manages a queue. Document the expected path and stop rule before the case begins. Reviewers can then distinguish a provider defect from an unclear company instruction, product limitation, missing access, or delayed owner decision.'
  ]},
  { heading: 'Measure company owner effort as part of delivery', paragraphs: [
    'Track every substantive touch by company HR, payroll, benefits, privacy, security, hiring managers, or other owners. Classify it as an expected decision, clarification, correction, access task, escalation, or avoidable chase. Outsourcing should not be judged only by provider hours or ticket closure. If internal owners must repeatedly restate scope, locate missing sources, or ask for status, the operating model is not yet producing the intended leverage. Conversely, necessary decisions should not count as provider failure merely because authority remains with the company.',
    'Examine the quality of decision packets. A strong escalation contains the authenticated source, completed steps, conflicting evidence, affected deadline, employee communication, and exact decision needed. A weak escalation forwards an email with no context. Measure whether owners can decide without reconstructing the case and whether instructions return to the correct record. This reveals a core value of administrative support: not replacing accountable judgment, but making that judgment timely, bounded, and easier to exercise.'
  ]},
  { heading: 'Review defects through cause and recovery', paragraphs: [
    'Create a defect log with case reference, consequence, detection source, affected employee, immediate containment, root-cause category, owner, correction, retest, and employee follow-up. Categories may include unclear instruction, training gap, access design, source-data problem, provider execution, system limitation, or company decision delay. Do not use the log to assign blame before evidence exists. Its purpose is to show whether the combined service can find, contain, explain, and prevent a recurrence.',
    'Test recovery deliberately. Use a duplicate record, wrong destination, missed dependency, unavailable owner, or provider outage in a controlled scenario. Observe who notices, how work is protected, what employees are told, and whether the final record preserves the original error and correction. A pilot that records only successful cases cannot support a resilience decision. The company needs evidence that failures remain visible and recoverable rather than disappearing behind a completed status.'
  ]},
  { heading: 'Make the day-30 decision from named evidence', paragraphs: [
    'Set review gates during the month rather than waiting for a final presentation. An early gate can confirm access and routing, a middle gate can assess case handling and owner burden, and the final gate can address stability, recovery, and residual defects. Define blockers for expansion, such as uncontrolled sensitive access, incorrect employee associations, silent missed deadlines, unsupported answers, unreliable evidence, or owner effort materially above the accepted design. Assign correction and retest instead of averaging critical failures into a general score.',
    'The final decision may be expand, continue within the same boundary, correct and retest, reduce scope, or stop. Preserve the baseline, cases, measures, defect history, owner feedback, employee-impact evidence, outstanding risks, and approved next step. Do not convert a pilot date into automatic production approval. The reader outcome is a bounded experiment whose conclusion another leader can audit: the tested work was real, authority remained clear, burdens and failures were visible, and expansion follows evidence rather than momentum.'
  ]}
];

export const october5PilotArticles: Record<string, RichArticle> = { [slug]: {
  slug, title: october5PilotPost.title, description: october5PilotPost.excerpt, published: october5BlogDate, updated: october5BlogDate, minutes: 16, revision: '2026-10-05-hr-admin-pilot-draft-1', heroImage: '/hr-team.jpg',
  directAnswer: ['Design a 30-day outsourced HR administration pilot around one decision question, a bounded but complete workflow, a baseline, representative and difficult cases, retained company-owner effort, defect recovery, and explicit expansion gates.', 'Do not treat the calendar end as approval. Expand only when evidence shows the provider can operate authorized tasks, route decisions, protect records, communicate with employees, recover failures, and reduce avoidable owner burden.'],
  takeaways: sections.map(section=>section.heading), sections,
  taskRows: sections.map((section,index)=>({lane:section.heading,philippinesTeam:`Operate and document pilot checkpoint ${index+1}.`,owner:`Approve scope, decisions, and gate ${index+1}.`,check:'Retain baseline, case evidence, owner effort, defect, recovery, and result.'})),
  pilotStats: [{value:'1',label:'Decision question',note:'Written before selecting work.'},{value:'3',label:'Review gates',note:'Access, operations, and final evidence.'},{value:'2',label:'Case sources',note:'Supervised live work and redacted simulations.'},{value:'0',label:'Automatic approvals',note:'The calendar never replaces evidence.'}],
  scripts: [{label:'Decision packet',text:'Here are the authenticated source, completed actions, conflict, affected deadline, employee update, and exact company decision needed.'},{label:'Pilot defect notice',text:'The case failed the stated checkpoint. The immediate risk is contained, the original evidence is preserved, and the named owner will correct and retest the full path.'}],
  workflow: sections.map((section,index)=>({step:String(index+1).padStart(2,'0'),title:section.heading,text:section.paragraphs[0].split('. ')[0]+'.'})),
  faqs: [{question:'How much work belongs in the pilot?',answer:'Use a bounded scope containing complete workflows and a meaningful mix of ordinary and difficult cases.'},{question:'Should employee cases be simulated?',answer:'Use supervised live work where appropriate and redacted simulations when live exposure is unnecessary.'},{question:'What internal effort should be counted?',answer:'Track required decisions separately from avoidable clarification, correction, access, and status-chasing work.'},{question:'What happens on day 30?',answer:'Choose expand, continue, correct and retest, reduce scope, or stop from the named evidence and blockers.'}],
  related: [{title:'HR operations support',href:'/services/operations-support',note:'Choose a bounded administrative workflow.'},{title:'HR reporting and QA',href:'/services/reporting-and-qa',note:'Define evidence and defect review.'},{title:'Onboarding coordination',href:'/services/onboarding-coordination',note:'Build a dependency-rich pilot case.'},{title:'Plan a supervised HR pilot',href:'/contact-us',note:'Discuss scope, owners, cases, and decision gates.'}],
  sources: [{name:'NIST Cybersecurity Framework 2.0',url:'https://www.nist.gov/cyberframework',note:'Official framework supporting governed risk, response, and recovery.'},{name:'NIST Privacy Framework',url:'https://www.nist.gov/privacy-framework',note:'Official framework for assessing privacy risk in data processing.'}], banners: []
} };
