import type { RichArticle } from './article-data';

const date = '2026-09-18';

type Topic = {
  slug: string; title: string; description: string; workflow: string; trigger: string;
  owner: string; stop: string; proof: string; service: string;
  source: { name: string; url: string; note: string };
};

const topics: Topic[] = [
  { slug: 'i9-reverification-deadline-queue', title: 'How to Run an I-9 Reverification Deadline Queue', description: 'A practical workflow for tracking Form I-9 reverification dates without letting an outsourced HR coordinator choose documents or decide work authorization.', workflow: 'I-9 reverification tracking', trigger: 'an authorized company owner places a worker and required follow-up date on the approved reverification list', owner: 'the employer representative responsible for Form I-9 compliance', stop: 'a document appears unacceptable, a date conflicts, discrimination concerns arise, or work authorization requires interpretation', proof: 'the employer representative confirms the completed action in the restricted I-9 record', service: 'employee-records-administration', source: { name: 'USCIS Handbook for Employers (M-274)', url: 'https://www.uscis.gov/i-9-central/form-i-9-resources/handbook-for-employers-m-274', note: 'Official employer guidance for Form I-9 completion, reverification, and prohibited practices.' } },
  { slug: 'fmla-notice-deadline-tracker', title: 'Build an FMLA Notice and Deadline Tracker Without Making Eligibility Decisions', description: 'Track FMLA-related notices, forms, and owner deadlines while qualified company owners retain eligibility, designation, and leave decisions.', workflow: 'FMLA notice and deadline tracking', trigger: 'the designated leave owner opens a case after receiving information that may require an FMLA review', owner: 'the employer leave administrator or qualified adviser', stop: 'eligibility, certification sufficiency, designation, intermittent leave, retaliation, or another legal question must be decided', proof: 'the leave owner records the issued notice, decision, and next deadline in the authorized leave system', service: 'hr-help-desk-support', source: { name: 'U.S. Department of Labor FMLA Employer Guide', url: 'https://www.dol.gov/agencies/whd/fmla/employer-guide', note: 'Official employer guide to FMLA responsibilities and notices.' } },
  { slug: 'accommodation-request-intake-routing', title: 'Route Workplace Accommodation Requests Without Diagnosing or Deciding', description: 'Set up a discreet accommodation-request intake lane that preserves the employee message and moves decisions to the authorized company team.', workflow: 'workplace accommodation request intake', trigger: 'an employee or applicant communicates that a workplace change may be needed for a medical or religious reason', owner: 'the authorized HR, legal, or accommodation decision owner', stop: 'the request needs medical inquiry, undue-hardship analysis, a legal conclusion, or a change to employment terms', proof: 'the authorized owner acknowledges receipt and records the controlled next step without exposing unnecessary detail', service: 'hr-help-desk-support', source: { name: 'EEOC Enforcement Guidance on Reasonable Accommodation', url: 'https://www.eeoc.gov/laws/guidance/enforcement-guidance-reasonable-accommodation-and-undue-hardship-under-ada', note: 'Official EEOC guidance on the accommodation process and employer responsibilities.' } },
  { slug: 'cobra-qualifying-event-handoff', title: 'Create a COBRA Qualifying-Event Handoff That Protects Deadlines', description: 'Coordinate event intake and vendor handoff for COBRA administration without allowing support staff to decide plan coverage or qualified-beneficiary status.', workflow: 'COBRA qualifying-event handoff', trigger: 'the benefits owner confirms that an employment or dependent event should enter the COBRA review lane', owner: 'the plan administrator or authorized benefits specialist', stop: 'plan coverage, event classification, qualified-beneficiary status, election rights, premium treatment, or notice timing is disputed', proof: 'the plan administrator or vendor confirms receipt with the event record and required notice status', service: 'benefits-administration-support', source: { name: 'U.S. Department of Labor COBRA Continuation Coverage', url: 'https://www.dol.gov/agencies/ebsa/laws-and-regulations/laws/cobra', note: 'Official overview and employer resources for COBRA continuation coverage.' } },
  { slug: 'background-check-authorization-status', title: 'Track Background-Check Authorization and Status Without Screening Candidates', description: 'Keep recruiting logistics moving while decision owners control disclosure, authorization, adverse-action, and hiring judgments.', workflow: 'background-check authorization and status tracking', trigger: 'the recruiting owner requests an approved screening step for a named candidate and role', owner: 'the employer representative authorized to manage screening compliance and hiring decisions', stop: 'authorization is missing, identity data conflicts, a report may affect the decision, or adverse-action steps may apply', proof: 'the authorized owner confirms the permitted status and next candidate communication in the recruiting record', service: 'candidate-sourcing', source: { name: 'Federal Trade Commission: Background Checks', url: 'https://www.ftc.gov/business-guidance/resources/background-checks-what-employers-need-know', note: 'Official business guidance on federal background-check duties under the FCRA.' } },
  { slug: 'wage-garnishment-order-intake', title: 'Design a Wage Garnishment Order Intake and Payroll Handoff', description: 'Receive, restrict, and route garnishment orders to qualified payroll owners without interpreting the order or changing deductions independently.', workflow: 'wage garnishment order intake', trigger: 'an order arrives through an approved company channel and is assigned a controlled case identifier', owner: 'the authorized payroll, legal, or garnishment administrator', stop: 'the person, order, jurisdiction, priority, amount, protected earnings, response, or withholding treatment is unclear', proof: 'the authorized owner records the instruction, effective payroll cycle, and secure destination confirmation', service: 'payroll-preparation-support', source: { name: 'U.S. Department of Labor Fact Sheet 30', url: 'https://www.dol.gov/agencies/whd/fact-sheets/30-cppa', note: 'Official Wage and Hour Division summary of federal wage-garnishment protections.' } },
  { slug: 'unemployment-claim-deadline-routing', title: 'Route Unemployment Claim Notices Before the Response Deadline', description: 'Build a factual intake and evidence-collection lane for unemployment claim notices while the employer controls the response and legal position.', workflow: 'unemployment claim notice routing', trigger: 'a state notice reaches the approved mailbox or portal and is assigned to the responsible company owner', owner: 'the employer representative or adviser authorized to respond to the state agency', stop: 'facts are disputed, a separation reason must be characterized, a hearing is scheduled, or a legal position is requested', proof: 'the response owner records timely submission or another authorized disposition with source evidence', service: 'offboarding-coordination', source: { name: 'U.S. Department of Labor Unemployment Insurance', url: 'https://www.dol.gov/general/topic/unemployment-insurance', note: 'Official federal overview with links to state unemployment insurance programs.' } },
  { slug: 'workplace-incident-record-intake', title: 'Set Up Workplace Incident Record Intake Without Investigating the Case', description: 'Capture immediate facts, protect sensitive records, and alert safety owners without asking an outsourced coordinator to investigate or classify an incident.', workflow: 'workplace incident record intake', trigger: 'a worker, manager, or approved system reports an injury, illness, or safety event', owner: 'the company safety, HR, workers compensation, or legal owner', stop: 'urgent care is needed, facts are contested, recordability or causation must be decided, or retaliation concerns appear', proof: 'the responsible owner acknowledges the event and records the authorized safety, claim, or reporting action', service: 'operations-support', source: { name: 'OSHA Recordkeeping', url: 'https://www.osha.gov/recordkeeping', note: 'Official OSHA recordkeeping resources and employer guidance.' } },
  { slug: 'employment-verification-request-control', title: 'Control Employment Verification Requests From Intake to Release', description: 'Use a narrow verification workflow that authenticates the requester, limits disclosed fields, and preserves employer approval.', workflow: 'employment verification request handling', trigger: 'a request arrives through an approved verification channel with a stated purpose and employee identity', owner: 'the company representative authorized to approve employment information releases', stop: 'consent is missing, requester identity is uncertain, requested fields exceed policy, or employment facts conflict', proof: 'the authorized owner approves the exact fields and the delivery channel records successful release', service: 'employee-records-administration', source: { name: 'NIST Privacy Framework', url: 'https://www.nist.gov/privacy-framework', note: 'Official framework for identifying and managing privacy risk in data processing.' } },
  { slug: 'new-hire-reporting-handoff', title: 'Build a New-Hire Reporting Handoff With State Confirmation', description: 'Prepare state new-hire reporting records from approved payroll data while employer owners retain filing responsibility and exception decisions.', workflow: 'new-hire reporting preparation and handoff', trigger: 'an approved hire enters payroll with the fields required by the employer reporting process', owner: 'the employer or authorized payroll representative responsible for the filing', stop: 'a required identifier is missing, the work state is uncertain, duplicate employment exists, or a filing rule needs interpretation', proof: 'the authorized filer records acceptance or a corrected response from the designated reporting destination', service: 'onboarding-coordination', source: { name: 'Office of Child Support Services: New Hire Reporting', url: 'https://www.acf.hhs.gov/css/employers/employer-responsibilities/new-hire-reporting', note: 'Official federal employer overview of state new-hire reporting responsibilities.' } },
  { slug: 'personnel-record-correction-request', title: 'Manage Personnel-Record Correction Requests Without Silent Overwrites', description: 'Preserve the employee request, source evidence, approval, effective date, and downstream confirmation for personnel-record corrections.', workflow: 'personnel-record correction request handling', trigger: 'an employee submits a correction through the approved HR channel and the request receives a stable case ID', owner: 'the company HR record owner authorized to approve the correction', stop: 'the source conflicts, the change affects pay or employment terms, retention is disputed, or a legal access question arises', proof: 'the owner-approved value, effective date, prior value, and destination confirmation remain linked in the case record', service: 'employee-records-administration', source: { name: 'NIST Privacy Framework', url: 'https://www.nist.gov/privacy-framework', note: 'Official privacy-risk framework used for controlled data processing and accountability.' } },
  { slug: 'applicant-record-retention-disposal-queue', title: 'Run an Applicant-Record Retention and Disposal Queue', description: 'Track recruiting records through approved retention and disposal decisions without deleting evidence early or keeping candidate data by default.', workflow: 'applicant-record retention and disposal tracking', trigger: 'a closed requisition or candidate record reaches the review date set by the employer retention schedule', owner: 'the employer records, legal, privacy, or recruiting owner', stop: 'a complaint, charge, litigation hold, contract, audit, or conflicting retention requirement may apply', proof: 'the authorized owner records retention, hold, or disposal approval and the destination confirms the action', service: 'candidate-sourcing', source: { name: 'EEOC Recordkeeping Requirements', url: 'https://www.eeoc.gov/employers/recordkeeping-requirements', note: 'Official EEOC overview of employment recordkeeping requirements.' } }
];

export const september18BlogPosts = topics.map(({ slug, title, description }) => ({ slug: `september18-hr-${slug}`, title, excerpt: description, minutes: 12, published: date }));

export const september18Articles: Record<string, RichArticle> = Object.fromEntries(topics.map((topic, index) => {
  const slug = `september18-hr-${topic.slug}`;
  return [slug, {
    slug, title: topic.title, description: topic.description, published: date, updated: date, minutes: 12,
    revision: `${date}-${slug}`,
    directAnswer: [
      `Treat ${topic.workflow} as a controlled administrative lane, not as delegated authority. Open the lane only when ${topic.trigger}. Give the coordinator a written field list, a named company owner, a response target, and a stop rule.`,
      `A Philippines-based HR coordinator can preserve source records, check required fields, maintain deadlines, request missing administrative details, and prepare a handoff. The coordinator should stop when ${topic.stop}. Close the item only after ${topic.proof}.`
    ],
    takeaways: [
      'Start from the original notice, request, or approved system event.',
      'Keep copied tracker fields separate from the controlling record.',
      `Send decisions and exceptions to ${topic.owner}.`,
      'Limit access, exports, downloads, and messages to the assigned task.',
      `Require ${topic.proof} before marking the work complete.`
    ],
    taskRows: [
      { lane: 'Open', philippinesTeam: 'Preserve the source, received time, case identity, due date, and assigned owner.', owner: 'Confirm that the case belongs in this workflow and define the permitted task.', check: 'The original source remains retrievable' },
      { lane: 'Prepare', philippinesTeam: 'Check the approved field list and identify missing or conflicting information without resolving it.', owner: 'Answer exceptions and approve any consequential instruction.', check: 'Submitted, source, and approved values are distinct' },
      { lane: 'Route', philippinesTeam: `Pause when ${topic.stop}. Send one bounded question through the restricted channel.`, owner: 'Make the required decision and return a dated instruction.', check: 'The decision has a person, time, and source' },
      { lane: 'Close', philippinesTeam: 'Apply only the approved administrative step and attach destination evidence.', owner: 'Review the result and authorize closure.', check: topic.proof }
    ],
    pilotStats: [
      { value: '1', label: 'Source record', note: 'Keep the controlling evidence intact' },
      { value: '5', label: 'Test paths', note: 'Routine, missing, conflict, sensitive, failed destination' },
      { value: String(8 + index), label: 'Pilot cases', note: 'Review every early case' },
      { value: '2', label: 'Owner checks', note: 'Decision and closeout' }
    ],
    sections: [
      { heading: `Define the opening event for ${topic.workflow}`, paragraphs: [`A reliable queue begins with an event someone can verify. For this workflow, open the task only when ${topic.trigger}. Record who supplied the event, when it arrived, the source location, the accountable company owner, and the next required checkpoint. Do not open work from an unverified forwarded message or a coordinator's assumption.`, `Write a one-page role boundary before the first live case. It should list permitted fields, approved systems, the exact administrative actions the coordinator may take, and the decisions reserved for ${topic.owner}. Include examples of a routine record, an incomplete record, a conflict, and an urgent escalation so the procedure works when the easy path fails.`] },
      { heading: 'Keep the source separate from the working queue', paragraphs: [`A shared tracker helps people see ownership and timing, but it should not become a second personnel file. Keep the original request, notice, form, or system event in its approved location. Put only the case ID, status, owner, due time, next action, and minimum operational detail in the queue. Link to the restricted source instead of copying sensitive narratives into comments.`, `When new information arrives, add a dated event rather than replacing the earlier value. A reviewer should be able to distinguish what was submitted, what the controlling source showed, what the owner approved, and what eventually reached the destination. That history prevents silent corrections and gives the company a usable record when an employee, vendor, auditor, or manager asks what happened.`] },
      { heading: 'Separate completeness checks from decisions', paragraphs: [`The coordinator may compare a record with a written checklist: required field present, identifier formatted, owner assigned, due date recorded, attachment readable, and destination available. Those checks describe the packet; they do not establish legal sufficiency or decide the person's rights. Use labels such as received, missing field, waiting for owner, approved action, destination rejected, and closed.`, `The stop rule is central: pause when ${topic.stop}. The handoff should quote or link the relevant source, name the unresolved point, identify the person who can decide it, and state the deadline. It should not recommend an employment outcome, diagnose a condition, characterize a dispute, or invent an answer merely to keep the service-level clock green.`] },
      { heading: 'Use narrow access and controlled communication', paragraphs: [`Grant a named account only the permissions required to view the queue, retrieve its approved source, and perform the documented administrative action. Review search, bulk export, download, forwarding, printing, delegated mailbox access, and deletion separately. A person who can update status does not automatically need every attachment or the ability to release information outside the company.`, `Prepare message templates for receipt, missing administrative fields, owner escalation, deadline reminder, and confirmed closeout. A template is not permission to answer a new policy or legal question. If a reply changes a person's pay, benefits, leave, work status, privacy rights, safety response, or candidacy, return it to the owner for approval before sending.`] },
      { heading: 'Test the exceptions before scaling the queue', paragraphs: [`Run at least five redacted scenarios: a complete routine case, a missing required field, two sources that disagree, a message containing sensitive information, and a destination that rejects the update. For each scenario, check whether the coordinator knows where to stop, whether the correct owner receives an answerable question, and whether someone can reconstruct the result from retained evidence.`, `Review every early case instead of sampling immediately. Track defects by type: wrong source, excess data copied, missed deadline, unapproved message, owner ambiguity, premature closure, or missing destination proof. Correct the checklist or access design that produced the defect. Do not solve a process problem by asking the coordinator to exercise authority the role was never meant to hold.`] },
      { heading: 'Measure aging, decisions, and closure separately', paragraphs: [`A useful dashboard separates open volume from completed work. Show received time, next deadline, current owner, waiting reason, owner-response time, rejected destination updates, reopened cases, and age at closure. Do not count a forwarded email as a completed case. Forwarding measures activity; completion requires the authorized outcome and evidence from the system or owner that controls it.`, `For ${topic.workflow}, the closure standard is specific: ${topic.proof}. Leave the task open if that evidence is absent. If the owner intentionally chooses another disposition, record that dated instruction instead of forcing the case into a completed status. Weekly review should focus on repeated waiting reasons and unclear ownership, not on pressuring staff to close unresolved work.`] },
      { heading: 'Plan handback, retention, and access removal', paragraphs: [`The employer should set retention and disposal rules for the source, working queue, approvals, exports, and closeout evidence. The coordinator can apply an approved schedule but should not decide how long a personnel, benefits, medical, payroll, recruiting, safety, or legal record must remain. Holds, complaints, audits, and active disputes go to the qualified owner before anything is changed or removed.`, `When the assignment changes or ends, transfer every open case with its source link, current status, owner, deadline, unresolved question, and last verified action. Remove the named account, delegated mailbox rights, shared links, exports, and local downloads according to the company checklist. Have the company owner confirm both access removal and ownership of the remaining queue.`] },
      { heading: 'Questions to ask an HR outsourcing provider', paragraphs: [`Ask the provider to demonstrate ${topic.workflow} with one ordinary redacted example and one exception. Have the proposed coordinator show the opening event, minimum queue fields, access boundary, stop rule, owner handoff, destination check, and closeout proof. A clear demonstration is more useful than a promise that the team follows best practices.`, `Confirm who reviews the first cases, how quickly an unresolved item reaches ${topic.owner}, what happens when that owner does not respond, and how corrections are preserved. Ask how accounts are provisioned and removed, how restricted material stays out of shared notes, and how the provider returns open work. Use the answers to define a small pilot before increasing volume.`] }
    ],
    scripts: [
      { label: 'Owner escalation', text: `I paused this ${topic.workflow} item because ${topic.stop}. The source and conflicting or missing fields remain unchanged. Please provide the controlling instruction and effective date.` },
      { label: 'Closeout check', text: `Before closure, please confirm that ${topic.proof}. I will keep the case pending until that evidence is attached or you approve another disposition.` }
    ],
    workflow: [
      { step: '01', title: 'Receive', text: 'Preserve the source, received time, case ID, owner, and deadline.' },
      { step: '02', title: 'Check', text: 'Compare the approved field list without deciding conflicts.' },
      { step: '03', title: 'Escalate', text: 'Send one bounded question to the authorized company owner.' },
      { step: '04', title: 'Apply', text: 'Perform only the dated administrative instruction.' },
      { step: '05', title: 'Verify', text: 'Confirm the destination, attach evidence, and complete owner review.' }
    ],
    faqs: [
      { question: `Can an outsourced HR coordinator own ${topic.workflow}?`, answer: 'The coordinator can own the documented administrative queue, completeness checks, reminders, and evidence collection. The company must retain legal, policy, employment, pay, benefits, safety, privacy, and exception decisions.' },
      { question: 'What should be kept in the shared tracker?', answer: 'Use a case ID, status, assigned owner, deadline, waiting reason, next action, and source link. Keep sensitive documents and narratives in the approved restricted system.' },
      { question: 'What happens when information conflicts?', answer: `Preserve both values and their sources, then route the decision to ${topic.owner}. Do not overwrite one value to make the queue look complete.` },
      { question: 'What proves the task is complete?', answer: `Require this result: ${topic.proof}. A sent email, reminder, or checked box does not by itself prove the authoritative destination changed.` },
      { question: 'How should the first month be reviewed?', answer: 'Review every early case, classify defects, inspect access and messages, and revise the written boundary before increasing volume or reducing the review rate.' }
    ],
    related: [
      { title: 'Related HR service', href: `/services/${topic.service}`, note: 'Review the matching administrative support lane.' },
      { title: 'HR reporting and QA', href: '/services/reporting-and-qa', note: 'Design owner checks and destination evidence.' },
      { title: 'Plan your HR support workflow', href: '/contact-us', note: 'Bring a redacted case to a role-scoping discussion.' }
    ],
    sources: topic.source.url === 'https://www.nist.gov/privacy-framework' ? [topic.source] : [topic.source, { name: 'NIST Privacy Framework', url: 'https://www.nist.gov/privacy-framework', note: 'Official framework for managing privacy risk and accountable data processing.' }],
    banners: [
      { eyebrow: 'Map the case', title: `Define the ${topic.workflow} boundary.`, text: 'Name the source, permitted checks, decision owner, stop rule, and closeout proof.', href: `/services/${topic.service}`, linkLabel: 'Review the service scope' },
      { eyebrow: 'Test the handoff', title: 'Practice the exception before increasing volume.', text: 'Use redacted routine, missing-field, conflict, sensitive, and failed-update cases.', href: '/services/reporting-and-qa', linkLabel: 'See reporting and QA' },
      { eyebrow: 'Scope the role', title: 'Keep consequential decisions with the employer.', text: 'Turn a real workflow into a narrow support brief with named owner checks.', href: '/contact-us', linkLabel: 'Discuss HR support' }
    ]
  } satisfies RichArticle];
}));
