import type { RichArticle } from './article-data';

const date = '2026-09-22';

export type BlogBatchTopic = {
  slug: string; title: string; description: string; workflow: string; trigger: string;
  owner: string; stop: string; proof: string; service: string;
  example: string; source: { name: string; url: string; note: string };
};

const topics: BlogBatchTopic[] = [
  { slug: 'payroll-deduction-authorization-intake', title: 'How to Control Payroll Deduction Authorization Intake', description: 'A practical intake lane for deduction requests that preserves employee authorization and keeps pay decisions with the employer.', workflow: 'payroll deduction authorization intake', trigger: 'an employee submits a request through the approved channel and the payroll owner confirms the request type is supported', owner: 'the authorized payroll and benefits owner', stop: 'authorization is missing, the amount or effective date conflicts, the deduction may be legally restricted, or net pay could be affected unexpectedly', proof: 'the payroll owner confirms the approved deduction, effective pay cycle, and post-payroll result', service: 'payroll-preparation-support', example: 'An employee asks to begin a voluntary deduction, but the signed form and ticket show different effective dates', source: { name: 'IRS Publication 15, Employer’s Tax Guide', url: 'https://www.irs.gov/publications/p15', note: 'Official federal employer guidance for payroll withholding and employment taxes.' } },
  { slug: 'payroll-tax-notice-routing', title: 'Route Payroll Tax Notices Without Losing the Response Clock', description: 'Receive, restrict, and route payroll tax notices while qualified company owners control interpretation and response.', workflow: 'payroll tax notice routing', trigger: 'an original agency notice arrives in an approved mailbox or portal and receives a stable case ID', owner: 'the employer tax, payroll, finance, or legal owner', stop: 'the notice identity is uncertain, amounts conflict with payroll records, a deadline needs interpretation, or a response position must be chosen', proof: 'the authorized owner records the disposition, submission evidence, and next monitoring date', service: 'payroll-preparation-support', example: 'A notice references a quarter that does not match the period named in the internal ticket', source: { name: 'IRS Employment Tax Recordkeeping', url: 'https://www.irs.gov/businesses/small-businesses-self-employed/employment-tax-recordkeeping', note: 'Official IRS recordkeeping guidance for employment taxes.' } },
  { slug: 'benefits-carrier-census-reconciliation', title: 'Reconcile a Benefits Carrier Census Before File Delivery', description: 'Compare approved eligibility data with a carrier census without allowing support staff to decide coverage or plan eligibility.', workflow: 'benefits carrier census reconciliation', trigger: 'the benefits owner releases a dated eligibility roster and carrier template for the same coverage period', owner: 'the plan administrator or authorized benefits specialist', stop: 'eligibility, dependent status, class, coverage level, effective date, or plan interpretation is unclear', proof: 'the benefits owner approves the final census and the carrier confirms accepted processing', service: 'benefits-administration-support', example: 'The HR system lists family coverage while the carrier extract lists employee-only coverage', source: { name: 'U.S. Department of Labor Health Plans and Benefits', url: 'https://www.dol.gov/general/topic/health-plans', note: 'Official DOL overview and resources for employer health benefit plans.' } },
  { slug: 'retirement-contribution-change-handoff', title: 'Build a Retirement Contribution Change Handoff', description: 'Track employee contribution-change requests from source to payroll and plan confirmation without giving advice or changing elections.', workflow: 'retirement contribution change handoff', trigger: 'an authenticated employee election reaches the plan’s approved workflow', owner: 'the plan administrator and authorized payroll owner', stop: 'the election is incomplete, limits or plan terms need interpretation, payroll timing is disputed, or the employee requests financial advice', proof: 'the plan and payroll owners confirm the approved effective cycle and destination result', service: 'benefits-administration-support', example: 'The plan portal shows a new percentage after payroll has already frozen inputs for the next run', source: { name: 'DOL Employee Contributions Fact Sheet', url: 'https://www.dol.gov/sites/dolgov/files/EBSA/about-ebsa/our-activities/resource-center/fact-sheets/employee-contributions-fact-sheet.pdf', note: 'Official EBSA guidance about safeguarding and forwarding employee plan contributions.' } },
  { slug: 'workers-compensation-document-handoff', title: 'Coordinate a Workers’ Compensation Document Handoff', description: 'Preserve incident and claim documents, control access, and route deadlines without deciding causation, coverage, or recordability.', workflow: 'workers compensation document handoff', trigger: 'the company safety or HR owner opens a claim-support case after an incident report or carrier request', owner: 'the company safety, HR, insurance, or legal owner', stop: 'medical care is urgent, facts conflict, causation or coverage is questioned, recordability must be decided, or retaliation concerns appear', proof: 'the authorized owner or carrier confirms receipt and records the next required action', service: 'hr-help-desk-support', example: 'A carrier asks for a document whose dates differ from the original incident report', source: { name: 'OSHA Injury and Illness Recordkeeping', url: 'https://www.osha.gov/recordkeeping', note: 'Official OSHA recordkeeping resources; state claim rules may also apply.' } },
  { slug: 'performance-plan-meeting-coordination', title: 'Coordinate Performance Plan Meetings Without Managing the Decision', description: 'Schedule sensitive performance meetings and preserve approved materials while managers retain evaluation and employment decisions.', workflow: 'performance plan meeting coordination', trigger: 'the authorized HR or management owner opens a restricted coordination request with approved attendees and materials', owner: 'the employee’s manager and authorized HR or legal owner', stop: 'content changes, the employee disputes facts, accommodation or leave issues appear, or any employment decision is requested', proof: 'the owner confirms the meeting disposition, approved record location, and any assigned follow-up', service: 'performance-review-administration', example: 'A manager changes a meeting time after the employee has received an approved invitation', source: { name: 'EEOC Prohibited Employment Policies and Practices', url: 'https://www.eeoc.gov/prohibited-employment-policiespractices', note: 'Official EEOC overview of employment practices covered by federal discrimination laws.' } },
  { slug: 'training-certification-expiration-queue', title: 'Run a Training Certification Expiration Queue', description: 'Track expiring certifications and completion evidence while qualified owners decide role eligibility and required training.', workflow: 'training certification expiration tracking', trigger: 'an approved roster identifies a certification, owner, authoritative expiry date, and review window', owner: 'the company learning, safety, compliance, or role owner', stop: 'the credential cannot be authenticated, requirements conflict, expiry affects work eligibility, or an exception is requested', proof: 'the qualified owner validates the credential status and authorizes the roster outcome', service: 'learning-administration', example: 'A certificate image shows one expiry date while the issuing portal shows another', source: { name: 'NIST Privacy Framework', url: 'https://www.nist.gov/privacy-framework', note: 'Official framework for accountable processing and privacy-risk management.' } },
  { slug: 'recruiting-agency-candidate-ownership-conflict', title: 'Route Recruiting Agency Candidate-Ownership Conflicts', description: 'Preserve submission evidence and pause duplicate-candidate disputes while recruiting and legal owners decide agency ownership.', workflow: 'recruiting agency candidate ownership conflict routing', trigger: 'the recruiting system detects the same candidate from more than one approved source', owner: 'the company recruiting, procurement, or legal owner', stop: 'contract terms, fees, representation, consent, or candidate treatment must be interpreted', proof: 'the authorized owner records the source decision and permitted next candidate action', service: 'candidate-sourcing', example: 'An agency submission and an employee referral carry timestamps on the same day', source: { name: 'EEOC Recordkeeping Requirements', url: 'https://www.eeoc.gov/employers/recordkeeping-requirements', note: 'Official EEOC overview of employment recordkeeping requirements.' } },
  { slug: 'offer-compensation-input-reconciliation', title: 'Reconcile Offer Compensation Inputs Before Drafting', description: 'Compare approved compensation inputs before an offer draft is prepared, without allowing coordinators to negotiate or set terms.', workflow: 'offer compensation input reconciliation', trigger: 'the hiring owner supplies an approved requisition, candidate identity, level, and compensation instruction', owner: 'the authorized hiring, compensation, HR, and finance owners', stop: 'amounts, currency, level, location, approvals, classification, or start date conflict', proof: 'the authorized owner approves one versioned offer-input packet before drafting or release', service: 'interview-coordination', example: 'The requisition approval names one salary while the hiring ticket contains a later unapproved amount', source: { name: 'EEOC Compensation Discrimination', url: 'https://www.eeoc.gov/compensation-discrimination', note: 'Official EEOC overview of federal compensation-discrimination protections.' } },
  { slug: 'hr-vendor-invoice-approval-support', title: 'Set Up HR Vendor Invoice Approval Support', description: 'Match HR vendor invoices to approved services and evidence while budget owners retain payment and dispute decisions.', workflow: 'HR vendor invoice approval support', trigger: 'an invoice arrives from an approved vendor with a purchase reference and service period', owner: 'the company HR, procurement, finance, or accounts-payable owner', stop: 'rates, scope, taxes, worker identity, service acceptance, duplicate billing, or contract terms are unclear', proof: 'the budget owner records approval or dispute and accounts payable confirms the resulting status', service: 'operations-support', example: 'A recruiting invoice names a placement but the approved fee schedule is not attached', source: { name: 'GAO Green Book', url: 'https://www.gao.gov/green-book', note: 'Official internal-control principles used to frame authorization and evidence checks.' } },
  { slug: 'employee-privacy-request-intake', title: 'Create an Employee Privacy Request Intake Lane', description: 'Authenticate, log, and route employee privacy requests without exposing records or letting support staff decide access rights.', workflow: 'employee privacy request intake', trigger: 'a request arrives through the approved privacy or HR channel and receives an authenticated case identity', owner: 'the company privacy, legal, security, or authorized HR owner', stop: 'identity is uncertain, scope or jurisdiction needs interpretation, records involve another person, or disclosure and deletion rights must be decided', proof: 'the qualified owner records the authorized response and secure delivery or other disposition', service: 'employee-records-administration', example: 'An employee asks for “everything HR has” from an email address not yet verified', source: { name: 'NIST Privacy Framework', url: 'https://www.nist.gov/privacy-framework', note: 'Official voluntary framework for identifying and managing privacy risk.' } },
  { slug: 'employment-record-legal-hold-tracking', title: 'Track Employment-Record Legal Holds Without Altering Evidence', description: 'Distribute approved hold instructions, preserve acknowledgments, and track custodians while legal owners control scope and release.', workflow: 'employment record legal hold tracking', trigger: 'authorized counsel or the company legal owner issues a written hold instruction with defined custodians and record scope', owner: 'authorized company counsel or the legal and records owner', stop: 'scope, custodian coverage, preservation method, conflicting retention, collection, or release is unclear', proof: 'the legal owner confirms custodian acknowledgment, preservation status, and any later written release', service: 'employee-records-administration', example: 'A scheduled disposal queue contains files that may fall within a newly issued hold', source: { name: 'EEOC Recordkeeping Requirements', url: 'https://www.eeoc.gov/employers/recordkeeping-requirements', note: 'Official EEOC overview explaining employment-record preservation duties in covered circumstances.' } }
];

export const september22BlogPosts = topics.map(({ slug, title, description }) => ({ slug: `september22-hr-${slug}`, title, excerpt: description, minutes: 12, published: date }));

export const buildBlogBatch = (batchDate: string, slugPrefix: string, batchTopics: BlogBatchTopic[]): Record<string, RichArticle> => Object.fromEntries(batchTopics.map((topic, index) => {
  const slug = `${slugPrefix}${topic.slug}`;
  return [slug, {
    slug, title: topic.title, description: topic.description, published: batchDate, updated: batchDate, minutes: 12,
    revision: `${batchDate}-${slug}`,
    directAnswer: [
      `Treat ${topic.workflow} as a controlled administrative lane. Open it only when ${topic.trigger}. Give the coordinator a written field list, a named company owner, a response target, and a stop rule.`,
      `A Philippines-based HR coordinator can preserve source records, check required fields, maintain deadlines, request missing administrative details, and prepare a handoff. The coordinator should stop when ${topic.stop}. Close the item only after ${topic.proof}.`
    ],
    takeaways: ['Start from an authenticated source event.', 'Keep working fields separate from the controlling record.', `Send decisions and exceptions to ${topic.owner}.`, 'Use named access and the minimum necessary data.', `Require ${topic.proof} before closure.`],
    taskRows: [
      { lane: 'Open', philippinesTeam: 'Preserve the source, received time, case identity, due date, and assigned owner.', owner: 'Confirm that the case belongs in this workflow and define the permitted task.', check: 'The original source remains retrievable' },
      { lane: 'Prepare', philippinesTeam: 'Check the approved field list and identify missing or conflicting information without resolving it.', owner: 'Answer exceptions and approve any consequential instruction.', check: 'Submitted, source, and approved values stay distinct' },
      { lane: 'Route', philippinesTeam: `Pause when ${topic.stop}. Send one bounded question through the restricted channel.`, owner: 'Make the required decision and return a dated instruction.', check: 'The decision has a person, time, and source' },
      { lane: 'Close', philippinesTeam: 'Apply only the approved administrative step and attach destination evidence.', owner: 'Review the result and authorize closure.', check: topic.proof }
    ],
    pilotStats: [
      { value: '1', label: 'Source record', note: 'Keep the controlling evidence intact' },
      { value: '5', label: 'Test paths', note: 'Routine, missing, conflict, sensitive, failed destination' },
      { value: String(10 + index), label: 'Pilot cases', note: 'Review every early case' },
      { value: '2', label: 'Owner checks', note: 'Decision and closeout' }
    ],
    sections: [
      { heading: `Define the opening event for ${topic.workflow}`, paragraphs: [`A reliable queue begins with an event another person can verify. Open this workflow only when ${topic.trigger}. Record who supplied the event, when it arrived, the protected source location, the accountable company owner, and the next checkpoint. Do not begin from an unverified forwarded message or a coordinator’s assumption.`, `Write a one-page boundary before the first live case. List permitted fields, approved systems, exact administrative actions, and the decisions reserved for ${topic.owner}. Use this realistic exception in training: ${topic.example}. The playbook should say who decides, how the question is sent, and what happens to the deadline while the item is paused.`] },
      { heading: 'Keep the source separate from the working queue', paragraphs: [`A shared tracker makes ownership and timing visible, but it should not become a second personnel, payroll, benefits, recruiting, or legal file. Keep the original request and sensitive evidence in the approved source. Put only the case ID, status, owner, due time, next action, and minimum operational detail in the queue. Link to restricted material instead of copying it into comments.`, `When new information arrives, add a dated event rather than replacing the earlier value. A reviewer should be able to distinguish what was submitted, what the authoritative source showed, what the owner approved, and what reached the destination. That sequence matters when a vendor, employee, manager, auditor, or adviser asks why an action occurred.`] },
      { heading: 'Separate completeness checks from decisions', paragraphs: [`The coordinator may compare the packet with a written checklist: required field present, identifier matched, date recorded, attachment readable, owner assigned, and destination available. Those checks describe the packet; they do not establish legal sufficiency, eligibility, employee rights, contract meaning, tax treatment, or the correct business outcome.`, `The stop rule is central: pause when ${topic.stop}. The handoff should quote or link the relevant source, name the unresolved point, identify who can decide it, and state the next deadline. It should not invent an answer to keep a service target green. A clean queue with hidden exceptions is less useful than an honest queue with visible owner work.`] },
      { heading: 'Use narrow access and controlled communication', paragraphs: [`Grant a named account only the permissions required to view the assigned queue, retrieve its approved source, and perform the documented step. Review search, bulk export, download, forwarding, printing, shared links, delegated mailbox access, and deletion separately. Status-update permission does not automatically require access to every attachment.`, `Prepare templates for receipt, missing administrative fields, owner escalation, deadline reminder, and confirmed closeout. A template is not permission to answer a new policy, legal, pay, benefit, medical, privacy, safety, or employment question. When a response could change a person’s position or the company’s obligation, obtain owner approval before sending.`] },
      { heading: 'Test the exception paths before scaling', paragraphs: [`Run at least five redacted scenarios: a complete routine case, a missing field, two sources that disagree, a message containing sensitive information, and a destination that rejects the update. Include the example for this lane: ${topic.example}. Check whether the coordinator stops at the right point and whether the owner receives a question that can actually be answered.`, `Review every early case rather than sampling immediately. Classify defects by source, copied data, timing, unapproved communication, owner ambiguity, premature closure, and missing destination proof. Correct the checklist, access design, or owner coverage that produced the defect. Do not solve a process gap by asking the coordinator to exercise authority the role was never meant to hold.`] },
      { heading: 'Measure waiting, decisions, and closure separately', paragraphs: [`A useful dashboard separates open volume from completed work. Show received time, next deadline, current owner, waiting reason, owner-response time, destination rejection, reopened cases, and age at closure. Do not count a forwarded email as a completed case. Forwarding shows activity; it does not prove the authorized outcome.`, `For ${topic.workflow}, closure is specific: ${topic.proof}. Leave the task open if that evidence is absent. If the owner chooses another disposition, record the dated instruction instead of forcing the case into a completed label. Weekly review should focus on repeated waiting reasons and unclear ownership, not pressure to close unresolved work.`] },
      { heading: 'Plan handback, retention, and access removal', paragraphs: [`The employer should set retention and disposal rules for source material, working fields, approvals, exports, and closeout evidence. The coordinator can apply an approved schedule but should not decide how long regulated or sensitive records remain. Holds, complaints, audits, disputes, and active cases go to the qualified owner before anything is changed or removed.`, `When an assignment changes or ends, transfer every open case with its source link, status, owner, deadline, unresolved question, and last verified action. Remove the named account, mailbox rights, shared links, exports, and local downloads according to the company checklist. Require the company owner to confirm both access removal and ownership of the remaining queue.`] },
      { heading: 'Questions to ask an HR outsourcing provider', paragraphs: [`Ask the provider to demonstrate ${topic.workflow} with one ordinary redacted example and one exception. Have the proposed coordinator show the opening event, minimum queue fields, access boundary, stop rule, owner handoff, destination check, and closeout proof. A concrete demonstration reveals more than a general promise about best practices.`, `Confirm who reviews the first cases, how quickly unresolved items reach ${topic.owner}, what happens when that owner does not respond, and how corrections remain visible. Ask how accounts are provisioned and removed, how restricted details stay out of shared notes, and how open work is returned. Use those answers to define a small pilot before increasing volume.`] }
    ],
    scripts: [
      { label: 'Owner escalation', text: `I paused this ${topic.workflow} item because ${topic.stop}. The source and conflicting or missing fields remain unchanged. Please provide the controlling instruction and effective date.` },
      { label: 'Closeout check', text: `Before closure, please confirm that ${topic.proof}. I will keep the case pending until that evidence is attached or you approve another disposition.` }
    ],
    workflow: [
      { step: '01', title: 'Receive', text: 'Preserve the source, received time, case ID, owner, and deadline.' },
      { step: '02', title: 'Check', text: 'Compare the approved field list without deciding conflicts.' },
      { step: '03', title: 'Escalate', text: 'Send one bounded question to the authorized company owner.' },
      { step: '04', title: 'Apply', text: 'Perform only the dated administrative instruction.' },
      { step: '05', title: 'Verify', text: 'Confirm the destination, attach evidence, and complete owner review.' }
    ],
    faqs: [
      { question: `Can an outsourced HR coordinator own ${topic.workflow}?`, answer: 'The coordinator can own the documented administrative queue, completeness checks, reminders, and evidence collection. The company must retain legal, policy, employment, pay, benefits, safety, privacy, contract, and exception decisions.' },
      { question: 'What should be kept in the shared tracker?', answer: 'Use a case ID, status, assigned owner, deadline, waiting reason, next action, and source link. Keep sensitive documents and narratives in the approved restricted system.' },
      { question: 'What happens when information conflicts?', answer: `Preserve both values and their sources, then route the decision to ${topic.owner}. Do not overwrite one value to make the queue look complete.` },
      { question: 'What proves the task is complete?', answer: `Require this result: ${topic.proof}. A sent email, reminder, or checked box does not by itself prove the authoritative destination changed.` },
      { question: 'How should the first month be reviewed?', answer: 'Review every early case, classify defects, inspect access and messages, and revise the written boundary before increasing volume or reducing review.' }
    ],
    related: [
      { title: 'Related HR service', href: `/services/${topic.service}`, note: 'Review the matching administrative support lane.' },
      { title: 'HR reporting and QA', href: '/services/reporting-and-qa', note: 'Design owner checks and destination evidence.' },
      { title: 'Plan your HR support workflow', href: '/contact-us', note: 'Bring a redacted case to a role-scoping discussion.' }
    ],
    sources: topic.source.url === 'https://www.nist.gov/privacy-framework' ? [topic.source] : [topic.source, { name: 'NIST Privacy Framework', url: 'https://www.nist.gov/privacy-framework', note: 'Official voluntary framework for managing privacy risk and accountable data processing.' }],
    banners: [
      { eyebrow: 'Map the case', title: `Define the ${topic.workflow} boundary.`, text: 'Name the source, permitted checks, decision owner, stop rule, and closeout proof.', href: `/services/${topic.service}`, linkLabel: 'Review the service scope' },
      { eyebrow: 'Test the handoff', title: 'Practice the exception before increasing volume.', text: 'Use redacted routine, missing-field, conflict, sensitive, and failed-update cases.', href: '/services/reporting-and-qa', linkLabel: 'See reporting and QA' },
      { eyebrow: 'Scope the role', title: 'Keep consequential decisions with the employer.', text: 'Turn a real workflow into a narrow support brief with named owner checks.', href: '/contact-us', linkLabel: 'Discuss HR support' }
    ]
  } satisfies RichArticle];
}));

export const september22Articles = buildBlogBatch(date, 'september22-hr-', topics);
