import type { RichArticle } from './article-data';
const date='2026-09-10';
const topics=[
['candidate-reschedule-consent-check','Check Candidate Consent Before Rescheduling Interviews','confirm a candidate-approved time before replacing the calendar event','interview-coordination'],
['onboarding-equipment-readiness-log','Build an Onboarding Equipment Readiness Log','track device ownership, delivery evidence, setup status, and the access owner','onboarding-coordination'],
['benefits-election-confirmation-reconcile','Reconcile Benefits Election Confirmations','compare submitted elections with carrier confirmation without deciding eligibility','benefits-administration-support'],
['payroll-variable-pay-source-register','Create a Source Register for Variable Pay Inputs','connect each payroll input to its period, approver, source, and cutoff status','payroll-preparation-support'],
['employee-name-change-document-route','Route Employee Name-Change Documents Safely','separate document intake, identity review, approval, and downstream updates','employee-records-administration'],
['hr-inbox-owner-absence-cover','Set Up HR Inbox Cover for an Absent Owner','keep routine requests moving while sensitive work remains restricted','hr-help-desk-support'],
['candidate-withdrawal-record-closeout','Close Candidate Withdrawal Records Consistently','preserve the candidate message, stop scheduled activity, and record an approved disposition','interview-coordination'],
['performance-review-form-version-lock','Lock the Form Version for a Performance Review Cycle','prevent managers from completing different review forms under one cycle name','performance-review-administration'],
['learning-completion-evidence-check','Check Evidence Before Closing Learning Assignments','distinguish attendance, completion, assessment, and approved exception evidence','learning-administration'],
['offboarding-forwarding-rule-expiry','Put Expiry Dates on Offboarding Forwarding Rules','record the approved recipient, business purpose, review date, and removal proof','offboarding-coordination'],
['hr-report-source-refresh-check','Verify Source Refreshes Before Publishing an HR Report','confirm that every report input covers the intended period before release','reporting-and-qa'],
['employee-emergency-contact-update-proof','Confirm Employee Emergency Contact Updates at the Destination','retain the request while proving the approved value reached the authoritative record','employee-records-administration']] as const;
export const september10BlogPosts=topics.map(([s,t,f])=>({slug:`september10-hr-${s}`,title:t,excerpt:`A practical HR operations guide to ${f}.`,minutes:9,published:date}));
export const september10Articles:Record<string,RichArticle>=Object.fromEntries(topics.map(([s,title,focus,service],i)=>{const slug=`september10-hr-${s}`,proof=`dated destination evidence for ${focus}`;return [slug,{
slug,title,description:`A controlled Philippines-based HR support workflow to ${focus}, with owner decisions and closeout evidence.`,published:date,updated:date,minutes:9,revision:`${date}-${slug}`,
directAnswer:[`Name the source record, the person allowed to approve the result, and the evidence that ends the task. The working objective is to ${focus}.`,'A Philippines-based coordinator can prepare, compare, remind, route, and document. The company keeps employment, pay, benefits, privacy, accommodation, safety, and policy decisions with qualified owners.'],
takeaways:['Keep the original request intact.','Record submitted and approved values separately.','Limit the queue to fields needed for this job.','Pause when a source conflicts or judgment is required.',`Close only with ${proof}.`],
taskRows:[{lane:'Receive',philippinesTeam:'Capture the source, received time, case ID, and requested action.',owner:'Define the authoritative source and permitted task.',check:'The unedited source can be retrieved'},{lane:'Check',philippinesTeam:'Compare required fields and dates without resolving discrepancies.',owner:'Decide which value controls when records disagree.',check:'Differences remain visible'},{lane:'Route',philippinesTeam:'Send one concise exception note through the approved channel.',owner:'Return an approval, correction, or stop instruction.',check:'Decision owner and time are recorded'},{lane:'Close',philippinesTeam:'Complete the approved admin step and attach destination proof.',owner:'Review exceptions and authorize closure.',check:proof}],
pilotStats:[{value:'1',label:'Source of truth',note:focus},{value:'5',label:'Test paths',note:'Routine, missing, conflict, sensitive, failed update'},{value:String(i+6),label:'Pilot cases',note:'Review each early case'},{value:'2',label:'Owner checks',note:'Approval and closure'}],
sections:[{heading:'Write the boundary in plain language',paragraphs:[`Describe the event that opens the queue and the result that closes it. For this lane, the team needs to ${focus}.`,'List the decisions the coordinator cannot make. Put a named company owner beside each stop point.']},{heading:'Preserve what arrived',paragraphs:['Keep the original message or system event, its timestamp, and a stable case identifier. A copied tracker value is a working aid, not a replacement for the source.','If a correction arrives, add it as a new event. Do not silently edit the history a reviewer will need later.']},{heading:'Give the coordinator a narrow view',paragraphs:['A shared queue normally needs a case ID, status, owner, due time, and next action. Sensitive narratives and documents belong in the restricted system.',`Grant only the permissions needed to ${focus}. Review download, export, and sharing rights separately.`]},{heading:'Practice the awkward cases',paragraphs:['Test an ordinary case, a missing field, a conflict, a sensitive message, and a failed destination update. The procedure should route every case without guesswork.','Ask a second reviewer to reconstruct the result using only retained records. Rewrite any field that forces reliance on verbal context.']},{heading:'Use proof from the destination',paragraphs:[`Treat ${proof} as closing evidence. A sent email or completed checklist shows activity, not the state of the destination.`,'Leave unresolved work open with a named next action and review time. Report aging separately from completion.']},{heading:'Questions for a provider review',paragraphs:[`Ask the provider to demonstrate, with a redacted example, how its team would ${focus}.`,'Confirm who reviews early work, how exceptions reach the company, and how accounts and records are returned when the assignment ends.']}],
scripts:[{label:'Exception note',text:`I paused this case because evidence is missing, conflicting, sensitive, or requires an owner decision. Please confirm the controlling instruction for ${focus}.`},{label:'Closeout note',text:`Closed after review of ${proof}.`}],
workflow:[{step:'01',title:'Receive',text:'Preserve the source, time, and case identity.'},{step:'02',title:'Compare',text:'Check named facts without choosing between conflicts.'},{step:'03',title:'Escalate',text:'Route the exception to its assigned owner.'},{step:'04',title:'Apply',text:'Perform only the approved administrative action.'},{step:'05',title:'Confirm',text:'Attach destination evidence and complete the review.'}],
faqs:[{question:'Can an outsourced coordinator own this task?',answer:'The coordinator can own documented administrative steps. The company retains consequential decisions and approvals.'},{question:'What belongs in the shared queue?',answer:'Use case identity, status, owner, timing, and next action. Keep sensitive details in the restricted source system.'},{question:'What if two sources disagree?',answer:'Preserve both values and route the conflict to the named company owner.'},{question:'What proves completion?',answer:`Require ${proof}. Activity by itself is not proof of the final state.`}],
related:[{title:'Related HR service',href:`/services/${service}`,note:'Review the matching administrative lane.'},{title:'HR reporting and QA',href:'/services/reporting-and-qa',note:'Design the evidence check and review sample.'}],sources:[{name:'NIST Privacy Framework',url:'https://www.nist.gov/privacy-framework',note:'Official framework for managing privacy risk.'},{name:'GAO Green Book',url:'https://www.gao.gov/green-book',note:'Official internal-control principles.'}],banners:[{eyebrow:'Map the handoff',title:'Set the boundary before assigning the queue.',text:'Name the source, owner, stop point, and destination evidence.',href:`/services/${service}`,linkLabel:'Review the service scope'}]} as RichArticle]}));
