import type { RichArticle } from './article-data';
const date='2026-09-07',heroImage='/blog-heroes/august31-hr-operations-field-guide.svg';
const topics=[
['candidate-time-zone-confirmation','Confirm candidate time zones before interview day','prevent silent time-zone assumptions from becoming missed interviews','interview-coordination'],
['onboarding-equipment-delivery-exceptions','Route onboarding equipment delivery exceptions','keep delayed equipment visible without making unsupported promises','onboarding-coordination'],
['benefits-enrollment-receipt-log','Build a benefits enrollment receipt log','track secure receipt while plan owners decide eligibility and coverage','benefits-administration-support'],
['payroll-bank-change-callback-tracker','Track payroll bank-change callback verification','separate intake, identity checks, approval, and payroll entry','payroll-preparation-support'],
['manager-approval-aging-board','Design a manager approval aging board','surface waiting decisions without exposing sensitive case narratives','reporting-and-qa'],
['candidate-withdrawal-record-handoff','Record a candidate withdrawal cleanly','preserve the source message and stop scheduled outreach','recruiting-coordination'],
['learning-completion-evidence-check','Check learning completion evidence before escalation','reconcile certificates, system status, and approved exemptions','learning-administration'],
['employee-name-change-system-map','Map an employee name change across HR systems','coordinate approved values across downstream destinations','employee-records-administration'],
['shared-mailbox-sensitive-case-routing','Route sensitive cases out of a shared HR mailbox','move complaints, medical details, and disputes to restricted owners','hr-help-desk-support'],
['performance-review-form-version-control','Control performance-review form versions','prevent managers from completing a retired review form','performance-review-administration'],
['offboarding-calendar-cleanup-check','Check calendars during an offboarding handback','find events that need cancellation or a new owner','offboarding-coordination'],
['weekly-record-correction-sample','Run a weekly sample of HR record corrections','review source, approval, changed values, and destination evidence','reporting-and-qa']] as const;
export const september7BlogPosts=topics.map(([s,t,d])=>({slug:`september7-hr-${s}`,title:t,excerpt:`A practical HR operations guide to ${d}.`,minutes:9,published:date}));
export const september7Articles:Record<string,RichArticle>=Object.fromEntries(topics.map(([s,title,focus,service],i)=>{const slug=`september7-hr-${s}`,stop='the source is incomplete, conflicting, or requires a policy decision',proof=`dated owner approval and destination confirmation for ${focus}`;return [slug,{
slug,title,description:`A bounded workflow to ${focus}, with clear ownership, access limits, and completion evidence.`,published:date,updated:date,minutes:9,revision:`${date}-${slug}`,heroImage,
directAnswer:[`Treat this work as a documented administrative lane: ${focus}. Name the controlling source, company owner, stop condition, and evidence before the first live case.`,`A coordinator can collect, compare, remind, route, and record. The company retains employment, pay, benefits, privacy, and exception decisions.`],
takeaways:['Name one controlling source.','Keep submitted and approved values separate.','Use the minimum necessary access.',`Pause when ${stop}.`,`Close only with ${proof}.`],
taskRows:[{lane:'Receive',philippinesTeam:'Preserve the request and record its source.',owner:'Set scope, authority, timing, and approved inputs.',check:'Source, owner, and due time are visible'},{lane:'Compare',philippinesTeam:'Check required fields without replacing conflicting evidence.',owner:'Resolve differences and approve consequential changes.',check:'Original and proposed values remain distinct'},{lane:'Escalate',philippinesTeam:'Pause and send one precise exception handoff.',owner:'Make the decision and return an actionable instruction.',check:'The exception has an owner and review time'},{lane:'Close',philippinesTeam:'Apply the approved step and attach confirmation.',owner:'Review exceptions and authorize closure.',check:proof}],
pilotStats:[{value:'1',label:'Queue',note:focus},{value:'4',label:'Test cases',note:'Routine, missing, conflict, exception'},{value:String(i+6),label:'Pilot records',note:'Review every early item'},{value:'2',label:'Owner checks',note:'Process and exception'}],
sections:[{heading:`Define the source for ${focus}`,paragraphs:[`Write down where the request arrives, which record controls, who approves action, and what proves completion. This makes ${focus} transferable without broad access.`,`Use event labels such as received, checked, waiting, approved, applied, and confirmed. Each should point to a timestamp or artifact.`]},{heading:'Keep disagreement visible',paragraphs:[`Preserve both values and timestamps when records conflict. Do not select the tidier version when ${stop}.`,'Record the owner instruction beside the action so another reviewer can reconstruct the change.']},{heading:'Limit access and narrative',paragraphs:['Give coordinators only the fields and systems required for the written lane. Shared trackers need status and ownership, not private employee narratives.','Keep underlying documents in the approved restricted system and use a case identifier for coordination.']},{heading:'Test awkward cases',paragraphs:[`Run a routine item, missing input, source conflict, and real exception for ${focus}. Verify that each reaches the right owner.`,`Review early records for source accuracy, access, wording, and destination proof. Repair the specific checklist step that failed.`]},{heading:'Close on evidence',paragraphs:[`The finish line is ${proof}. Until it exists, keep a next action and review date.`,'A checked box is weak when a reviewer cannot tell who acted, what changed, or where the result landed.']},{heading:'Questions for a provider',paragraphs:[`Ask for a redacted demonstration of ${focus}, including a routine case and exception.`,'Confirm who reviews initial work and how unfinished cases, records, and credentials return to the client.']}],
scripts:[{label:'Exception handoff',text:`I preserved the source and paused because ${stop}. Please confirm the controlling value and next action.`},{label:'Closure note',text:`This remains open until the record contains ${proof}.`}],workflow:[{step:'01',title:'Open',text:'Capture source, owner, timing, and access boundary.'},{step:'02',title:'Check',text:'Compare fields without hiding conflicts.'},{step:'03',title:'Route',text:'Send exceptions to the named owner.'},{step:'04',title:'Apply',text:'Perform only the approved action.'},{step:'05',title:'Confirm',text:'Save destination evidence and review defects.'}],
faqs:[{question:'Can outsourced support own this workflow?',answer:'It can own documented administration; company owners retain consequential decisions.'},{question:'How much access is appropriate?',answer:'Use named accounts and the smallest permission needed for the task.'},{question:'What happens when records disagree?',answer:'Preserve both values and ask the accountable owner which source controls.'},{question:'What closes the work?',answer:`Require ${proof}; activity is not completion.`}],related:[{title:'Related HR service',href:`/services/${service}`,note:'Review the matching administrative lane.'},{title:'HR reporting and QA',href:'/services/reporting-and-qa',note:'Plan source checks and early review.'}],sources:[{name:'NIST Privacy Framework',url:'https://www.nist.gov/privacy-framework',note:'Official framework used for privacy-risk and data-processing controls.'}],banners:[{eyebrow:'Map the lane',title:'Define the work before assigning it.',text:'Name the source, owner, stop point, and proof.',href:`/services/${service}`,linkLabel:'Review the service scope'}]} as RichArticle]}));
