import type { RichArticle } from './article-data';

type Topic={slug:string;title:string;description:string;focus:string;record:string;exception:string;outcome:string};
const date='2026-09-01';
const source={name:'NIST Privacy Framework',url:'https://www.nist.gov/privacy-framework',note:'Official framework used for privacy-risk, data-processing, and accountability controls.'};
const topics:Topic[]=[
 ['candidate-consent-renewal','Candidate consent renewal: a controlled recruiting follow-up','Build a candidate consent renewal queue that preserves the original permission, new purpose, response, and recruiter decision.','candidate consent renewal','candidate identifier, original consent, proposed use, request date, response, and recruiter owner','the candidate withdraws permission, changes the allowed use, or asks a privacy question','a current, evidenced permission record'],
 ['new-manager-onboarding','New manager onboarding administration: prepare the operating handoff','Coordinate a new manager’s HR calendars, access requests, team records, and training without assigning policy authority by accident.','new manager onboarding administration','manager start date, team scope, approved access, required training, meeting owner, and completion proof','requested access exceeds the approved role or the manager asks for confidential employee history','a manager-ready checklist with approved access'],
 ['beneficiary-change-intake','Beneficiary change intake without eligibility advice','Route beneficiary change forms and missing fields while plan owners retain eligibility, deadline, and coverage decisions.','beneficiary change intake','request receipt, plan, form version, missing fields, secure destination, and benefits owner','the employee asks whether a person qualifies or whether coverage applies','a complete form delivered to the qualified owner'],
 ['work-location-change-routing','Work location change routing across HR, payroll, and security','Coordinate a proposed work location change without treating a manager email or address edit as final approval.','work location change routing','requested location, effective date, manager response, HR owner, payroll review, and access impact','the location creates an unresolved tax, employment, immigration, safety, or security question','an owner-approved effective location across systems'],
 ['employee-equipment-accommodation-logistics','Equipment and accommodation logistics: separate delivery from judgment','Track approved equipment and delivery checkpoints while qualified owners decide accommodations, medical issues, and exceptions.','employee equipment and accommodation logistics','approved item, delivery address, vendor, due date, receipt, and restricted decision owner','the request reveals medical information or requires an accommodation decision','confirmed delivery without copying sensitive rationale'],
 ['internal-transfer-administration','Internal transfer administration with source-by-source reconciliation','Coordinate an internal transfer across position, manager, payroll, access, and onboarding records while preserving approval ownership.','internal transfer administration','approved role, manager, effective date, pay instruction source, access changes, and employee notice','two systems show different effective dates, roles, or managers','a reconciled transfer record with owner proof'],
 ['background-check-status-handoff','Background check status handoffs without screening judgment','Maintain status and candidate communications while authorized owners and providers handle results, disputes, and hiring decisions.','background check status handoff','candidate authorization, provider reference, status event, communication template, owner, and next checkpoint','a report contains a result, dispute, identity mismatch, or adverse-action question','a timely status trail with sensitive review routed correctly'],
 ['leave-return-calendar-coordination','Leave return calendar coordination with privacy boundaries','Coordinate return dates, meetings, reminders, and system tasks without exposing medical details or deciding readiness.','leave return calendar coordination','owner-approved date, calendar actions, notification list, system tasks, and next review','the date is conditional, disputed, or connected to restrictions or accommodation','an approved calendar plan with minimal disclosure'],
 ['policy-translation-version-control','Policy translation version control for distributed HR support','Track approved translations, reviewers, versions, and destinations without allowing administrative edits to change policy meaning.','policy translation version control','source policy, language, translator, qualified reviewer, version, approval, and destinations','a phrase changes a right, obligation, exception, deadline, or defined term','one approved translation mapped to its source version'],
 ['employee-anniversary-data-quality','Employee anniversary data quality before recognition messages','Check service dates, preferred names, exclusions, and message approvals before anniversary communications are scheduled.','employee anniversary data quality','employee identifier, controlling service date, display preference, exclusion, template, and approval','records disagree or an employee should not appear in a public recognition','an accurate, consent-aware recognition list'],
 ['recruiting-agency-submission-reconciliation','Recruiting agency submission reconciliation without ownership disputes','Reconcile agency submissions against candidate consent, requisitions, timestamps, and contract-owner decisions.','recruiting agency submission reconciliation','candidate authorization, agency, requisition, submission event, duplicate check, and contract owner','multiple sources claim the candidate or consent and requisition records do not align','a preserved submission trail routed for an owner decision'],
 ['hr-mail-returned-delivery-exceptions','Returned HR mail: a secure delivery-exception workflow','Handle returned employee mail through address verification, secure storage, reissue approval, and evidence of final disposition.','returned HR mail handling','mail type, return event, restricted location, approved contact method, address owner, and disposition','the item is time-sensitive, sensitive, opened, damaged, or tied to a disputed address','a secure and evidenced delivery resolution']
].map(([slug,title,description,focus,record,exception,outcome])=>({slug:`september1-philippines-hr-${slug}`,title,description,focus,record,exception,outcome}));

export const september1BlogPosts=topics.map(t=>({slug:t.slug,title:t.title,excerpt:t.description,minutes:10,published:date}));
export const september1Articles:Record<string,RichArticle>=Object.fromEntries(topics.map((t,index)=>[t.slug,{
 slug:t.slug,title:t.title,description:t.description,published:date,updated:date,minutes:10,revision:`${date}-${t.slug}`,heroImage:'/blog-heroes/august31-hr-operations-field-guide.svg',
 directAnswer:[`A Philippines-based HR coordinator can administer ${t.focus} when the employer specifies the source records, permitted preparation, decision owner, and stop rule. The coordinator can check, document, remind, and route; the employer retains employment, legal, medical, pay, privacy, and policy judgment.`,`The target is ${t.outcome}. Keep ${t.record}, and pause when ${t.exception}.`],
 takeaways:[`Define the controlling record for ${t.focus}.`,`Collect only the information needed to reach ${t.outcome}.`,'Keep administrative preparation separate from approval.','Preserve conflicting values instead of silently selecting one.',`Escalate when ${t.exception}.`],
 taskRows:[{lane:'Intake',philippinesTeam:`Open the ${t.focus} record and check required fields.`,owner:'Define permitted sources, access, priority, and authority.',check:'Requester, source, purpose, and received time are visible'},{lane:'Source check',philippinesTeam:`Compare ${t.record} and retain any mismatch.`,owner:'Choose the controlling source and approve corrections.',check:'Original and proposed values remain distinguishable'},{lane:'Exception',philippinesTeam:`Pause when ${t.exception} and send one precise question.`,owner:'Decide the exception and approve any sensitive communication.',check:'Handoff names the issue, recipient, boundary, and checkpoint'},{lane:'Closeout',philippinesTeam:`Record the approved action and evidence for ${t.outcome}.`,owner:'Confirm completion and retention treatment.',check:'Closure has an owner response or destination evidence'}],
 pilotStats:[{value:'1',label:'Intake lane',note:`Pilot only ${t.focus}`},{value:'2',label:'Named owners',note:'Process and exception owners'},{value:String(5+index),label:'Sample records',note:'Include ordinary and exception cases'},{value:'10',label:'Review days',note:'Inspect every early closeout'}],
 sections:[
  {heading:`Define the evidence for ${t.focus}`,paragraphs:[`Begin with a record another owner can reconstruct: ${t.record}. Keep sensitive material in its approved system and expose only the status needed for coordination.`,`Write statuses as events—received, checked, waiting for owner, corrected, delivered, or closed. The desired result is ${t.outcome}, not a convenient label.`]},
  {heading:'Put authority next to every action',paragraphs:[`The coordinator may prepare, compare, remind, and route. The coordinator must stop when ${t.exception}. That boundary belongs in the playbook and in the queue view.`,`The employer’s named owner retains policy interpretation, employment decisions, sensitive conversations, access approval, and exceptions. A fast handoff is useful only when it reaches someone who can act.`]},
  {heading:'Reconcile without erasing the disagreement',paragraphs:[`Keep the incoming request, controlling source, proposed action, and final evidence separate. If dates or values disagree, preserve both and ask the owner which controls.`,`For ${t.focus}, record the source location and effective date. This turns uncertainty into a bounded question and prevents an administrative update from manufacturing authority.`]},
  {heading:'Test the uncomfortable case before volume',paragraphs:[`Test a complete record, missing field, duplicate, conflicting source, and the case where ${t.exception}. Verify the exact permitted preparation and stop point.`,`Review whether private details stayed in the correct system, the handoff reached the qualified owner, and ${t.outcome} can be proven without reading unnecessary narrative.`]},
  {heading:'Close with evidence, not optimism',paragraphs:[`A closeout should name the checked source, approved action, destination, owner response, and completion time. Without an owner response, leave the item pending with a next checkpoint.`,`Classify defects such as wrong destination, missing proof, excess access, duplicate work, late escalation, or premature closure. Use those counts to improve the workflow rather than assign unsupported blame.`]},
  {heading:'Questions to ask an HR outsourcing provider',paragraphs:[`Ask the provider to demonstrate ${t.focus} with one redacted ordinary record and one exception. Have the team show the fields it needs, the judgment it will not make, and the proof it returns.`,`Ask how accounts are limited and removed, drafts are handled, unresolved work is returned, and playbooks change after an error. Specific evidence is more useful than a broad assurance.`]}
 ],
 scripts:[{label:'Owner handoff',text:`I checked the approved records for ${t.focus}. The unresolved point requires your decision. Please confirm the controlling source and approved next action.`},{label:'Stop rule',text:`I paused this item because ${t.exception}. I preserved the source values, routed it to the named owner, and recorded the next checkpoint.`}],
 workflow:[{step:'01',title:'Open the record',text:'Capture source, purpose, owner, due time, and privacy level.'},{step:'02',title:'Check the evidence',text:'Compare required fields without overwriting differences.'},{step:'03',title:'Route the exception',text:'Send one bounded question to the qualified owner.'},{step:'04',title:'Apply approval',text:'Carry out only the action the owner authorized.'},{step:'05',title:'Close and sample',text:'Save proof and review the lane for defects.'}],
 faqs:[{question:`Can outsourced staff own ${t.focus}?`,answer:'They can own defined administrative steps and queue hygiene. The employer retains decisions, exceptions, and sensitive communication.'},{question:'What access should the coordinator receive?',answer:'Use named accounts and the smallest useful view of approved sources and destinations. Avoid broad exports by default.'},{question:'What if records conflict?',answer:'Preserve both sources and route the controlling-source decision to the accountable owner.'},{question:'How should early quality be reviewed?',answer:'Review every pilot item for source accuracy, privacy handling, routing, and completion evidence.'},{question:'Is this legal or employment advice?',answer:'No. It is an administrative control pattern; qualified owners must decide legal, policy, medical, pay, and employment questions.'}],
 related:[{title:'HR operations support',href:'/services/operations-support',note:'Review the related administrative lane.'},{title:'HR reporting and QA',href:'/services/reporting-and-qa',note:'Plan source checks and owner review.'},{title:'Plan Philippines-based HR support',href:'/contact-us',note:'Bring a redacted workflow to a staffing discussion.'}],sources:[source],
 banners:[{eyebrow:'Map the record',title:`Define ${t.focus} before granting access.`,text:'Name the source, owner, stop point, and proof.',href:'/services/operations-support',linkLabel:'Review HR operations support'},{eyebrow:'Test the lane',title:'Sample ordinary and exception evidence.',text:'Check sources, access, routing, and closeout.',href:'/services/reporting-and-qa',linkLabel:'See reporting and QA'},{eyebrow:'Scope the role',title:'Keep substantive judgment with the employer.',text:'Use a redacted example to define the support boundary.',href:'/contact-us',linkLabel:'Discuss HR support'}]
} as RichArticle]));
