import type { RichArticle } from './article-data';
const date='2026-09-08';
const topics=[
['candidate-interview-panel-change-log','Keep an Interview Panel Change Log','align interviewer substitutions, calendar updates, candidate notices, and decision ownership','interview-coordination'],
['new-hire-missing-document-queue','Run a New-Hire Missing-Document Queue','separate routine reminders from eligibility, accommodation, and policy decisions','onboarding-coordination'],
['benefits-dependent-document-intake','Control Benefits Dependent-Document Intake','receive dependent records without copying sensitive files into a general tracker','benefits-administration-support'],
['payroll-retro-change-preparation','Prepare Retroactive Payroll Changes for Review','show the source period, approved correction, calculation input, and reviewer before payroll entry','payroll-preparation-support'],
['employee-record-retention-hold-flag','Add a Retention-Hold Flag to Employee Records','prevent routine disposition while a qualified owner reviews a hold or active matter','employee-records-administration'],
['hr-inbox-duplicate-request-linking','Link Duplicate Requests in the HR Inbox','consolidate repeated messages without losing the original sender, timestamp, or attachment trail','hr-help-desk-support'],
['candidate-accommodation-request-routing','Route Candidate Accommodation Requests Safely','move accommodation messages promptly to a restricted, qualified decision owner','interview-coordination'],
['manager-review-deadline-reset','Document Performance-Review Deadline Resets','distinguish an approved schedule change from an overdue or silently edited review','performance-review-administration'],
['learning-roster-version-check','Version-Control Mandatory Learning Rosters','tie every assignment and completion check to the approved audience snapshot','learning-administration'],
['offboarding-shared-drive-ownership','Transfer Shared-Drive Ownership During Offboarding','identify business files, assign a destination owner, and confirm access after transfer','offboarding-coordination'],
['hr-vendor-file-delivery-receipt','Verify HR Vendor File-Delivery Receipts','prove an approved recipient received the intended file through the approved channel','reporting-and-qa'],
['employee-address-change-effective-date','Check Effective Dates on Employee Address Changes','keep receipt date, approved effective date, and downstream confirmations distinct','employee-records-administration']] as const;
export const september8BlogPosts=topics.map(([s,t,f])=>({slug:`september8-hr-${s}`,title:t,excerpt:`A practical HR operations guide to ${f}.`,minutes:9,published:date}));
export const september8Articles:Record<string,RichArticle>=Object.fromEntries(topics.map(([s,title,focus,service],i)=>{const slug=`september8-hr-${s}`,proof=`dated owner approval and destination evidence for ${focus}`;return [slug,{
slug,title,description:`A bounded HR support workflow to ${focus}, with narrow access, stop rules, and reviewable evidence.`,published:date,updated:date,minutes:9,revision:`${date}-${slug}`,
directAnswer:[`Name the event that opens this lane, the controlling system, the company owner, and the proof needed to close it. The operational goal is to ${focus}.`,`A Philippines-based coordinator can collect, compare, remind, route, and record. The employer retains policy, privacy, pay, benefits, accommodation, employee-relations, and other consequential decisions.`],
takeaways:['Preserve the original request and timestamp.','Separate proposed, approved, and applied values.','Give access only to fields required for this lane.','Stop when evidence conflicts or a decision is required.',`Close with ${proof}.`],
taskRows:[{lane:'Open',philippinesTeam:'Capture source, received time, requested action, and case identifier.',owner:'Define the controlling source and allowed action.',check:'The original request remains available'},{lane:'Verify',philippinesTeam:'Compare required fields without choosing between conflicts.',owner:'Resolve conflicts and approve consequential changes.',check:'Submitted and approved values are distinct'},{lane:'Route',philippinesTeam:'Send one precise exception note to the restricted owner.',owner:'Return a decision or actionable correction.',check:'Owner, reason, and review time are recorded'},{lane:'Close',philippinesTeam:'Apply only the approved administrative step and attach confirmation.',owner:'Review exceptions and authorize closure.',check:proof}],
pilotStats:[{value:'1',label:'Controlling source',note:focus},{value:'5',label:'Test cases',note:'Routine, missing, conflict, sensitive, failed destination'},{value:String(i+8),label:'Pilot records',note:'Review every early item'},{value:'2',label:'Owner checks',note:'Decision and closure'}],
sections:[{heading:'Define the opening event',paragraphs:[`Write down exactly what starts the work and where that evidence lives. For this lane, the purpose is to ${focus}.`,'Record the received time and an immutable case identifier before adding reminders or status labels.']},{heading:'Separate facts from decisions',paragraphs:['A coordinator may check whether named fields are present and whether sources agree. A mismatch is an exception to expose, not permission to choose.','Keep submitted value, owner decision, effective date, and applied result in separate fields.']},{heading:'Use a narrow working view',paragraphs:['A shared queue needs case identifier, status, owner, due time, and next action. Sensitive documents and narratives stay in the restricted system.',`Limit permissions to the minimum needed to ${focus}; review exports and sharing separately.`]},{heading:'Test failure before launch',paragraphs:['Test a routine case, missing input, conflicting evidence, sensitive message, and failed downstream update. Each must reach a named owner.','Have a second reviewer reconstruct the result from retained evidence and repair any ambiguous checklist field.']},{heading:'Close on destination evidence',paragraphs:[`Completion means ${proof}. A sent message or checked box does not show that the destination changed.`,'Keep unresolved work open with a named next action and review time; report aging separately from completion.']},{heading:'Questions for a provider',paragraphs:[`Ask for a redacted demonstration of how the team would ${focus}.`,'Confirm who reviews early work and how access, open cases, and records return to the company.']}],
scripts:[{label:'Exception handoff',text:`I preserved the source and paused because evidence is incomplete, conflicting, or needs an owner decision. Please confirm the controlling value for ${focus}.`},{label:'Closure note',text:`Closed after review of ${proof}.`}],workflow:[{step:'01',title:'Receive',text:'Preserve source, time, and case identity.'},{step:'02',title:'Compare',text:'Check facts without resolving conflicts.'},{step:'03',title:'Escalate',text:'Route the exception to its owner.'},{step:'04',title:'Apply',text:'Perform only the approved action.'},{step:'05',title:'Confirm',text:'Attach destination evidence and review.'}],faqs:[{question:'Can outsourced support own this lane?',answer:'It can own documented administration; the employer retains consequential decisions.'},{question:'What belongs in the shared tracker?',answer:'Use identity, status, owner, timing, and next action. Keep sensitive narratives restricted.'},{question:'What happens when sources disagree?',answer:'Preserve both values and ask the named owner which source controls.'},{question:'What proves completion?',answer:`Require ${proof}; activity alone is not completion.`}],related:[{title:'Related HR service',href:`/services/${service}`,note:'Review the matching administrative lane.'},{title:'HR reporting and QA',href:'/services/reporting-and-qa',note:'Design the evidence review.'}],sources:[{name:'NIST Privacy Framework',url:'https://www.nist.gov/privacy-framework',note:'Official privacy-risk framework.'},{name:'GAO Green Book',url:'https://www.gao.gov/green-book',note:'Official internal-control framework.'}],banners:[{eyebrow:'Map the lane',title:'Define the work before assigning it.',text:'Name the source, owner, stop point, and evidence.',href:`/services/${service}`,linkLabel:'Review the service scope'}]} as RichArticle]}));
