import type { RichArticle } from './article-data';

type Topic = { slug: string; title: string; description: string; focus: string; snag: string; proof: string; service: string };
const date = '2026-09-04';
const heroImage = '/blog-heroes/august31-hr-operations-field-guide.svg';
const source = { name: 'NIST Privacy Framework', url: 'https://www.nist.gov/privacy-framework', note: 'Official framework used for privacy-risk and data-processing controls.' };

const topics: Topic[] = [
  { slug: 'september4-hr-shared-inbox-duplicate-request-control', title: 'Stop duplicate work in a shared HR inbox', description: 'A practical way to identify repeated employee requests, preserve context, and keep two coordinators from making conflicting updates.', focus: 'duplicate request control', snag: 'the messages disagree about the requested change', proof: 'one linked case history and a confirmed owner', service: 'hr-help-desk-support' },
  { slug: 'september4-hr-new-hire-start-date-change-handoff', title: 'Handle a new hire start-date change without losing the handoff', description: 'Keep recruiting, onboarding, payroll, and system owners on the same approved date when a new hire schedule changes.', focus: 'start-date change coordination', snag: 'the candidate message and approved requisition show different dates', proof: 'the approved date in every named destination', service: 'onboarding-coordination' },
  { slug: 'september4-hr-interview-no-show-follow-up', title: 'Interview no-shows: a follow-up workflow for recruiting coordinators', description: 'Record what happened, send approved follow-up, and return rescheduling or disposition decisions to the hiring owner.', focus: 'interview no-show follow-up', snag: 'anyone asks the coordinator to reject or prioritize the candidate', proof: 'a recorded contact attempt and hiring-owner instruction', service: 'interview-coordination' },
  { slug: 'september4-hr-payroll-cutoff-late-change-log', title: 'Build a late-change log around the payroll cutoff', description: 'Separate on-time inputs from late corrections so payroll owners can decide what enters the current cycle.', focus: 'late payroll change logging', snag: 'a late item affects pay and has no authorized decision', proof: 'a dated payroll-owner disposition for each late item', service: 'payroll-preparation-support' },
  { slug: 'september4-hr-benefits-dependent-document-follow-up', title: 'Follow up on dependent documents without deciding eligibility', description: 'Track missing benefits paperwork and secure receipt while the plan owner retains eligibility and coverage decisions.', focus: 'dependent document follow-up', snag: 'the employee asks whether a dependent qualifies', proof: 'secure receipt or a documented owner response', service: 'benefits-administration-support' },
  { slug: 'september4-hr-policy-acknowledgment-version-check', title: 'Check the policy version before chasing an acknowledgment', description: 'Match each reminder to the approved policy version, employee audience, and actual delivery record.', focus: 'policy acknowledgment version checks', snag: 'the employee received a different version or disputes delivery', proof: 'a version-matched delivery and response event', service: 'operations-support' },
  { slug: 'september4-hr-leave-calendar-return-date-reconciliation', title: 'Reconcile return dates on the HR leave calendar', description: 'Compare approved leave records with calendars and staffing trackers without interpreting leave rights or medical details.', focus: 'leave return-date reconciliation', snag: 'sources conflict or the return date needs a policy decision', proof: 'an owner-approved date reflected in each in-scope calendar', service: 'employee-records-administration' },
  { slug: 'september4-hr-training-expiry-reminder-queue', title: 'Run a training-expiry reminder queue that respects exceptions', description: 'Use due dates, completion evidence, and approved exemptions to keep reminders accurate.', focus: 'training-expiry reminder administration', snag: 'completion evidence conflicts with the learning system', proof: 'current completion status or an owner-reviewed exception', service: 'learning-administration' },
  { slug: 'september4-hr-employee-address-change-payroll-sync', title: 'Sync an employee address change with payroll records', description: 'Route one authenticated address change through HR and payroll while keeping source evidence and destination confirmation.', focus: 'address-change synchronization', snag: 'identity checks fail or the two systems reject different fields', proof: 'matching approved values and confirmations from both systems', service: 'employee-records-administration' },
  { slug: 'september4-hr-reference-check-consent-tracker', title: 'Track reference-check consent before outreach begins', description: 'Give recruiting coordinators a clear record of consent, approved contacts, outreach status, and stop conditions.', focus: 'reference-check consent tracking', snag: 'consent is missing, withdrawn, or narrower than the proposed outreach', proof: 'current consent tied to each approved contact', service: 'recruiting-coordination' },
  { slug: 'september4-hr-manager-change-open-task-transfer', title: 'Transfer open HR tasks after a manager change', description: 'Reassign approvals and employee follow-ups with a dated owner record instead of relying on an old directory entry.', focus: 'open-task ownership transfer', snag: 'the new manager lacks authority for a pending decision', proof: 'a confirmed owner for every open item', service: 'operations-support' },
  { slug: 'september4-hr-weekly-queue-aging-review', title: 'Make a weekly HR queue aging review useful', description: 'Show why work is waiting, who owns the next action, and which records need immediate review.', focus: 'weekly queue aging review', snag: 'a sensitive case would expose details in a broad report', proof: 'a privacy-safe report with an owner and next date for each exception', service: 'reporting-and-qa' }
];

export const september4BlogPosts = topics.map(t => ({ slug: t.slug, title: t.title, excerpt: t.description, minutes: 9, published: date }));
export const september4Articles: Record<string, RichArticle> = Object.fromEntries(topics.map((t, index) => [t.slug, {
  slug: t.slug, title: t.title, description: t.description, published: date, updated: date, minutes: 9,
  revision: `${date}-${t.slug}`, heroImage,
  directAnswer: [`Treat ${t.focus} as a bounded administrative job. Name the controlling record, the company owner, and the event that proves the work reached its destination.`, `A Philippines-based coordinator can prepare, compare, remind, and document. The coordinator should pause when ${t.snag}.`],
  takeaways: [`Define the source for ${t.focus}.`, 'Keep submitted and approved values separate.', 'Use a named company owner for exceptions.', `Stop when ${t.snag}.`, `Close only with ${t.proof}.`],
  taskRows: [
    { lane: 'Receive', philippinesTeam: `Open the ${t.focus} record and preserve the request.`, owner: 'Set scope, authority, due time, and approved sources.', check: 'The request, source, and owner are visible' },
    { lane: 'Compare', philippinesTeam: 'Check the required fields without replacing conflicting evidence.', owner: 'Resolve differences and approve any consequential change.', check: 'Original and proposed values remain distinguishable' },
    { lane: 'Escalate', philippinesTeam: `Pause and ask one precise question when ${t.snag}.`, owner: 'Make the decision and approve the response.', check: 'The handoff identifies the blocker and next action' },
    { lane: 'Close', philippinesTeam: 'Apply the approved administrative step and attach confirmation.', owner: 'Review exceptions and confirm closure.', check: `The record contains ${t.proof}` }
  ],
  pilotStats: [{ value: '1', label: 'Queue', note: t.focus }, { value: '4', label: 'Test cases', note: 'Routine, missing, conflict, exception' }, { value: String(5 + index), label: 'Pilot records', note: 'Review each early item' }, { value: '2', label: 'Owners', note: 'Process and exception coverage' }],
  sections: [
    { heading: `Define the record for ${t.focus}`, paragraphs: [`Write down the request channel, controlling source, company owner, due time, allowed action, and closeout evidence. That is enough structure for another person to pick up the case without opening unrelated employee files.`, 'Use statuses that describe events: received, checked, waiting for owner, approved, applied, and confirmed. A vague "in progress" label hides the next action.'] },
    { heading: 'Keep disagreement visible', paragraphs: [`When two sources differ, save both values and their timestamps. The coordinator should not quietly choose the tidier entry, especially when ${t.snag}.`, 'The owner can then decide which source controls. Record that instruction beside the change so a later reviewer can follow the reasoning.'] },
    { heading: 'Give the handoff a stopping point', paragraphs: [`Routine administration can move quickly, but the written boundary matters. Pause when ${t.snag}, identify what has already been checked, and ask the owner for one decision.`, 'Do not put sensitive narrative into a general tracker. Use a restricted system for the underlying material and expose only the status needed for coordination.'] },
    { heading: 'Test ordinary and awkward cases', paragraphs: [`Run one clean case, one missing-field case, one source conflict, and one exception before increasing volume. For ${t.focus}, reviewers should check access, message wording, owner response, and destination evidence.`, 'If another reviewer cannot reconstruct the event from the record, revise the checklist. More reminders will not repair a weak audit trail.'] },
    { heading: 'Close on evidence', paragraphs: [`The useful finish line is ${t.proof}. Until that evidence exists, leave the item open with a next review date.`, 'Review early defects by cause, then change the specific source check, access rule, template, or escalation step that failed.'] },
    { heading: 'Questions to ask a provider', paragraphs: [`Ask a provider to demonstrate ${t.focus} with a redacted routine example and a genuine exception. The demonstration should show the fields used, the access boundary, the company decision, and the final proof.`, 'Also ask who reviews the first live records and how unfinished work returns to the client when the assignment changes.'] }
  ],
  scripts: [{ label: 'Owner handoff', text: `I checked the approved records for ${t.focus}. The unresolved point needs your decision, so I preserved both values and paused the update.` }, { label: 'Closure note', text: `This item can close after the record contains ${t.proof}. Until then, the next owner check remains scheduled.` }],
  workflow: [{ step: '01', title: 'Open', text: 'Record the request, source, owner, due time, and data boundary.' }, { step: '02', title: 'Check', text: 'Compare required fields while preserving conflicts.' }, { step: '03', title: 'Route', text: 'Send exceptions to the named company owner.' }, { step: '04', title: 'Apply', text: 'Carry out only the approved administrative action.' }, { step: '05', title: 'Confirm', text: 'Save destination proof and review any defect.' }],
  faqs: [{ question: `Can outsourced support own ${t.focus}?`, answer: 'The support role can own documented administrative steps. The employer retains policy, employment, pay, benefits, privacy, and exception decisions.' }, { question: 'How much system access is appropriate?', answer: 'Use named accounts and the smallest view or edit permission required for the written task.' }, { question: 'What should happen when sources disagree?', answer: 'Preserve both values and ask the accountable owner which source controls.' }, { question: 'What closes the task?', answer: `Require ${t.proof}; a checked box by itself is not enough.` }],
  related: [{ title: 'Related HR service', href: `/services/${t.service}`, note: 'Review the matching administrative lane.' }, { title: 'HR reporting and QA', href: '/services/reporting-and-qa', note: 'Plan source checks and early review.' }],
  sources: [source],
  banners: [{ eyebrow: 'Map the lane', title: `Define ${t.focus}.`, text: 'Name the source, owner, stop point, and proof.', href: `/services/${t.service}`, linkLabel: 'Review the service scope' }]
} as RichArticle]));
