export type FleetService = { slug: string; title: string; desc: string; tasks: readonly string[]; controls: readonly string[]; firstWeek: readonly string[] };
export type ResearchPost = { slug: string; title: string; excerpt: string; published: string; sections: readonly { heading: string; body: string }[]; sources?: readonly { name: string; url: string }[]; related?: readonly string[] };

export const fleetServices: readonly FleetService[] = [
  { slug: 'candidate-sourcing', title: 'Candidate Sourcing', desc: 'Build a Philippines-based candidate sourcing workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring human resources work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'interview-coordination', title: 'Interview Coordination', desc: 'Build a Philippines-based interview coordination workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring human resources work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'employee-records-administration', title: 'Employee Records Administration', desc: 'Build a Philippines-based employee records administration workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring human resources work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'benefits-administration-support', title: 'Benefits Administration Support', desc: 'Build a Philippines-based benefits administration support workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring human resources work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'payroll-preparation-support', title: 'Payroll Preparation Support', desc: 'Build a Philippines-based payroll preparation support workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring human resources work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'onboarding-coordination', title: 'Onboarding Coordination', desc: 'Build a Philippines-based onboarding coordination workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring human resources work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'learning-administration', title: 'Learning Administration', desc: 'Build a Philippines-based learning administration workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring human resources work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'hr-help-desk-support', title: 'HR Help Desk Support', desc: 'Build a Philippines-based hr help desk support workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring human resources work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'performance-review-administration', title: 'Performance Review Administration', desc: 'Build a Philippines-based performance review administration workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring human resources work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'offboarding-coordination', title: 'Offboarding Coordination', desc: 'Build a Philippines-based offboarding coordination workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring human resources work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] }
];

const researchSources = [
  { name: 'U.S. Bureau of Labor Statistics: Human Resources Specialists', url: 'https://www.bls.gov/ooh/business-and-financial/human-resources-specialists.htm' },
  { name: 'U.S. Bureau of Labor Statistics: Human Resources Managers', url: 'https://www.bls.gov/ooh/management/human-resources-managers.htm' },
  { name: 'U.S. Department of Labor: FLSA recordkeeping', url: 'https://www.dol.gov/agencies/whd/fact-sheets/21-flsa-recordkeeping' },
  { name: 'U.S. Equal Employment Opportunity Commission: Recordkeeping', url: 'https://www.eeoc.gov/employers/recordkeeping-requirements' },
  { name: 'OSHA: Recordkeeping', url: 'https://www.osha.gov/recordkeeping' },
  { name: 'NIST: Access Control', url: 'https://csrc.nist.gov/glossary/term/access_control' },
  { name: 'NIST Cybersecurity Framework 2.0', url: 'https://www.nist.gov/cyberframework' },
  { name: 'CISA: Phishing Guidance', url: 'https://www.cisa.gov/topics/cyber-threats-and-advisories/phishing' },
  { name: 'Federal Trade Commission: Protecting Personal Information', url: 'https://www.ftc.gov/business-guidance/resources/protecting-personal-information-guide-business' },
  { name: 'U.S. Department of Labor: FLSA exemptions', url: 'https://www.dol.gov/agencies/whd/fact-sheets/17a-overtime' }
] as const;

const researchTopics = [
  ['hr-outsourcing-workflow-control-benchmarks', 'HR Outsourcing Workflow Controls: A 10-Point Benchmark', 'A source-backed benchmark for deciding which recurring HR workflows can be outsourced while keeping approvals, records, and access under control.', '10 control questions give a practical screening baseline for an outsourced HR workflow.', 'Workflow control is the unit of analysis: define the work, the permitted system actions, the reviewer, and the evidence retained. A vendor can execute a repeatable task without owning the employment decision.', 'Start with low-ambiguity work such as scheduling, status tracking, and document intake. Require named owners for exceptions, approvals, and changes to employee records.', 'Which HR work is easiest to outsource?\nAdministrative workflows with clear inputs, repeatable steps, and a named reviewer are usually the easiest starting point.\nWhat should stay with the employer?\nEmployment decisions, policy interpretation, investigations, and final approvals should remain with the accountable employer or counsel.'],
  ['hr-records-retention-outsourcing-guide', 'HR Records Retention and Outsourcing: A Practical Control Guide', 'How to design an outsourced records workflow around retention duties, access boundaries, and a defensible audit trail.', 'At least 3 years is a commonly cited federal FLSA retention period for payroll records; the exact schedule depends on record type and applicable law.', 'Retention is not the same as storage. Map each record class to its legal or policy schedule, owner, system of record, deletion rule, and exception path before delegating handling.', 'Use a retention matrix and sample-based monthly review. Do not let a service provider invent a deletion schedule, and do not treat a backup copy as the authoritative record.', 'Does outsourcing transfer retention responsibility?\nNo. Delegation of handling does not remove the employer’s responsibility to set and review a compliant schedule.\nHow should access be granted?\nGrant the smallest role needed for the task and review access when duties change.'],
  ['employee-onboarding-coordination-benchmark', 'Employee Onboarding Coordination: A Benchmark for Handoff Quality', 'A research-backed operating model for coordinating onboarding tasks across HR, hiring managers, IT, and a support partner.', 'Four ownership lanes—HR, manager, IT, and the employee—make missing handoffs easier to detect than a single undifferentiated checklist.', 'A dependable onboarding workflow makes ownership visible at every handoff. Separate readiness evidence from the task list: a checked box is not proof that an account, document, or training step is usable.', 'Measure completion, exception age, and first-day readiness separately. Escalate identity, payroll, access, and policy exceptions rather than allowing a coordinator to guess.', 'What is the best onboarding KPI?\nUse a small set: first-day readiness, overdue tasks, exception age, and rework.\nCan a coordinator approve access?\nA coordinator can route and document requests; the designated system owner should approve access.'],
  ['hr-help-desk-triage-operating-model', 'HR Help Desk Triage: An Operating Model for Safe Outsourcing', 'A practical triage model for routing employee questions without turning a support queue into an unapproved policy or legal advice channel.', 'Three queue classes—routine, sensitive, and decision-required—are enough to separate service speed from escalation risk.', 'Triage should classify the request before answering it. Routine status questions can follow an approved knowledge base; sensitive matters need restricted handling; decision-required matters need an authorized owner.', 'Track response time, transfer rate, reopen rate, and unresolved age. Keep the answer source and escalation reason with the ticket, while limiting exposure of personal data.', 'What should be escalated immediately?\nPotential discrimination, retaliation, safety, pay, leave, accommodation, investigation, or termination matters require the designated owner.\nCan an outsourced agent answer policy questions?\nOnly from an approved, current knowledge base and within an explicit authority boundary.'],
  ['payroll-preparation-control-checklist', 'Payroll Preparation Controls: What to Delegate and What to Review', 'A control-first guide to delegating payroll preparation support without delegating the employer’s final review and approval.', 'A four-step control chain—input, preparation, review, approval—creates a clear separation of duties for payroll support.', 'Payroll preparation is a high-consequence workflow. A support partner may collect inputs, reconcile a checklist, and flag anomalies; the accountable payroll owner must review and approve the final result.', 'Require a dated cutoff, change log, exception report, reviewer sign-off, and secure transfer path. Never resolve an unexplained variance by editing source data without an owner’s decision.', 'What can support staff prepare?\nThey can organize approved inputs, reconcile expected fields, and document exceptions within assigned access.\nWho approves payroll?\nThe employer’s authorized payroll owner retains final approval responsibility.'],
  ['benefits-administration-support-controls', 'Benefits Administration Support: A Source-Backed Control Framework', 'How to structure benefits support work around eligibility inputs, employee privacy, carrier handoffs, and escalation.', 'Five checkpoints—eligibility, election, evidence, transmission, confirmation—cover the core support handoffs.', 'Benefits support combines repeatable administration with sensitive personal information. Make the source of truth explicit and require review for eligibility changes, qualifying events, and carrier discrepancies.', 'Use role-based access, secure document intake, and an exception queue. Record what was received and routed without copying sensitive details into unnecessary systems.', 'Can a support partner determine eligibility?\nThey can apply an approved workflow and flag a mismatch; the authorized benefits owner should decide ambiguous cases.\nWhat should be measured?\nAging exceptions, correction rate, and confirmation completeness are more useful than raw ticket volume.'],
  ['interview-coordination-data-minimization', 'Interview Coordination and Data Minimization: A Safer Workflow', 'A practical design for outsourcing interview scheduling while reducing unnecessary access to candidate and employee information.', 'Two separate records—calendar coordination and hiring evaluation—help prevent scheduling work from becoming an informal applicant file.', 'Interview coordination should expose only the information needed to schedule, confirm, reschedule, and document attendance. Evaluation notes and hiring decisions belong in the designated recruiting workflow.', 'Use templated messages, controlled calendars, and explicit cancellation rules. Audit shared links and remove access when a role or hiring campaign ends.', 'Should coordinators see interview feedback?\nNot unless the task specifically requires it and the permission is approved.\nWhat is a good control?\nSeparate scheduling permissions from evaluation permissions and test both with a sample account.'],
  ['employee-offboarding-access-revocation', 'Employee Offboarding: Access Revocation and Handoff Controls', 'A research-backed checklist for coordinating offboarding while preserving evidence, privacy, and timely access changes.', 'Three clocks should be tracked independently: manager confirmation, system revocation, and records handoff.', 'Offboarding is a coordination problem with security consequences. A coordinator can assemble the checklist and evidence, but system owners should execute or confirm revocation and HR should own the employment record.', 'Use a time-stamped trigger, named approvers, system-by-system confirmation, equipment disposition, and a restricted exception log. Never infer completion from a single platform status.', 'Who owns the offboarding trigger?\nThe employer’s authorized HR or manager process should trigger it; support staff should not create termination decisions.\nHow do you prove completion?\nRetain confirmations from each relevant system owner and reconcile exceptions.'],
  ['hr-service-level-agreements-workflow-design', 'HR Service-Level Agreements: Designing Useful Workflow Metrics', 'How to choose service metrics that reveal HR workflow quality instead of rewarding fast but unsafe ticket closure.', 'Four measures—first response, resolution, exception age, and rework—show different parts of service quality and should not be collapsed into one score.', 'A service-level agreement should describe scope, hours, handoffs, severity, evidence, and escalation. Speed without correct routing can increase risk and rework.', 'Set different targets by queue class. Review samples for accuracy and unauthorized disclosure, and treat repeated reopens as a process signal rather than simply an agent failure.', 'Is response time enough?\nNo. Pair it with accuracy, exception age, and rework so the metric cannot be optimized by premature closure.\nWho changes the SLA?\nThe process owner should approve scope and target changes after reviewing evidence.'],
  ['hr-outsourcing-access-review-cadence', 'HR Outsourcing Access Reviews: A Cadence for Least Privilege', 'A practical cadence for reviewing vendor and support access to HR systems using least-privilege principles.', 'Three review triggers are essential: a scheduled review, a role change, and an exception or security event.', 'Access control is a lifecycle, not a one-time setup. Inventory accounts, map each permission to a task, identify an owner, and remove access that no longer has a business need.', 'Run a periodic user-and-role review, record the approver and date, and test deprovisioning with a controlled sample. Keep service credentials out of shared documents and chat.', 'How often should access be reviewed?\nUse a risk-based schedule, plus immediate review on role changes and incidents.\nWhat evidence is useful?\nThe account list, role mapping, owner approval, exceptions, and completion date.'],
  ['hr-vendor-quality-scorecard', 'HR Support Vendor Quality: A Balanced Scorecard', 'A source-backed scorecard for reviewing an outsourced HR support partner on quality, control, and handoff performance.', 'Five dimensions—accuracy, timeliness, control adherence, escalation quality, and rework—cover more than a volume-only score.', 'A vendor scorecard should connect service evidence to the employer’s operating risks. Use a small sample of completed work and inspect whether the workflow, source, permission, and escalation were appropriate.', 'Review trends monthly and investigate outliers. Do not publish a vendor ranking from incomplete samples, and do not use employee-sensitive examples outside the approved review channel.', 'What makes a fair scorecard?\nDefined measures, a known sample, consistent review rules, and a way for the vendor to correct process defects.\nShould volume be scored?\nOnly as context; high volume is not quality if rework or control failures rise.'],
  ['hr-knowledge-base-governance', 'HR Knowledge Base Governance: Keeping Outsourced Answers Current', 'How to govern an HR knowledge base so outsourced support gives consistent, source-backed answers within approved boundaries.', 'Four fields make an article governable: owner, source, effective date, and next review date.', 'A knowledge base is a controlled operational asset. Each answer should state its scope, source, effective date, and escalation route; stale or ambiguous content should be quarantined rather than improvised around.', 'Review high-risk content more often than routine instructions. Keep policy interpretation and legal advice with the authorized owner, and log material revisions.', 'Who owns an HR knowledge article?\nA named policy or process owner should approve it and its review date.\nWhat happens when the answer is unclear?\nPause the answer, capture the question, and escalate to the designated owner.'],
  ['hr-outsourcing-business-continuity', 'HR Outsourcing Business Continuity: A Practical Readiness Test', 'A readiness test for keeping essential HR workflows moving when a vendor, system, or communication channel is unavailable.', 'Three dependency layers should be tested: people, systems, and records.', 'Continuity planning should identify critical workflows, acceptable interruption, alternate owners, recovery steps, and the evidence needed to resume safely. A backup contact list alone is not a continuity plan.', 'Run a tabletop exercise on one critical workflow. Capture what failed, who could authorize workarounds, and which records or access paths were missing; convert findings into owned actions.', 'What is the first continuity question?\nWhich HR workflows must continue, and what is the maximum tolerable interruption?\nShould a backup process bypass controls?\nNo. Workarounds still need authorization, logging, and a later reconciliation.']
] as const;

export const researchPosts: readonly ResearchPost[] = researchTopics.map(([slug, title, excerpt, stat, method, takeaway, faq]) => ({
  slug, title, excerpt, published: '2026-08-07', sources: researchSources,
  related: researchTopics.filter(([otherSlug]) => otherSlug !== slug).slice(0, 3).map(([otherSlug]) => otherSlug),
  sections: [
    { heading: 'Key Stats', body: stat },
    { heading: 'Methodology', body: `This report synthesizes the ten authoritative sources listed below and translates their control principles into an HR outsourcing workflow. It distinguishes sourced requirements from operating recommendations; it is not legal advice. ${method}` },
    { heading: 'Key Takeaways', body: takeaway },
    { heading: 'Implementation Checks', body: 'Name the process owner, define the system of record, limit permissions to the task, record exceptions, and review a sample of completed work. Revalidate the workflow whenever the policy, system, vendor, or role changes.' },
    { heading: 'FAQs', body: faq },
    { heading: 'Related Research', body: 'Use the three related reports shown below to compare adjacent controls, handoffs, and review responsibilities.' }
  ]
}));
export const postsPerPage = 20;
