export type FleetService = { slug: string; title: string; desc: string; tasks: readonly string[]; controls: readonly string[]; firstWeek: readonly string[] };
export type ResearchPost = { slug: string; title: string; excerpt: string; published: string; modified?: string; thumbnail?: string; sections: readonly { heading: string; body: string }[]; sources?: readonly { name: string; url: string }[]; serviceLink?: { title: string; href: string; body: string } };
import { august13ResearchPosts } from './research/august13-batch';
import { august14ResearchPosts } from './research/august14-batch';
import { august17ResearchPosts } from './research/august17-batch';
import { august18ResearchPosts } from './research/august18-batch';
import { august19ResearchPosts } from './research/august19-batch';
import { august21ResearchPosts } from './research/august21-repair-address';
import { august21StatusPosts } from './research/august21-repair-status';
import { august21RetentionPosts } from './research/august21-repair-retention';
import { august21ApprovalPosts } from './research/august21-repair-approval';
import { august21PortalPosts } from './research/august21-repair-portal';
import { august21NewResearchPosts } from './research/august21-research-batch';
import { august23ResearchPosts } from './research/august23-research-batch';
import { august31ResearchPosts } from './research/august31-research-batch';

export const fleetServices: readonly FleetService[] = [
  { slug: 'candidate-sourcing', title: 'Candidate Sourcing', desc: 'Build a Philippines-based candidate sourcing workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring human resources work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'interview-coordination', title: 'Interview Coordination', desc: 'Build a Philippines-based interview coordination workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring human resources work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'employee-records-administration', title: 'Employee Records Administration', desc: 'Build a Philippines-based employee records administration workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring human resources work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'benefits-administration-support', title: 'Benefits Administration Support', desc: 'Build a Philippines-based benefits administration support workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring human resources work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'payroll-preparation-support', title: 'Payroll Preparation Support', desc: 'Build a Philippines-based payroll preparation support workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring human resources work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'onboarding-coordination', title: 'Onboarding Coordination', desc: 'Build a Philippines-based onboarding coordination workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring human resources work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'learning-administration', title: 'Learning Administration', desc: 'Build a Philippines-based learning administration workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring human resources work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'hr-help-desk-support', title: 'HR Help Desk Support', desc: 'Build a Philippines-based hr help desk support workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring human resources work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'performance-review-administration', title: 'Performance Review Administration', desc: 'Build a Philippines-based performance review administration workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring human resources work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'offboarding-coordination', title: 'Offboarding Coordination', desc: 'Build a Philippines-based offboarding coordination workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring human resources work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] }
];

// Add reviewed, source-backed original research here. The templates and sitemap update automatically.
export const researchPosts: readonly ResearchPost[] = [
  { slug: 'hr-workflow-documentation-control-points', title: 'HR Workflow Documentation: Where Control Points Matter Most', excerpt: 'A practical, source-backed framework for documenting recurring HR workflows without losing approval ownership.', published: '2026-08-08', sections: [
    { heading: 'Research question', body: 'Which parts of a recurring HR workflow should be documented first? The answer is the points where personal data is collected, a decision is made, or work is handed to another owner.' },
    { heading: 'Methodology', body: 'This report synthesizes official guidance on records, privacy, and internal controls, then translates it into a repeatable workflow map. It is operational guidance, not legal advice.' },
    { heading: 'Key statistic', body: 'NIST describes a security control as a safeguard or countermeasure for managing risk. That framing supports treating each approval, access check, and exception path as an explicit control rather than an informal habit.' },
    { heading: 'Workflow model', body: 'For each workflow, record the trigger, required inputs, named preparer, reviewer, system of record, retention rule, exception path, and completion evidence. Start with hiring, onboarding, payroll preparation, and offboarding because errors there can propagate.' },
    { heading: 'Implementation takeaway', body: 'A useful brief is short enough to follow during a busy day and specific enough to show who may act. Review it quarterly and after any system or policy change.' }
  ], sources: [
    { name: 'NIST Cybersecurity Framework 2.0', url: 'https://www.nist.gov/cyberframework' }, { name: 'NIST Privacy Framework', url: 'https://www.nist.gov/privacy-framework' }, { name: 'U.S. Department of Labor Recordkeeping', url: 'https://www.dol.gov/general/topic/workhours/recordkeeping' }, { name: 'EEOC Recordkeeping Requirements', url: 'https://www.eeoc.gov/employers/recordkeeping-requirements' }, { name: 'FTC Protecting Personal Information', url: 'https://www.ftc.gov/business-guidance/resources/protecting-personal-information-guide-business' }, { name: 'CISA Cybersecurity Performance Goals', url: 'https://www.cisa.gov/cybersecurity-performance-goals' }, { name: 'ICO Accountability Framework', url: 'https://ico.org.uk/for-organisations/accountability-framework/' }, { name: 'ISO management standards overview', url: 'https://www.iso.org/management-system-standards.html' }, { name: 'SHRM HR policy guidance', url: 'https://www.shrm.org/topics-tools/tools/toolkits' }, { name: 'NARA Records Management', url: 'https://www.archives.gov/records-mgmt' }
  ] },
  { slug: 'employee-records-access-review-benchmark', title: 'Employee Records Access Reviews: A Practical Benchmark', excerpt: 'How HR teams can scope records access, review it consistently, and document exceptions.', published: '2026-08-08', sections: [
    { heading: 'Research question', body: 'What makes an employee-records access review useful? It should connect each permission to a job task, a data category, an owner, and an expiry or review date.' },
    { heading: 'Methodology', body: 'The analysis compares privacy-by-design and records-management guidance with a lightweight quarterly review process for small and midsize teams.' },
    { heading: 'Key statistic', body: 'The NIST Privacy Framework is organized around identifying and governing privacy risk. For HR operations, that means maintaining an inventory of data uses before changing access.' },
    { heading: 'Review checklist', body: 'Export the current user-role list, classify the records each role can see, confirm the business need with the manager, remove stale access, and retain the review result. Escalate mismatched or shared accounts.' },
    { heading: 'Implementation takeaway', body: 'Separate read, edit, export, and delete capabilities. A reviewer should be able to see the evidence without receiving broader access to employee data.' }
  ], sources: [
    { name: 'NIST Privacy Framework', url: 'https://www.nist.gov/privacy-framework' }, { name: 'NIST SP 800-53 Access Control', url: 'https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final' }, { name: 'FTC Protecting Personal Information', url: 'https://www.ftc.gov/business-guidance/resources/protecting-personal-information-guide-business' }, { name: 'CISA Identity and Access Management', url: 'https://www.cisa.gov/topics/cyber-threats-and-advisories/identity-and-access-management' }, { name: 'ICO Access control guidance', url: 'https://ico.org.uk/for-organisations/uk-gdpr-guidance-and-resources/security/access-control/' }, { name: 'U.S. Department of Labor Recordkeeping', url: 'https://www.dol.gov/general/topic/workhours/recordkeeping' }, { name: 'EEOC Recordkeeping Requirements', url: 'https://www.eeoc.gov/employers/recordkeeping-requirements' }, { name: 'NARA Records Management', url: 'https://www.archives.gov/records-mgmt' }, { name: 'CIS Controls', url: 'https://www.cisecurity.org/controls' }, { name: 'SHRM HR policy guidance', url: 'https://www.shrm.org/topics-tools/tools/toolkits' }
  ] },
  { slug: 'onboarding-coordination-handoff-risk', title: 'Onboarding Coordination: Reducing Handoff Risk', excerpt: 'A source-backed look at the small handoffs that determine whether onboarding is repeatable.', published: '2026-08-08', sections: [
    { heading: 'Research question', body: 'Where does onboarding work most often lose momentum? At handoffs between recruiting, HR, IT, payroll, the manager, and the new employee.' },
    { heading: 'Methodology', body: 'We mapped common onboarding inputs to official I-9, tax, privacy, and security guidance, then identified evidence that can be checked without exposing unnecessary personal data.' },
    { heading: 'Key statistic', body: 'USCIS identifies Form I-9 as a required employment-eligibility process for covered hires. The operational lesson is to assign a trained owner and a deadline instead of treating the form as a casual checklist item.' },
    { heading: 'Handoff design', body: 'Use one status record with due dates for identity and work authorization, payroll setup, equipment, access, manager expectations, and first-week check-ins. Each handoff should name sender, receiver, due date, and evidence.' },
    { heading: 'Implementation takeaway', body: 'Do not place sensitive documents in general chat or email threads. Link to the approved system and record completion status, not document contents.' }
  ], sources: [
    { name: 'USCIS Form I-9 Central', url: 'https://www.uscis.gov/i-9-central' }, { name: 'IRS Employer Tax Guide', url: 'https://www.irs.gov/publications/p15' }, { name: 'NIST Privacy Framework', url: 'https://www.nist.gov/privacy-framework' }, { name: 'FTC Protecting Personal Information', url: 'https://www.ftc.gov/business-guidance/resources/protecting-personal-information-guide-business' }, { name: 'CISA Cybersecurity Performance Goals', url: 'https://www.cisa.gov/cybersecurity-performance-goals' }, { name: 'DOL FLSA Recordkeeping', url: 'https://www.dol.gov/agencies/whd/flsa/recordkeeping' }, { name: 'EEOC Recordkeeping Requirements', url: 'https://www.eeoc.gov/employers/recordkeeping-requirements' }, { name: 'NARA Records Management', url: 'https://www.archives.gov/records-mgmt' }, { name: 'SHRM Onboarding Toolkit', url: 'https://www.shrm.org/topics-tools/tools/toolkits' }, { name: 'CISA Identity and Access Management', url: 'https://www.cisa.gov/topics/cyber-threats-and-advisories/identity-and-access-management' }
  ] },
  { slug: 'payroll-preparation-four-eyes-review', title: 'Payroll Preparation and the Four-Eyes Review', excerpt: 'Why payroll preparation benefits from a separate preparer and reviewer, with an evidence trail for changes.', published: '2026-08-08', sections: [
    { heading: 'Research question', body: 'How can a small HR team reduce preventable payroll preparation errors? Separate data preparation from approval and make changes traceable.' },
    { heading: 'Methodology', body: 'This report uses payroll recordkeeping guidance and internal-control principles to define a minimum review pattern. It does not provide tax or payroll advice.' },
    { heading: 'Key statistic', body: 'The U.S. Department of Labor requires employers to keep specified payroll records for covered employees. The practical implication is to design the workflow so records are created as work happens.' },
    { heading: 'Review pattern', body: 'The preparer reconciles starters, leavers, time, leave, approved changes, and exceptions. A separate reviewer checks totals and high-risk changes before submission. Both people sign the review log.' },
    { heading: 'Implementation takeaway', body: 'Use a controlled change queue, never a last-minute informal message. Escalate missing approvals, unexplained variance, duplicate entries, and requests to bypass the normal cutoff.' }
  ], sources: [
    { name: 'DOL FLSA Recordkeeping', url: 'https://www.dol.gov/agencies/whd/flsa/recordkeeping' }, { name: 'IRS Employer Tax Guide', url: 'https://www.irs.gov/publications/p15' }, { name: 'IRS Publication 15-T', url: 'https://www.irs.gov/publications/p15t' }, { name: 'NIST Internal Controls', url: 'https://csrc.nist.gov/glossary/term/internal_control' }, { name: 'GAO Green Book', url: 'https://www.gao.gov/green-book' }, { name: 'EEOC Recordkeeping Requirements', url: 'https://www.eeoc.gov/employers/recordkeeping-requirements' }, { name: 'NARA Records Management', url: 'https://www.archives.gov/records-mgmt' }, { name: 'FTC Protecting Personal Information', url: 'https://www.ftc.gov/business-guidance/resources/protecting-personal-information-guide-business' }, { name: 'CISA Cybersecurity Performance Goals', url: 'https://www.cisa.gov/cybersecurity-performance-goals' }, { name: 'SHRM Payroll Toolkit', url: 'https://www.shrm.org/topics-tools/tools/toolkits' }
  ], serviceLink: { title: 'Payroll preparation support for Philippines-based teams', href: '/services/payroll-preparation-support', body: 'Need help setting up the admin side of a payroll handoff? See the Philippines-based Payroll Preparation Support service for a starter task list, review points, and client approval boundaries.' } },
  { slug: 'hr-help-desk-service-level-evidence', title: 'HR Help Desk Service Levels: Measure the Work, Not Just the Queue', excerpt: 'A measurement framework for HR help desks that balances responsiveness, accuracy, privacy, and escalation.', published: '2026-08-08', modified: '2026-08-27', sections: [
    { heading: 'Research question', body: 'Which measures help an HR help desk improve without encouraging unsafe shortcuts? Combine response time with resolution quality, reopen rate, privacy handling, and escalation accuracy.' },
    { heading: 'Methodology', body: 'We adapted service-management measurement concepts to HR support and cross-checked the controls against privacy and records guidance.' },
    { heading: 'Key statistic', body: 'NIST’s Privacy Framework treats privacy risk management as an ongoing governance activity. Therefore a faster answer is not a better answer if it discloses information to the wrong person.' },
    { heading: 'Scorecard', body: 'Track first response, time to resolution, percentage resolved with approved knowledge, reopened cases, escalations by category, and sampled quality. Keep personal details out of the performance dashboard.' },
    { heading: 'Implementation takeaway', body: 'Publish the service boundary: what the coordinator can answer, what requires HR owner review, and what must go to legal, payroll, or security. Review samples weekly.' }
  ], sources: [
    { name: 'NIST Privacy Framework', url: 'https://www.nist.gov/privacy-framework' }, { name: 'NIST CSF 2.0', url: 'https://www.nist.gov/cyberframework' }, { name: 'CISA Cybersecurity Performance Goals', url: 'https://www.cisa.gov/cybersecurity-performance-goals' }, { name: 'ICO Accountability Framework', url: 'https://ico.org.uk/for-organisations/accountability-framework/' }, { name: 'FTC Protecting Personal Information', url: 'https://www.ftc.gov/business-guidance/resources/protecting-personal-information-guide-business' }, { name: 'DOL Worker Protection Resources', url: 'https://www.dol.gov/general/topics' }, { name: 'EEOC Employer Resources', url: 'https://www.eeoc.gov/employers' }, { name: 'ITIL Practices overview', url: 'https://www.peoplecert.org/ways-to-get-certified/itil' }, { name: 'NARA Records Management', url: 'https://www.archives.gov/records-mgmt' }, { name: 'SHRM HR policy guidance', url: 'https://www.shrm.org/topics-tools/tools/toolkits' }
  ], serviceLink: { title: 'Set up a bounded HR help desk support lane', href: '/services/hr-help-desk-support', body: 'Use a Philippines-based support lane to sort routine requests, send approved answers, and record clear handoffs. Your HR owner keeps sensitive cases, exceptions, and final decisions.' } },
  { slug: 'performance-review-administration-data-quality', title: 'Performance Review Administration and Data Quality', excerpt: 'How administrators can improve review-cycle reliability while leaving judgment with managers.', published: '2026-08-08', sections: [
    { heading: 'Research question', body: 'What should an HR administrator own in a performance-review cycle? Scheduling, reminders, version control, completion evidence, and escalation—not the manager’s evaluation judgment.' },
    { heading: 'Methodology', body: 'The framework combines records, equal-employment, and privacy guidance with a simple review-cycle control map.' },
    { heading: 'Key statistic', body: 'EEOC recordkeeping rules make retention a defined employer responsibility for covered records. The workflow should therefore preserve approved final records and the applicable retention decision.' },
    { heading: 'Control map', body: 'Set the cycle calendar, confirm the template, lock the final version, monitor completion, route exceptions, and archive approved records. Log edits to deadlines or templates.' },
    { heading: 'Implementation takeaway', body: 'Do not rewrite a manager’s assessment to make it sound polished. Return unclear or unsupported statements to the manager and escalate policy questions to the HR owner.' }
  ], sources: [
    { name: 'EEOC Recordkeeping Requirements', url: 'https://www.eeoc.gov/employers/recordkeeping-requirements' }, { name: 'EEOC Performance Management', url: 'https://www.eeoc.gov/employers/small-business/what-you-should-know-about-performance-management' }, { name: 'NIST Privacy Framework', url: 'https://www.nist.gov/privacy-framework' }, { name: 'DOL Recordkeeping', url: 'https://www.dol.gov/general/topic/workhours/recordkeeping' }, { name: 'NARA Records Management', url: 'https://www.archives.gov/records-mgmt' }, { name: 'FTC Protecting Personal Information', url: 'https://www.ftc.gov/business-guidance/resources/protecting-personal-information-guide-business' }, { name: 'CISA Cybersecurity Performance Goals', url: 'https://www.cisa.gov/cybersecurity-performance-goals' }, { name: 'SHRM Performance Management Toolkit', url: 'https://www.shrm.org/topics-tools/tools/toolkits' }, { name: 'ISO management standards overview', url: 'https://www.iso.org/management-system-standards.html' }, { name: 'GAO Green Book', url: 'https://www.gao.gov/green-book' }
  ] },
  { slug: 'offboarding-coordination-access-revocation', title: 'Offboarding Coordination: Access Revocation as a Handoff', excerpt: 'A compact operating model for coordinating offboarding tasks, evidence, and responsible owners.', published: '2026-08-08', sections: [
    { heading: 'Research question', body: 'Why is offboarding a coordination problem rather than a single HR task? Because payroll, records, equipment, managers, and identity systems each have a different owner and deadline.' },
    { heading: 'Methodology', body: 'We synthesized identity-management, privacy, and records guidance into a sequence that can be adapted to an employer’s policies and jurisdiction.' },
    { heading: 'Key statistic', body: 'CISA identifies identity and access management as a core cybersecurity practice. In an offboarding workflow, the key control is a verified request and a recorded completion signal from each system owner.' },
    { heading: 'Sequence', body: 'Confirm the approved effective time, notify owners, suspend or revoke access, recover assets, document payroll and benefits handoffs, preserve required records, and close the case only after exceptions are resolved.' },
    { heading: 'Implementation takeaway', body: 'Avoid broadcasting sensitive separation details. Use minimum-necessary notifications and separate operational status from confidential case notes.' }
  ], sources: [
    { name: 'CISA Identity and Access Management', url: 'https://www.cisa.gov/topics/cyber-threats-and-advisories/identity-and-access-management' }, { name: 'NIST Access Control', url: 'https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final' }, { name: 'NIST Privacy Framework', url: 'https://www.nist.gov/privacy-framework' }, { name: 'FTC Protecting Personal Information', url: 'https://www.ftc.gov/business-guidance/resources/protecting-personal-information-guide-business' }, { name: 'DOL Recordkeeping', url: 'https://www.dol.gov/general/topic/workhours/recordkeeping' }, { name: 'EEOC Recordkeeping Requirements', url: 'https://www.eeoc.gov/employers/recordkeeping-requirements' }, { name: 'NARA Records Management', url: 'https://www.archives.gov/records-mgmt' }, { name: 'CISA Cybersecurity Performance Goals', url: 'https://www.cisa.gov/cybersecurity-performance-goals' }, { name: 'SHRM Offboarding Toolkit', url: 'https://www.shrm.org/topics-tools/tools/toolkits' }, { name: 'ISO management standards overview', url: 'https://www.iso.org/management-system-standards.html' }
  ] },
  { slug: 'benefits-administration-change-control', title: 'Benefits Administration Change Control', excerpt: 'How to route benefits changes with clear approvals, deadlines, and employee-facing evidence.', published: '2026-08-08', sections: [
    { heading: 'Research question', body: 'Which benefits changes deserve a formal control? Any change that affects eligibility, deductions, elections, dependents, or a carrier transmission should have a request, approval, and reconciliation trail.' },
    { heading: 'Methodology', body: 'This report focuses on administrative reliability and privacy. Plan documents and applicable law remain the authority for eligibility and deadlines.' },
    { heading: 'Key statistic', body: 'The IRS publishes employer guidance on cafeteria plans and benefits administration. The operational lesson is to anchor changes to the governing plan and keep a dated evidence trail.' },
    { heading: 'Change workflow', body: 'Capture the request, verify the permitted event or window, obtain approval, update the system of record, reconcile the outbound file or invoice, and confirm the employee-facing result.' },
    { heading: 'Implementation takeaway', body: 'Use a separate exception queue for missing documentation, deadline conflicts, and unclear eligibility. Never infer a benefit decision from an incomplete request.' }
  ], sources: [
    { name: 'IRS Cafeteria Plans', url: 'https://www.irs.gov/government-entities/federal-state-local-governments/cafeteria-plans' }, { name: 'Department of Labor EBSA', url: 'https://www.dol.gov/agencies/ebsa' }, { name: 'DOL Summary Plan Description', url: 'https://www.dol.gov/general/topic/health-plans/planinformation' }, { name: 'NIST Privacy Framework', url: 'https://www.nist.gov/privacy-framework' }, { name: 'FTC Protecting Personal Information', url: 'https://www.ftc.gov/business-guidance/resources/protecting-personal-information-guide-business' }, { name: 'DOL Recordkeeping', url: 'https://www.dol.gov/general/topic/workhours/recordkeeping' }, { name: 'NARA Records Management', url: 'https://www.archives.gov/records-mgmt' }, { name: 'CISA Cybersecurity Performance Goals', url: 'https://www.cisa.gov/cybersecurity-performance-goals' }, { name: 'EEOC Employer Resources', url: 'https://www.eeoc.gov/employers' }, { name: 'SHRM Benefits Toolkit', url: 'https://www.shrm.org/topics-tools/tools/toolkits' }
  ] },
  { slug: 'recruiting-coordination-candidate-data', title: 'Recruiting Coordination and Candidate Data Minimization', excerpt: 'A practical research brief for coordinating recruiting activity while limiting unnecessary candidate-data exposure.', published: '2026-08-08', sections: [
    { heading: 'Research question', body: 'How can recruiting coordination stay efficient without spreading candidate information across too many systems? Collect the minimum needed, restrict access by task, and define the approved record.' },
    { heading: 'Methodology', body: 'We translated privacy-by-design and equal-employment recordkeeping principles into a candidate coordination workflow.' },
    { heading: 'Key statistic', body: 'The EEOC identifies employment records that employers should retain under applicable requirements. A coordinator should know which record is official before creating copies or exports.' },
    { heading: 'Coordination pattern', body: 'Use structured stages for requisition approval, interview scheduling, feedback collection, decision approval, and disposition. Keep interview notes in the approved system and limit broad exports.' },
    { heading: 'Implementation takeaway', body: 'Do not make selection decisions or provide legal interpretations as an administrator. Escalate accommodation, discrimination, background-check, and policy questions to the designated owner.' }
  ], sources: [
    { name: 'EEOC Recordkeeping Requirements', url: 'https://www.eeoc.gov/employers/recordkeeping-requirements' }, { name: 'EEOC Employer Resources', url: 'https://www.eeoc.gov/employers' }, { name: 'NIST Privacy Framework', url: 'https://www.nist.gov/privacy-framework' }, { name: 'FTC Protecting Personal Information', url: 'https://www.ftc.gov/business-guidance/resources/protecting-personal-information-guide-business' }, { name: 'FTC Employment Background Checks', url: 'https://www.ftc.gov/business-guidance/resources/using-consumer-reports-what-employers-need-know' }, { name: 'DOL Recordkeeping', url: 'https://www.dol.gov/general/topic/workhours/recordkeeping' }, { name: 'CISA Cybersecurity Performance Goals', url: 'https://www.cisa.gov/cybersecurity-performance-goals' }, { name: 'NARA Records Management', url: 'https://www.archives.gov/records-mgmt' }, { name: 'SHRM Recruiting Toolkit', url: 'https://www.shrm.org/topics-tools/tools/toolkits' }, { name: 'ISO management standards overview', url: 'https://www.iso.org/management-system-standards.html' }
  ] },
  { slug: 'learning-administration-completion-evidence', title: 'Learning Administration: Completion Evidence That Holds Up', excerpt: 'How to make training administration auditable without turning it into a paperwork exercise.', published: '2026-08-08', sections: [
    { heading: 'Research question', body: 'What does a reliable learning-administration record contain? A defined course, assigned audience, due date, completion signal, exception reason, and responsible reviewer.' },
    { heading: 'Methodology', body: 'This operational brief connects training-record practices with privacy and records-management principles. Training requirements vary by employer and jurisdiction.' },
    { heading: 'Key statistic', body: 'OSHA maintains employer recordkeeping guidance for workplace safety and health. The lesson for administrators is to distinguish required training evidence from optional learning activity.' },
    { heading: 'Evidence model', body: 'Maintain a roster from an approved source, assign the correct course version, monitor due dates, reconcile completion reports, and route exemptions or failures to the owner.' },
    { heading: 'Implementation takeaway', body: 'Store completion status and course identifiers in the operational report; keep sensitive learner details in the source system with appropriate access controls.' }
  ], sources: [
    { name: 'OSHA Recordkeeping', url: 'https://www.osha.gov/recordkeeping' }, { name: 'OSHA Training Requirements', url: 'https://www.osha.gov/training' }, { name: 'NIST Privacy Framework', url: 'https://www.nist.gov/privacy-framework' }, { name: 'FTC Protecting Personal Information', url: 'https://www.ftc.gov/business-guidance/resources/protecting-personal-information-guide-business' }, { name: 'DOL Recordkeeping', url: 'https://www.dol.gov/general/topic/workhours/recordkeeping' }, { name: 'NARA Records Management', url: 'https://www.archives.gov/records-mgmt' }, { name: 'CISA Cybersecurity Performance Goals', url: 'https://www.cisa.gov/cybersecurity-performance-goals' }, { name: 'EEOC Employer Resources', url: 'https://www.eeoc.gov/employers' }, { name: 'SHRM Learning Toolkit', url: 'https://www.shrm.org/topics-tools/tools/toolkits' }, { name: 'ISO management standards overview', url: 'https://www.iso.org/management-system-standards.html' }
  ] },
  { slug: 'hr-metrics-data-dictionary', title: 'An HR Metrics Data Dictionary for Small Teams', excerpt: 'A starter data dictionary that keeps HR reporting definitions stable across people and systems.', published: '2026-08-08', sections: [
    { heading: 'Research question', body: 'Why do HR dashboards disagree? Usually because terms such as headcount, time to hire, turnover, and completion have different definitions in different workflows.' },
    { heading: 'Methodology', body: 'We built a minimum dictionary from official recordkeeping and privacy guidance, emphasizing definitions that can be reproduced from an approved source.' },
    { heading: 'Key statistic', body: 'The Bureau of Labor Statistics publishes technical notes describing how labor measures are defined and collected. The operational takeaway is to document numerator, denominator, population, date window, and exclusions.' },
    { heading: 'Minimum dictionary', body: 'For every metric record its name, business question, formula, source system, refresh cadence, owner, allowed breakdowns, and caveats. Version the definition when policy changes.' },
    { heading: 'Implementation takeaway', body: 'Do not expose individual employee details in a general dashboard. Report aggregates, suppress small cells where appropriate, and keep a link to the definition beside every number.' }
  ], sources: [
    { name: 'BLS Handbook of Methods', url: 'https://www.bls.gov/opub/hom/' }, { name: 'BLS Labor Force Statistics', url: 'https://www.bls.gov/cps/' }, { name: 'NIST Privacy Framework', url: 'https://www.nist.gov/privacy-framework' }, { name: 'FTC Protecting Personal Information', url: 'https://www.ftc.gov/business-guidance/resources/protecting-personal-information-guide-business' }, { name: 'EEOC Data and Statistics', url: 'https://www.eeoc.gov/data' }, { name: 'DOL Recordkeeping', url: 'https://www.dol.gov/general/topic/workhours/recordkeeping' }, { name: 'NARA Records Management', url: 'https://www.archives.gov/records-mgmt' }, { name: 'CISA Cybersecurity Performance Goals', url: 'https://www.cisa.gov/cybersecurity-performance-goals' }, { name: 'GAO Green Book', url: 'https://www.gao.gov/green-book' }, { name: 'SHRM HR Analytics Toolkit', url: 'https://www.shrm.org/topics-tools/tools/toolkits' }
  ] }
];

// 2026-08-09 Research batch: independently screened topics with family-specific slugs.
const researchBatchSources = [
  { name: 'NIST Cybersecurity Framework 2.0', url: 'https://www.nist.gov/cyberframework' },
  { name: 'NIST Privacy Framework', url: 'https://www.nist.gov/privacy-framework' },
  { name: 'NIST SP 800-53 Access Control', url: 'https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final' },
  { name: 'FTC Protecting Personal Information', url: 'https://www.ftc.gov/business-guidance/resources/protecting-personal-information-guide-business' },
  { name: 'CISA Cybersecurity Performance Goals', url: 'https://www.cisa.gov/cybersecurity-performance-goals' },
  { name: 'U.S. Department of Labor Recordkeeping', url: 'https://www.dol.gov/general/topic/workhours/recordkeeping' },
  { name: 'EEOC Recordkeeping Requirements', url: 'https://www.eeoc.gov/employers/recordkeeping-requirements' },
  { name: 'NARA Records Management', url: 'https://www.archives.gov/records-mgmt' },
  { name: 'GAO Green Book', url: 'https://www.gao.gov/green-book' },
  { name: 'SHRM HR Toolkits', url: 'https://www.shrm.org/topics-tools/tools/toolkits' }
] as const;

const researchBatchTopics = [
  ['hr-case-intake-privacy-controls', 'HR Case Intake: Privacy Controls for Consistent Triage', 'A practical evidence-first model for routing HR questions while limiting unnecessary employee-data exposure.', 'NIST describes the Privacy Framework as a way to manage privacy risk; the operational implication is to classify the request before collecting more data.', 'Use a structured intake with category, urgency, approved requester, minimum necessary facts, owner, due date, and escalation reason.', 'Which requests need escalation? Anything involving suspected discrimination, safety, accommodation, legal interpretation, payroll correction, or a security incident.'],
  ['hr-document-retention-review-cycle', 'HR Document Retention: Designing a Review Cycle', 'How small HR teams can turn retention rules into a repeatable review and disposition workflow.', 'The Department of Labor and EEOC both publish recordkeeping requirements, showing why retention should be mapped to record type and jurisdiction rather than one blanket timer.', 'Create a register with record class, authority, retention trigger, system of record, owner, legal hold flag, and approved disposition evidence.', 'What is the safest default? Pause disposition when a legal hold, investigation, audit, or unresolved employee matter may apply, then escalate to the responsible owner.'],
  ['hr-employee-change-request-audit-trail', 'Employee Change Requests: Building an Audit Trail', 'A control map for job, manager, location, status, and compensation-change administration.', 'GAO’s Green Book frames documentation as evidence that supports internal control; for HR administration, each approved change should leave a traceable request and reviewer signal.', 'Separate request, validation, approval, system update, reconciliation, and employee notification. Record timestamps without copying sensitive case details into general logs.', 'Can an administrator approve a change? Only when the written delegation says so; otherwise route it to the named HR or management owner.'],
  ['hr-absence-tracking-data-quality', 'Absence Tracking Data Quality: Definitions Before Dashboards', 'Why dependable absence reporting starts with shared definitions and an exception queue.', 'BLS methodology materials demonstrate that a measure is only useful when its population, period, and definitions are explicit.', 'Define absence type, qualifying event, unit, start and end rules, source, correction authority, and aggregation method before publishing a report.', 'How should disputed entries be handled? Preserve the source value, open an exception, record the owner, and avoid silently overwriting history.'],
  ['hr-policy-acknowledgment-evidence', 'HR Policy Acknowledgments: Evidence That Is Easy to Reconcile', 'A workflow for assigning, tracking, and reconciling policy acknowledgments without over-collecting data.', 'NIST’s Privacy Framework emphasizes governance of data processing; a status record usually proves completion without retaining unnecessary copies of the policy recipient’s personal information.', 'Version each policy, assign the correct audience, record assignment and completion signals, route exceptions, and archive the final reconciliation.', 'What counts as completion? Use the approved system’s completion event and policy version, not an informal reply or screenshot in a chat channel.'],
  ['hr-employee-file-quality-check', 'Employee File Quality Checks: A Risk-Based Sampling Method', 'A lightweight sampling method for finding missing, stale, or misplaced HR records.', 'NIST SP 800-53 treats assessment as an ongoing control activity; sampling lets a small team test quality without granting broad access to every record.', 'Choose a documented sample, test required fields and access boundaries, log defects by category, assign remediation owners, and retain aggregate results.', 'Should every file be copied for review? No. Inspect in the approved system and record findings at the minimum level needed for remediation.'],
  ['hr-offer-approval-workflow-controls', 'Offer Approval Workflow Controls for Recruiting Teams', 'Where approval, version control, and candidate-data boundaries matter in offer administration.', 'The EEOC recordkeeping guidance supports preserving employment records, while FTC guidance highlights the need to protect personal information; offer workflows need both record and privacy controls.', 'Lock the approved requisition, route compensation and terms for authorized review, preserve the final version, and keep candidate communications in the approved system.', 'Who owns legal or policy questions? The designated HR or legal owner; the coordinator should not improvise a term or make a selection decision.'],
  ['hr-employee-survey-governance', 'Employee Survey Governance: Useful Aggregates, Safer Handling', 'A practical design for collecting workplace feedback while protecting confidentiality and interpretability.', 'The NIST Privacy Framework centers risk management, so survey governance should define purpose, access, aggregation, retention, and follow-up before launch.', 'Document purpose, audience, minimum demographic breakdown, suppression rule, responsible analyst, response window, and action owner.', 'Can every comment be shared with managers? No. Apply the approved confidentiality and access rules, and escalate threats or sensitive disclosures.'],
  ['hr-knowledge-base-content-controls', 'HR Knowledge Base Controls: Keeping Answers Current', 'How to govern HR help content so answers remain owned, dated, and safe to reuse.', 'ISO management-system guidance and NIST CSF governance principles both support named ownership and review evidence for controlled operational information.', 'Give each article an owner, scope, jurisdiction, effective date, review date, source authority, escalation boundary, and change history.', 'What should a coordinator do with an outdated answer? Mark it for review, link the approved source, and escalate instead of silently editing policy language.'],
  ['hr-timekeeping-exception-management', 'Timekeeping Exceptions: A Reviewable Queue for Payroll Support', 'A structured approach to missing punches, schedule mismatches, and approval exceptions.', 'DOL recordkeeping guidance requires employers to retain specified hours and wage records; exception handling should make corrections traceable to an authorized reviewer.', 'Classify the exception, preserve the original signal, obtain the correction rationale, route approval, update the system of record, and reconcile the payroll feed.', 'May an administrator infer hours? No. Request evidence and escalate unresolved or disputed entries to the responsible manager or payroll owner.'],
  ['hr-background-check-coordination-controls', 'Background-Check Coordination: Separating Process From Decision', 'A boundary-focused workflow for coordinating background checks without making employment decisions.', 'The FTC states that employers using consumer reports have obligations under the FCRA; process coordinators should therefore track consent and notices while leaving decisions to the authorized owner.', 'Use an approved vendor, verify authorization, restrict report access, track required notices, and document the decision owner without reproducing report contents.', 'What must be escalated? Disputes, adverse-action questions, jurisdictional differences, and any request to bypass required notices.'],
  ['hr-remote-worker-records-access', 'Remote Worker Records Access: A Least-Privilege Review', 'A role-based approach to remote access for HR records and workflow tools.', 'CISA identifies identity and access management as a core practice; the measurable HR control is a current role-to-task mapping with review evidence.', 'Separate read, edit, export, and administrative permissions; use named accounts; review role changes at onboarding, transfer, and offboarding.', 'Should shared credentials be allowed? No. Escalate any workflow that depends on shared or untraceable access.'],
  ['hr-exit-interview-data-handling', 'Exit Interview Data Handling: From Notes to Actionable Signals', 'How to preserve useful exit themes while minimizing exposure of confidential employee comments.', 'NARA records-management guidance reinforces the need for defined records and lifecycle decisions; exit data should have a purpose, owner, access boundary, and retention decision.', 'Separate operational completion from confidential notes, code themes consistently, report aggregates, restrict raw comments, and document follow-up ownership.', 'When should raw comments be shared? Only under the approved purpose and access rules; safety, legal, or security concerns should be escalated immediately.']
] as const;

export const researchBatchPosts: readonly ResearchPost[] = researchBatchTopics.map(([slug, title, excerpt, statistic, model, faq]) => ({
  slug, title, excerpt, published: '2026-08-09',
  sections: [
    { heading: 'Research question', body: `This report asks: what makes ${title.toLowerCase().replace(/^.*?: /, '')} repeatable, reviewable, and safe for a small HR operations team?` },
    { heading: 'Methodology', body: 'We synthesized the ten listed primary and professional sources, screened the topic against the existing Research slugs and titles, and translated the guidance into an operational control model. This is general workflow guidance, not legal advice.' },
    { heading: 'Key statistic', body: statistic },
    { heading: 'Key takeaways and data model', body: `${model} Track status, owner, source system, due date, exception category, and completion evidence as separate fields so a reviewer can test the workflow without receiving unnecessary personal data.` },
    { heading: 'Implementation checklist', body: 'Confirm the trigger and owner; use the approved system of record; restrict access by task; retain the evidence required by policy; review exceptions weekly; and document the escalation outcome.' },
    { heading: 'FAQs', body: faq }
  ],
  sources: researchBatchSources
})) ;

// 2026-08-10 Research batch: twelve additional, screened topics for the daily run.
const researchRunSources = [
  { name: 'NIST Cybersecurity Framework 2.0', url: 'https://www.nist.gov/cyberframework' },
  { name: 'NIST Privacy Framework', url: 'https://www.nist.gov/privacy-framework' },
  { name: 'NIST SP 800-53 Rev. 5', url: 'https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final' },
  { name: 'FTC Protecting Personal Information', url: 'https://www.ftc.gov/business-guidance/resources/protecting-personal-information-guide-business' },
  { name: 'CISA Cybersecurity Performance Goals', url: 'https://www.cisa.gov/cybersecurity-performance-goals' },
  { name: 'U.S. Department of Labor Recordkeeping', url: 'https://www.dol.gov/general/topic/workhours/recordkeeping' },
  { name: 'EEOC Recordkeeping Requirements', url: 'https://www.eeoc.gov/employers/recordkeeping-requirements' },
  { name: 'NARA Records Management', url: 'https://www.archives.gov/records-mgmt' },
  { name: 'GAO Green Book', url: 'https://www.gao.gov/green-book' },
  { name: 'SHRM HR Toolkits', url: 'https://www.shrm.org/topics-tools/tools/toolkits' },
] as const;

const researchRunTopics = [
  ['hr-onboarding-task-control-points', 'Onboarding Task Controls: Making Handoffs Reviewable', 'A source-backed model for assigning, checking, and closing onboarding work without losing ownership.', 'NIST control guidance supports explicit owners and review evidence; onboarding needs a task-level record rather than an informal checklist.', 'Map trigger, owner, dependency, due date, system of record, exception reason, and completion evidence. Reconcile identity, access, policy, and payroll handoffs separately.', 'Who closes an overdue task? The named owner or delegated reviewer; coordinators should escalate instead of silently changing the due date.'],
  ['hr-payroll-input-reconciliation', 'Payroll Input Reconciliation: A Control Model for HR Support', 'How to reconcile payroll inputs while preserving source values, approvals, and correction evidence.', 'DOL recordkeeping guidance makes hours and wage records a controlled business record; reconciliation should connect each correction to an authorized source and reviewer.', 'Compare source and outbound values, classify variances, preserve the original, obtain approval, update the system of record, and retain the reconciliation result.', 'Can a coordinator estimate a missing input? No. Preserve the gap and route it to the responsible manager or payroll owner.'],
  ['hr-access-review-worker-lifecycle', 'Worker Lifecycle Access Reviews: Joining, Moving, and Leaving', 'A practical research brief for keeping HR-system permissions aligned to worker status and role.', 'CISA emphasizes identity and access management; a lifecycle review turns that principle into a measurable role-to-access checklist.', 'Review access at hire, transfer, temporary assignment, and separation; distinguish read, edit, export, and administrative rights; retain reviewer and date.', 'What if access cannot be removed? Record the exception, restrict the account if authorized, and escalate to the security or system owner.'],
  ['hr-requisition-intake-data-quality', 'Requisition Intake Data Quality: Definitions Before Recruiting Starts', 'Why recruiting workflows improve when requisition fields, approvals, and source ownership are explicit.', 'EEOC recordkeeping guidance shows the importance of preserving employment records; a controlled requisition also prevents unapproved criteria from entering the process.', 'Define role scope, location, owner, approved criteria, compensation authority, opening date, and disposition rules before sourcing begins.', 'May a coordinator change a requirement to improve response rates? Only with documented owner approval; otherwise return the requisition for clarification.'],
  ['hr-manager-self-service-boundaries', 'Manager Self-Service Boundaries: Routing HR Work Safely', 'A decision framework for separating routine manager requests from work that needs HR review.', 'The NIST Privacy Framework links data processing to purpose and risk; routing should classify the request before exposing employee details or changing a record.', 'Create request categories, minimum fields, authority checks, service-level expectations, escalation triggers, and closure evidence.', 'Which requests always need HR review? Discrimination, accommodation, leave disputes, discipline, pay corrections, safety, and legal interpretation.'],
  ['hr-employee-data-export-review', 'Employee Data Exports: A Preflight Review Checklist', 'How to review HR exports for purpose, scope, recipient, and retention before they leave the system of record.', 'FTC privacy guidance recommends safeguards for personal information; an export review converts that principle into a repeatable approval step.', 'Record purpose, fields, population, recipient, transfer method, expiry, owner, and deletion or return evidence. Prefer filtered views over full-database exports.', 'Can a broad export be sent for convenience? No. Reduce scope or escalate the business need and approved safeguards.'],
  ['hr-performance-cycle-administration', 'Performance-Cycle Administration: Evidence Without Decision Drift', 'A workflow for scheduling reviews and reconciling completion while leaving evaluation decisions with managers.', 'EEOC employer resources and records guidance support preserving employment records; administrators should coordinate the cycle without altering evaluative content.', 'Version the cycle, confirm population, assign deadlines, monitor status, protect comments, route exceptions, and preserve the approved completion event.', 'Can an administrator change a rating to resolve a workflow error? No. Return it to the authorized manager and retain the correction trail.'],
  ['hr-leave-request-workflow-controls', 'Leave Request Workflow Controls: From Intake to Reconciliation', 'A control map for routing leave requests without making eligibility decisions from incomplete information.', 'DOL recordkeeping and NIST privacy guidance together support defined records, limited access, and explicit escalation for sensitive requests.', 'Capture request type, dates, source documents, reviewer, status, exception reason, and system-of-record update; keep medical or sensitive details out of general logs.', 'Should a coordinator decide eligibility? No. Escalate incomplete, disputed, or jurisdiction-specific cases to the authorized HR owner.'],
  ['hr-hris-change-management', 'HRIS Change Management: Testing Small Workflow Updates', 'How to introduce HR-system changes with a lightweight test, approval, and rollback record.', 'GAO’s Green Book treats control activities and documentation as evidence; even small HRIS changes need an accountable change path.', 'Record requested change, risk, test case, approver, implementation window, result, rollback plan, and affected workflow owner.', 'Can a coordinator change production settings directly? Only if documented access and delegation permit it; otherwise prepare the change and escalate.'],
  ['hr-employee-relations-case-routing', 'Employee-Relations Case Routing: Triage Before Detail', 'A privacy-conscious intake model for routing employee-relations matters to the right owner.', 'NIST privacy principles support collecting information for a defined purpose; triage should identify risk and owner before gathering extensive case detail.', 'Use category, urgency, safety flag, involved owner, minimum necessary summary, access boundary, next action, and escalation timestamp.', 'What belongs in a general operations queue? Only the minimum routing data; sensitive narratives remain in the approved case system.'],
  ['hr-hr-vendor-access-governance', 'HR Vendor Access Governance: Scope, Review, and Offboarding', 'A practical way to govern third-party access to HR workflows and records.', 'NIST CSF and CISA guidance emphasize governance and access control; vendor access needs the same owner, scope, and review signals as internal access.', 'Maintain vendor, purpose, systems, data classes, approved users, contract owner, review date, incident path, and offboarding evidence.', 'Should vendors receive standing broad access? No. Use task-limited access and escalate any exception for written approval.'],
  ['hr-workforce-planning-data-definitions', 'Workforce Planning Data Definitions: A Reproducible Baseline', 'A source-backed starter model for headcount, vacancies, capacity, and movement reporting.', 'BLS methodology demonstrates why population, period, and definitions must be explicit before a workforce measure is compared.', 'Define each measure, formula, population, date window, source, owner, refresh cadence, exclusions, and permitted aggregation.', 'Can planning reports include named employee rows by default? No. Use aggregates and approved access boundaries unless an authorized purpose requires detail.'],
] as const;

export const researchRunPosts: readonly ResearchPost[] = researchRunTopics.map(([slug, title, excerpt, statistic, model, faq]) => ({
  slug, title, excerpt, published: '2026-08-10',
  sections: [
    { heading: 'Research question', body: `This report asks: what makes ${title.toLowerCase().replace(/^.*?: /, '')} repeatable, reviewable, and safe for a small HR operations team?` },
    { heading: 'Methodology', body: 'We synthesized the ten listed primary and professional sources, screened this topic against existing Research slugs and titles, and translated the guidance into an operational control model. This is general workflow guidance, not legal advice.' },
    { heading: 'Key statistic', body: statistic },
    { heading: 'Key takeaways and data model', body: `${model} Track status, owner, source system, due date, exception category, and completion evidence as separate fields so a reviewer can test the workflow without receiving unnecessary personal data.` },
    { heading: 'Implementation checklist', body: 'Confirm the trigger and owner; use the approved system of record; restrict access by task; retain the evidence required by policy; review exceptions weekly; and document the escalation outcome.' },
    { heading: 'FAQs', body: faq },
  ],
  sources: researchRunSources,
}));

// 2026-08-10 Research run: selected target 15. Topics were screened against
// every existing Research and Blog slug before acceptance into this family-only batch.
const researchRun15Sources = [
  { name: 'NIST Cybersecurity Framework 2.0', url: 'https://www.nist.gov/cyberframework' },
  { name: 'NIST Privacy Framework', url: 'https://www.nist.gov/privacy-framework' },
  { name: 'NIST SP 800-53 Rev. 5', url: 'https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final' },
  { name: 'FTC Protecting Personal Information', url: 'https://www.ftc.gov/business-guidance/resources/protecting-personal-information-guide-business' },
  { name: 'CISA Cybersecurity Performance Goals', url: 'https://www.cisa.gov/cybersecurity-performance-goals' },
  { name: 'U.S. Department of Labor Recordkeeping', url: 'https://www.dol.gov/general/topic/workhours/recordkeeping' },
  { name: 'EEOC Recordkeeping Requirements', url: 'https://www.eeoc.gov/employers/recordkeeping-requirements' },
  { name: 'NARA Records Management', url: 'https://www.archives.gov/records-mgmt' },
  { name: 'GAO Green Book', url: 'https://www.gao.gov/green-book' },
  { name: 'SHRM HR Toolkits', url: 'https://www.shrm.org/topics-tools/tools/toolkits' },
] as const;

const researchRun15Topics = [
  ['hr-new-hire-identity-access-handoff', 'New-Hire Identity and Access Handoffs: A Reviewable Control Map', 'How HR teams can coordinate identity, equipment, and system access without losing ownership at the handoff.', 'NIST access-control guidance supports assigning access by role and reviewing it as part of the worker lifecycle.', 'Separate the hiring event, role approval, account request, provisioned access, manager confirmation, and closeout evidence.', 'Who approves access? The system or data owner, not the coordinator preparing the request.'],
  ['hr-training-completion-reconciliation', 'Training Completion Reconciliation: From Assignment to Evidence', 'A practical research model for reconciling required training without exposing unnecessary learner details.', 'OSHA and records-management guidance show why completion status needs a defined source, owner, and evidence trail.', 'Version the course, assign the audience, reconcile completion signals, route exceptions, and preserve the final report location.', 'What should be shared in a dashboard? Status, course version, and exception owner. Do not include unnecessary personal detail.'],
  ['hr-employee-master-data-change-control', 'Employee Master-Data Changes: A Controlled Request Pattern', 'A source-backed workflow for names, locations, managers, status, and other employee-record changes.', 'GAO internal-control principles support preserving request, approval, change, and reconciliation evidence.', 'Validate the source request, confirm authority, record the before-and-after fields, obtain approval, update the system of record, and reconcile downstream outputs.', 'May an administrator correct a field from memory? No. Require an approved source and preserve the correction trail.'],
  ['hr-recruiting-interview-feedback-integrity', 'Interview Feedback Integrity: Collecting Evidence Without Editing Judgment', 'How recruiting coordinators can improve scorecard completion while leaving assessment decisions with interviewers.', 'EEOC recordkeeping guidance makes consistent preservation of employment records an operational requirement for recruiting workflows.', 'Lock the scorecard version, remind owners, record missing responses, restrict access, and retain submitted content without rewriting evaluator judgment.', 'Can a coordinator normalize a scorecard comment? No. Return unclear content to its author or hiring owner.'],
  ['hr-hris-role-permission-matrix', 'HRIS Role-Permission Matrices: A Practical Review Method', 'A lightweight way to connect HR-system permissions to real tasks, owners, and review dates.', 'NIST SP 800-53 and CISA identity guidance support explicit role-to-access mappings and periodic review.', 'List each task, data class, read/edit/export/delete capability, named owner, delegated reviewer, and review date; remove access that lacks a current purpose.', 'What is the most important first step? Inventory actual access before designing the ideal role model.'],
  ['hr-employee-complaint-intake-routing', 'Employee Complaint Intake: Route Risk Before Collecting Detail', 'A privacy-conscious model for triaging complaints and getting them to the right qualified owner.', 'NIST privacy principles support purpose-limited collection; sensitive case narratives belong in an approved case system.', 'Capture only category, urgency, safety flag, owner, minimum routing facts, and timestamp in the general queue; preserve details behind the correct access boundary.', 'What must be escalated immediately? Safety threats, discrimination concerns, retaliation, harassment, and legal or investigation questions.'],
  ['hr-benefits-enrollment-document-control', 'Benefits Enrollment Document Control: Completeness Without Overcollection', 'How HR support teams can track enrollment work while keeping eligibility and advice with the qualified owner.', 'FTC privacy guidance supports limiting personal-information exposure to the purpose and safeguards actually required.', 'Track request type, plan year, required field status, source system, owner, deadline, and exception reason instead of copying full documents into a tracker.', 'Can a coordinator decide eligibility? No. They can check completeness and route questions to the benefits owner.'],
  ['hr-termination-checklist-evidence', 'Termination Checklists: Evidence, Access Closeout, and Ownership', 'A control model for coordinating offboarding tasks without making the employment decision.', 'CISA access-management guidance supports prompt lifecycle review, while records guidance supports documented closeout.', 'Separate decision authority, communication approval, access disablement, asset return, record retention, and reconciliation into named tasks.', 'Who owns the termination decision? The authorized employer representative; support staff only coordinate approved steps.'],
  ['hr-hr-metrics-definition-governance', 'HR Metrics Definition Governance: Make Reports Reproducible', 'A source-backed starter model for metrics that different reviewers can reproduce.', 'BLS methodology materials demonstrate that population, period, definitions, and exclusions must be explicit before comparisons are meaningful.', 'Version each metric’s formula, population, date window, source, refresh cadence, owner, permitted breakdowns, and caveats.', 'Can a dashboard change its definition silently? No. Version the definition and record the effective date.'],
  ['hr-manager-request-authentication', 'Manager HR Requests: Verify Authority Before Action', 'How to route manager requests safely when a request could change an employee record or reveal sensitive information.', 'NIST privacy and access-control frameworks connect data use to purpose, authority, and risk.', 'Verify requester, purpose, target record, allowed action, approval level, and system-of-record destination before preparing work.', 'What if the requester is urgent but authority is unclear? Pause and escalate; urgency does not replace authorization.'],
  ['hr-candidate-communication-approval', 'Candidate Communication Approval: Protect Consistency and Record Quality', 'A workflow for scheduling and routine follow-up that keeps hiring decisions and sensitive messages with the hiring owner.', 'EEOC recordkeeping resources support retaining employment communications and consistent process evidence.', 'Use approved templates, record the role and stage, route exceptions, preserve the sent version, and keep selection decisions outside the coordination lane.', 'May a coordinator improvise rejection or offer language? No. Use approved copy or escalate for review.'],
  ['hr-hr-calendar-deadline-exceptions', 'HR Calendar Deadline Exceptions: Keep Misses Visible', 'A practical method for tracking recurring HR deadlines and escalating exceptions instead of hiding them.', 'NARA records-management principles support reliable evidence of what was due, who owned it, and what happened next.', 'Record deadline, source, owner, dependency, reminder history, exception reason, revised date, and approval for any changed commitment.', 'Should a missed deadline be silently moved? No. Preserve the original date and document the authorized change.'],
  ['hr-employee-file-duplicate-prevention', 'Employee File Duplicate Prevention: A Quality-Control Pattern', 'How to reduce duplicate records and conflicting versions in employee-file administration.', 'NIST privacy and records guidance support maintaining a defined system of record and limiting unnecessary copies.', 'Check identity keys, document type, effective date, version, source, and destination before filing; route ambiguity instead of guessing.', 'Can the newest-looking file replace the old one automatically? No. Confirm the authoritative version and retention rule first.'],
  ['hr-policy-change-communication-tracking', 'Policy Change Communication Tracking: Version, Audience, Evidence', 'A workflow for showing which employees received the right policy version and what remains unresolved.', 'NIST governance principles support named ownership, effective dates, and review evidence for controlled information.', 'Record policy version, effective date, audience, delivery channel, acknowledgment signal, exception owner, and closeout date.', 'What proves communication? The approved delivery or acknowledgment record tied to the correct version.'],
  ['hr-people-ops-month-end-close', 'People-Ops Month-End Close: Reconcile Before Reporting', 'A source-backed close process for HR operations data, open tasks, and recurring reports.', 'GAO internal-control guidance supports reconciliations, review evidence, and clear responsibility for corrections.', 'Freeze the reporting window, reconcile starters and leavers, check open exceptions, confirm source freshness, obtain owner signoff, and archive the close record.', 'Can unresolved exceptions be omitted from the report? No. Show the exception, owner, impact, and next action.'],
] as const;

// Keep the repair date on each accepted source record, rather than deriving it
// from the batch or the introducing commit timestamp.
const researchRun15SourceDates: Record<string, '2026-08-10'> = {
  'hr-new-hire-identity-access-handoff': '2026-08-10',
  'hr-training-completion-reconciliation': '2026-08-10',
  'hr-employee-master-data-change-control': '2026-08-10',
  'hr-recruiting-interview-feedback-integrity': '2026-08-10',
  'hr-hris-role-permission-matrix': '2026-08-10',
  'hr-employee-complaint-intake-routing': '2026-08-10',
  'hr-benefits-enrollment-document-control': '2026-08-10',
  'hr-termination-checklist-evidence': '2026-08-10',
  'hr-hr-metrics-definition-governance': '2026-08-10',
  'hr-manager-request-authentication': '2026-08-10',
  'hr-candidate-communication-approval': '2026-08-10',
  'hr-hr-calendar-deadline-exceptions': '2026-08-10',
  'hr-employee-file-duplicate-prevention': '2026-08-10',
  'hr-policy-change-communication-tracking': '2026-08-10',
  'hr-people-ops-month-end-close': '2026-08-10',
};

export const researchRun15Posts: readonly ResearchPost[] = researchRun15Topics.map(([slug, title, excerpt, statistic, model, faq]) => ({
  slug, title, excerpt, published: researchRun15SourceDates[slug], thumbnail: `/research-banners/${slug}.svg`,
  sections: [
    { heading: 'Research question', body: `This report asks how ${title.toLowerCase().replace(/^.*?: /, '')} can remain repeatable, reviewable, and properly owned by a small HR operations team.` },
    { heading: 'Methodology', body: 'We synthesized the ten listed authoritative and professional sources, screened this topic against existing Research and Blog slugs, and translated the guidance into an operational control model. This is general workflow guidance, not legal advice.' },
    { heading: 'Key statistic', body: statistic },
    { heading: 'Key takeaways and data model', body: `${model} Track status, owner, source system, due date, exception category, and completion evidence as separate fields so a reviewer can test the workflow without receiving unnecessary personal data.` },
    { heading: 'Implementation checklist', body: 'Confirm the trigger and owner; use the approved system of record; restrict access by task; retain the evidence required by policy; review exceptions weekly; and document the escalation outcome.' },
    { heading: 'FAQs', body: faq },
  ],
  sources: researchRun15Sources,
}));

const frozenResearchOrder = [
  'hr-benefits-enrollment-document-control',
  'hr-candidate-communication-approval',
  'hr-employee-complaint-intake-routing',
  'hr-employee-file-duplicate-prevention',
  'hr-employee-master-data-change-control',
  'hr-hr-calendar-deadline-exceptions',
  'hr-hr-metrics-definition-governance',
  'hr-hris-role-permission-matrix',
  'hr-manager-request-authentication',
  'hr-new-hire-identity-access-handoff',
  'hr-people-ops-month-end-close',
  'hr-policy-change-communication-tracking',
  'hr-recruiting-interview-feedback-integrity',
  'hr-termination-checklist-evidence',
  'hr-training-completion-reconciliation',
] as const;
const orderedResearchRun15Posts = frozenResearchOrder
  .map(slug => researchRun15Posts.find(post => post.slug === slug))
  .filter((post): post is ResearchPost => Boolean(post));

// 2026-08-11 Research batch: each record owns its literal publication date.
const august11ResearchSources = [
  { name: 'NIST Cybersecurity Framework 2.0', url: 'https://www.nist.gov/cyberframework' },
  { name: 'NIST Privacy Framework', url: 'https://www.nist.gov/privacy-framework' },
  { name: 'NIST SP 800-53 Rev. 5', url: 'https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final' },
  { name: 'FTC Protecting Personal Information', url: 'https://www.ftc.gov/business-guidance/resources/protecting-personal-information-guide-business' },
  { name: 'CISA Cybersecurity Performance Goals', url: 'https://www.cisa.gov/cybersecurity-performance-goals' },
  { name: 'U.S. Department of Labor Recordkeeping', url: 'https://www.dol.gov/general/topic/workhours/recordkeeping' },
  { name: 'EEOC Recordkeeping Requirements', url: 'https://www.eeoc.gov/employers/recordkeeping-requirements' },
  { name: 'NARA Records Management', url: 'https://www.archives.gov/records-mgmt' },
  { name: 'GAO Green Book', url: 'https://www.gao.gov/green-book' },
  { name: 'SHRM HR Toolkits', url: 'https://www.shrm.org/topics-tools/tools/toolkits' },
] as const;

const august11ResearchPosts: readonly ResearchPost[] = [
  { slug: 'hr-employee-data-retention-review', title: 'Employee Data Retention Reviews: Align Records With Purpose', excerpt: 'A source-backed way for HR teams to review retention needs without keeping every copy forever.', published: '2026-08-12', sections: [{ heading: 'Research question', body: 'How can a small HR team decide which records to retain, where to keep them, and when to review them? The answer starts with purpose, record category, owner, and the applicable retention rule.' }, { heading: 'Evidence and model', body: 'Records guidance and privacy frameworks point to a documented inventory, defined owner, access boundary, review date, and disposition evidence. A support role can prepare the inventory, while the HR or legal owner approves the rule.' }, { heading: 'Operational implication', body: 'Separate the authoritative record from working copies. Log the record class, system of record, trigger date, review date, and exception owner; never infer a disposal date from file age alone.' }], sources: august11ResearchSources },
  { slug: 'hr-employee-status-change-reconciliation', title: 'Employee Status Changes: Reconcile the Record Across Systems', excerpt: 'How to reduce downstream HR errors when a status, manager, location, or work arrangement changes.', published: '2026-08-12', sections: [{ heading: 'Research question', body: 'What makes an employee-status change reliable after the request is approved? The change must have an authoritative source, a named approver, a controlled update, and a reconciliation across dependent systems.' }, { heading: 'Evidence and model', body: 'Internal-control guidance supports recording the request, approval, effective date, changed fields, system update, and post-change check. The administrator prepares and reconciles; the authorized owner decides whether the change is valid.' }, { heading: 'Operational implication', body: 'Use a change register that distinguishes requested, approved, applied, and reconciled. Keep rejected or superseded requests visible so later reviewers can explain the final state.' }], sources: august11ResearchSources },
  { slug: 'hr-employee-request-response-evidence', title: 'Employee Request Response Evidence: Measure Accuracy With Context', excerpt: 'A practical research model for reviewing HR request handling without rewarding unsafe speed.', published: '2026-08-12', sections: [{ heading: 'Research question', body: 'Which evidence shows that an HR request was handled well? Response time matters, but it must be read alongside accuracy, privacy handling, escalation quality, and whether the request was actually resolved.' }, { heading: 'Evidence and model', body: 'Privacy and records guidance support a minimum dataset: category, received time, owner, approved source, response status, escalation reason, and closure evidence. Keep personal narratives out of aggregate reporting.' }, { heading: 'Operational implication', body: 'Review a sample by risk category, not only by speed. A fast response that gives an unauthorized answer should count as a control failure and route to owner review.' }], sources: august11ResearchSources },
  { slug: 'hr-recruiting-records-retention-map', title: 'Recruiting Records Retention: Map the Evidence Before the Role Closes', excerpt: 'A source-backed framework for keeping recruiting records findable, consistent, and appropriately limited.', published: '2026-08-12', sections: [{ heading: 'Research question', body: 'How should a recruiting team preserve process evidence without collecting unnecessary candidate information? Define the hiring event, record category, owner, access group, and retention trigger.' }, { heading: 'Evidence and model', body: 'Employment-record guidance makes consistent preservation important, while privacy principles require purpose-limited access. Keep the approved role, stage history, scorecards, communications, and disposition evidence in defined locations.' }, { heading: 'Operational implication', body: 'A coordinator can check completeness and link records to the correct requisition. They should not rewrite interviewer judgment, infer a selection decision, or move sensitive material into a general tracker.' }], sources: august11ResearchSources },
  { slug: 'hr-policy-acknowledgment-exception-review', title: 'Policy Acknowledgment Exceptions: Make the Unresolved Work Visible', excerpt: 'How HR teams can distinguish delivery, acknowledgment, refusal, and exception states.', published: '2026-08-12', sections: [{ heading: 'Research question', body: 'What does a reliable policy acknowledgment record need to show? It should identify the approved version, audience, delivery event, acknowledgment signal, exception owner, and next review date.' }, { heading: 'Evidence and model', body: 'Governance and records guidance support version control and evidence of communication. A status of pending is not the same as refused, failed delivery, or an approved exception.' }, { heading: 'Operational implication', body: 'Keep the original delivery and acknowledgment events. Route missing or disputed acknowledgments to the policy owner instead of repeatedly sending untracked reminders or changing the status by assumption.' }], sources: august11ResearchSources },
  { slug: 'hr-manager-approval-delegation-review', title: 'Manager Approval Delegation: Review Authority Before It Expires', excerpt: 'A control model for temporary HR approval delegation, with clear scope and closeout evidence.', published: '2026-08-12', sections: [{ heading: 'Research question', body: 'When can a delegated manager approval be trusted? The delegation needs a named delegator, delegate, scope, start and end dates, affected workflow, and a recorded closeout.' }, { heading: 'Evidence and model', body: 'Access-control and internal-control guidance support least privilege, explicit authorization, and periodic review. A coordinator may maintain the register, but cannot broaden its scope or extend it without the authorized owner.' }, { heading: 'Operational implication', body: 'Check delegation status at the point of action, not only when the delegation is created. Preserve superseded entries so a reviewer can distinguish a valid approval from an expired one.' }], sources: august11ResearchSources },
  { slug: 'hr-onboarding-document-completeness-review', title: 'Onboarding Document Completeness: Check Fields Without Becoming the Approver', excerpt: 'A source-backed method for finding missing onboarding information while protecting decision ownership.', published: '2026-08-12', sections: [{ heading: 'Research question', body: 'Which checks improve onboarding completeness without turning administration into eligibility or legal judgment? Check required fields, source, due date, owner, and approved destination.' }, { heading: 'Evidence and model', body: 'Employment and privacy guidance support collecting only what the process requires and keeping sensitive documents in approved systems. Completion status is useful evidence; a copied document is not always necessary.' }, { heading: 'Operational implication', body: 'Separate missing-field follow-up from questions about eligibility, accommodation, or policy interpretation. Those exceptions belong with the qualified HR owner.' }], sources: august11ResearchSources },
  { slug: 'hr-hris-audit-log-review', title: 'HRIS Audit-Log Reviews: Turn System Events Into Owner-Ready Evidence', excerpt: 'How to review HRIS changes for unexpected activity, missing approvals, and unresolved exceptions.', published: '2026-08-12', sections: [{ heading: 'Research question', body: 'What makes an HRIS audit-log review useful to an HR owner? It should connect an event to a user, record, field, timestamp, reason, approval, and expected outcome.' }, { heading: 'Evidence and model', body: 'Security frameworks treat logging and review as governance signals. Filter routine noise, preserve the original event, classify anomalies, and route any unexplained change to the system or data owner.' }, { heading: 'Operational implication', body: 'Do not edit logs to make a report cleaner. Produce a separate review record with the query window, reviewer, sampled events, exceptions, and escalation result.' }], sources: august11ResearchSources },
  { slug: 'hr-employee-file-access-exception-review', title: 'Employee-File Access Exceptions: Review the Why, Not Just the Who', excerpt: 'A practical research approach to investigating unusual access without expanding exposure.', published: '2026-08-12', sections: [{ heading: 'Research question', body: 'How should HR investigate an unusual employee-file access event? Start with purpose, role, record category, time, approved task, and the minimum evidence needed to explain the event.' }, { heading: 'Evidence and model', body: 'Privacy and access-control guidance support reviewing access against a defined business need. The reviewer should work from metadata and approved logs before opening sensitive content.' }, { heading: 'Operational implication', body: 'Route unclear or high-risk events to security or the HR owner. A support administrator can assemble the evidence packet but should not decide whether an exception is acceptable.' }], sources: august11ResearchSources },
  { slug: 'hr-people-ops-reporting-close-controls', title: 'People-Ops Reporting Close: Freeze Definitions Before Comparing Results', excerpt: 'A research model for closing recurring HR reports with stable definitions and visible exceptions.', published: '2026-08-12', sections: [{ heading: 'Research question', body: 'Why do recurring HR reports drift even when the spreadsheet formula appears unchanged? Population, effective dates, source freshness, exclusions, and definitions can change silently.' }, { heading: 'Evidence and model', body: 'Measurement methodology and internal-control guidance support versioned definitions, a fixed reporting window, source checks, reconciliation, and owner signoff. Document the reason for any restatement.' }, { heading: 'Operational implication', body: 'Close the reporting window before explaining trends. Show unresolved exceptions rather than excluding them, and keep the metric definition alongside the report so another reviewer can reproduce it.' }], sources: august11ResearchSources },
] as const;

export const allResearchPosts: readonly ResearchPost[] = [...august31ResearchPosts, ...august23ResearchPosts, ...august21AiTransparencyPosts, ...august21CrossCulturalPosts, ...august21DataPrivacyPosts, ...august21KnowledgeRetentionPosts, ...august21ProductivityPosts, ...august21NewResearchPosts, ...august21ResearchPosts, ...august21StatusPosts, ...august21RetentionPosts, ...august21ApprovalPosts, ...august21PortalPosts, ...august19ResearchPosts, ...august18ResearchPosts, ...august17ResearchPosts, ...august14ResearchPosts, ...august13ResearchPosts, ...august11ResearchPosts, ...researchPosts, ...researchBatchPosts, ...orderedResearchRun15Posts]
  .toSorted((a, b) => b.published.localeCompare(a.published));
export const postsPerPage = 20;

import { august21AiTransparencyPosts } from './research/august21-ai-transparency-virtual-assistant-performance';
import { august21CrossCulturalPosts } from './research/august21-cross-cultural-communication-distributed-teams';
import { august21DataPrivacyPosts } from './research/august21-data-privacy-virtual-assistant-platforms';
import { august21KnowledgeRetentionPosts } from './research/august21-knowledge-retention-va-client-transitions';
import { august21ProductivityPosts } from './research/august21-productivity-metrics-remote-admin-support';
