export type FleetService = { slug: string; title: string; desc: string; tasks: readonly string[]; controls: readonly string[]; firstWeek: readonly string[] };
export type ResearchPost = { slug: string; title: string; excerpt: string; published: string; sections: readonly { heading: string; body: string }[]; sources?: readonly { name: string; url: string }[] };

export const fleetServices: readonly FleetService[] = [
  { slug: 'candidate-sourcing', title: 'Candidate Sourcing', desc: 'Build a Philippines-based candidate sourcing workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring human resources work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'interview-coordination', title: 'Interview Coordination', desc: 'Build a Philippines-based interview coordination workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring human resources work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'employee-records-administration', title: 'Employee Records Administration', desc: 'Build a Philippines-based employee records administration workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring human resources work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'benefits-administration-support', title: 'Benefits Administration Support', desc: 'Build a Philippines-based benefits administration support workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring human resources work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'payroll-preparation-support', title: 'Payroll Preparation Support', desc: 'Build a Philippines-based payroll preparation support workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring human resources work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'onboarding-coordination', title: 'Onboarding Coordination', desc: 'Build a Philippines-based onboarding coordination workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring human resources work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'learning-administration', title: 'Learning Administration', desc: 'Build a Philippines-based learning administration workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring human resources work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'hr-help-desk-support', title: 'HR Help Desk Support', desc: 'Build a Philippines-based hr help desk support workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring human resources work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'performance-review-administration', title: 'Performance Review Administration', desc: 'Build a Philippines-based performance review administration workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring human resources work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'offboarding-coordination', title: 'Offboarding Coordination', desc: 'Build a Philippines-based offboarding coordination workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring human resources work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] }
];

// Add reviewed, source-backed original research here. The templates and sitemap update automatically.
export const researchPosts: readonly ResearchPost[] = [];
export const postsPerPage = 20;
