import type { ResearchPost } from '../fleet-data';

const sources = [
  { name: 'NIST Cybersecurity Framework 2.0', url: 'https://www.nist.gov/cyberframework' },
  { name: 'NIST Privacy Framework', url: 'https://www.nist.gov/privacy-framework' },
  { name: 'NIST SP 800-53 Rev. 5', url: 'https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final' },
  { name: 'FTC Protecting Personal Information', url: 'https://www.ftc.gov/business-guidance/resources/protecting-personal-information-guide-business' },
  { name: 'CISA Cybersecurity Performance Goals', url: 'https://www.cisa.gov/cybersecurity-performance-goals' },
  { name: 'U.S. Department of Labor Recordkeeping', url: 'https://www.dol.gov/general/topic/workhours/recordkeeping' },
  { name: 'EEOC Recordkeeping Requirements', url: 'https://www.eeoc.gov/employers/recordkeeping-requirements' },
  { name: 'NARA Records Management', url: 'https://www.archives.gov/records-mgmt' },
  { name: 'GAO Green Book', url: 'https://www.gao.gov/green-book' },
] as const;

type Topic = { slug: string; title: string; excerpt: string; question: string; setting: string; evidence: string; finding: string; model: string; limits: string; conclusion: string };

const topics: readonly Topic[] = [
  { slug: 'hr-benefits-eligibility-event-reconciliation', title: 'Benefits Eligibility: Reconcile Events Before Asking a Plan Owner to Decide', excerpt: 'A research model for separating employment events, eligibility evidence, enrollment activity, and plan-owner decisions.', question: 'What evidence lets an HR support team explain a benefits eligibility discrepancy without deciding eligibility itself?', setting: 'A hire, status change, leave, or termination can affect several benefit workflows at different effective dates. A support coordinator may see a human-resources record, a vendor file, and an employee question that do not agree. Treating the newest value as authoritative can create a confident but unsupported answer.', evidence: 'NIST privacy principles support purpose-limited handling of sensitive information; GAO control principles support authorization and reconciliation; NARA principles support preserving versions and effective dates. DOL and EEOC recordkeeping resources show why employment records need context. These sources support an evidence trail, not one universal benefits rule.', finding: 'The useful comparison is between the approved employment event, the applicable plan or policy version, the transmitted enrollment state, and the vendor acknowledgment. Separate missing evidence, timing difference, rejected transaction, duplicate submission, and owner decision. A current enrollment display is not proof that eligibility was correctly determined.', model: 'Record worker token, event type, event date, effective date, plan or policy version, source system, submission state, vendor response, question owner, access class, and exception reason. The support lane can compare defined fields, request an approved missing item, and route an exception. The plan or HR owner decides eligibility, coverage, correction, and employee communication.', limits: 'Plan documents, jurisdiction, employment status, collective arrangements, vendor rules, and effective dates vary. This model does not determine eligibility, coverage, tax treatment, or a remedy.', conclusion: 'An event-based reconciliation gives the authorized benefits owner a defensible packet while keeping administrative support from turning a data mismatch into a benefits ruling.' },
  { slug: 'hr-employee-leave-request-state-integrity', title: 'Leave Requests: Preserve the Difference Between Request, Approval, and Balance', excerpt: 'Research on leave administration records that keeps employee requests, approvals, accruals, and payroll consequences distinct.', question: 'How should HR administration represent a leave request when request status, manager approval, balance, and payroll treatment are separate facts?', setting: 'Leave work becomes difficult when a single screen uses “approved” to describe a manager response, an HR eligibility check, a system balance, and a payroll result. Those events may happen at different times. An outsourced coordinator can keep the states visible, but should not infer entitlement from a calendar entry.', evidence: 'DOL recordkeeping materials make hours and employment records material in covered contexts. GAO controls support documented authorization and reconciliation, while NIST privacy guidance supports limiting health or personal detail. NARA guidance supports retaining the original request and later versions. None of these sources decides an employer’s leave policy.', finding: 'Report request received, information complete, manager response, HR or policy review, balance impact, payroll transmission, and cancellation separately. Reconcile the approved absence against the accrual or balance snapshot for the relevant effective date. A balance is an output that may lag an event, not the whole entitlement record.', model: 'Use request identifier, leave category, requested dates, receipt time, policy version, approval state, balance source and timestamp, payroll state, correction history, restricted detail link, and owner. Support can check required fields and reconcile approved events; HR, payroll, or the policy owner decides entitlement, exceptions, and communications.', limits: 'Leave rules differ by jurisdiction, policy, plan, collective agreement, system configuration, and individual facts. The article does not determine protected leave, pay, carryover, forfeiture, or approval.', conclusion: 'A state-based leave record explains what happened without collapsing a request into an entitlement decision. That distinction is the useful control for recurring HR support.' },
  { slug: 'hr-recruiting-scorecard-version-control', title: 'Recruiting Scorecards: Study Version Drift Before Comparing Interview Results', excerpt: 'A bounded research approach to scorecard governance that protects the difference between process evidence and selection judgment.', question: 'What must a recruiting record show before an HR team compares interview feedback across candidates or roles?', setting: 'Interview scorecards often change while a requisition is open. A question may be clarified, a rating scale may be renamed, or one interviewer may use a private document. Comparing scores without version and stage context makes a number look more consistent than the underlying process.', evidence: 'EEOC recordkeeping guidance supports preserving employment-process records. NIST privacy guidance supports limiting candidate information to purpose and access. GAO controls support approved versions, accountable review, and exceptions. These sources support provenance; they do not establish that a score is valid, unbiased, or predictive.', finding: 'Before comparing feedback, identify requisition, stage, scorecard version, interviewer role, completion time, missing fields, and whether comments were edited after submission. Treat calibration, reviewer disagreement, and late changes as process evidence. Never convert an administrative completeness check into a candidate ranking or rewrite an interviewer’s judgment.', model: 'Maintain a version register with owner, approval date, effective stage, question set, rating definitions, and retirement date. Link each submitted scorecard to its version and preserve corrections as events. A coordinator can monitor completion and flag drift; recruiters and hiring managers interpret evidence and make selection decisions.', limits: 'Selection law, role requirements, accommodations, interviewer training, and local practice vary. Scorecard records cannot prove fairness, job-relatedness, or candidate quality.', conclusion: 'Versioned scorecards make comparison more honest because they reveal whether the inputs were actually comparable. Administrative support can protect that evidence while selection authority remains with the qualified hiring owner.' },
  { slug: 'hr-employee-master-data-effective-dates', title: 'Employee Master Data: Use Effective Dates to Explain Conflicting HR Records', excerpt: 'A research model for reconciling employee master data without overwriting history or treating every field as universally current.', question: 'When HR systems disagree about an employee attribute, which dates and purposes determine whether the values are actually conflicting?', setting: 'Manager, work arrangement, address purpose, cost center, status, and title changes can have request dates, approval dates, entry dates, and effective dates. A downstream system may be correct for its own period while a current HR profile shows a later event. Replacing one value with another hides that chronology.', evidence: 'NIST privacy guidance supports purpose-specific data use and limited access. GAO control concepts support reconciliation and review. NARA principles support authentic records and version history, while DOL and EEOC resources show why employment records require context. The evidence does not supply a universal system-of-record rule.', finding: 'A reconciliation should compare field meaning, source authority, effective period, entry timestamp, and downstream purpose. Classify differences as timing, purpose, stale synchronization, duplicate, or unresolved authority. “Latest entered” and “currently displayed” are not interchangeable. Preserve the prior value and the approved change reference.', model: 'Define a field dictionary naming source, purpose, allowed states, effective-date rule, approver, downstream consumers, and correction method. Support can prepare a discrepancy report and confirm propagation. The HR, payroll, manager, benefits, tax, or security owner decides which value applies to its process.', limits: 'Data definitions, systems, policy, tax treatment, and jurisdiction differ. This method cannot determine residency, work authorization, classification, or the correctness of an employment decision.', conclusion: 'Effective-date reasoning turns a confusing data conflict into a bounded question for the right owner. It improves HR administration without pretending one profile field answers every downstream need.' },
  { slug: 'hr-employee-relations-intake-privacy-minimization', title: 'Employee-Relations Intake: Measure Routing Without Repeating Sensitive Narratives', excerpt: 'Research on preserving intake provenance while limiting unnecessary exposure in an HR support queue.', question: 'What minimum administrative evidence shows that an employee-relations concern was received and routed without copying its sensitive narrative into routine tracking?', setting: 'An intake message may include allegations, health information, safety concerns, or names of other employees. A general queue needs enough context to assign an owner and monitor acknowledgment, but copying the narrative into several tools increases exposure and can make an allegation look like a finding.', evidence: 'EEOC employer resources establish the sensitivity of workplace concerns. NIST privacy principles support data minimization and access by purpose; NARA supports authentic, retrievable records; GAO supports named responsibility and review. Together they support a restricted case record plus a minimal routing index, not a universal investigation procedure.', finding: 'Measure receipt, protected case identifier, routing category, urgency signal, authorized owner, acknowledgment, transfer history, and next checkpoint. Keep the narrative in the approved restricted repository. Receipt, triage, investigation, substantiation, and closure are distinct states. None can be inferred from a fast acknowledgment.', model: 'Use a non-sensitive category, received timestamp, access group, owner, acknowledgment, checkpoint, transfer reason, and closure authority in the operational index. Support can route defined facts and reconcile acknowledgments. HR, legal, safety, or investigation owners decide scope, credibility, findings, and communications.', limits: 'Law, privilege, safety duties, collective arrangements, and individual facts vary. This framework cannot assess credibility, retaliation, discrimination, harassment, or legal reporting obligations.', conclusion: 'A minimal routing index protects provenance and privacy at the same time. It gives the responsible owner a clean handoff without asking administrative support to characterize the underlying concern.' },
  { slug: 'hr-hris-integration-reconciliation-failures', title: 'HRIS Integrations: Investigate Failed Handoffs Before Replaying Records', excerpt: 'A source-backed research method for finding integration failures while preserving approved source events and owner boundaries.', question: 'How can an HR operations team distinguish a failed integration from a late, rejected, duplicated, or intentionally excluded HR event?', setting: 'Automated HR handoffs can fail quietly: a status update may be accepted by one system, rejected by another, or delivered twice after a retry. Replaying the same record without understanding its identifier and effective date can create duplicate or contradictory changes.', evidence: 'NIST security guidance supports logging, controlled access, and accountable system activity. GAO supports reconciliation and exception review; NARA supports retaining source and transaction history; FTC guidance supports protecting personal data in operational systems. These principles support diagnosis, not an assumption that every error should be replayed.', finding: 'Compare source event ID, payload version, sent time, acknowledgment, target state, retry history, and exclusion rule. Separate transport failure, validation rejection, duplicate, stale event, mapping defect, and owner-approved suppression. A green queue can hide a mismatch if it reports delivery rather than target-state reconciliation.', model: 'Create a reconciliation table with source system, event identifier, effective date, target system, expected state, observed state, response code, retry count, owner, and protected evidence link. Support can identify mismatches and route a replay proposal; system or HR owners authorize correction and test downstream impact.', limits: 'Integrations, vendor contracts, data schemas, access rights, and correction rules differ. This research does not prescribe a replay, rollback, or data repair.', conclusion: 'Event identity and target-state evidence prevent an integration retry from becoming an unreviewed data change. The support lane can surface the failure; the system owner approves the repair.' },
  { slug: 'hr-training-assignment-population-drift', title: 'Required Training: Detect Population Drift Before Calling Completion a Rate', excerpt: 'A research model for reconciling training assignments, audience definitions, completion signals, and evidence scope.', question: 'What does a training completion percentage mean when the assigned population or course version changed during the reporting period?', setting: 'Training dashboards often combine employees assigned by role, location, start date, or manual exception. A course can be replaced while old assignments remain open. Without a frozen audience and version, a completion rate may measure population drift rather than learning administration.', evidence: 'EEOC and DOL materials show that some training and employment records require careful context. NIST privacy guidance supports limiting learner detail; GAO supports defined populations and review; NARA supports versioned records. These sources do not prove competence from a completion timestamp.', finding: 'Declare the assignment rule, course version, effective period, denominator, exclusions, and completion signal. Separate assigned, delivered, started, completed, expired, exempted, failed, and superseded states. Report reassignment and late corrections. Completion is evidence of a recorded event, not evidence that a learner understood or can perform the task.', model: 'Record course identifier and version, assignment rule, population snapshot date, worker token, due date, completion source, score where authorized, exception reason, reviewer, and retention location. Support can reconcile LMS exports and route anomalies. The policy or learning owner decides requirement, exemption, competence, and corrective action.', limits: 'Training requirements, assessment quality, privacy, accessibility, and policy differ. This model does not determine whether a person is qualified or whether a course satisfies a legal duty.', conclusion: 'A stable audience and version make a completion measure interpretable. Administrative support can make the evidence coherent while learning and policy owners retain judgment about meaning.' },
  { slug: 'hr-offboarding-knowledge-transfer-evidence', title: 'Offboarding Knowledge Transfer: Verify Handoffs Without Ranking the Departing Employee', excerpt: 'Research on documenting transfer scope, recipient acknowledgment, and unresolved work during HR-coordinated offboarding.', question: 'Which evidence shows that important work was handed to a new owner without turning a transfer record into a judgment about the departing employee?', setting: 'Offboarding may include open HR cases, recruiting tasks, recurring reports, vendor contacts, and confidential records. A handoff list can show what was named and received, but it cannot establish work quality, cause of departure, or whether the recipient is ready to own every decision.', evidence: 'NARA supports retrievable records and version history; NIST supports least-necessary access; GAO supports ownership and review; CISA supports access governance around account changes. These sources support a controlled transition record, not an employment assessment.', finding: 'Distinguish inventory, transfer prepared, recipient acknowledged, access changed, work accepted, exception opened, and closure reviewed. Keep sensitive case detail in its system of record. A recipient’s acknowledgment proves receipt of a handoff, not agreement with every historical decision or competence to resolve it.', model: 'Track work item identifier, purpose, current owner, receiving owner, sensitivity class, last verified status, source link, transfer date, acknowledgment, unresolved question, access action, and closure reviewer. Support can assemble and reconcile the inventory. HR, managers, security, legal, or process owners decide access, retention, and substantive continuity.', limits: 'Employment facts, confidentiality, system access, retention, and role authority vary. The model cannot decide liability, performance, misconduct, or whether a handoff is legally sufficient.', conclusion: 'A bounded transfer record protects continuity and access without converting administrative evidence into a verdict about a person. That is the right research boundary for outsourced offboarding coordination.' },
  { slug: 'hr-employee-document-correction-provenance', title: 'Employee-Record Corrections: Preserve Provenance When a Field Changes', excerpt: 'A research approach to correction requests that keeps original values, authority, effective dates, and downstream impact visible.', question: 'What makes an employee-record correction explainable after the new value has been entered?', setting: 'Corrections are often treated as cleanup, but a changed name, date, status, pay input, or address can affect several dependent processes. If the original value disappears, a later reviewer cannot tell whether the change was authorized, when it took effect, or which systems received it.', evidence: 'NARA records principles support authenticity and version history. NIST privacy guidance supports limiting copied personal information; GAO supports authorization and reconciliation; DOL and EEOC resources support context around employment records. These sources support traceability, not a decision about which value is legally correct.', finding: 'A correction record should show original value or protected reference, requested value, source, reason category, requester identity signal, approval, effective date, entry date, downstream consumers, and reconciliation result. Separate typographical correction, source update, policy change, and disputed record. Do not use a later timestamp to erase an earlier event.', model: 'Use an append-only change history where practical, with field name, old-state reference, new-state reference, actor, approval, effective date, system update, and exception owner. Support can check completeness and propagate an approved correction. The HR, payroll, legal, benefits, or data owner decides disputed facts and scope.', limits: 'Correction rights, retention, system capability, privacy, and employment law vary. This article does not resolve identity disputes, tax effects, eligibility, or legal record requirements.', conclusion: 'Provenance makes a correction reviewable without keeping broad copies of sensitive data. The administrative role is to preserve the chain and route judgment to the owner.' },
  { slug: 'hr-month-end-headcount-definition-reconciliation', title: 'Month-End Headcount: Freeze the Definition Before Explaining the Trend', excerpt: 'A research model for reconciling headcount reports when effective dates, worker populations, and system snapshots differ.', question: 'Why can two accurate HR reports show different month-end headcount, and what evidence lets an owner explain the difference?', setting: 'Headcount depends on who is included, which effective date applies, whether contingent workers are counted, and when a system snapshot was taken. A report can be internally consistent yet incomparable with another report using a different population or date rule. The danger is explaining a numerical difference as a workforce event before checking the definition.', evidence: 'GAO control principles support defined inputs, reconciliations, and review. NIST privacy guidance supports aggregating only what is needed. NARA supports preserving report versions and source context; DOL and EEOC resources demonstrate that worker records have different purposes. Sources inform measurement discipline, not one mandatory headcount definition.', finding: 'Freeze the population rule, as-of timestamp, worker categories, effective-date treatment, source systems, exclusions, and restatement policy before comparing periods. Reconcile starters, leavers, transfers, duplicates, leaves, and late entries separately. Show unresolved exceptions rather than silently excluding them. A trend is a calculation about a defined population, not a self-explanatory business story.', model: 'Store metric definition, query date, source snapshots, population filters, numerator and denominator, exception list, reviewer, signoff, and version. Support can run an approved query and reconcile source counts. HR or finance owners interpret the trend and decide whether a restatement or communication is warranted.', limits: 'Definitions, worker categories, snapshot timing, systems, and reporting purposes vary. This model cannot infer attrition, organizational health, or causal workforce change from a count.', conclusion: 'A frozen definition makes headcount differences explainable and prevents administrative reporting from overstating what a number proves. The owner gets a stable evidence base for interpretation.' },
];

const shared = (t: Topic): ResearchPost['sections'] => [
  { heading: 'Research question', body: `${t.question} This report treats one dated event or record state as the unit of analysis. It distinguishes what a system recorded from what an authorized owner may conclude about a person, policy, or employment outcome.` },
  { heading: 'Methodology and evidence scope', body: `We compared the listed public sources on privacy, access, records, security, and internal controls, then mapped their principles to recurring outsourced HR administration. The sources are authoritative for their own subjects, but they do not create one universal process. We use them to identify evidence, ownership, versioning, and limitations. The analysis is general information, not legal, tax, clinical, payroll, benefits, or employment advice.` },
  { heading: 'Niche operating context', body: t.setting },
  { heading: 'What the evidence supports', body: t.evidence },
  { heading: 'Finding', body: t.finding },
  { heading: 'Record design', body: `${t.model} Keep operational metadata separate from restricted detail. Name the authoritative source, the event timestamp, the effective timestamp, the reviewer, and the exception owner. When sources disagree, show the disagreement and route it; do not fill the gap from memory or from the newest-looking field.` },
  { heading: 'Measurement and review', body: `Freeze the population, observation period, source version, denominator, and exclusion rules before calculating a measure. Report counts beside percentages and split ordinary, late, rejected, disputed, corrected, superseded, and owner-dependent states. Sample routine and exceptional cases. Preserve the query or export used, the reviewer, and any restatement. A clean queue can still hide rework, unauthorized access, or unresolved judgment, so review those signals separately. The goal is a reproducible process finding, not a flattering score.` },
  { heading: 'Role boundary', body: `An outsourced HR administrator may gather defined inputs, check completeness, reconcile approved sources, maintain a register, send an approved reminder, prepare a draft, and return an exception with evidence. The role should not infer eligibility, interpret a policy, select a candidate, approve pay or leave, investigate a complaint, decide an accommodation, or broaden access. The client-side HR, manager, payroll, benefits, legal, security, finance, or policy owner retains consequential judgment and accountability.` },
  { heading: 'Failure modes and safeguards', body: `Common failures include treating a message as authority, treating a delivery event as acceptance, overwriting original values, combining unlike populations, copying sensitive narratives into convenience trackers, and closing work because a deadline moved. Use explicit states and preserve rejected or superseded events. Test a normal case, a late case, a correction, a dispute, and a withdrawn request. When authority or evidence is missing, pending review is the accurate state. Give the next owner the minimum necessary context and a protected path to the source.` },
  { heading: 'Limitations', body: `${t.limits} Results also depend on source quality, system clocks, integration completeness, reviewer consistency, and the employer’s approved access boundary. Administrative evidence describes a process state; it does not prove complete legal compliance, employee agreement, competence, or a favorable outcome.` },
  { heading: 'Evidence-led conclusion', body: `${t.conclusion} The practical test is whether another reviewer can reconstruct the event without guessing what a status meant, which source controlled, or who was authorized to decide.` },
  { heading: 'FAQs', body: 'Who owns the decision? The authorized employer-side owner for the relevant domain. What can support do? Gather defined inputs, check completeness, reconcile approved values, and report exceptions. What happens when evidence is missing? Preserve the event, pause the consequential action, and escalate with minimum necessary context.' },
];

const makePost = (t: Topic): Omit<ResearchPost, 'published'> => ({ slug: t.slug, title: t.title, excerpt: t.excerpt, sections: shared(t), sources });

export const august18ResearchPosts: readonly ResearchPost[] = [
  { ...makePost(topics[0]), published: '2026-08-18' },
  { ...makePost(topics[1]), published: '2026-08-18' },
  { ...makePost(topics[2]), published: '2026-08-18' },
  { ...makePost(topics[3]), published: '2026-08-18' },
  { ...makePost(topics[4]), published: '2026-08-18' },
  { ...makePost(topics[5]), published: '2026-08-18' },
  { ...makePost(topics[6]), published: '2026-08-18' },
  { ...makePost(topics[7]), published: '2026-08-18' },
  { ...makePost(topics[8]), published: '2026-08-18' },
  { ...makePost(topics[9]), published: '2026-08-18' },
];
