import type { ResearchPost } from '../fleet-data';

const sources = [
  { name: 'NIST Cybersecurity Framework 2.0', url: 'https://www.nist.gov/cyberframework' },
  { name: 'NIST Privacy Framework', url: 'https://www.nist.gov/privacy-framework' },
  { name: 'NIST SP 800-53 Rev. 5', url: 'https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final' },
  { name: 'FTC Protecting Personal Information', url: 'https://www.ftc.gov/business-guidance/resources/protecting-personal-information-guide-business' },
  { name: 'CISA Cybersecurity Performance Goals', url: 'https://www.cisa.gov/cybersecurity-performance-goals' },
  { name: 'U.S. Department of Labor Recordkeeping', url: 'https://www.dol.gov/general/topic/workhours/recordkeeping' },
  { name: 'EEOC Recordkeeping Requirements', url: 'https://www.eeoc.gov/employers/recordkeeping-requirements' },
  { name: 'NARA Records Management', url: 'https://www.archives.gov/records-mgmt' },
  { name: 'GAO Green Book', url: 'https://www.gao.gov/green-book' },
  { name: 'SHRM HR Toolkits', url: 'https://www.shrm.org/topics-tools/tools/toolkits' },
] as const;

type Topic = { slug: string; title: string; excerpt: string; question: string; evidence: string; model: string; finding: string; limits: string; conclusion: string };

const topics: Topic[] = [
  { slug: 'hr-job-description-change-history', title: 'Job Description Change History: Preserve the Role Before the Hire', excerpt: 'How HR teams can connect a hiring decision to the approved role definition without rewriting history.', question: 'When a job description changes during recruiting, which version describes the role that was actually approved, advertised, and evaluated?', evidence: 'EEOC recordkeeping guidance makes employment-selection records important, while NARA lifecycle principles favor identifiable versions and meaningful event history. NIST governance guidance adds ownership and authorization. Together, these sources support preserving each approved role version rather than replacing an old file with the latest wording.', model: 'Maintain a role register with requisition identifier, version, effective timestamp, approving owner, location, employment classification, essential functions, selection criteria, publication channels, and retirement reason. Link each candidate stage to the version in force at that stage. A coordinator can compare fields and flag drift; the hiring owner decides whether a material change requires reapproval or renewed communication.', finding: 'The important unit is not the document alone but the relationship between version, audience, and decision event. A stable history reveals whether a late requirement changed the candidate pool, interview evidence, or accommodation discussion.', limits: 'Version history cannot establish that a criterion was job-related, consistently applied, or legally sufficient. Classification, accommodation, and selection questions require qualified review.', conclusion: 'A defensible recruiting record lets an owner explain which role was approved at each point and prevents administrative cleanup from obscuring a consequential change.' },
  { slug: 'hr-candidate-accommodation-request-routing', title: 'Candidate Accommodation Requests: Route the Signal, Protect the Detail', excerpt: 'A bounded intake model for candidate accommodation requests that preserves confidentiality and decision ownership.', question: 'How can recruiting operations identify an accommodation request quickly without copying medical or sensitive detail into general hiring records?', evidence: 'NIST privacy principles emphasize purpose limitation and controlled access. EEOC employer materials make consistent employment records relevant, but they do not authorize every coordinator to inspect sensitive information. The evidence supports separating a routing signal from the confidential accommodation record.', model: 'Use a minimal intake event: candidate or requisition identifier, received time, stage, requested adjustment category at the narrowest useful level, response owner, deadline, secure destination, and escalation state. Keep substantive documentation in the approved restricted location. Record whether the request was acknowledged and whether the interview plan was updated, without restating private details in the scorecard.', finding: 'Routing quality is measured by timely ownership and protected handling, not by the amount of information captured. A missing detail should trigger a secure follow-up, not a request for broad disclosure.', limits: 'Accommodation duties vary by jurisdiction, role, applicant situation, and employer process. The model does not decide reasonableness, medical sufficiency, or selection outcomes.', conclusion: 'A small, access-controlled routing record helps the right owner act while keeping recruiting administration out of the accommodation decision.' },
  { slug: 'hr-employee-complaint-document-preservation', title: 'Employee Complaint Records: Preserve the Timeline Before the Narrative Spreads', excerpt: 'A research framework for keeping complaint-related evidence findable, restricted, and chronologically reliable.', question: 'What should an HR operations team preserve when a complaint arrives, before anyone decides what the complaint means?', evidence: 'EEOC recordkeeping requirements and NARA records guidance both make retention context and retrievability material. NIST privacy guidance supports limiting access to the purpose and role. These sources point toward an event timeline and controlled case location, not a shared narrative tracker.', model: 'Capture received timestamp, channel, reporter identifier, subject category, immediate safety signal, assigned owner, preservation instruction, secure case location, access group, and next review date. Preserve the original message and subsequent authorized events separately. An administrator may acknowledge receipt, route, index, and maintain the evidence log; an authorized investigator or HR owner determines scope and findings.', finding: 'Chronology is often more defensible than an early summary. Separating original evidence, administrative events, and interpretive findings makes later review possible without treating an intake label as a conclusion.', limits: 'No intake model can determine credibility, retaliation, privilege, or legal reporting duties. Local law, policy, collective agreements, and urgent safety conditions may change the escalation path.', conclusion: 'The operational objective is a protected, chronological handoff with clear ownership, not a polished account created before the responsible reviewer has assessed the matter.' },
  { slug: 'hr-payroll-input-cutoff-reconciliation', title: 'Payroll Inputs: Reconcile Cutoff Changes Without Hiding Exceptions', excerpt: 'How to distinguish approved payroll inputs, late changes, and unresolved exceptions at the close of a pay period.', question: 'Which evidence shows that payroll inputs were complete and authorized at cutoff when changes continue to arrive?', evidence: 'GAO internal-control guidance emphasizes documented control activities and review. DOL recordkeeping guidance makes hours and employment records consequential, while NIST access guidance supports separation of preparation and approval. The combined implication is a dated cutoff and an explicit exception path.', model: 'Define pay period, cutoff timestamp, source systems, input categories, preparer, reviewer, approval status, correction window, and reconciliation test. Compare approved time, leave, rate or status changes, and one-time inputs to the payroll-ready extract using stable identifiers. Keep late submissions and corrections as separate events with reason, owner, and disposition; never move the cutoff to make an exception disappear.', finding: 'A close can be complete even when exceptions remain, provided the population, accepted inputs, pending items, and approval decisions are visible. Throughput alone cannot show whether a late change was safely handled.', limits: 'Payroll law and collective or employment agreements vary. The model does not calculate entitlement, determine exempt status, or replace payroll and legal review.', conclusion: 'The strongest payroll support record explains what was frozen, what changed afterward, who approved each correction, and how the final output was reconciled.' },
  { slug: 'hr-absence-record-correction-controls', title: 'Absence Record Corrections: Keep the Original Event and the Reason for Change', excerpt: 'A source-backed approach to correcting attendance records without turning history into a clean-looking fiction.', question: 'How should an HR team correct an absence entry when the original record is wrong, incomplete, or disputed?', evidence: 'DOL recordkeeping requirements make hours and attendance-related records important. NARA principles favor preserving original records and disposition context, while GAO controls support authorization and review. These sources support append-only correction evidence rather than silent overwrites.', model: 'Record worker identifier, original event, source, received correction request, reason category, requested effective date, supporting authority, approver, corrected value, timestamp, and downstream systems checked. A support lane can identify duplicates, compare source values, and prepare a proposed correction. The designated manager, HR, or payroll owner approves the change and any disputed interpretation.', finding: 'The useful metric is not only correction volume. Track correction age, repeat source defects, disputed items, approval latency, and whether downstream records were reconciled. A higher correction count can reflect better reporting rather than worse attendance data.', limits: 'An administrative correction does not resolve whether an absence was protected, paid, excused, or policy-compliant. Jurisdiction and employment terms remain controlling.', conclusion: 'Preserving the original event and the authorized reason for change protects both the employee record and the owner who must explain the final state.' },
  { slug: 'hr-benefits-eligibility-event-tracking', title: 'Benefits Eligibility Events: Track the Trigger Before the Enrollment Result', excerpt: 'Why benefits administration needs a reliable event record before an enrollment status can be interpreted.', question: 'What evidence connects a life event, worker-status change, or coverage decision to the benefits record that follows?', evidence: 'NIST privacy guidance supports purpose-limited handling of sensitive information, and GAO control principles support authorization and reconciliation. DOL materials demonstrate that benefits records can carry specific administrative obligations. The shared lesson is to preserve the trigger, rule version, and owner rather than treating a portal status as self-explanatory.', model: 'Capture event type, received date, effective date, worker population, rule or plan version, required evidence state, administrator, approval state, enrollment transmission, confirmation, and exception owner. Keep sensitive supporting material in the designated system. Reconcile the approved event to the carrier or platform response and record any mismatch without guessing eligibility.', finding: 'The result of an enrollment transaction is only one observation. A defensible record distinguishes an event received, an eligibility determination, an election made, a transmission accepted, and a coverage confirmation.', limits: 'Eligibility and special enrollment rules depend on plan documents, jurisdiction, worker status, and event facts. This framework cannot make a benefits determination.', conclusion: 'Benefits support is strongest when it makes the trigger and governing version visible while leaving eligibility and exception decisions with the authorized owner.' },
  { slug: 'hr-manager-employee-file-request-review', title: 'Manager Requests for Employee Files: Test Purpose Before Access', excerpt: 'A practical research model for responding to manager file requests with least-necessary disclosure.', question: 'When a manager asks for an employee file, how can HR distinguish a legitimate task from an unnecessarily broad access request?', evidence: 'NIST access-control and privacy frameworks support purpose, least privilege, and reviewable authorization. FTC safeguards guidance reinforces protecting personal information. The evidence favors a task-specific response rather than treating managerial status as blanket access.', model: 'Require requester identity, employee or population, business purpose, record categories, date range, decision owner, approved destination, expiration, and any legal or investigation hold. Offer a narrow report or controlled view where possible. Log what was disclosed, by whom, when, and under which approval. A coordinator may validate scope and prepare the package; the record owner decides whether disclosure is appropriate.', finding: 'The useful comparison is requested scope versus approved scope. Review sampled requests for oversized populations, indefinite access, repeated exports, and missing closeout evidence, while inspecting content only when metadata cannot explain the variance.', limits: 'Access rights vary by policy, jurisdiction, investigation status, and collective agreement. No generic register resolves privilege, litigation hold, or safety concerns.', conclusion: 'A purpose-bound request record lets managers receive what their work requires without making the employee file a default repository for every operational question.' },
  { slug: 'hr-workforce-location-record-governance', title: 'Workforce Location Records: Govern Changes Before They Affect HR Decisions', excerpt: 'How to keep work location and jurisdiction fields reliable when employees move, travel, or change work arrangements.', question: 'Which evidence shows that a workforce location field is current enough for payroll, benefits, policy, and reporting decisions?', evidence: 'NIST governance and privacy frameworks support defined data purpose, ownership, and controlled change. DOL and EEOC recordkeeping materials show why employment context and consistent records matter. These sources support treating location as a governed data element rather than a free-text convenience field.', model: 'Define location vocabulary, effective-date rule, source of authority, worker identifier, work arrangement, approver, evidence state, downstream consumers, and review trigger. Reconcile changes to payroll, benefits, access, and reporting systems. Keep historical values with effective periods and route conflicts to the responsible HR or legal owner instead of selecting the most recent entry by assumption.', finding: 'A location record can be accurate for one purpose and stale for another. Reports should state whether they use worksite, residence, payroll jurisdiction, or assigned office, plus the snapshot date and treatment of temporary arrangements.', limits: 'Location can interact with tax, labor, privacy, immigration, and employment-law questions. This model does not determine jurisdiction or tax treatment.', conclusion: 'Clear definitions and effective dates prevent a seemingly minor field change from silently propagating an unsupported HR decision.' },
  { slug: 'hr-hr-service-provider-incident-intake', title: 'HR Service-Provider Incidents: Build a Traceable Intake Before Remediation', excerpt: 'A bounded incident-intake model for HR vendors and service providers handling sensitive employee work.', question: 'What should an HR team capture when a provider reports a possible error, outage, disclosure, or unauthorized change?', evidence: 'NIST CSF and CISA guidance emphasize detection, response ownership, and evidence. FTC safeguards guidance focuses on protecting personal information, while NARA principles support preserving the event record. Together they support a minimal incident register linked to, but separate from, the affected HR records.', model: 'Record provider, system, received timestamp, reporter, event category, affected process, suspected population, immediate containment, evidence location, client owner, severity signal, notification status, next checkpoint, and closure authority. Do not copy sensitive payloads into the register. Preserve provider communications and system logs, and maintain a distinction between reported, confirmed, contained, remediated, and closed.', finding: 'A quick status can be useful only if its evidence state is explicit. Measure time to acknowledge, classify, contain, assign, and close, but interpret those durations alongside severity, dependencies, and unresolved uncertainty.', limits: 'Notification duties, breach analysis, privilege, and contractual remedies require qualified security, legal, and client-owner review. The intake model does not determine whether a report is a breach.', conclusion: 'A disciplined intake gives the right owner a usable timeline while reducing the risk that a support queue becomes an uncontrolled incident repository.' },
  { slug: 'hr-performance-cycle-calibration-evidence', title: 'Performance-Cycle Calibration: Preserve Evidence Without Rewriting Judgment', excerpt: 'How HR operations can make calibration records comparable while leaving performance judgment with managers.', question: 'Which administrative checks improve the reliability of a performance cycle without changing a manager’s assessment?', evidence: 'NARA records guidance supports retaining meaningful versions and events, while NIST privacy principles support limiting access to purpose. GAO control principles support review and separation of preparation from approval. These sources favor completeness and traceability checks, not administrative editing of evaluative content.', model: 'Track cycle, worker, role, manager, criteria version, submission event, required sections, calibration meeting event, approved outcome, employee acknowledgment, appeal or correction state, and record owner. Flag missing fields, wrong-cycle templates, duplicate submissions, and post-submission edits. Preserve original comments and record any authorized amendment as a separate event.', finding: 'Completeness, consistency, and fairness are different questions. A filled form can still contain unsupported judgment; a changed rating can be legitimate or contested. Reporting should show the evidence state and route substance to the manager, HR, or review panel.', limits: 'This model cannot evaluate performance, detect all bias, or establish legal sufficiency. Local policy, accommodation, protected activity, and collective arrangements may alter the review path.', conclusion: 'Administrative rigor is valuable when it makes the record easier to inspect without turning a coordinator into the author of someone else’s judgment.' },
];

const sections = (t: Topic) => [
  { heading: 'Research question', body: t.question },
  { heading: 'Evidence base', body: `${t.evidence} The sources are used to frame governance and record-quality implications, not to claim that one universal procedure fits every employer. The unit of analysis is the event named in the question. It should have a purpose, owner, source, effective period, and reviewable state.` },
  { heading: 'Operating model', body: `${t.model} Separate preparation, authorization, execution, and reconciliation. Give each event an actor, timestamp, source, and outcome. A missing field should remain missing until its owner resolves it; filling gaps from memory produces an attractive record that cannot be defended. Use the narrowest system and permission that can complete the task.` },
  { heading: 'Measurement design', body: `Use a fixed observation period and declare the denominator before calculating a rate. For this topic, the unit may be one role version, request, complaint event, payroll input, correction, eligibility event, access request, location change, incident, or review submission. Report counts beside rates, retain the query date, and separate overdue, paused, disputed, rejected, and missing-evidence states. A small denominator can make a percentage unstable, so avoid presenting precision the data cannot support.` },
  { heading: 'What the evidence can show', body: `${t.finding} Compare the documented state with a sample of source events. Include ordinary cases and exceptions, because a process that works only on the happy path is not reliable. Preserve the population, exclusions, source extract description, and any restatement so another reviewer can explain a different result in a later period.` },
  { heading: 'Practical implementation', body: `Start with one workflow and one accountable owner. Inventory the trigger, required inputs, authority, system of record, destination, review point, and closeout evidence. Test normal, late, corrected, and disputed cases. Ask the owner to confirm definitions and escalation thresholds before changing a form or tracker. Use redacted examples, store sensitive material only in the approved location, and keep a separate administrative index when a case repository contains restricted detail.` },
  { heading: 'Roles and boundaries', body: `Administrative support can gather defined inputs, check completeness, apply an already approved update, reconcile two values, maintain an index, send an approved reminder, and return an exception with evidence. It should not infer eligibility, interpret a legal obligation, select a candidate, decide whether a complaint is substantiated, approve pay or leave, rewrite judgment, or broaden access because a task is inconvenient. The named HR, payroll, manager, legal, security, benefits, or policy owner retains the decision.` },
  { heading: 'Review cadence', body: `Review when the workflow, system, role, policy, vendor, or population changes. Stable lower-risk work may be sampled monthly or quarterly; privileged access, sensitive cases, active payroll windows, and unresolved exceptions may need a shorter interval. Record population, sample or query, reviewer, findings, action owner, due date, and closeout. “No issue found” must describe what was tested, not imply universal assurance.` },
  { heading: 'Failure modes', body: `Common failures include treating a status as proof, copying sensitive detail into a convenience tracker, overwriting the original value, accepting an urgent request without checking authority, changing a due date to close an exception, and measuring throughput without rework or privacy exposure. Another failure is using the newest record without checking its effective date. When authority or evidence is unclear, the correct state is pending review, not an invented answer.` },
  { heading: 'Limitations', body: t.limits },
  { heading: 'Bounded interpretation', body: `The findings support a narrow operational claim: explicit definitions, limited access, separated approval, and preserved evidence make recurring HR administration easier to review. They do not prove legal compliance, employee outcomes, manager quality, or causal improvement. Interpret results within the stated population and period, and record jurisdiction, system limitations, unusual volume, and excluded cases.` },
  { heading: 'Conclusion', body: `${t.conclusion} For Human Resources Outsourced readers, the service-relevant boundary is clear: a support lane may prepare accurate, bounded work while the client-side owner retains judgment, approval, and accountability. That boundary belongs in the record, not only in a verbal handoff.` },
  { heading: 'FAQs', body: 'Who owns the decision? The authorized employer-side HR, manager, payroll, legal, security, benefits, or policy owner. What can an administrator do? Gather defined inputs, check completeness, apply approved changes, reconcile outcomes, and report exceptions. What happens when authority or evidence is missing? Pause the action, preserve the request or event, and escalate with the minimum necessary context.' },
];

export const august13ResearchPosts: readonly ResearchPost[] = topics.map(topic => ({
  slug: topic.slug,
  title: topic.title,
  excerpt: topic.excerpt,
  published: '2026-08-13',
  sections: sections(topic),
  sources,
}));
