import type { ResearchPost } from '../fleet-data';

const sources = [
  { name: 'NIST Cybersecurity Framework 2.0', url: 'https://www.nist.gov/cyberframework' },
  { name: 'NIST Privacy Framework', url: 'https://www.nist.gov/privacy-framework' },
  { name: 'NIST SP 800-53 Rev. 5', url: 'https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final' },
  { name: 'FTC Protecting Personal Information', url: 'https://www.ftc.gov/business-guidance/resources/protecting-personal-information-guide-business' },
  { name: 'CISA Cybersecurity Performance Goals', url: 'https://www.cisa.gov/cybersecurity-performance-goals' },
  { name: 'U.S. Department of Labor Recordkeeping', url: 'https://www.dol.gov/general/topic/workhours/recordkeeping' },
  { name: 'EEOC Recordkeeping Requirements', url: 'https://www.eeoc.gov/employers/recordkeeping-requirements' },
  { name: 'NARA Records Management', url: 'https://www.archives.gov/records-mgmt' },
  { name: 'GAO Green Book', url: 'https://www.gao.gov/green-book' },
  { name: 'SHRM HR Toolkits', url: 'https://www.shrm.org/topics-tools/tools/toolkits' },
] as const;

type Topic = { slug: string; title: string; excerpt: string; question: string; evidence: string; model: string; finding: string; limits: string; conclusion: string };

const topics: readonly Topic[] = [
  { slug: 'hr-employee-absence-pattern-review', title: 'Employee Absence Patterns: Interpret Records Without Jumping to Conclusions', excerpt: 'A bounded research model for reviewing absence records by period, source, and context while keeping employment judgment with the authorized owner.', question: 'What can an absence record show about timing and completeness, and what can it not show about cause, entitlement, or performance?', evidence: 'DOL recordkeeping guidance makes hours and employment records important sources, while NIST privacy guidance supports purpose-limited access. GAO control principles support reconciliations with declared populations and owners. These sources favor a dated event view instead of an unexplained attendance score.', model: 'Define worker identifier, absence category as already recorded by the owner, scheduled period, reported period, source, approval state, correction history, reviewer, and decision owner. Administrative support may compare approved records and identify missing evidence. The employer-side HR or manager owner decides how policy, accommodation, leave, or performance questions should be handled.', finding: 'A pattern is only a pattern within a declared cohort and period. Reconcile scheduled time, reported absence, approved status, reversals, and late corrections. Show counts alongside percentages and distinguish a missing record, an unapproved event, a disputed classification, and a confirmed policy state. Never convert frequency into a conclusion about intent.', limits: 'Absence definitions, privacy duties, leave rules, and accommodation processes vary by jurisdiction, policy, contract, and individual facts. This article does not determine entitlement, misconduct, disability, or discipline.', conclusion: 'A carefully scoped absence review helps owners see data quality and timing signals without turning administrative records into unsupported judgments.' },
  { slug: 'hr-employee-job-title-history-integrity', title: 'Job-Title History: Preserve Effective Dates and Meaning', excerpt: 'How HR teams can distinguish a title change, a role change, and a reporting correction when systems disagree.', question: 'What evidence makes an employee job-title history reliable across effective dates, approvals, and downstream records?', evidence: 'NARA records principles support authentic, retrievable versions. GAO control concepts support authorization and reconciliation, while NIST governance guidance supports accountable ownership. DOL and EEOC recordkeeping materials show why employment records should retain context rather than only the current value.', model: 'Capture worker identifier, prior and new title, role or classification reference, request source, approval authority, effective date, entry date, system of record, downstream consumers, superseded event, and exception owner. Support staff can compare defined fields and route conflicts; the authorized HR or business owner determines the meaning and effect of a change.', finding: 'The current title is an output, not a history. Test whether effective date differs from entry date, whether multiple changes overlap, whether a title was used for a different purpose, and whether dependent records received the approved value. Preserve rejected and superseded requests so a later reviewer can explain why the current value won.', limits: 'Titles may have different legal, compensation, organizational, or communication meanings. This framework does not determine classification, exemption, pay, seniority, promotion, or an employee’s qualifications.', conclusion: 'Effective-dated title history gives HR a more defensible record of change while keeping interpretation and approval with the proper owner.' },
  { slug: 'hr-employee-pay-change-effective-date', title: 'Pay-Change Effective Dates: Reconcile Approval, Period, and Entry', excerpt: 'A source-backed way to review pay-change records without calculating wages or making compensation decisions.', question: 'Which evidence shows that an approved pay-related change was entered for the intended worker and period?', evidence: 'DOL recordkeeping materials identify wage and hours records as material employment evidence. GAO principles support authorization, completeness, and reconciliation; NIST privacy guidance supports restricted access to payroll data. Together they support an event-to-period comparison rather than reliance on a final register alone.', model: 'Record worker identifier, change type, approved amount or value only where authorized, approval reference, effective date, payroll period, cutoff, entry timestamp, source system, downstream acknowledgment, correction state, and payroll owner. An administrator may assemble approved events and flag mismatches. Payroll or compensation owners interpret the change and approve corrections.', finding: 'Approval date, effective date, payroll entry date, and pay-period close are different facts. Reconcile each separately. Report out-of-period entries, missing approvals, duplicate events, rejected inputs, retroactive changes, and post-close corrections by observation period. Retain the original approved state when a correction is made.', limits: 'Compensation rules, tax treatment, agreements, classification, and payroll calendars vary. This article does not calculate pay, determine exemption, or authorize a compensation change.', conclusion: 'A dated pay-change ledger helps an owner explain what was approved, when it should apply, what the system received, and where review remains open.' },
  { slug: 'hr-employee-benefit-election-record-reconciliation', title: 'Benefit Election Records: Separate Submission, Acceptance, and Coverage', excerpt: 'A research framework for reconciling benefit elections while preserving plan-owner judgment and sensitive-data boundaries.', question: 'How can HR distinguish an employee submission from a validated election and an effective coverage record?', evidence: 'DOL EBSA materials point to plan documents and participant communications as governing sources. NIST privacy guidance supports minimum-necessary access, and NARA principles support version and provenance. GAO control concepts support comparing source submissions with carrier or system acknowledgments.', model: 'Define plan or program, participant identifier, event window, election version, submission timestamp, completeness state, reviewer, acceptance state, effective date, carrier acknowledgment, correction, and owner. Support staff can check defined completeness and route missing acknowledgments; benefits or plan owners determine eligibility, effect, and required communication.', finding: 'Submitted, received, complete, accepted, effective, and confirmed are distinct states. Measure each by event period and plan version. Treat an incomplete form, a portal receipt, a pending review, a carrier rejection, and an effective election as different evidence. Never infer coverage from a saved draft or a single status field.', limits: 'Plan terms, jurisdiction, enrollment windows, individual facts, and carrier processing determine outcomes. This model does not decide eligibility, coverage, tax treatment, or participant rights.', conclusion: 'State separation gives benefits owners a clearer exception queue and avoids promising an outcome that the underlying record does not establish.' },
  { slug: 'hr-employee-organization-chart-data-quality', title: 'Organization-Chart Data Quality: Test Relationships, Not Just Boxes', excerpt: 'How to review organizational relationships by effective date, source, and approval without treating a chart as the full authority record.', question: 'What makes an organization-chart relationship explainable when reporting lines, temporary assignments, and system timing differ?', evidence: 'NARA principles support preserving source history. GAO controls support authorized changes and reconciliation, while NIST governance guidance supports named accountability. Employment recordkeeping guidance reinforces the need to retain context for records that affect work relationships.', model: 'Capture worker and manager identifiers, unit, relationship type, source request, approval authority, effective date, end date, temporary or permanent status, system propagation, acknowledgment, and exception owner. An administrator can identify orphaned, overlapping, or stale relationships; the employer-side owner decides authority, delegation, and consequences.', finding: 'A chart snapshot cannot explain a temporary delegation or a backdated change. Compare effective dates with entry dates, find duplicate managers, identify workers without an owner, and check whether approval routes used the intended relationship at the time. State the snapshot date and preserve the source event.', limits: 'Reporting relationships may be informational, supervisory, operational, or legally significant depending on context. This method does not determine discipline authority, compensation approval, evaluation responsibility, or employment status.', conclusion: 'A relationship ledger makes organizational data more reviewable while acknowledging that a visual chart is only one representation of authority.' },
  { slug: 'hr-employee-reimbursement-record-completeness', title: 'Employee Reimbursement Records: Check Completeness Before Interpretation', excerpt: 'A bounded method for reviewing reimbursement submissions, approvals, and payment status without deciding policy exceptions.', question: 'Which fields show that a reimbursement record is ready for owner review, and which questions must remain outside administrative checking?', evidence: 'GAO control principles support authorization, evidence, and reconciliation. NIST privacy guidance supports limiting financial and personal data exposure, while NARA principles support retrievable versions. DOL recordkeeping materials illustrate why payment-related records require careful retention and context.', model: 'Define claimant identifier, expense period, category, source receipt reference, amount where access is authorized, policy version, submission date, approval, exception reason, payment state, correction history, and owner. Support staff may check required fields and reconcile statuses. Finance or HR owners determine policy interpretation, tax treatment, and exceptions.', finding: 'A submitted claim is not an approved claim, and an approved claim is not proof of payment. Reconcile those states with the relevant period and policy version. Report missing evidence, duplicate submissions, rejected items, out-of-period costs, returned payments, and manual overrides separately. Keep the original submission visible after correction.', limits: 'Reimbursement policy, tax treatment, payroll integration, and record requirements vary. This article does not decide whether an expense is allowable, taxable, reimbursable, or fraudulent.', conclusion: 'A state-based reimbursement record improves owner review without allowing an administrative completeness check to become a policy ruling.' },
  { slug: 'hr-employee-address-change-record-governance', title: 'Employee Address Changes: Separate Source, Purpose, and Effective Use', excerpt: 'A privacy-conscious research model for handling address updates across HR, payroll, benefits, and emergency-contact contexts.', question: 'How can one address update be reviewed without assuming that a value suitable for one HR purpose is current or authorized for every other purpose?', evidence: 'NIST Privacy Framework principles support purpose limitation and appropriate access. FTC safeguards guidance emphasizes protecting personal information, while NARA records principles support source and effective date. GAO controls support reconciling approved changes with dependent systems.', model: 'Record worker identifier, address purpose, source, received date, effective date, verification state, approval or policy basis, systems affected, propagation acknowledgment, access class, and exception owner. An administrator can route and reconcile a defined update. HR, payroll, benefits, tax, safety, or legal owners decide implications for their domain.', finding: 'A current value needs a purpose and a date. Test whether the change was sourced through an approved channel, whether effective and entry dates differ, whether a temporary address was closed, and whether downstream consumers received the intended version. Do not copy full addresses into broad tracking tools when a status and approved link are sufficient.', limits: 'Address use, tax effects, benefits records, privacy obligations, and verification standards vary. This framework does not determine residency, tax nexus, work authorization, emergency reachability, or permission to work remotely.', conclusion: 'Purpose-specific address evidence reduces stale and overexposed data while keeping downstream decisions with the relevant owner.' },
  { slug: 'hr-employee-grievance-record-integrity', title: 'Grievance Records: Preserve Intake Integrity and Decision Boundaries', excerpt: 'How HR administration can protect the provenance of a grievance while routing it to the qualified owner.', question: 'What administrative evidence shows that a grievance was received, protected, routed, and acknowledged without prejudging its substance?', evidence: 'EEOC employer resources demonstrate the sensitivity of workplace concerns. NIST privacy principles support minimum-necessary collection, while NARA principles support authentic records and GAO controls support ownership and review evidence. The combined evidence favors a restricted case record and a minimal routing index.', model: 'Capture case identifier, received timestamp, stated category, urgency or safety signal, access group, authorized owner, acknowledgment, next checkpoint, transfer history, and closure authority. Keep the narrative and supporting material in the approved restricted repository. Administrative support may route defined facts; HR, legal, investigation, or safety owners decide scope and findings.', finding: 'Receipt, triage, investigation, substantiation, and closure are separate states. Measure acknowledgment and routing completeness without presenting them as proof of the allegation. Preserve the original submission, record transfers, and document why access or scope changed. A missing detail should trigger a safe request or escalation, not a guessed classification.', limits: 'Applicable law, policy, privilege, collective arrangements, safety facts, and individual circumstances vary. This framework cannot determine credibility, retaliation, discrimination, harassment, legal reporting duties, or outcome.', conclusion: 'A provenance-preserving intake record lets the right owner act while protecting the distinction between an allegation, an administrative event, and a finding.' },
  { slug: 'hr-employee-remote-equipment-return-evidence', title: 'Remote Equipment Returns: Reconcile Custody, Condition, and Closeout', excerpt: 'A research approach to equipment-return records that keeps asset evidence separate from employment judgments.', question: 'What evidence shows that equipment was assigned, returned, received, inspected, and closed without overstating what an inventory record proves?', evidence: 'NIST and CISA guidance support asset awareness, access governance, and accountable ownership. FTC safeguards guidance supports protecting information held on devices, while NARA principles support retention of custody and disposition records. GAO concepts support reconciliation of expected and observed states.', model: 'Define asset identifier, worker or custodian, assignment date, approved return trigger, shipping or handoff reference, receipt date, inspection state, data-protection action, exception owner, and disposition authority. Support staff can maintain the register and route exceptions. IT, security, HR, or asset owners decide wipe, repair, replacement, retention, or dispute outcomes.', finding: 'A return label, carrier scan, receipt, inspection, and secure disposition are different events. Reconcile them by asset and date. Report assets with no custodian, overdue returns, returned-but-uninspected items, duplicate identifiers, damaged condition, and unresolved data-protection actions. Preserve custody changes rather than overwriting the last holder.', limits: 'Asset policy, security controls, contracts, jurisdiction, and device capability vary. This method does not determine liability, misconduct, data exposure, replacement obligation, or employment consequence.', conclusion: 'An event-based custody record helps owners close equipment work with evidence while avoiding unsupported conclusions from a missing scan or damaged item.' },
  { slug: 'hr-employee-policy-exception-register', title: 'Policy Exceptions: Make Scope, Approval, and Expiry Visible', excerpt: 'A source-backed framework for reviewing HR policy exceptions without turning an exception register into a substitute policy.', question: 'What makes a temporary HR policy exception reviewable from request through expiry or renewal?', evidence: 'NIST governance guidance supports accountable risk ownership and documented decisions. GAO control principles support authorization and monitoring, while NARA records principles support preserving versions and effective dates. NIST privacy guidance adds a purpose and access boundary when employee information is involved.', model: 'Record policy identifier and version, requested scope, affected population, reason as stated by the requester, risk owner, approval authority, start and end dates, conditions, review checkpoint, communication state, renewal or closure, and evidence location. Support staff may maintain the register and remind owners; the policy owner decides whether an exception is approved, extended, or denied.', finding: 'A request, approval, implementation, and expiry are distinct. Review whether the exception was limited to the stated scope, whether the owner accepted the risk, whether the end date was monitored, and whether impacted records used the correct version. Never silently extend an expired exception or treat repeated use as a permanent rule.', limits: 'Policy authority, legal requirements, collective arrangements, risk appetite, and individual facts vary. This model does not approve an exception, waive a legal duty, or determine employee entitlement.', conclusion: 'A visible exception lifecycle prevents temporary decisions from becoming invisible defaults and gives the authorized owner evidence for renewal, closure, or policy change.' },
];

const sections = (t: Topic) => [
  { heading: 'Research question', body: `${t.question} The useful unit of analysis is the dated event, not a broad impression about a person or department. A good record states what was observed, where it came from, which period it covers, and which owner may interpret it. That framing prevents an administrative queue from quietly becoming a decision system.` },
  { heading: 'Evidence base', body: `${t.evidence} These authorities provide governance, privacy, records, and control principles; they do not create one universal HR procedure. Apply the relevant rule for the employer, jurisdiction, plan, system, and population. Cite the source that supports a claim, preserve the source version or retrieval date where material, and distinguish an external requirement from an internal operating choice.` },
  { heading: 'Definitions and unit of analysis', body: `Before measuring ${t.title.toLowerCase()}, define the population, inclusion rules, observation period, event timestamp, effective timestamp, source system, and missing-data treatment. A request, approval, correction, employee, asset, or reporting period may be the unit, but those units must not be mixed in one denominator. Keep a data dictionary with field meaning, owner, allowed states, and the event that closes the record.` },
  { heading: 'Operating model', body: `${t.model} Separate preparation, authorization, execution, and reconciliation. Give each event an actor, timestamp, source, and outcome. A missing field should remain missing until its owner resolves it; filling gaps from memory produces a convenient record that cannot be defended. Use the narrowest system and permission that can complete the task, and link to restricted detail rather than copying it into a general tracker.` },
  { heading: 'Measurement design', body: `Use a fixed observation period and declare the denominator before calculating a percentage. Report counts beside percentages, retain the query date, and separate overdue, paused, disputed, rejected, superseded, and missing-evidence states. A small denominator can make a percentage unstable, so avoid false precision. Track rework and late corrections because a record that closes quickly but reopens often is not equivalent to a clean first-pass result. Describe exclusions and restatements so another reviewer can reproduce the result.` },
  { heading: 'What the evidence can show', body: `${t.finding} Compare documented states with a sample of source events, including ordinary cases and exceptions. Check whether the record can answer who acted, under which authority, for which period, and with what result. If a source is incomplete, report the limitation instead of substituting a neighboring field. A strong finding is narrow: it describes the tested population and evidence, not every employee or every future period.` },
  { heading: 'Implementation design', body: `Start with one workflow and one accountable owner. Inventory the trigger, required inputs, authority, system of record, destination, review point, and closeout evidence. Test normal, late, corrected, disputed, and withdrawn cases. Use a small redacted sample to validate field definitions before expanding the process. Ask the owner to confirm escalation thresholds and retention treatment. Change a form or tracker only after the owner agrees what each status means and how an exception leaves the queue.` },
  { heading: 'Roles and boundaries', body: `Administrative support can gather defined inputs, check completeness, apply an already approved update, reconcile two values, maintain an index, send an approved reminder, and return an exception with evidence. It should not infer eligibility, interpret a legal obligation, select a candidate, decide whether a complaint is substantiated, approve pay or leave, rewrite judgment, or broaden access because a task is inconvenient. The named HR, payroll, manager, legal, security, benefits, finance, or policy owner retains the decision.` },
  { heading: 'Review cadence', body: `Review when the workflow, system, role, policy, vendor, or population changes. Stable lower-risk work may be sampled monthly or quarterly; privileged access, sensitive cases, active payroll windows, and unresolved exceptions may need a shorter interval. Record population, sample or query, reviewer, findings, action owner, due date, and closeout. “No issue found” must describe what was tested, not imply universal assurance. Revisit the metric definition when the source or business meaning changes.` },
  { heading: 'Failure modes', body: `Common failures include treating a status as proof, copying sensitive detail into a convenience tracker, overwriting the original value, accepting an urgent request without checking authority, changing a due date to close an exception, and measuring throughput without rework or privacy exposure. Another failure is using the newest record without checking its effective date. When authority or evidence is unclear, the correct state is pending review, not an invented answer. Preserve rejected, expired, and superseded states so the record explains what did not proceed.` },
  { heading: 'Limitations', body: `${t.limits} The research model also depends on source quality, system clocks, integration completeness, reviewer consistency, and the employer’s approved access boundary. Those constraints mean a clean administrative record is evidence of a process state, not proof of a favorable employee outcome or complete legal compliance.` },
  { heading: 'Bounded interpretation', body: `The findings support a narrow operational claim: explicit definitions, limited access, separated approval, and preserved evidence make recurring HR administration easier to review. They do not prove legal compliance, employee outcomes, manager quality, or causal improvement. Interpret results within the stated population and period, record unusual volume and excluded cases, and escalate any issue that requires legal, clinical, safety, compensation, or employment judgment.` },
  { heading: 'Conclusion', body: `${t.conclusion} For Human Resources Outsourced readers, the service-relevant boundary is clear: a support lane may prepare accurate, bounded work while the client-side owner retains judgment, approval, and accountability. That boundary belongs in the record, not only in a verbal handoff. The practical test is whether a reviewer can reconstruct the event without guessing what a status meant or who was authorized to decide.` },
  { heading: 'FAQs', body: 'Who owns the decision? The authorized employer-side HR, manager, payroll, legal, security, benefits, finance, or policy owner. What can an administrator do? Gather defined inputs, check completeness, apply approved changes, reconcile outcomes, and report exceptions. What happens when authority or evidence is missing? Pause the action, preserve the request or event, and escalate with the minimum necessary context.' },
];

const post = (t: Topic): Omit<ResearchPost, 'published'> => ({ slug: t.slug, title: t.title, excerpt: t.excerpt, sections: sections(t), sources });

export const august14ResearchPosts: readonly ResearchPost[] = [
  { ...post(topics[0]), published: '2026-08-14' }, { ...post(topics[1]), published: '2026-08-14' },
  { ...post(topics[2]), published: '2026-08-14' }, { ...post(topics[3]), published: '2026-08-14' },
  { ...post(topics[4]), published: '2026-08-14' }, { ...post(topics[5]), published: '2026-08-14' },
  { ...post(topics[6]), published: '2026-08-14' }, { ...post(topics[7]), published: '2026-08-14' },
  { ...post(topics[8]), published: '2026-08-14' }, { ...post(topics[9]), published: '2026-08-14' },
];
