import type { ResearchPost } from '../fleet-data';

type Study = {
  slug: string; title: string; excerpt: string; service: string; lens: string;
  authority: string; population: string; sequence: string; exceptions: string;
  evidence: string; tests: string; measures: string; boundary: string; conclusion: string;
  sources: readonly { name: string; url: string }[];
};

const studies: readonly Study[] = [
  {
    slug: 'fmla-notice-sequence-reconciliation',
    title: 'FMLA Notice Administration: Reconcile the Sequence, Not Just the Deadline',
    excerpt: 'A control study for buyers separating notice preparation, employer determinations, delivery evidence, and later corrections in an outsourced leave workflow.',
    service: 'employee-records-administration',
    lens: 'The decision problem is whether an employer can reconstruct the complete notice sequence for a potentially FMLA-qualifying absence without allowing an administrator to make the eligibility or designation decision. A queue may show that a document was sent while hiding which facts were available, which form version was used, whether rights and responsibilities accompanied eligibility, whether a later designation matched the employer decision, and whether delivery reached the intended employee. Sequence integrity matters because a timely but mismatched notice can create a false sense of control. The buyer therefore needs event-level states, not one green completion flag.',
    authority: 'The Department of Labor describes general, eligibility, rights-and-responsibilities, and designation notices as distinct employer communications. Its current Fact Sheet 28D explains that the designation notice follows once the employer has enough information to know whether leave qualifies. That is a source-backed ordering principle, but it does not authorize a service provider to decide coverage, eligibility, qualifying reason, certification sufficiency, substitution of paid leave, or restoration rights. This study treats the official material as the rule source and derives a clerical control model around it. Employer counsel and qualified leave owners must resolve jurisdiction-specific or fact-sensitive questions.',
    population: 'Build the denominator from every intake that contains an absence or leave signal specified by the employer, including requests that arrive through managers, HR inboxes, scheduling tools, call centers, payroll feeds, and approved vendor channels. Preserve duplicates, reopened cases, intermittent episodes, changed start dates, missing contact details, returned mail, inaccessible formats, language needs, and cases later determined not to qualify. Segment by employing entity, work location, policy population, request channel, notice type, source version, delivery method, employer decision owner, and current state. Excluding stopped or negative cases would prevent a reviewer from testing whether the correct notice path was considered.',
    sequence: 'At intake, assign a stable case reference and record only the minimum facts needed for routing. Confirm the employing entity and authoritative owner before calculating any operational target supplied by that owner. Prepare the approved notice packet from controlled fields, then hold it for the employer determination where judgment is required. Record approval, document version, intended recipient, permitted channel, sent time, and delivery result as separate events. When facts change, issue a linked correction rather than overwriting history. Closure occurs only after the required sequence is reconciled, delivery exceptions have owners, and later designation evidence is linked to the same case.',
    exceptions: 'The strongest challenge set includes an employee who never uses the words FMLA or leave, a manager who forwards a message late, two overlapping reasons, an employee moving between entities, an eligibility calculation awaiting hours data, a certification arriving after a notice, a revised schedule, an undeliverable address, a language or accessibility need, and a designation corrected after new facts. Add a holiday and timezone boundary and a case that transfers to a leave vendor. The control should stop unsupported decisions, retain the original event time, and expose the employer-owned exception rather than silently restarting the clock or marking the file complete.',
    evidence: 'A defensible record contains intake source and time, employer entity, case reference, notice trigger identified by the approved procedure, facts available at each decision point, owner request, determination reference, template identifier and version, generated document hash, recipient, address or channel, accessibility or language variant, approval, sent time, delivery evidence, returned or failed status, correction linkage, and final reconciliation. Sensitive medical detail belongs in the restricted leave system, not the general queue. The operating record should reference the protected source without reproducing it. Reviewers need enough metadata to reconstruct actions while minimizing unnecessary disclosure.',
    tests: 'Test the design with synthetic cases before live use. Independently calculate expected state transitions from the employer-approved rules, then compare them with the queue. Attempt to send an outdated template, designate without an owner decision, change a sent record, close a returned notice, and expose medical text in an operations report. Reperform a sample from intake through delivery, including negative and stopped cases. Verify that a backup owner can act without borrowing credentials. After any template, vendor, policy, entity, integration, or workflow change, rerun the sequence tests and confirm that retired forms cannot be selected.',
    measures: 'Useful measures distinguish intakes awaiting triage, employer decisions pending, packets prepared, notices approved, notices sent, delivery failures, corrections, stopped actions, and reconciled closures. Show age by state and decision owner rather than one blended turnaround average. Report template-version exceptions, missing delivery evidence, duplicate cases, reopened sequences, and samples that cannot be reconstructed. A rapid send rate is not success if the wrong notice or audience was used. Publish the measurement window, population, exclusions, unknowns, and definition version, and keep provider-controlled time separate from time awaiting an employer determination.',
    boundary: 'An outsourced coordinator may capture approved routing facts, prepare controlled documents, monitor employer decisions, send specifically approved notices, record delivery evidence, reconcile states, and escalate exceptions. The coordinator must not determine FMLA coverage or eligibility, decide whether a reason qualifies, evaluate certification, calculate entitlement without an approved method and source data, select a legal position, promise job protection, or give individualized legal advice. Employer HR and qualified legal or leave owners retain every substantive determination and sensitive communication. The support scope should name reachable backups and a safe holding action when authority or facts are missing.',
    conclusion: 'A reliable FMLA administration lane is visible as a chain of authorized events. Buyers should be able to prove what the employer knew, who decided, which controlled notice was approved, how it was delivered, and how changed facts were reconciled. Human Resources Outsourced can operate the preparation, evidence, delivery-monitoring, and exception-routing mechanics within a bounded procedure. The employer remains responsible for legal applicability, substantive determinations, policy choices, employee rights, and final resolution.',
    sources: [
      { name: 'Fact Sheet #28D: Employer Notification Requirements under the FMLA — U.S. Department of Labor — checked October 2, 2026', url: 'https://www.dol.gov/agencies/whd/fact-sheets/28d-fmla-employer%20notification' },
      { name: 'FMLA Frequently Asked Questions — U.S. Department of Labor — checked October 2, 2026', url: 'https://www.dol.gov/agencies/whd/fmla/faq' },
      { name: 'NIST Privacy Framework — NIST — checked October 2, 2026', url: 'https://www.nist.gov/privacy-framework' },
    ],
  },
  {
    slug: 'form-i9-reverification-evidence-queue', title: 'Form I-9 Reverification Queues: Separate Document Expiration From Authorized Action',
    excerpt: 'A buyer-oriented study of reverification queue evidence, controlled reminders, Supplement B preparation, and employer-owned exceptions.', service: 'onboarding-offboarding-support',
    lens: 'The operational question is how to maintain a reverification queue without treating every document expiration as an instruction to request new documents. A sound queue begins with the employer-approved population and the authoritative Form I-9 record, then distinguishes work-authorization expiration, documents that should not be reverified, rehire events, name changes, receipts, and unresolved source quality. The service buyer needs evidence that reminders and preparation follow current instructions without steering an employee toward a particular document. A calendar built from copied expiration dates is not enough because an incorrect population can produce inappropriate requests at scale.',
    authority: 'USCIS instructions place reverification and eligible rehire recording in Supplement B and explain the employer or authorized representative certification. Those instructions are the primary operating source; a vendor checklist cannot replace them. The official material also makes document handling fact-dependent, so this research does not create a universal reverification rule. Our inference is narrower: outsourced support can maintain source-linked dates, prepare an employer-approved workflow, and surface uncertainty, while trained employer owners decide whether reverification is required and how unusual status, receipt, extension, remote examination, discrimination, or retention questions are resolved.',
    population: 'Inventory active employees from the employer’s authoritative roster and connect them to the actual Form I-9 record without copying identity documents into a broad tracker. Include remote hires, reverification candidates, rehired workers, leaves, transfers, terminated workers mistakenly left active, records with multiple Supplement B pages, receipts, automatic-extension evidence, missing forms, unreadable dates, and conflicts between the HRIS and protected repository. Segment by employing entity, original form version, authorization basis recorded by the employer, source location, relevant date, workflow owner, review state, and exception type. Unknown records remain visible and must not be converted into guessed deadlines.',
    sequence: 'A coordinator first reconciles the active roster to protected form references. An approved rule classifies records into no action, owner review, future follow-up, preparation, or resolved. Reminders use neutral employer-approved language and never demand a specific document. Before preparation, staff re-open the authoritative record, confirm the employee and employer entity, and verify that no superseding evidence or owner instruction exists. The employer or authorized representative completes the required examination and certification. The coordinator may then index Supplement B, preserve the completion reference, update the next approved state, and route discrepancies without rewriting the underlying form.',
    exceptions: 'Challenge the queue with a permanent resident card expiration, a U.S. passport expiration, expiring employment authorization, an automatic extension, a receipt, a rehire near the permitted window, a legal name change, a missing original form, two records for one employee, an employee transferred between entities, and a reminder generated after termination. Include a worker who offers a different acceptable document and a record whose date format was misread. The desired behavior is a safe stop and owner review, not confident automation. Test that no report exposes document numbers or images to staff who only need queue status.',
    evidence: 'Preserve roster snapshot time, employee reference, employing entity, protected Form I-9 location, form and supplement version, source date as recorded, classification rule version, reviewer, exception reason, reminder template, approval, communication event, authorized representative, completion date, Supplement B reference, quality review, correction linkage, and retention state. Do not place document images, citizenship or immigration narratives, numbers, or sensitive attachments in a general project board. A hash can help detect an unintended file change but cannot establish that the examination or legal determination was correct. Evidence must tie the operational step to the authorized employer actor.',
    tests: 'Use synthetic forms and employee records to test every state, including documents that must not create a reverification task. Compare the generated queue with an independently prepared answer set. Try to edit a source date without approval, request a named document, complete certification with an expired delegation, attach an image to the wrong worker, and close a missing-form exception. Review access logs and export permissions. Sample resolved items back to Supplement B and the active roster. Re-test after USCIS form or instruction changes, system migrations, remote-examination process changes, acquisitions, or modifications to the employer’s authorized-representative model.',
    measures: 'Report records reconciled, no-action classifications, owner reviews, upcoming authorized actions, completed supplements, unresolved source conflicts, missing forms, stopped reminders, corrections, and access exceptions. Age the owner-review queue and show the number of dates derived from authoritative records versus secondary imports. Measure false-positive reminder attempts and records that changed state after source review. Never rank employees by immigration-related status. Trend operational defects by root cause—roster lag, indexing, transcription, integration, training, or unclear ownership—and publish the population, observation time, exclusions, rule version, and unknown count with every result.',
    boundary: 'Support personnel may reconcile neutral identifiers, maintain protected references, apply an employer-approved classification, prepare neutral reminders, schedule authorized review, index completed supplements, and escalate inconsistencies. They may not decide which documents an employee must present, provide immigration advice, infer status, accept documentation outside delegated authority, alter attestation, backdate a form, conceal a missing record, or decide discrimination and retaliation questions. The employer appoints trained HR, legal, immigration, privacy, security, and authorized-representative owners. Minimum access, secure transfer, named accounts, and documented delegation are necessary regardless of where support staff work.',
    conclusion: 'The trustworthy output is not an alert; it is a reconciled, source-linked queue that prevents inappropriate requests and preserves employer authority. Human Resources Outsourced can maintain the workflow, evidence, reminders, and exception routing. The employer retains all examination, certification, legal interpretation, anti-discrimination, retention, correction, and risk decisions.',
    sources: [
      { name: 'Instructions for Form I-9 — U.S. Citizenship and Immigration Services — checked October 2, 2026', url: 'https://www.uscis.gov/sites/default/files/document/forms/i-9instr.pdf' },
      { name: 'Form I-9 Supplement B, Reverification and Rehire — USCIS — checked October 2, 2026', url: 'https://www.uscis.gov/sites/default/files/document/forms/i-9.pdf?page=3' },
      { name: 'NIST Privacy Framework — NIST — checked October 2, 2026', url: 'https://www.nist.gov/privacy-framework' },
    ],
  },
  {
    slug: 'aca-form-1095c-source-reconciliation', title: 'Form 1095-C Source Reconciliation: Test Monthly Evidence Before Coding',
    excerpt: 'A research framework for reconciling monthly employment and coverage inputs while reserving ACA coding and filing decisions for qualified owners.', service: 'reporting-and-qa',
    lens: 'ACA information reporting compresses a year of employment, offer, affordability, and enrollment facts into coded monthly records. The buyer problem is not simply whether a file passes a vendor validation. It is whether every monthly output can be traced to authoritative sources and an owner-approved interpretation. A technically accepted transmission can still carry an incorrect employee population, entity, offer period, or self-insured enrollment record. Outsourced support is most useful when it makes source conflicts visible before coding and preserves the evidence used by the qualified reporting owner.',
    authority: 'IRS instructions explain that Applicable Large Employer members use Forms 1094-C and 1095-C for required information reporting and that Form 1095-C reports all twelve months for relevant employees. The instructions and IRS employer pages are primary sources, but they do not turn a coordinator into a tax adviser. This study derives a source-reconciliation control: establish the employer-approved reporting population, freeze monthly facts, document transformations, and route code or filing judgments. Applicability, ALE status, aggregated groups, full-time determinations, offer codes, affordability, self-insured reporting, corrections, and filing positions remain owner decisions.',
    population: 'Construct the review population from the authoritative employee roster, employing-entity history, hours or status determination output approved by the employer, benefits eligibility, offers, waivers, enrollments, dependent coverage where applicable, leaves, rehires, terminations, payroll calendars, and prior filed records. Include workers who changed entity, moved between measurement states, declined coverage, enrolled late, lost coverage, were retroactively corrected, or appear in one system but not another. Segment by ALE member, tax year, employee, month, source system, employment state, offer state, enrollment state, correction state, and owner review. Never remove conflicts just to balance totals.',
    sequence: 'Freeze dated source extracts and record their owners. Normalize neutral identifiers in a restricted workspace, then reconcile employee-to-entity and month-to-month continuity before applying owner-approved mappings. Generate an exception file for missing months, overlapping entities, impossible date sequences, offer/enrollment disagreement, dependent mismatches, or retroactive changes. Qualified owners resolve tax and benefits meaning. Only then should approved codes populate a draft return. Reconcile draft counts to the frozen population, obtain signoff, transmit through the authorized path, preserve acknowledgments, and link corrections to the original submission without overwriting the facts used earlier.',
    exceptions: 'Test an employee crossing an entity boundary, a new hire near month-end, a return from leave, a retroactive termination, a coverage rescission, a dependent added after the effective date, an offer recorded without delivery evidence, a waived offer, conflicting Social Security number fields, a duplicate person, and a self-insured participant who is not a full-time employee. Add a vendor import that silently defaults blank months and a correction received after draft approval. The control should hold the affected record, preserve the source conflict, and route it rather than selecting the most convenient value.',
    evidence: 'The evidence package should include tax year, ALE member, frozen population timestamp, source-system versions, extraction queries or report identifiers, field map version, employee reference, month-level source references, transformation logs, exception history, qualified-owner decisions, draft hash, review totals, signoffs, transmission identifier, acceptance or rejection response, correction links, and distribution evidence. SSNs and dependent details stay in tightly restricted systems. General trackers use neutral case identifiers and status. A vendor acceptance code proves processing status, not substantive correctness, so it must be connected to the approved draft and reconciliation package.',
    tests: 'Create synthetic year histories with known expected outcomes and run them through extraction, normalization, exception generation, draft creation, and correction. Check that entity totals and employee-month totals reconcile at each boundary. Attempt to submit with unresolved conflicts, change a mapping after signoff, merge two people, default a blank month, and reuse a prior-year rule table. Independently reproduce a sample of month-level facts from source records. Test access segregation and secure distribution. Repeat after IRS instruction changes, benefit-plan changes, acquisitions, payroll or HRIS migrations, vendor releases, and any alteration to owner-approved mappings.',
    measures: 'Track population reconciliation differences, employee-month exceptions, missing source fields, cross-entity conflicts, late changes, owner-decision aging, draft revisions, rejected transmissions, corrections, and records independently reproduced. Separate mechanical validation errors from source conflicts and interpretive decisions. Report denominators by ALE member and tax year. A low vendor rejection rate is not an accuracy measure. Explain extract times, definition versions, unresolved cases, and changes after the freeze. Protect small or sensitive breakdowns. Trend recurring defects back to their generating system so the process improves before the next annual filing cycle.',
    boundary: 'An outsourced analyst can collect approved extracts, normalize identifiers, execute documented comparisons, prepare exception files, populate owner-approved mappings, reconcile counts, preserve acknowledgments, and coordinate correction tasks. The analyst should not determine ALE status, full-time status, affordability, coverage codes, tax liability, filing positions, intentional disregard, or employee tax guidance. Employer tax, benefits, payroll, HR, legal, privacy, security, and finance owners approve definitions, interpretations, submissions, corrections, and communications. Access to tax identifiers must be narrow, monitored, and time-bounded.',
    conclusion: 'Decision-grade ACA reporting starts with reproducible monthly evidence, not a clean vendor dashboard. Human Resources Outsourced can operate the controlled reconciliation and exception workflow. The employer and its qualified advisers retain all tax, benefits, filing, correction, and employee-communication decisions.',
    sources: [
      { name: 'Instructions for Forms 1094-C and 1095-C (2025) — Internal Revenue Service — checked October 2, 2026', url: 'https://www.irs.gov/instructions/i109495c' },
      { name: 'Information Reporting by Applicable Large Employers — IRS — checked October 2, 2026', url: 'https://www.irs.gov/affordable-care-act/employers/information-reporting-by-applicable-large-employers' },
      { name: 'Questions and Answers about Forms 1094-C and 1095-C — IRS — checked October 2, 2026', url: 'https://www.irs.gov/affordable-care-act/employers/questions-and-answers-about-information-reporting-by-employers-on-form-1094-c-and-form-1095-c' },
    ],
  },
  {
    slug: 'wage-garnishment-order-conflict-reconciliation', title: 'Wage Garnishment Administration: Reconcile Competing Orders Before Payroll Execution',
    excerpt: 'A control study for intake authenticity, employee matching, order conflicts, payroll evidence, and employer-owned legal decisions.', service: 'payroll-support',
    lens: 'A garnishment workflow can fail even when payroll withholds an amount on time. The order may belong to another person, arrive through an unapproved channel, conflict with an existing order, use a different earnings definition, be superseded, or require a response outside the payroll system. The buyer decision is which preparation and reconciliation steps can be outsourced without transferring legal interpretation. A reliable lane separates document authenticity, employee match, authority review, calculation inputs, payroll execution, remittance, communication, and release. One status labeled active conceals too many materially different states.',
    authority: 'The Department of Labor explains federal Consumer Credit Protection Act limits for ordinary garnishments and notes that other categories, including support and tax matters, can follow different rules. That distinction makes a universal calculation template unsafe. The official material supports the need to classify the authority and protect employees from impermissible withholding or discharge, but employer counsel and payroll owners must interpret the actual order and applicable federal, state, and local rules. Our operational inference is to preserve the source, expose conflicts, and require an authorized decision before any payroll configuration changes.',
    population: 'Inventory every received order, levy, support notice, release, amendment, creditor communication, agency response, returned payment, payroll configuration, remittance, and employee inquiry. Include unmatched orders, duplicate service, multiple concurrent matters, transferred employees, terminated employees, rehired employees, bonus or commission runs, off-cycle pay, negative net pay, protected data, and orders held for authenticity review. Segment by employee, employing entity, issuing authority, order category assigned by the owner, received time, service method, effective state, pay group, remittance destination, priority decision, and exception. Unmatched and rejected items stay in the denominator.',
    sequence: 'Log receipt using a stable matter reference and restrict the original document. Verify sender and channel under the employer procedure, then match the subject using more than a name while exposing as little personal data as possible. Assemble existing orders and payroll context for the qualified owner. Record the owner’s classification, priority, effective instruction, calculation method, response duty, and stop conditions. A separate payroll actor configures the approved instruction; another reviewer compares the setup with the decision. Each pay cycle reconciles disposable-earnings inputs, withholding, remittance, residual balances, rejects, and releases. Changes create new linked events rather than edits to prior authority.',
    exceptions: 'Challenge the design with two employees sharing a name, a fraudulent fax, duplicate service, conflicting priority instructions, an amended amount, child support plus an ordinary debt, a tax levy, a bankruptcy notice, a terminated worker, a multi-state transfer, a bonus, insufficient disposable earnings, an overpayment, a rejected remittance, and a release arriving after payroll cutoff. Include pressure from a creditor and an employee asking the coordinator for legal advice. The safe result may be a hold and rapid escalation. Tests should prove that silence, urgency, or a familiar template cannot substitute for owner authorization.',
    evidence: 'Retain received time and channel, protected source location, authenticity checks, employee-match evidence, employing entity, authority and matter identifiers, owner classification, applicable instruction version, priority decision, effective dates, payroll configuration change, independent review, per-pay-period inputs, withheld amount, remittance result, balances, notices, exceptions, corrections, release, and closure approval. General workflow systems should not store full account, court, tax, or identity data. Delivery receipts and payroll logs strengthen evidence only when they link to the correct order and owner decision. Never erase an incorrect setup; document reversal and remediation.',
    tests: 'Use synthetic orders and payroll results to verify intake, matching, conflict detection, setup, calculation handoff, remittance, and release. Compare expected states prepared by qualified owners with system output. Try to activate an unmatched order, allow the preparer to approve their own setup, change a rate without a new decision, send funds to a modified account, ignore a rejected payment, and apply a release to the wrong matter. Sample live configuration metadata without exposing unnecessary employee data. Re-test after payroll upgrades, bank or vendor changes, new employing entities, jurisdictional changes, procedure revisions, or any real exception.',
    measures: 'Report new orders, unmatched items, authenticity holds, owner decisions pending, conflicting matters, configured instructions, review failures, remittance rejects, releases pending, corrections, and closed matters. Measure provider processing separately from owner or authority waiting. Track wrong-person prevention, duplicate detection, configuration defects, returned funds, and cases independently reconstructed. Speed alone can reward unsafe withholding. Publish the population window, pay groups, included order types, exclusions, unknowns, and method version. Use root-cause categories that support remediation without exposing employee financial circumstances in broad reports.',
    boundary: 'Support staff may receive through approved channels, index restricted documents, perform documented identity matching, prepare a conflict packet, enter specifically approved payroll settings, reconcile outputs, monitor remittance evidence, and route inquiries. They must not interpret an order, choose priority, decide disposable earnings, advise an employee or creditor, alter a remittance destination without verification, release a withholding, or decide how competing laws apply. Employer payroll, legal, HR, finance, privacy, security, and treasury owners retain those decisions and appoint reachable backups for cutoff-sensitive events.',
    conclusion: 'The control objective is not maximum automation; it is exact execution of a verified, employer-owned instruction with visible conflicts and recoverable evidence. Human Resources Outsourced can support intake, controlled setup, reconciliation, and exception tracking. The employer and qualified advisers retain all legal classification, calculation, priority, communication, correction, and release authority.',
    sources: [
      { name: 'Federal Wage Garnishments — U.S. Department of Labor — checked October 2, 2026', url: 'https://www.dol.gov/agencies/whd/wage-garnishment' },
      { name: 'Fact Sheet #30: Wage Garnishment Protections of the CCPA — U.S. Department of Labor — checked October 2, 2026', url: 'https://www.dol.gov/agencies/whd/fact-sheets/30-cppa' },
      { name: 'NIST Privacy Framework — NIST — checked October 2, 2026', url: 'https://www.nist.gov/privacy-framework' },
    ],
  },
  {
    slug: 'osha-recordkeeping-case-state-reconciliation', title: 'OSHA Recordkeeping Support: Reconcile Case States Without Making the Recordability Decision',
    excerpt: 'A buyer framework for incident intake, qualified-owner decisions, Forms 300/301 evidence, privacy cases, and annual summary reconciliation.', service: 'employee-records-administration',
    lens: 'Workplace incident intake and OSHA recordkeeping are related but not identical. An incident can require internal action while not becoming an OSHA log entry, and a recordability decision can change when later facts arrive. Buyers therefore need a workflow that preserves the original report, routes urgent safety matters, obtains a qualified decision, maintains form evidence, protects privacy-concern cases, and reconciles later changes. Outsourced administration should improve completeness and timeliness without deciding work-relatedness, medical treatment, restriction, days away, or another substantive criterion.',
    authority: 'OSHA states that covered employers use Forms 300, 300A, and 301 or equivalent forms for recordable injuries and illnesses, and its regulation describes the basic form requirements. OSHA resources also distinguish recording criteria and annual summary responsibilities. Those are authoritative reference points; they do not make every incident recordable or every employer subject to the same submission duties. This study infers an administrative control from the official structure. The employer’s trained safety and legal owners decide coverage, recordability, privacy treatment, classification, reporting, certification, posting, and electronic submission.',
    population: 'Start with all workplace incident signals received through approved channels, not only cases already labeled recordable. Include employee and manager reports, near misses if the employer tracks them, clinic information, workers’ compensation feeds, restrictions, days-away updates, fatalities or severe-event escalations, transferred cases, contractors, duplicates, late reports, and records reopened by new medical facts. Segment by establishment, event date, discovery date, worker relationship, restricted source location, urgent-reporting route, owner decision, form state, privacy state, days-away or restriction updates, and annual-summary inclusion. Keep negative determinations and incomplete cases visible for reconciliation.',
    sequence: 'Capture minimum incident-routing facts and immediately follow the employer’s urgent safety and reporting procedure; routine queueing must never delay an emergency path. Assign the establishment and qualified owner, preserve the source report, and obtain the recordability and classification decision. After approval, prepare the appropriate 300 and 301 fields or equivalent record, applying the owner’s privacy instruction. A reviewer checks the entry against the decision. Later changes to outcome or days create dated updates. At year end, reconcile case counts and totals, route certification, preserve posting evidence, and separately document any required electronic submission and agency acknowledgment.',
    exceptions: 'Test a case with only first aid, later medical treatment, delayed days away, a worker assigned to another establishment, remote work, travel, a contractor, a duplicate clinic feed, a privacy-concern case, a name accidentally exposed on the log, an incident crossing year end, and a severe event requiring the employer’s urgent reporting route. Add a form changed after annual totals were prepared and an electronic submission rejection. The workflow must preserve the earlier state, notify the owner, recalculate affected totals, and prevent an administrator from independently deciding recordability to make the numbers reconcile.',
    evidence: 'Maintain incident reference, received time and channel, establishment, protected narrative location, emergency escalation evidence, qualified decision owner, decision date, criteria reference supplied by the owner, form identifiers, classification, privacy-case instruction, entry and review actors, dated outcome updates, days-away and restriction totals, correction history, annual reconciliation, executive certification, posting evidence, submission file hash where applicable, agency acknowledgment, and unresolved exceptions. Do not reproduce diagnoses or detailed narratives in general operational reports. The OSHA log, incident report, workers’ compensation file, and internal investigation may have different purposes and access rules.',
    tests: 'Use synthetic cases with known owner decisions to test routing and form-state transitions. Confirm urgent paths bypass ordinary service targets. Attempt to enter a case before decision, disclose a privacy-case name, assign the wrong establishment, alter days without a source event, certify totals with unresolved discrepancies, and reuse a prior-year submission file. Recalculate annual totals independently and trace a sample from intake through Form 301 and Form 300. Verify role separation and access. Re-test after OSHA guidance or form changes, establishment changes, acquisitions, system integrations, vendor changes, and lessons from actual reporting exceptions.',
    measures: 'Show all incident intakes, urgent escalations, decisions pending, recordable and non-recordable outcomes, entries awaiting review, privacy exceptions, later updates, unreconciled establishment totals, certification status, posting evidence, submission responses, and corrections. Age each operational state and distinguish employer-decision time from administrative handling. Track wrong-establishment defects, duplicate signals, missing source evidence, privacy exposures, and independently reproduced samples. Do not use recordable counts as a performance score for individuals. Publish the period, establishments, source coverage, exclusions, definition version, and unresolved population.',
    boundary: 'A coordinator may receive approved intake, preserve source references, route urgent signals, prepare forms after an owner decision, apply explicit privacy instructions, update approved factual fields, reconcile totals, maintain posting evidence, and monitor submission responses. The coordinator must not decide OSHA coverage or recordability, diagnose an injury, determine work-relatedness, classify treatment, suppress a case, certify a summary, report to an agency without authorization, or advise on retaliation and employee rights. Employer safety, legal, HR, medical, privacy, security, establishment, and executive owners retain all substantive and certification authority.',
    conclusion: 'A trustworthy recordkeeping process keeps incident intake, qualified decisions, form administration, privacy controls, and annual reconciliation connected without collapsing them. Human Resources Outsourced can support the evidence and workflow mechanics. The employer retains safety response, legal interpretation, recordability, classification, certification, reporting, communication, and corrective-action decisions.',
    sources: [
      { name: 'OSHA Injury and Illness Recordkeeping Forms — OSHA — checked October 2, 2026', url: 'https://www.osha.gov/recordkeeping/forms' },
      { name: 'Recording Criteria — OSHA — checked October 2, 2026', url: 'https://www.osha.gov/recordkeeping/recording' },
      { name: '29 CFR 1904.29 Forms — OSHA — checked October 2, 2026', url: 'https://www.osha.gov/laws-regs/regulations/standardnumber/1904/1904.29' },
    ],
  },
];

const method = 'Methodology: we reviewed the cited primary government materials on October 2, 2026, separated their express requirements from our operational inferences, and modeled the workflow from intake through owner decision, execution, evidence, exception, correction, and review. We used scenario analysis rather than employee data or production testing. The model asks what a buyer can verify, which steps can be standardized, where professional judgment begins, and whether another authorized reviewer can reproduce the result. It does not estimate market prevalence, provider performance, or legal outcomes.';
const limitations = 'Limitations and uncertainty: public guidance can change, and applicability depends on the employer, workforce, entity structure, jurisdiction, systems, contracts, plans, facts, and current law. We did not audit an employer, inspect employee records, test a production platform, or obtain a legal opinion. A control can reduce preventable administrative error without proving compliance or a correct substantive decision. Buyers should obtain qualified legal, tax, benefits, payroll, safety, privacy, security, accessibility, records, and technical review whenever the question requires it.';
const checklist = 'Buyer implementation checklist: name the authoritative source and owner; define the full population and explicit exclusions; document intake channels and stable identifiers; separate preparation, decision, execution, review, and communication; restrict sensitive content to approved systems; create safe-stop conditions; name primary and backup owners; preserve original and corrected states; test ordinary, edge, and unauthorized paths with synthetic data; reconcile source counts to outputs; measure exceptions with denominators; and require retesting after a material rule, system, vendor, integration, entity, staffing, or scope change. If any step depends on memory, silence, shared credentials, or an undocumented side channel, keep the lane in pilot.';
const rollout = 'Practical rollout: begin with one employing entity, one authoritative repository, and a narrow observation window. Inventory the real states before configuring automation. Have the employer approve the source hierarchy, field definitions, decision owners, access groups, communication templates, and stop rules. Run synthetic ordinary and exception records through the entire lane, then pilot with daily reconciliation and a second-person review. Compare system permissions with contractual scope and remove unnecessary access. At the end of the pilot, ask an independent authorized reviewer to reconstruct a stratified sample from intake through closure using only retained evidence. Record missing evidence and disagreements as defects rather than explaining them away. Expand volume only after corrective actions are tested, backups can act through their own accounts, and reporting shows unresolved items with named owners. Schedule periodic source checks and event-driven reviews so a changed form, instruction, integration, entity, vendor, or employer policy cannot silently leave an obsolete workflow in service.';

export const october2ResearchPosts: readonly ResearchPost[] = studies.map((study) => ({
  slug: study.slug, title: study.title, excerpt: study.excerpt, published: '2026-10-02',
  thumbnail: '/hr-team.jpg',
  sections: [
    { heading: 'Research question and buyer decision', body: study.lens },
    { heading: 'Methodology', body: `${study.title} uses this method. ${method}` },
    { heading: 'What primary sources say—and our inference', body: study.authority },
    { heading: 'Population and denominator', body: study.population },
    { heading: 'Controlled operating sequence', body: study.sequence },
    { heading: 'Exception and challenge cases', body: study.exceptions },
    { heading: 'Evidence model', body: study.evidence },
    { heading: 'Control testing', body: study.tests },
    { heading: 'Decision-grade measures', body: study.measures },
    { heading: 'Role boundaries', body: study.boundary },
    { heading: 'Buyer implementation checklist', body: `For ${study.title}, apply this checklist. ${checklist}` },
    { heading: 'Practical rollout sequence', body: `For the ${study.slug} control lane, use this rollout. ${rollout}` },
    { heading: 'Limitations and uncertainty', body: `These limitations apply specifically to ${study.title}. ${limitations}` },
    { heading: 'Conclusion for outsourced HR buyers', body: study.conclusion },
  ],
  sources: study.sources,
  serviceLink: { title: 'Connect this research to a bounded service lane', href: `/services/${study.service}`, body: 'Review the related support scope while preserving employer authority for substantive decisions and exceptions.' },
}));
