type ResearchSupport = { method:string; checklist:string; rollout:string; limitations:string };

export const october2IndependentResearchSupport: Record<string,ResearchSupport> = {
  'fmla-notice-sequence-reconciliation': {
    method:'We converted the Department of Labor notice guidance into a state-transition model. The unit of analysis is a potentially qualifying absence episode, not a sent document. For each synthetic episode we tracked employer awareness, eligibility review, rights-and-responsibilities delivery, certification activity, designation, delivery result, later fact changes, and correction. We challenged the sequence with late manager forwarding, overlapping reasons, changing schedules, undeliverable notices, and vendor transfer. The test asks whether an authorized reviewer can reconstruct what the employer knew at each decision point without relying on a coordinator’s legal conclusion.',
    checklist:'Define the absence population and the event that places an item in review. Name owners for eligibility, certification, designation, delivery, employee communication, and corrections. Record source timestamps separately from administrative handling dates. Preserve notice version, delivery evidence, returned mail, changed facts, and owner decisions. Test indirect leave signals, entity changes, intermittent schedules, accessibility needs, and vendor handoffs. Reconcile all open episodes to an owner and next deadline; never use a sent-form count as the completion measure.',
    rollout:'Begin with one leave intake channel and a short observation period. Sample recent absence messages to learn how potential signals actually arrive, then let the leave owner approve trigger categories and safe-stop rules. Run synthetic episodes through ordinary, late, overlapping, inaccessible, and corrected paths. Pilot with daily sequence reconciliation and second-person review of every notice packet. Expand only when delivery failures remain visible, backup owners can act, and a reviewer can reconstruct each episode from retained evidence without private side-channel explanations.',
    limitations:'This model does not decide whether an employee is eligible, whether a condition qualifies, whether certification is sufficient, or which deadline applies to a particular fact pattern. Employer size, worksite, hours, entity history, state law, military provisions, collective agreements, and current guidance can change the analysis. The study did not inspect employee data or test a leave platform. It evaluates administrative traceability and escalation, which can reduce missed handoffs but cannot prove legal compliance or a correct substantive leave decision.'
  },
  'form-i9-reverification-evidence-queue': {
    method:'We modeled reverification as a population-classification problem anchored to the employer’s existing Form I-9 record and current USCIS instructions. Synthetic records were assigned to categories such as no action, reverification review, rehire review, receipt follow-up, source defect, and qualified-owner decision. We tested whether the queue distinguishes status expiration from ordinary document expiration and whether it accepts any permitted employee-presented document rather than prescribing one. Evidence was evaluated from the original record through reminder, owner instruction, Section 3 or supplement action, correction, and retention.',
    checklist:'Inventory the employer-approved population before sending reminders. Record the controlling form version, employment-authorization date where applicable, prior reverification, receipt, rehire event, source quality, and owner. Exclude documents and people that should not enter reverification solely because a card or passport expires. Give employees neutral instructions and choice within the authorized process. Test automatic extensions, receipts, permanent-resident cards, U.S. passports, name changes, missing forms, duplicates, terminations, and entity transfers. Reconcile completed action to the authoritative form record.',
    rollout:'Start with a read-only comparison of a small population against the authoritative Form I-9 repository. The employer’s immigration or legal owner should approve inclusion rules, reminder timing, templates, accepted evidence routes, and escalation conditions. Run synthetic edge cases before any employee contact. Pilot reminders with owner review and daily reconciliation of responses, undeliverable messages, and source defects. Expand only after false-positive rates are understood, unnecessary document requests are eliminated, access is restricted, and an authorized reviewer can reproduce why every person entered or left the queue.',
    limitations:'The study does not determine work authorization, choose documents, complete a form for an employer, or interpret individual immigration circumstances. Form editions, temporary rules, automatic extensions, rehire options, retention duties, and remote examination procedures can change. We did not inspect Forms I-9 or verify a production system. The control tests whether an administrative queue follows an owner-approved population and preserves evidence; it cannot establish that a particular reverification action is lawful or complete.'
  },
  'aca-form-1095c-source-reconciliation': {
    method:'We treated each employee-month as the unit of analysis and compared four evidence families: employment and entity status, offer and delivery, affordability or safe-harbor inputs, and enrollment for self-insured reporting. Synthetic annual records were expanded into monthly states, coded by an authorized owner, reassembled into draft forms, and reconciled to vendor output. Challenge cases included month-end hires, leave, entity transfer, retroactive changes, dependent activity, duplicate identities, and blank-month defaults. The method tests traceability of codes and covered-individual records rather than whether a transmission file passes technical validation.',
    checklist:'Define applicable entities, employee population, measurement approach, plan year, source hierarchy, code owner, and correction owner. Reconcile every month to employment status, full-time determination, offer evidence, employee contribution, coverage result, and any self-insured covered individual. Preserve source extracts and approved interpretation separately. Test transfers, rehires, leave, waived offers, retroactive termination, rescission, dependent changes, identifier conflicts, vendor defaults, and late corrections. Require control totals before draft approval and retain accepted-file and correction acknowledgments.',
    rollout:'Pilot one applicable entity and one reporting year in a read-only environment. First reconcile population counts among HRIS, payroll, benefits, and the reporting vendor. Have benefits, tax, payroll, and legal owners approve monthly definitions and code decisions. Run synthetic edge cases through import, validation, draft form, approval, transmission, and correction. Review every discrepancy during the pilot. Expand only after blank defaults are visible, entity transfers are controlled, covered-individual totals reproduce, and a second authorized reviewer can trace sampled form lines to monthly source evidence.',
    limitations:'This operational model does not determine applicable-large-employer status, full-time status, affordability, offer codes, penalties, or filing obligations for a particular employer. Controlled-group facts, plan design, measurement methods, relief, forms, instructions, and filing systems can change. We did not inspect tax returns, enrollment records, or vendor configuration. Traceable monthly reconciliation can expose inconsistencies, but only qualified tax, benefits, payroll, and legal owners can approve coding and corrections. A technically reproducible record may still rest on a substantive interpretation outside this study’s scope. The comparison also assumes stable employee identifiers across systems. When identifiers have changed, the reporting owner must approve the crosswalk rather than letting the reconciliation process infer that two records represent the same person. Likewise, a balanced annual total cannot reveal an offer that was assigned to the wrong month, so sampled line-level tracing remains necessary after aggregate totals agree.'
  },
  'wage-garnishment-order-conflict-reconciliation': {
    method:'We modeled an order as a controlled case with authenticity, employee match, jurisdiction, order type, priority instruction, earnings basis, limit decision, payroll execution, remittance, response, amendment, and release states. Synthetic pay periods contained competing orders, bonuses, insufficient disposable earnings, entity moves, and late releases. The study separated calculations that an authorized payroll owner approved from administrative data entry and payment evidence. Testing focused on whether conflicts stop for legal or payroll review and whether every withheld amount can be traced to the governing instruction and destination acknowledgment.',
    checklist:'Use a restricted intake route and preserve the received order. Verify employee match and route authenticity or service questions to the designated owner. Inventory existing orders before adding another. Record owner-approved priority, earnings definition, limits, start period, remittance destination, response duty, and release criteria. Test fraudulent documents, duplicate service, child support, ordinary debt, tax levy, bankruptcy, bonus, termination, transfer, insufficient earnings, rejected payment, amendment, and release after cutoff. Reconcile payroll withholding to remittance and case balance each period.',
    rollout:'Begin with one payroll group and a read-only inventory of open orders. Payroll and legal owners should approve the order taxonomy, decision fields, calculation evidence, payment routes, communications, and emergency escalation. Run synthetic conflicts through two payroll periods, including amendments and releases. Pilot with dual review of every setup and per-run reconciliation of withheld, remitted, rejected, and outstanding amounts. Expand only when existing orders are reliably surfaced, bank changes receive independent verification, and backup owners can reconstruct priority and limits without using coordinator judgment.',
    limitations:'This study does not authenticate a particular order, interpret federal or state priority, calculate disposable earnings, decide exemptions, advise an employee, or determine the effect of bankruptcy or termination. Jurisdiction, order type, pay components, employer location, and current law matter. We did not inspect wage records or court documents. The model addresses administrative custody and reconciliation; it cannot prove that a withholding decision, amount, response, or remittance is legally correct. A matching control total does not validate the owner’s underlying legal instruction. Returned remittances also require case-specific review: a rejected payment may reflect stale banking data, a closed case, or a processing error, and the administrative team should not choose among those explanations without direction from the responsible owner.'
  },
  'osha-recordkeeping-case-state-reconciliation': {
    method:'We separated incident intake from the employer’s recordability decision and represented each case through urgent-response, establishment, decision, form-entry, privacy, later-update, annual-summary, and electronic-submission states. Synthetic cases changed over time—for example, first aid followed by medical treatment or later days away—so the test could detect whether prior entries and totals were corrected visibly. We traced sampled cases across incident source, qualified decision, Forms 301 and 300, annual totals, certification, posting, and submission response without asking an administrator to decide work-relatedness or treatment classification.',
    checklist:'Define covered establishments, intake channels, urgent escalation, decision owners, form custodians, privacy-case handling, annual reconciliation, certification, posting, and submission ownership. Preserve original reports and later factual updates. Test first aid, later treatment, days away, restricted work, remote work, travel, contractor status, establishment transfer, duplicate feeds, privacy cases, year-end changes, severe-event escalation, and rejected submission. Recalculate annual totals independently and require a qualified owner for recordability, classification, privacy, correction, and certification decisions.',
    rollout:'Start with one establishment and compare incident sources with the current log without altering either. Safety and legal owners should approve source hierarchy, urgent paths, decision evidence, privacy rules, and form access. Run synthetic ordinary and evolving cases through the full year-end cycle. Pilot with daily intake reconciliation and second-person review of every owner decision and form update. Expand only after urgent cases bypass routine queues, privacy names stay protected, establishment totals reproduce, and an executive owner can certify from reconciled evidence.',
    limitations:'The model does not determine OSHA coverage, work-relatedness, recordability, treatment classification, privacy-case status, severe-event reporting, or certification for a real incident. Establishment structure, state-plan rules, industry exemptions, medical facts, and current regulations can alter duties. We did not inspect incident or medical records or submit to OSHA. The workflow can make missing decisions and mismatched totals visible, but only qualified employer owners can make and certify substantive safety and reporting judgments. Administrative completeness must never delay emergency response or required owner escalation. Later medical facts may also require a newly authorized review. Annual agreement between the log and summary is therefore only a reconciliation result, not proof that each case was classified correctly. Establishment transfers and acquisitions deserve separate owner review because a case can disappear from a local queue while still requiring retention, updating, or inclusion elsewhere. The study does not resolve that allocation.'
  },
};
