import type { ResearchPost } from '../fleet-data';

const date = '2026-09-04';
const thumbnail = '/research-heroes/august31-hr-controls-research.svg';
const sources = [
  { name: 'NIST Privacy Framework', url: 'https://www.nist.gov/privacy-framework' }, { name: 'NIST Cybersecurity Framework 2.0', url: 'https://www.nist.gov/cyberframework' },
  { name: 'GAO Green Book', url: 'https://www.gao.gov/green-book' }, { name: 'National Archives records management', url: 'https://www.archives.gov/records-mgmt' },
  { name: 'EEOC recordkeeping requirements', url: 'https://www.eeoc.gov/employers/recordkeeping-requirements' }, { name: 'Department of Labor recordkeeping fact sheet', url: 'https://www.dol.gov/agencies/whd/fact-sheets/21-flsa-recordkeeping' },
  { name: 'FTC data security guidance', url: 'https://www.ftc.gov/business-guidance/privacy-security/data-security' }, { name: 'CISA Cybersecurity Performance Goals', url: 'https://www.cisa.gov/cybersecurity-performance-goals' },
  { name: 'ICO data minimisation guidance', url: 'https://ico.org.uk/for-organisations/uk-gdpr-guidance-and-resources/data-protection-principles/a-guide-to-the-data-protection-principles/' }, { name: 'ILO working time and work organization', url: 'https://www.ilo.org/topics-and-sectors/working-time-and-work-organization' }
];
const studies = [
  { slug: 'hr-handoff-latency-measurement-boundaries', title: 'Measuring HR Handoff Latency Without Blaming the Queue', excerpt: 'A source-backed model that separates administrative waiting time from owner decisions, employee response time, system delay, and approved holds.', question: 'Which timestamps make handoff delay useful without assigning every elapsed hour to the support team?', method: 'The review combines internal-control, records-management, and working-time guidance. It models a request as events with different owners rather than one uninterrupted timer.', finding: 'A single open-to-close duration hides where the work waited. Received, ready for owner, owner response, destination submission, destination confirmation, and approved-hold events create a more honest record.', model: 'Keep a clock for active administrative work and separate clocks for owner, requester, and system waits. Report the count and age of each wait state beside the overall duration.', test: 'Test a late manager decision, a missing employee document, a payroll system outage, a reopened record, and a clean same-day request. Confirm that each delay lands with the right event owner.', limits: 'The event model does not establish a universal service level or prove staff productivity. System timestamps can be incomplete, working schedules differ, and sensitive cases may need approved pauses.', conclusion: 'Handoff reporting improves when teams show where the request waited. The event trail supports process repair without turning elapsed time into a careless performance judgment.' },
  { slug: 'hr-reminder-fatigue-suppression-evidence', title: 'Reminder Fatigue and Suppression Evidence in HR Operations', excerpt: 'Research on when recurring HR reminders should stop after a response, status change, exception, or failed delivery.', question: 'What evidence should suppress an automated reminder before the next scheduled send?', method: 'The analysis applies privacy minimization, governance, and records principles to scheduled HR messages. It examines status at send time and does not attempt to measure employee motivation.', finding: 'Reminder schedules drift when they rely on the audience captured at launch. A response event, approved exception, departure, audience change, or persistent delivery failure can make the next message unnecessary or inappropriate.', model: 'Resolve the current audience and status before every send. Preserve the suppression reason, source event, timestamp, and owner, then route disputed statuses instead of guessing.', test: 'Run a completed task, approved exemption, employee departure, bounced address, changed policy audience, and conflicting system status through the send check.', limits: 'The method cannot decide whether a person is legally required to respond or how often an employer should communicate. Those choices depend on policy, context, and applicable rules.', conclusion: 'A reminder queue needs a fresh eligibility check before each send. Suppression evidence reduces stale messages and leaves the owner a record of why contact stopped.' },
  { slug: 'hr-destination-confirmation-reliability', title: 'How Reliable Is Destination Confirmation in HR Data Changes?', excerpt: 'A research framework for distinguishing a submitted HR update from one that the destination system actually accepted and retained.', question: 'When does a system message provide enough evidence that an approved HR change reached its intended destination?', method: 'The review translates records and security guidance into an evidence hierarchy for administrative changes. It compares submission receipts, success messages, audit events, read-back checks, and downstream reconciliation.', finding: 'A successful submission can show transport without proving the final stored value. Stronger confirmation connects the record, field, approved value, destination, event time, and responsible account.', model: 'Classify evidence as submitted, accepted, stored, or reconciled. Choose the required level for each workflow and keep any destination mismatch open for an owner decision.', test: 'Test a queued import, partial batch failure, overwritten value, delayed synchronization, duplicate employee record, and a successful read-back.', limits: 'No confirmation method proves that the underlying decision was correct. Audit access varies by system, and read-back checks can expose more employee data than the coordinator needs.', conclusion: 'Teams should define confirmation before work begins. A precise evidence level keeps "sent" from being mistaken for "finished" while limiting unnecessary access.' },
  { slug: 'hr-exception-taxonomy-stability-review', title: 'Keeping an HR Exception Taxonomy Stable Enough to Learn From', excerpt: 'Research on classifying HR workflow defects without rewriting categories whenever an awkward case appears.', question: 'How can an HR team keep exception categories consistent while still recording new kinds of operational failure?', method: 'The analysis uses governance and records-management principles to separate stable reporting categories from detailed case notes. It treats taxonomy changes as controlled definitions.', finding: 'Overly broad categories hide patterns, while a new category for every event makes comparison impossible. A stable parent category with a specific cause and versioned definition offers a workable middle ground.', model: 'Use a small set of parent causes such as source, access, approval, routing, destination, timing, and closure. Add a plain-language detail, owner disposition, and taxonomy version to each event.', test: 'Classify a missing source, excess permission, expired approval, wrong recipient, rejected update, late handoff, and premature closure. Have a second reviewer repeat the exercise.', limits: 'The taxonomy is not a legal risk rating and cannot make unlike workflows directly comparable. Definitions require local review, and rare serious cases may need their own restricted investigation.', conclusion: 'Stable categories help teams see repeated control failures. Versioned definitions and specific case detail preserve learning without forcing every exception into an artificial label.' },
  { slug: 'hr-small-queue-backlog-forecast-limits', title: 'What a Small HR Queue Can Really Tell You About Backlog', excerpt: 'A source-backed examination of why low-volume HR queues need case-level aging and scenario ranges instead of confident forecasts.', question: 'Which backlog measures remain useful when an HR queue has too few cases for a stable trend?', method: 'The review applies internal-control and working-time concepts to low-volume administrative queues. It uses case states and scenario ranges rather than claiming statistical precision.', finding: 'One sensitive or owner-blocked case can dominate a small monthly average. Counts by age band, wait owner, risk, and next action reveal more than a forecast based on a short history.', model: 'Show every material exception, group ordinary items into age bands, and calculate a low, expected, and high completion range from documented capacity assumptions. Revisit the assumptions after each cycle.', test: 'Apply the method to queues of five, ten, and twenty records with one owner hold, one system delay, and one privacy-sensitive exception.', limits: 'Scenario ranges are planning aids, not predictions or staffing guarantees. Arrival patterns change, cases differ in effort, and historical speed does not show whether the work was accurate.', conclusion: 'Small queues call for visible cases and modest claims. Aging, ownership, and next-action data support decisions better than a precise-looking forecast built on thin history.' }
];
export const september4ResearchPosts: readonly ResearchPost[] = studies.map(study => ({ slug: study.slug, title: study.title, excerpt: study.excerpt, published: date, thumbnail, sections: [
  { heading: 'Research question', body: study.question }, { heading: 'Evidence scope and method', body: study.method }, { heading: 'Finding', body: study.finding }, { heading: 'Operational model', body: study.model }, { heading: 'Control test', body: study.test },
  { heading: 'Implementation boundary', body: 'A Philippines-based coordinator can maintain the event record, run approved checks, assemble evidence, and route exceptions. The employer retains policy interpretation, access approval, employment decisions, sensitive communication, and corrective action.' },
  { heading: 'Limitations', body: study.limits }, { heading: 'Evidence-led conclusion', body: study.conclusion }
], sources, serviceLink: { title: 'Apply the research to an HR support lane', href: '/services/reporting-and-qa', body: 'Turn the model into a narrow queue with a named owner, explicit data boundary, and documented review.' } }));
