import type { ResearchPost } from '../fleet-data';
const specs=[
['employee-payroll-account-change-authentication','Employee Payroll Account Changes: Authenticate the Request Before Processing','payroll bank-detail change','payroll and security','identity conflict, an unapproved channel, a cutoff exception, or self-approval'],
['employee-data-export-request-scope-verification','Employee Data Export Requests: Verify Scope, Authority, and Destination','employee-data export','privacy, legal, and HR data','missing purpose, excessive fields, an unapproved destination, or a count variance'],
['hr-vendor-contact-change-payment-fraud-control','HR Vendor Contact Changes: Control Payment and Impersonation Risk','HR vendor contact or payment-instruction change','procurement, finance, and security','a lookalike domain, changed payment details, an unknown contact, or combined duties'],
['employee-emergency-contact-change-purpose-access','Employee Emergency Contact Changes: Limit Purpose, Access, and Reuse','employee emergency-contact change','HR, privacy, and safety','failed employee authentication, secondary use, a disputed value, or unclear retention'],
['hr-case-delegate-conflict-of-interest-routing','HR Case Delegation: Detect Conflicts Before Routing Sensitive Work','sensitive HR case assignment','employee relations, legal, and ethics','an involved owner, reporting-line conflict, missing alternate, or urgent safety risk']
] as const;
const sources=[{name:'NIST Privacy Framework — checked September 18, 2026',url:'https://www.nist.gov/privacy-framework'},{name:'NIST Cybersecurity Framework 2.0 — checked September 18, 2026',url:'https://www.nist.gov/cyberframework'},{name:'NIST Digital Identity Guidelines — checked September 18, 2026',url:'https://pages.nist.gov/800-63-4/'},{name:'FTC Start with Security — checked September 18, 2026',url:'https://www.ftc.gov/business-guidance/resources/start-security-guide-business'},{name:'GAO Green Book — checked September 18, 2026',url:'https://www.gao.gov/green-book'},{name:'National Archives Records Management — checked September 18, 2026',url:'https://www.archives.gov/records-mgmt'},{name:'EEOC Recordkeeping Requirements — checked September 18, 2026',url:'https://www.eeoc.gov/employers/recordkeeping-requirements'}];
const headings=['Research question','Methodology','Source findings','Evidence model','Identity and authority','Role boundary','Stop rules','Privacy and access','Records and retention','Exception handoff','Control test','Measures','Implementation','Limitations','Conclusion'];
function body(h:string,event:string,owners:string,stop:string){return `${h} is evaluated for a ${event}. Official NIST, FTC, GAO, National Archives, and EEOC materials checked September 18, 2026 support risk governance, proportionate authentication, least privilege, documented authorization, monitoring, and reliable records. They do not prescribe one universal HR workflow or transfer an employer decision to support staff. Our analysis separates the original request, asserted facts, verified evidence, approved action, implementation event, destination acknowledgment, exception, and review. The minimum record identifies the requester, purpose, subject, source channel, received and effective times, masked sensitive values, preparer, approver, affected systems, and reconciliation result. A Philippines-based coordinator may check required fields, apply an approved verification script, prepare an owner-ready packet, monitor deadlines, and record responses. The coordinator must not invent authority, interpret law or policy, approve a payment or employment outcome, expand disclosure, or treat silence as consent. Decisions remain with ${owners} owners. Work pauses for ${stop}; the pause records the last proven event, missing decision, authorized owner, safe holding action, backup, and next checkpoint. Restricted evidence stays in an approved system while a broad queue holds only a neutral reference, owner, deadline, and state. Named accounts, strong authentication, access logs, controlled exports, and independent review reduce risk but cannot prove an outcome correct. Test a routine case, impersonation, correction, late request, unavailable owner, and conflicting instruction with synthetic data. Two reviewers should independently reproduce authority, current state, disclosure boundary, next action, and closure proof. Measure complete authority evidence, exceptions by type and age, independent approvals, variances, reopened cases, and destination confirmations with stated populations and denominators. Do not reward premature closure. Law, contracts, jurisdiction, system configuration, and individual facts can change the required result; qualified owners must review material exceptions. Human Resources Outsourced can support preparation and reconciliation while the employer retains judgment.`}
export const september18SecondResearchPosts:readonly ResearchPost[]=specs.map(([slug,title,event,owners,stop])=>({slug,title,excerpt:`Decision-grade research for controlling a ${event} without transferring employer judgment.`,published:'2026-09-18',sections:headings.map(h=>({heading:h,body:body(h,event,owners,stop)})),sources,serviceLink:{title:'Review the bounded HR support scope',href:'/services',body:'Match administrative work with explicit employer ownership and stop rules.'}}));
