import type { ResearchPost } from '../fleet-data';
const date='2026-09-07';
const sources=[{name:'NIST Privacy Framework',url:'https://www.nist.gov/privacy-framework'},{name:'NIST Cybersecurity Framework 2.0',url:'https://www.nist.gov/cyberframework'},{name:'GAO Green Book',url:'https://www.gao.gov/green-book'},{name:'National Archives records management',url:'https://www.archives.gov/records-mgmt'},{name:'EEOC recordkeeping requirements',url:'https://www.eeoc.gov/employers/recordkeeping-requirements'},{name:'Department of Labor recordkeeping fact sheet',url:'https://www.dol.gov/agencies/whd/fact-sheets/21-flsa-recordkeeping'},{name:'FTC data security guidance',url:'https://www.ftc.gov/business-guidance/privacy-security/data-security'},{name:'CISA Cybersecurity Performance Goals',url:'https://www.cisa.gov/cybersecurity-performance-goals'},{name:'ICO data minimisation guidance',url:'https://ico.org.uk/for-organisations/uk-gdpr-guidance-and-resources/data-protection-principles/a-guide-to-the-data-protection-principles/'},{name:'NIST least privilege glossary',url:'https://csrc.nist.gov/glossary/term/least_privilege'}];
const studies=[
['hr-approval-queue-denominator-design','Choosing Denominators for HR Approval-Queue Reporting','Why approval rates need a defined eligible population, cutoff, and exception treatment.','Which denominator makes approval-queue reporting reproducible?','Use requests ready for a named approver during a fixed window; report withdrawals, duplicates, and incomplete requests separately.','This model does not set a universal service level or measure decision quality.'],
['hr-access-review-sampling-risk-bands','Risk-Banded Sampling for HR Access Reviews','Review sensitive permissions more often without ignoring ordinary accounts.','How can a small HR team allocate access-review effort?','Review privileged, export, payroll, and broad record access first; maintain a rotating sample of narrower roles.','Risk bands require local judgment and cannot prove how a permission was used.'],
['hr-case-reopen-rate-measurement','What an HR Case Reopen Rate Can and Cannot Show','Separate premature closure from new facts and later requests.','When is a reopened HR case evidence of a workflow defect?','Count a possible defect only when original scope was unresolved, evidence was missing, or the recorded result was wrong.','Incomplete event histories make classification uncertain; the rate alone cannot establish performance.'],
['hr-employee-data-export-control-evidence','Evidence for Controlled Employee-Data Exports','A model for approval, minimum fields, transfer, receipt, retention, and deletion.','What evidence should accompany an employee-data export?','Record purpose, approver, selected fields, recipient, protected transfer, receipt, retention instruction, and deletion confirmation.','Lawful basis and retention duties vary; this operational model is not legal advice.'],
['hr-workflow-change-control-small-teams','Lightweight Change Control for Small HR Teams','Keep recurring work stable with versioned checklists and short approval records.','What is the smallest useful control for changing an HR workflow?','A dated note should identify owner, reason, affected step, effective date, test case, and rollback instruction.','Formal records do not guarantee sound policy, and urgent incidents may require an emergency process.']] as const;
export const september7ResearchPosts:readonly ResearchPost[]=studies.map(([slug,title,excerpt,question,finding,limits])=>({slug,title,excerpt,published:date,modified:date,sections:[{heading:'Research question',body:question},{heading:'Method and scope',body:'We synthesized official internal-control, records, security, and privacy guidance into an event-based HR operations model. The scope is recurring administration; it excludes legal conclusions and causal claims about workers.'},{heading:'Finding',body:finding},{heading:'Implementation model',body:'Define the source event, eligible population, named owner, allowed action, exception route, completion evidence, and review interval. Preserve original evidence and keep sensitive narrative in its approved system.'},{heading:'Validation exercise',body:'Test a routine case, missing input, conflicting source, access exception, and failed destination. Ask a second reviewer to reproduce the classification from the retained record.'},{heading:'Limitations',body:limits},{heading:'Practical conclusion',body:'Pilot the control on a small queue, review early cases, and revise the documented step that creates ambiguous evidence. Company owners remain responsible for policy, privacy, employment, and legal decisions.'}],sources,serviceLink:{title:'HR reporting and QA',href:'/services/reporting-and-qa',body:'Translate the findings into a reviewable operating control.'}}));
