import type { ResearchPost } from '../fleet-data';

const published = '2026-09-18';
const nistPrivacy = { name: 'NIST Privacy Framework', url: 'https://www.nist.gov/privacy-framework' };
const nistSecurity = { name: 'NIST Cybersecurity Framework 2.0', url: 'https://www.nist.gov/cyberframework' };
const gaoControls = { name: 'GAO Standards for Internal Control in the Federal Government', url: 'https://www.gao.gov/green-book' };
const naraRecords = { name: 'National Archives records management guidance', url: 'https://www.archives.gov/records-mgmt' };
const eeocHiring = { name: 'EEOC: Recruiting, hiring, and promoting employees', url: 'https://www.eeoc.gov/employers/small-business/3-im-recruiting-hiring-or-promoting-employees' };
const eeocQuestions = { name: 'EEOC: Pre-employment inquiries and medical questions', url: 'https://www.eeoc.gov/pre-employment-inquiries-and-medical-questions-examinations' };
const eeocRecords = { name: 'EEOC recordkeeping requirements', url: 'https://www.eeoc.gov/employers/recordkeeping-requirements' };
const ftcBackground = { name: 'FTC: Background checks and employment decisions', url: 'https://www.ftc.gov/business-guidance/resources/background-checks-what-employers-need-know' };
const ftcData = { name: 'FTC data security guidance', url: 'https://www.ftc.gov/business-guidance/privacy-security/data-security' };
const ofccpRecords = { name: 'OFCCP applicant recordkeeping requirements Q&A', url: 'https://www.dol.gov/sites/dolgov/files/ofccp/CAGuides/files/Applicant-Recordkeeping-FAQ-WEB_080119_CONTR508c.pdf' };

export const september18ResearchPosts: readonly ResearchPost[] = [
  {
    slug: 'requisition-approval-version-control',
    title: 'Job Requisition Approval: Which Version Should Recruiting Operations Use?',
    excerpt: 'A research-backed control model for keeping sourcing and scheduling tied to the employer-approved job request.',
    published,
    sections: [
      { heading: 'Research question', body: 'When a hiring manager, finance reviewer, and recruiter circulate different versions of a job requisition, which record should a Philippines-based recruiting coordinator use for sourcing, outreach, and interview administration? The operational problem is not simply finding the newest attachment. A later file can still be a draft, while an older version can remain the last authorized instruction. Role title, location, employment status, reporting line, compensation range, minimum qualifications, interview panel, and target date can each change on a different path. This study asks what evidence is sufficient to identify the approved operating version without letting an administrative support role approve headcount, rewrite selection criteria, or choose between conflicting business owners.' },
      { heading: 'Methodology and source scope', body: 'We conducted a qualitative synthesis of current official guidance from the EEOC, OFCCP, NIST, GAO, and the National Archives. EEOC materials inform consistent hiring practices and employment-record handling. OFCCP guidance shows why covered contractors need defined applicant and requisition records, though coverage and duties vary. NIST contributes privacy and security governance principles, GAO contributes authorization and control concepts, and National Archives guidance contributes record integrity. We mapped those principles to a requisition event chain, then challenged it with an urgent replacement, a changed location, a revised qualification, a withdrawn budget approval, and two simultaneous drafts. This is workflow research, not legal advice or a statement that every cited rule applies to every employer.' },
      { heading: 'Facts, analysis, and inference', body: 'The cited sources establish broad facts: hiring practices should be applied consistently, sensitive information needs governance, and reliable controls depend on documented responsibility and usable records. They do not prescribe the exact requisition ledger described here. Our analysis is that version, authority, and effective time must be separate fields. Our inference is that a coordinator can safely act when one record links the approved business request to the current recruiting instructions and identifies unresolved changes. Uncertainty remains when approvals occur in informal channels, when local law changes required content, or when the employer has no written delegation. In those cases, the honest state is approval unresolved, not approved by recency.' },
      { heading: 'The minimum approval chain', body: 'A reviewable chain begins with a stable requisition identifier and records the requesting owner, business reason category, job profile reference, worker type, location, reporting owner, approved range or range authority, recruiting stages, required reviewers, requested start window, and budget or headcount decision. Each revision needs a version identifier, author, timestamp, changed fields, reason, and named approver. The active version should point to the evidence of approval rather than copy a vague approved label from another tracker. If finance approves headcount but HR has not approved a changed qualification, the ledger should show split authority. One partial approval must not silently authorize every field.' },
      { heading: 'Why the latest file can be wrong', body: 'File modification time measures storage activity, not decision authority. A coordinator may download a document, convert its format, correct punctuation, or add interview availability after approval. Those actions can make a file newer without changing the authorized job. Conversely, a manager may approve a change in a system whose exported document still shows an earlier timestamp. The control should therefore compare stable version identifiers and approval events, not filenames such as final or final-two. When a changed field could alter who is sourced or screened, pause new action at the affected stage and route the difference. Already completed activity should remain visible rather than being rewritten to look as if the new criteria always applied.' },
      { heading: 'Coordinator permissions and decision boundary', body: 'A Philippines-based coordinator can create the requisition record from an approved template, check required fields, compare a proposed revision with the active version, link supporting approvals, publish approved scheduling details, and flag work performed under a superseded instruction. The coordinator should not create headcount, select a compensation range, decide worker classification, add a preferred qualification, resolve a conflict between HR and a hiring manager, or infer approval from silence. They may correct a clerical error only through the employer-defined correction rule. Every exception needs the missing decision, authorized owner, permitted holding action, and next checkpoint. This keeps fast administrative support from becoming an invisible hiring-policy layer.' },
      { heading: 'A practical version-state model', body: 'Use states that describe evidence: draft, submitted for named review, partially approved, approved but not effective, active, superseded, withdrawn, and closed. Avoid ready when it could mean complete fields, available budget, or permission to source. Record field-level differences when the effect is material. A title punctuation correction may not require the same route as a location, qualification, or worker-type change, but that distinction must come from a written employer rule. Link candidates and outreach batches to the version used. If a version changes during sourcing, the hiring owner decides whether earlier candidates remain in scope; the coordinator records and executes that decision without independently re-screening people.' },
      { heading: 'Control test and measurements', body: 'Test the model with five redacted cases: a duplicate requisition, an approved replacement with an unapproved range, a location change after outreach, a qualification change after interviews begin, and a withdrawn opening with scheduled candidates. Give the evidence to a second reviewer and ask which version was active at each event, what work was permitted, and who owned each unresolved choice. Useful measures include actions linked to an active version, unresolved field conflicts, time awaiting a named owner, and corrective actions after supersession. Do not rank coordinators by raw throughput because a properly paused requisition can require more control work than a clean one. Publish definitions, denominators, exclusions, and the review window.' },
      { heading: 'Implementation sequence', body: 'Begin with one active requisition and inventory every place where its instructions appear. Choose the employer-controlled system of record, assign field-level approvers, and define which changes stop sourcing or scheduling. Migrate only the current authorized version and preserve older evidence through controlled links. Train the coordinator and backup on two known conflicts, then require the hiring owner to review the first complete audit trail. After the pilot, compare candidate communications and interview activity with the version ledger. Fix any unlabeled copy or undocumented approval before expanding. A weekly review should focus on open conflicts and superseded work, not merely on how many requisitions moved forward.' },
      { heading: 'Privacy, access, and retention', body: 'The coordination ledger needs job and authorization data, not private manager commentary about candidates or employees. Limit access to the people who approve or administer the requisition. Candidate records should remain linked by approved identifiers rather than copied into the approval log. Retention must follow the employer’s applicable policy and legal obligations; OFCCP requirements matter only where coverage and circumstances make them relevant. Preserve superseded versions when required to explain actions, but do not keep uncontrolled email copies merely because they are convenient. A record hold, complaint, audit, or investigation can change ordinary disposition, so the qualified owner must decide those exceptions.' },
      { heading: 'Limitations and uncertainty', body: 'Employers use different applicant-tracking, finance, HR, and document systems. Approval authority depends on organization design, jurisdiction, contracts, and regulatory coverage. A complete ledger does not prove that criteria are lawful, job related, inclusive, affordable, or strategically sound. Timestamps can reflect integration delays, and electronic approval can be delegated or compromised. Small samples may miss inconsistent treatment. The model also cannot decide whether a changed requirement should apply to people already in process. It makes the decision path visible and reproducible. HR, finance, legal, and hiring owners remain accountable for the underlying authorization and selection rules.' },
      { heading: 'Evidence-led conclusion', body: 'Recruiting operations should use the version with traceable field-level authority and effective status, not whichever file looks newest. A stable requisition identifier, visible revisions, separate approvers, and candidate-to-version links let an employer reconstruct what instruction governed each action. Human Resources Outsourced can support this work through a Philippines-based coordinator who checks completeness, maintains the ledger, schedules approved steps, and escalates conflicts. The employer retains control of headcount, budget, qualifications, compensation, classification, and candidate decisions. The recommended first step is a pilot on one opening with one primary approver and a documented fallback, followed by an independent reconstruction before the control expands.' },
    ],
    sources: [eeocHiring, eeocRecords, ofccpRecords, nistPrivacy, nistSecurity, gaoControls, naraRecords, ftcData],
    serviceLink: { title: 'Candidate sourcing with approved criteria', href: '/services/candidate-sourcing', body: 'Use a bounded sourcing lane that keeps shortlist and selection decisions with the employer.' },
  },
  {
    slug: 'conditional-offer-version-acceptance-evidence',
    title: 'Conditional Job Offers: Preserve Version, Conditions, and Acceptance Evidence',
    excerpt: 'Research on coordinating offer records without letting administrative status stand in for a hiring or eligibility decision.',
    published,
    sections: [
      { heading: 'Research question', body: 'What evidence allows a recruiting coordinator to say that a candidate received and accepted the current conditional offer without claiming that every condition is satisfied or that employment has begun? An offer can pass through compensation approval, document generation, candidate delivery, questions, revision, signature, background review, and start-date coordination. Each event has a different owner and meaning. The research question focuses on administrative truth: which version was authorized, what the candidate received, what response referred to that version, and which conditions remain with qualified owners? It excludes the legal validity of the offer, the fairness of a condition, and the decision to hire, rescind, negotiate, or waive a requirement.' },
      { heading: 'Methodology and source scope', body: 'We synthesized official EEOC hiring and pre-employment inquiry materials with FTC background-check guidance, NIST privacy and security frameworks, GAO internal-control concepts, and National Archives records principles. The sources establish important boundaries around hiring consistency, medical inquiries, third-party consumer reports, protected information, authorization, and reliable records. They do not provide one universal offer workflow. We converted recurring principles into an event model and tested it against a revised salary, a changed start date, a candidate counterquestion, a background-screen condition, a post-offer medical step, and an expired response window. No employee-level data or outcome claims were used.' },
      { heading: 'Facts, analysis, and inference', body: 'EEOC guidance distinguishes pre-offer and post-conditional-offer treatment of certain medical questions, while FTC guidance describes required steps when an employer uses covered consumer reports. Those are factual regulatory contexts, subject to coverage and jurisdiction. Our analysis is that the offer document, acceptance event, and condition-resolution events must remain separate. Our inference is that an administrative status can safely report accepted only when it identifies a specific authorized version and a valid response channel. It should not render cleared, eligible, or hired unless the employer defines that state and the authorized owner supplies the underlying decision. Where rules conflict or coverage is unclear, legal or HR review is required.' },
      { heading: 'Separate the offer from its conditions', body: 'The offer record should carry a stable candidate and requisition reference, version identifier, authorized issuer, issue time, delivery channel, response deadline, proposed role and terms, listed conditions, and links to restricted supporting records. Each condition needs its own owner, permitted statuses, decision evidence, and effective time. A signed offer can prove a response to stated terms; it does not prove that a background review, work authorization step, medical inquiry, reference, or internal approval is complete. Likewise, completion of one condition does not authorize the coordinator to mark the entire offer unconditional. The final transition should come from the employer’s designated hiring owner.' },
      { heading: 'Version drift after delivery', body: 'A frequent failure occurs when a candidate signs version one after version two has been prepared. Another occurs when a recruiter confirms a new start date in email but the signed document retains the old date. The ledger should retain both records, show what changed, record who approved the change, and connect the candidate’s response to the version actually presented. Do not overwrite the earlier document or transfer its signature to a revised version. If the employer treats a written clarification as an amendment, that rule and its approving authority must be explicit. Until then, the coordinator should report a version mismatch and request a decision rather than describing acceptance as complete.' },
      { heading: 'Coordinator permissions and red lines', body: 'A Philippines-based coordinator can populate an approved template from the authorized requisition, run a defined field comparison, route the draft for review, send the authorized version through the approved channel, record delivery and response events, schedule owner follow-up, and maintain a condition checklist. The role should not negotiate compensation, interpret restrictive language, decide whether a candidate met a condition, ask prohibited or sensitive questions, waive a deadline, promise a start date, rescind an offer, or infer acceptance from an informal message. Candidate questions that affect terms, medical information, background results, accommodation, or legal rights go to the named qualified owner with minimum necessary detail.' },
      { heading: 'Status language that resists overclaiming', body: 'Use precise states such as draft awaiting approval, authorized to send, delivered, delivery failed, candidate question open, response received for version, revision required, accepted version pending conditions, declined, expired, and employer decision required. Avoid successful, cleared, locked, or good to go because those labels compress several judgments. A dashboard can show the current administrative state while restricted condition details remain in their approved systems. If a deadline passes, expired should describe the response window, not a decision to reject the person. Only the employer’s authorized owner decides the consequence and whether a later response can be considered.' },
      { heading: 'Validation exercise and measures', body: 'Build a synthetic test set with a clean acceptance, a revised term, a missing signature, a failed delivery, a candidate question, and conflicting start dates. Ask an independent reviewer to identify the operative version, last proven event, unresolved owner, and next permitted action. Then test whether the public-facing or management status overstates any condition. Useful measures include delivery confirmation by version, open candidate questions, version mismatches, condition-owner aging, and cases reopened after apparent acceptance. Measures should not score candidates for negotiating, asking questions, seeking accommodation, or taking the available response time. Those actions are not administrative defects.' },
      { heading: 'Implementation sequence', body: 'Select one offer template and map every populated field to an approved source. Name the people who can authorize terms, release the document, answer candidate questions, resolve each condition, and confirm the final transition. Configure the broad tracker to hold event metadata only, with restricted links for sensitive evidence. Test a revision after delivery and a response to an obsolete version before sending a live offer. During the first cycle, review every status change with the owner and compare the candidate-facing record with the ledger. Expand only after another reviewer can reproduce the current terms, open conditions, and next action without relying on private chat or memory.' },
      { heading: 'Privacy and record handling', body: 'The general offer tracker should contain only the fields needed to coordinate the process. Medical information, background reports, identity documents, and sensitive explanations require narrower systems and access. NIST and FTC guidance support purpose-limited handling and reasonable safeguards; applicable law and employer policy determine specific duties. Use named accounts, controlled links, and an audit trail. Avoid attaching restricted reports to broad recruiting tickets. Preserve the authorized offer and relevant response evidence under the employer’s retention schedule, and stop ordinary disposition when a qualified owner places a hold. The coordinator records the hold state without needing access to the confidential reason.' },
      { heading: 'Limitations and uncertainty', body: 'Offer requirements differ by country, state, worker type, employer policy, contract, collective agreement, and regulated role. Electronic-signature tools produce different evidence, and delivery does not prove reading or understanding. A version-perfect record cannot establish that terms are lawful, that consent is valid, that a condition is appropriate, or that a decision is nondiscriminatory. Regulatory guidance can change, and local rules may add notices or timing duties. The model therefore supports coordination and review, not legal conclusions. Employers should validate templates, status definitions, conditions, deadlines, and decision authority with qualified advisers for their actual hiring locations.' },
      { heading: 'Evidence-led conclusion', body: 'A trustworthy conditional-offer process preserves the authorized version, delivery event, candidate response, open questions, and each condition as distinct evidence. This prevents a signature from being mistaken for final clearance and prevents a later draft from being mistaken for the accepted terms. Human Resources Outsourced can provide Philippines-based administrative support for template population, version checks, delivery tracking, scheduling, and exception routing. The employer keeps authority over terms, negotiation, sensitive inquiries, condition outcomes, rescission, and the final hiring decision. Pilot the model with one offer type and require a second person to reconstruct the case before using the states in management reporting.' },
    ],
    sources: [eeocHiring, eeocQuestions, eeocRecords, ftcBackground, nistPrivacy, nistSecurity, gaoControls, naraRecords],
    serviceLink: { title: 'Interview coordination through the employer-owned decision line', href: '/services/interview-coordination', body: 'Keep candidate communications and scheduling moving while the employer controls offer terms and selection.' },
  },
  {
    slug: 'background-screen-handoff-status-boundaries',
    title: 'Employment Background Screens: Design Status Handoffs Without Making the Decision',
    excerpt: 'A control study for coordinating consent, vendor events, disputes, and employer review without exposing report content.',
    published,
    sections: [
      { heading: 'Research question', body: 'How can an outsourced recruiting coordinator track an employment background screen without interpreting the report or collapsing required employer actions into a vendor status? The workflow may include disclosure, authorization, vendor submission, identity matching, report completion, a candidate dispute, pre-adverse-action steps, employer review, and final communication. The vendor and employer do not own the same decisions. This study asks which minimum events let administration move safely across time zones while keeping report content, legal analysis, and employment judgment with qualified owners. It does not decide whether a screen is permitted, what standards apply, or what outcome an employer should reach.' },
      { heading: 'Methodology and source scope', body: 'We reviewed current official FTC guidance for employers using consumer reports, EEOC background-check and hiring guidance, NIST privacy and cybersecurity frameworks, GAO control concepts, and National Archives records principles. FTC and EEOC materials describe federal contexts for covered reports and nondiscrimination, while noting that other rules may apply. NIST, GAO, and records guidance inform access, responsibility, and evidence handling. We mapped the sources to a status handoff and tested it with missing authorization, vendor delay, possible identity mismatch, completed report, candidate dispute, and an employer contemplating an adverse action. The research is operational and cannot replace jurisdiction-specific counsel.' },
      { heading: 'Facts, analysis, inference, and uncertainty', body: 'FTC guidance says employers using covered consumer reports must follow steps that include disclosure and permission, and additional steps before and after certain adverse actions. EEOC guidance states that background information cannot be used in a discriminatory manner. These are source-backed facts at a general federal level. Our analysis is that vendor completion is merely a delivery event, not a hiring conclusion. Our inference is that broad tracking needs only process metadata, while report content should remain restricted. Uncertainty arises around report type, employer coverage, local fair-chance rules, role-specific law, and the content of any dispute. Those uncertainties belong with legal, HR, or authorized hiring owners.' },
      { heading: 'Build an event chain, not a pass-fail field', body: 'The coordination record should distinguish approved screening request, disclosure version, authorization received, vendor order identifier, submission time, vendor receipt, information requested, candidate response, report available, restricted owner notified, dispute or correction open, employer action pending, required communication owned, and process closed. Avoid pass, fail, red flag, or clear unless an authorized employer policy defines the term and the proper owner records it. Even then, expose the minimum status to the coordination lane. A vendor label can reflect data availability or automated rules, and the coordinator should not translate it into candidate suitability or employment eligibility.' },
      { heading: 'Identity mismatches and candidate disputes', body: 'A mismatch can arise from common names, changed names, incomplete identifiers, source errors, or vendor processing. The coordinator may route an approved request for missing administrative information and record that a dispute channel was provided. They should not decide that a record belongs to the candidate, ask for extra sensitive data outside the approved process, summarize disputed content in a ticket, or tell the hiring team that the candidate was deceptive. Preserve the original vendor event and subsequent correction as linked records. If the employer pauses a decision during review, record the authorized pause and owner without guessing what the final outcome will be.' },
      { heading: 'Coordinator permissions and escalation', body: 'A Philippines-based coordinator can confirm that the employer-approved process version is in use, check that required administrative steps are recorded, submit an authorized vendor order, monitor non-substantive status, send approved reminders, restrict links, and alert the designated owner when a report or dispute event arrives. The coordinator should not select screening criteria, review report substance, assess job relevance, compare candidates, recommend adverse action, draft legal notices beyond approved templates, or promise a result date. Escalations should identify the missing event and requested owner action. They should not reproduce report details in email, chat, or a general applicant-tracking note.' },
      { heading: 'Time zones and queue design', body: 'Cross-time-zone support is useful when the queue makes waiting states explicit. At shift end, each case should show the last verified event, the system holding restricted content, the next checkpoint, the decision owner, and what the next coordinator may do. A report that arrives during the Philippines workday can be secured and routed without being opened by the coordinator. A candidate question can be acknowledged using approved language while the qualified owner is offline. Silence must not advance the case. Automated reminders should stop when a dispute, accommodation, legal review, or other protected exception state is active.' },
      { heading: 'Validation and monitoring', body: 'Use synthetic cases for missing authorization, failed vendor delivery, duplicate order, mismatched identity, candidate dispute, and owner consideration of an adverse action. Ask two reviewers to reconstruct what happened using only permitted metadata. Confirm that neither can infer sensitive content from a broad status. Measure orders tied to the approved process, unresolved vendor exceptions, time awaiting an owner, duplicate submissions prevented, and restricted-content exposure incidents. Do not measure candidate quality, risk, or honesty from operational events. Review both fast and slow cases because a rapid vendor response can still enter the wrong workflow or reach an unauthorized person.' },
      { heading: 'Implementation sequence', body: 'Start by documenting one vendor connection, one job family, and one employer-approved screening process. Inventory integration statuses and translate each into a neutral event description without changing its meaning. Confirm who may order, open, interpret, communicate about, and dispose of the report. Configure restricted links and test access with the coordinator account rather than assuming role settings work. Run a duplicate-order and candidate-dispute simulation, then inspect notifications, exports, and audit logs. For early live cases, the qualified owner should review every transition. Close the pilot only after the owner can match vendor history, broad tracker metadata, candidate communications, and final employer action without exposing report content to the support queue.' },
      { heading: 'Security, privacy, and retention', body: 'Background information is sensitive. Apply least access, named accounts, secure vendor links, controlled exports, and logging appropriate to the employer’s risk. The operational tracker usually needs an identifier, process version, event state, timestamp, and owner, not the report itself. Retention and disposal depend on applicable law, litigation or complaint holds, vendor contracts, and employer policy. FTC guidance addresses secure handling and disposal in covered contexts, but the qualified owner must set the rule for the actual organization. A coordinator can execute an approved schedule and document completion; they should not decide that a hold is unnecessary.' },
      { heading: 'Limitations', body: 'Federal guidance is only part of the picture. State, local, sector, and international rules may affect timing, permissible checks, notices, consent, data transfer, and decision criteria. Not every screening product is treated the same way, and vendor terminology is inconsistent. System timestamps may not show when a person reviewed a record. Administrative evidence cannot establish accuracy, job relatedness, business necessity, fairness, or compliance in an individual case. The model reduces ambiguity about process ownership but does not validate an employer’s screening policy. Qualified counsel and HR leaders must review the real workflow and its jurisdictions.' },
      { heading: 'Evidence-led conclusion', body: 'The safest coordination model treats a background screen as a sequence of governed events, not a pass-fail result. It separates disclosure and authorization, vendor processing, restricted report availability, disputes, employer review, communications, and closure. Human Resources Outsourced can support this lane with Philippines-based administration that monitors events, protects links, sends approved reminders, and hands exceptions to named owners. The employer retains criteria, report interpretation, required notices, individualized assessment, and hiring decisions. Start with one vendor and one job family, then independently test whether every status can be reproduced without revealing report content or expanding coordinator authority.' },
    ],
    sources: [ftcBackground, eeocHiring, eeocRecords, nistPrivacy, nistSecurity, gaoControls, naraRecords, ftcData],
    serviceLink: { title: 'Candidate sourcing with controlled records', href: '/services/candidate-sourcing', body: 'Keep factual sourcing administration separate from screening and selection decisions.' },
  },
  {
    slug: 'employment-reference-check-provenance',
    title: 'Employment Reference Checks: Preserve Authorization and Response Provenance',
    excerpt: 'Research on reference-check coordination that separates verified communications from candidate evaluation.',
    published,
    sections: [
      { heading: 'Research question', body: 'What can an administrative coordinator reliably prove about an employment reference check, and what remains a hiring judgment? Reference workflows are vulnerable to wrong contacts, inconsistent questions, informal side channels, unverifiable responses, excessive personal information, and notes that blur fact with opinion. A Philippines-based coordinator may improve follow-up coverage, but time-zone availability does not authorize them to select references, change questions, assess credibility, or weigh a response. This study asks how to preserve candidate authorization, contact provenance, questionnaire version, response channel, and employer ownership so the hiring team can review evidence without treating the coordinator as an investigator or decision maker.' },
      { heading: 'Methodology and source scope', body: 'We synthesized official EEOC hiring and recordkeeping guidance, FTC privacy and data-security materials, NIST privacy and cybersecurity frameworks, GAO internal-control principles, and National Archives records guidance. These sources support consistent process, controlled collection, defined responsibility, and trustworthy records. They do not create a universal reference-check requirement or prescribe questions for a particular job. We translated the principles into a provenance model and tested candidate-supplied contacts, employer-directory contacts, bounced messages, delegated responders, phone responses, unsolicited sensitive detail, and contradictory references. We used no real candidate data and make no claim about predictive validity.' },
      { heading: 'Fact, analysis, inference, and uncertainty', body: 'A factual coordination record can establish that a candidate supplied or authorized a contact, a message went to a particular address, a named person responded through a channel, and the response used a particular questionnaire version. It cannot by itself establish the responder’s identity, authority, truthfulness, or relevance. Our analysis is that provenance must travel with the response. Our inference is that uncertainty should be recorded directly instead of converted into a credibility score. EEOC guidance supports consistent treatment, but it does not validate a reference question or selection rule. Employers must decide job relevance, lawful use, and how conflicting information affects the hiring process.' },
      { heading: 'Define the evidence chain', body: 'Create a stable check identifier linked to the candidate and requisition. Record the authorization source and time, contact source, approved contact details, relationship category supplied by the candidate or employer, questionnaire version, outreach events, delivery results, responder identity claim, response channel, receipt time, restricted response location, verification steps permitted by policy, and hiring-owner acknowledgment. Keep unverified and verified as evidence states, not conclusions about honesty. If a responder delegates to another person, preserve both the referral and the new response rather than silently replacing the original contact.' },
      { heading: 'Consistent questions without mechanical judgment', body: 'The employer should approve question sets by job family or defined purpose and identify questions that require qualified review. The coordinator can select the approved version based on the requisition field, send it, and flag missing or out-of-scope answers. They should not improvise follow-up questions, ask about protected characteristics or medical history, solicit off-record commentary, or convert narrative answers into a candidate score unless the employer has a validated, authorized method and assigns that work. Consistency does not mean ignoring context. It means deviations are visible, owned, and reviewed rather than arising from whoever happened to conduct the check.' },
      { heading: 'Handling unexpected information', body: 'References can volunteer health, family, age, religion, national origin, complaints, rumors, or other sensitive and potentially irrelevant material. The coordinator should stop unnecessary collection, restrict the record, and route it under the employer’s written escalation rule. Do not repeat the detail in a general tracker or summarize it for convenience. A neutral event such as restricted information received can alert the qualified owner without broadening exposure. The hiring owner and, where needed, counsel decide relevance, permitted use, and any candidate communication. The support role records the route and preserves the original evidence according to policy.' },
      { heading: 'Coordinator permissions and boundaries', body: 'A Philippines-based coordinator can confirm an approved authorization is present, validate required administrative fields, use the approved contact source, send standard requests, schedule calls for an authorized interviewer, record delivery, transcribe only under a defined protocol, store responses in the approved system, and chase missing acknowledgments. They should not impersonate the employer, use personal accounts, search for undisclosed contacts, judge tone, verify disputed claims through independent investigation, decide that a reference is acceptable, or recommend selection. If identity or authority cannot be established through the approved steps, label the uncertainty and return it to the hiring owner.' },
      { heading: 'Testing provenance and handoffs', body: 'Build redacted or synthetic cases for a valid written response, a personal email address, a delegated responder, a phone callback from a different number, an unanswered request, and unsolicited sensitive detail. Ask a second reviewer to identify what is proven, what is merely claimed, what information should be restricted, and which owner acts next. Measure approved-questionnaire use, responses with complete provenance, unresolved identity questions, restricted-detail exposures, and time waiting for the hiring owner. Do not measure coordinators on positive-reference rates or penalize candidates for unreachable contacts without an employer-approved interpretation.' },
      { heading: 'Implementation sequence', body: 'Choose one job family and approve a single question set, contact-source rule, candidate authorization record, response system, and exception owner. Disable personal messaging channels for the pilot. Test how the workflow handles a delegated responder and unexpected sensitive statement before contacting a live reference. Review the first cases jointly with the hiring owner, comparing the original communications with the provenance fields. Correct gaps in identity claims, timestamps, questionnaire versions, and restricted storage. Only then allow routine follow-up across shifts. A periodic sample should include unanswered and contradictory cases, because reviewing only clean responses can hide unsafe improvisation and unrecorded side conversations.' },
      { heading: 'Interpretation discipline', body: 'Reference administration should report process quality separately from response substance. A complete, authenticated response can still be irrelevant or biased, while an incomplete response can reflect contact policy rather than candidate behavior. If managers want a summary, the employer must define who writes it, which source statements it may contain, how uncertainty is represented, and who checks it against the original. The coordinator should never normalize tone, remove caveats, or blend multiple references into one apparent consensus. Preserving disagreement and missing evidence gives the hiring owner a more honest record and reduces the chance that administrative neatness will be mistaken for reliable evaluation.' },
      { heading: 'Privacy, access, and retention', body: 'Collect only information needed for the approved reference purpose. Use named accounts and employer-controlled channels, and separate contact metadata from response content where practical. Limit response access to the hiring roles that need it. Retention must follow the employer’s applicable recordkeeping obligations, policy, and holds; a coordinator should not keep a private working copy. Data transfers involving an overseas support team require employer-approved systems and safeguards. NIST and FTC materials offer risk-management principles, while the employer must determine the actual control set, vendor terms, jurisdictional requirements, and approved disposition evidence.' },
      { heading: 'Limitations', body: 'A provenance record does not make a reference accurate or useful. People may misunderstand questions, speak outside their authority, provide incomplete memories, or use channels that are hard to authenticate. Some employers restrict what references may disclose. Local law, contracts, and regulated roles can change the available process. Consistency checks cannot eliminate bias, and a small operational sample cannot demonstrate predictive validity. The model also cannot determine whether a candidate must supply a particular reference or receive a chance to respond. Those are employer policy and legal questions, not administrative defaults.' },
      { heading: 'Evidence-led conclusion', body: 'Reference-check administration is reliable when authorization, contact source, question version, response channel, identity claim, restricted content, and owner review remain linked. The coordinator can prove the communication history and surface uncertainty, but cannot prove the truth of a statement or its hiring significance. Human Resources Outsourced can provide Philippines-based follow-up, scheduling, record control, and exception routing within approved systems. The employer retains question design, identity standards, relevance analysis, candidate communication, and selection decisions. A bounded pilot should use one question set and require an independent reviewer to reconstruct both a routine response and a sensitive exception.' },
    ],
    sources: [eeocHiring, eeocRecords, nistPrivacy, nistSecurity, gaoControls, naraRecords, ftcData],
    serviceLink: { title: 'Candidate sourcing with factual, source-linked records', href: '/services/candidate-sourcing', body: 'Use a bounded research lane while the employer keeps evaluation and shortlist authority.' },
  },
  {
    slug: 'applicant-accommodation-routing-privacy',
    title: 'Applicant Accommodation Requests: Route the Need Without Spreading Sensitive Detail',
    excerpt: 'A research-backed workflow for coordinating accessible hiring steps while keeping medical and legal decisions with qualified owners.',
    published,
    sections: [
      { heading: 'Research question', body: 'How can a recruiting coordinator respond when an applicant asks for a change to the application or interview process without collecting excessive medical detail or deciding whether an accommodation is required? The request may arrive in a scheduling email, application form, phone call, or recruiter message. It can affect timing, location, technology, communication method, or assessment format. A quick administrative response matters, yet the wrong follow-up can expose sensitive information or move a legal and employment decision to an unauthorized person. This study asks what minimum evidence supports acknowledgment, privacy-preserving routing, logistical execution, and closure while keeping substantive judgment with the employer’s qualified owner.' },
      { heading: 'Methodology and source scope', body: 'We reviewed current official EEOC guidance on recruiting, pre-employment inquiries, disability-related questions, and recordkeeping, then combined it with NIST privacy and cybersecurity frameworks, GAO internal-control concepts, FTC data-security guidance, and National Archives records principles. EEOC materials distinguish important boundaries in the hiring process, including limits on pre-offer medical questions and the need for assistance in some application contexts. The other sources inform minimization, access, ownership, and evidence. We tested the model against interview access, scheduling, communication, assessment-format, and unsolicited medical-detail scenarios. This operational synthesis does not decide legal entitlement or a specific accommodation.' },
      { heading: 'Facts, analysis, inference, and uncertainty', body: 'EEOC guidance states that employers may need to accommodate applicants in the hiring process and places restrictions on disability-related questions before an offer. It also gives examples such as assistance with an application or rescheduling in appropriate circumstances. Those facts are subject to employer coverage and individual context. Our analysis is that the broad recruiting queue needs the requested process change and routing state, not a diagnosis. Our inference is that a coordinator can acknowledge and arrange an approved logistical change without owning the underlying eligibility decision. Uncertainty about necessity, reasonableness, documentation, alternatives, hardship, or legal scope belongs with qualified HR, accommodation, or legal owners.' },
      { heading: 'Design a minimum-necessary intake', body: 'The intake record should capture the candidate and requisition identifiers, affected hiring step, requested process change in the applicant’s own functional terms, preferred contact channel, timing constraint, receipt event, restricted-detail flag, assigned owner, acknowledgment, approved action, execution evidence, and follow-up state. Do not require a diagnosis, medical history, medication list, or broad explanation in the general recruiting form. If the person volunteers sensitive detail, place it in the approved restricted channel and leave only a neutral reference in the operational queue. The qualified owner defines when additional information may be requested and who may see it.' },
      { heading: 'Separate routing from adjudication', body: 'Routing asks which authorized owner and process should receive the request. Adjudication asks what the employer must or will provide. The coordinator may perform the first but should not perform the second unless the employer has explicitly assigned a qualified role and appropriate training. A request for captions, an accessible room, extra time, a support person, a different communication channel, or schedule flexibility can often be described functionally. The coordinator acknowledges receipt, prevents automatic closure, and sends the request to the named owner. They should not demand proof, challenge the request, promise an outcome, rank urgency by perceived disability, or tell interviewers unnecessary details.' },
      { heading: 'Executing an approved change', body: 'Once the authorized owner records an approved logistical instruction, the coordinator can update the calendar, reserve the specified resource, confirm the accessible channel, send approved candidate-facing language, notify only participants who need an operational fact, and record completion. The coordinator should not reveal why the change was made. Interviewers may need to know that a session will use captions or a changed format, but not the candidate’s medical information. If the requested resource fails, reopen the task and notify the owner rather than marking the interview complete. The operational record should distinguish approved, arranged, candidate confirmed, delivered, failed, and owner review required.' },
      { heading: 'Cross-time-zone handoff', body: 'A Philippines-based team can provide useful coverage when requests arrive outside the employer owner’s hours. The shift handoff should state the last verified event, time-sensitive hiring step, restricted record location, assigned owner, safe acknowledgment already sent, holding action, and next checkpoint. It should not summarize medical detail or treat the absence of an immediate owner response as denial or approval. Automated reminders and ordinary scheduling sequences should pause when they could conflict with the request. A backup owner must be defined for imminent interviews, but that person’s authority should be tested before the urgent case occurs.' },
      { heading: 'Control test and measures', body: 'Use synthetic cases for an accessible interview platform, a religious scheduling conflict, an application assistance request, volunteered medical detail, an unclear request, and a resource failure. Ask two reviewers to identify the minimum record, proper owner, permitted acknowledgment, disclosure boundary, and proof of implementation. Track time to acknowledgment, time to qualified-owner assignment, approved changes implemented before the event, preventable disclosure incidents, reopened logistics, and requests stalled without a named owner. Do not publish small-group breakdowns that could identify candidates. Do not use accommodation volume or type as a candidate-quality, recruiter-performance, or workforce-planning signal.' },
      { heading: 'Implementation sequence', body: 'Inventory every channel where an applicant can request help and place the same privacy-preserving routing instruction at each entry point. Name a primary and backup qualified owner, define a safe acknowledgment, and decide how ordinary automation pauses. Configure separate operational and restricted records, then test calendar descriptions, notifications, exports, and interviewer permissions. Run the resource-failure and out-of-hours scenarios before launch. During the first live requests, review the entire trail after the hiring step and ask whether the applicant had to repeat sensitive information. Revise the intake or handoff that caused duplication, delay, or unnecessary disclosure before adding more recruiters, locations, or assessment tools.' },
      { heading: 'Candidate communication quality', body: 'An acknowledgment should be prompt, neutral, and specific about the next process step without demanding explanation or promising an outcome. It should confirm the channel for further information and identify how urgent scheduling conflicts will be handled. Once an action is approved, candidate-facing communication should describe the logistical arrangement, date, and contact for problems. Avoid labels that disclose or characterize the request. If the applicant corrects the coordinator’s understanding, preserve the correction and update the functional need rather than treating it as inconsistency. Communication quality can be sampled for accuracy, privacy, and accessibility, but it should not be scored by whether the applicant accepted the proposed arrangement.' },
      { heading: 'Privacy, security, and records', body: 'Restrict sensitive applicant information by purpose and role. Use employer-controlled accounts, approved systems, controlled links, and access logging. Keep operational scheduling notes separate from confidential medical or accommodation records. Retention must reflect applicable law, EEOC requirements where relevant, employer policy, and any complaint or litigation hold. A general deletion timer should not override a qualified hold decision. The support team may execute approved filing and disposition steps and retain evidence that the step occurred, but should not decide the legal record category. Privacy review should include overseas access, exports, notification settings, and what appears in calendar invitations.' },
      { heading: 'Limitations and uncertainty', body: 'Accommodation duties and permitted inquiries depend on jurisdiction, employer coverage, hiring stage, request, role, and individual facts. Religious, disability, pregnancy-related, language-access, and other requests may follow different standards. Technology advertised as accessible may fail for a particular person. A completed logistical checklist does not prove effective access or legal compliance. Applicants may change their preferred solution, and coordinators may misunderstand functional language. The model cannot determine reasonableness, undue hardship, essential functions, documentation needs, or remedies. It creates a safer administrative path to the people who can make and review those decisions.' },
      { heading: 'Evidence-led conclusion', body: 'Applicant accommodation coordination should collect the functional process need, restrict sensitive detail, assign a qualified owner, and preserve the difference between acknowledgment, decision, arrangement, delivery, and follow-up. Human Resources Outsourced can support this workflow through Philippines-based monitoring, approved communications, scheduling changes, resource coordination, and evidence maintenance. The employer retains legal interpretation, information requests, approval, alternatives, interviewer guidance, and hiring decisions. Begin with one interview workflow, test the backup-owner route and a failed-resource scenario, then review the record for unnecessary detail before expanding the model to other hiring stages.' },
    ],
    sources: [eeocHiring, eeocQuestions, eeocRecords, nistPrivacy, nistSecurity, gaoControls, naraRecords, ftcData],
    serviceLink: { title: 'Interview coordination with clear escalation boundaries', href: '/services/interview-coordination', body: 'Coordinate approved logistics while the employer keeps accommodation and hiring decisions.' },
  },
];
