import type { ResearchPost } from '../fleet-data';

const date = '2026-09-02';
const thumbnail = '/research-heroes/august31-hr-controls-research.svg';
const sources = [
  { name: 'NIST Privacy Framework', url: 'https://www.nist.gov/privacy-framework' },
  { name: 'NIST Cybersecurity Framework 2.0', url: 'https://www.nist.gov/cyberframework' },
  { name: 'GAO Green Book', url: 'https://www.gao.gov/green-book' },
  { name: 'National Archives records management', url: 'https://www.archives.gov/records-mgmt' },
  { name: 'EEOC recordkeeping requirements', url: 'https://www.eeoc.gov/employers/recordkeeping-requirements' },
  { name: 'Department of Labor recordkeeping fact sheet', url: 'https://www.dol.gov/agencies/whd/fact-sheets/21-flsa-recordkeeping' },
  { name: 'FTC data security guidance', url: 'https://www.ftc.gov/business-guidance/privacy-security/data-security' },
  { name: 'CISA Cybersecurity Performance Goals', url: 'https://www.cisa.gov/cybersecurity-performance-goals' },
  { name: 'ICO data minimisation guidance', url: 'https://ico.org.uk/for-organisations/uk-gdpr-guidance-and-resources/data-protection-principles/a-guide-to-the-data-protection-principles/' },
  { name: 'ILO working time and work organization', url: 'https://www.ilo.org/topics-and-sectors/working-time-and-work-organization' }
];

type Study = { slug: string; title: string; excerpt: string; question: string; method: string; finding: string; model: string; test: string; limits: string; conclusion: string };

const studies: Study[] = [
  { slug: 'hr-source-record-confidence-scoring', title: 'Source Record Confidence Scoring in HR Operations', excerpt: 'Research on how HR support teams can compare source authority, recency, approval, and destination confirmation without hiding disagreement behind one confidence score.', question: 'Can a confidence score help an HR coordinator route conflicting records without making the underlying decision?', method: 'The analysis compares privacy, internal-control, security, and records-management guidance. It treats confidence as a routing aid built from visible evidence, not a prediction that a record is correct.', finding: 'A single numeric score can conceal the reason for uncertainty. A usable assessment keeps source authority, effective date, approval state, identity match, and destination confirmation as separate observations.', model: 'Create a comparison record for each disputed value. Show the incoming source, controlling-source candidate, timestamps, named owner, unresolved difference, and owner disposition. Use labels such as verified, incomplete, conflicting, or awaiting confirmation instead of an unexplained percentage.', test: 'Run the model against a corrected start date, duplicate employee profile, manager change, retroactive status update, and an update confirmed in only one destination. Check whether a reviewer can reconstruct why work stopped.', limits: 'The model cannot determine which employment record is legally controlling. Source hierarchies and effective-date rules vary by employer and system, and a confident administrative assessment can still be wrong.', conclusion: 'Confidence is useful only when its components remain visible. HR support teams should route the evidence and disagreement to an accountable owner, then preserve the decision that allowed downstream work to continue.' },
  { slug: 'hr-queue-closure-reopen-rates', title: 'What HR Queue Reopen Rates Can and Cannot Measure', excerpt: 'A research model for separating genuine completion defects from new information, employee follow-up, policy changes, and system synchronization delays.', question: 'When does a reopened HR request indicate poor closeout quality, and when does it represent a legitimate new event?', method: 'This study applies internal-control and records-management concepts to queue events. It separates the original closeout evidence from later messages so the metric does not punish work for facts that did not yet exist.', finding: 'A raw reopen rate mixes several causes. It becomes useful after teams classify missing evidence, wrong routing, premature closure, new employee information, changed owner instruction, and delayed destination updates.', model: 'Keep the original request, close reason, evidence, close time, reopening event, cause code, owner review, and final resolution. Report defect-related reopens separately from new-event reopens and show the age of each unresolved item.', test: 'Review a bounced message, a corrected form submitted after closure, an owner who reverses approval, a payroll update that posts late, and a request closed without destination proof. Confirm that each case receives a different cause.', limits: 'Reopen rates do not measure employee satisfaction or legal compliance. Teams use different queue designs, and a low rate may reflect inaccessible support or aggressive closure rather than good service.', conclusion: 'A reopen metric needs an event history and a cause. The operational lesson comes from the reason the record returned, not from pushing the percentage toward zero.' },
  { slug: 'hr-approval-delegation-expiry-events', title: 'Approval Delegation Expiry Events in HR Workflows', excerpt: 'Research on the evidence needed when a temporary HR approver starts, acts, expires, or loses authority during an open request.', question: 'How should an HR support queue verify that a delegated approver still has authority at the moment of action?', method: 'The analysis translates access-control, governance, and records guidance into an event ledger for temporary approval authority. It focuses on verifiable dates and scope rather than job-title assumptions.', finding: 'A delegate list without effective times can authorize late or out-of-scope actions. The queue needs the delegator, delegate, permitted decisions, excluded decisions, start time, end time, revocation event, and source of authority.', model: 'Resolve each approval against the delegation record at the action timestamp. If authority has expired or the request falls outside its scope, freeze the administrative update and route it to the standing owner.', test: 'Simulate early revocation, overlapping delegates, a request submitted before expiry but approved afterward, a sensitive exception, and a delegate whose system access outlasts authority. Inspect both the queue and access record.', limits: 'An event ledger cannot establish whether delegation is lawful or appropriate. Organizations must set their own approval rules, and urgent cases may need a separate authorized path.', conclusion: 'Temporary approval should behave like a dated control, not a name copied into a spreadsheet. Expiry, revocation, and scope checks keep administrative speed from manufacturing decision authority.' },
  { slug: 'hr-reminder-recipient-drift', title: 'Recipient Drift in Automated HR Reminders', excerpt: 'Research on how manager changes, transfers, departures, and group-address edits can send routine HR reminders to the wrong person.', question: 'Which checks should run before an automated reminder reuses a recipient selected earlier in an HR workflow?', method: 'The study combines privacy minimization, access control, and records-management principles with a dependency model for scheduled messages. It examines address authority at send time.', finding: 'A valid recipient at intake may be invalid when the reminder fires. Long-running cases need a fresh check of role, employment status, manager relationship, group membership, message sensitivity, and alternate owner.', model: 'Store the intended recipient role separately from the resolved address. Before each send, resolve the current authorized person, compare it with the prior recipient, apply suppression rules, and retain the result of the check.', test: 'Test a manager transfer, departing approver, renamed distribution list, employee confidentiality flag, shared inbox owner change, and a reminder queued before an organizational update.', limits: 'Recipient validation cannot decide who should receive sensitive employment information. Directory data may lag, emergency communications may use different rules, and local privacy obligations vary.', conclusion: 'Scheduled reminders should revalidate authority close to send time. Separating the intended role from the current address makes recipient drift visible before a routine message becomes a privacy incident.' },
  { slug: 'hr-evidence-sampling-small-queues', title: 'Evidence Sampling for Small HR Support Queues', excerpt: 'A research approach to reviewing low-volume HR work when percentages are unstable and one missed exception can matter more than the monthly average.', question: 'How can a small HR team sample administrative work without treating a handful of cases as a reliable performance trend?', method: 'The analysis uses internal-control ideas to design a judgmental sample for small queues. It favors coverage of risk events and workflow stages over statistical claims that the available volume cannot support.', finding: 'Random sampling alone may miss the only sensitive exception in a small queue. A useful review includes routine cases plus every high-risk, overridden, reopened, late, or manually corrected record.', model: 'Divide the review into a fixed exception census and a rotating routine sample. Record the source check, access used, stop-rule behavior, owner response, destination confirmation, defect type, and corrective action for each item.', test: 'Apply the sample to queues with five, twelve, and thirty monthly records. Seed one privacy exception, one late approval, one destination mismatch, and one clean routine case, then check whether the method surfaces each risk.', limits: 'This design does not produce a statistically representative defect rate. Review effort must fit the sensitivity and volume of the queue, and the employer must define material exceptions.', conclusion: 'Small queues benefit from deliberate coverage rather than impressive percentages. Review every material exception and rotate the ordinary cases so the team can improve the workflow without overstating what the sample proves.' }
];

export const september2ResearchPosts: readonly ResearchPost[] = studies.map((study) => ({
  slug: study.slug,
  title: study.title,
  excerpt: study.excerpt,
  published: date,
  thumbnail,
  sections: [
    { heading: 'Research question', body: study.question },
    { heading: 'Evidence scope and method', body: study.method },
    { heading: 'Finding', body: study.finding },
    { heading: 'Operational model', body: study.model },
    { heading: 'Control test', body: study.test },
    { heading: 'Implementation boundary', body: 'A Philippines-based coordinator can maintain records, run approved comparisons, collect evidence, and route exceptions. The employer retains policy interpretation, access approval, employment decisions, sensitive communications, and corrective action.' },
    { heading: 'Limitations', body: study.limits },
    { heading: 'Evidence-led conclusion', body: study.conclusion }
  ],
  sources,
  serviceLink: { title: 'Apply the research to an HR support lane', href: '/services/reporting-and-qa', body: 'Turn the model into a narrow queue with a named owner, explicit data boundary, and review sample.' }
}));
