import type { ResearchPost } from '../fleet-data';

const checked = 'checked September 28, 2026';
const sources = [
  { name: `Privacy Framework 1.0 — NIST — ${checked}`, url: 'https://www.nist.gov/privacy-framework' },
  { name: `Cybersecurity Framework 2.0 — NIST — ${checked}`, url: 'https://www.nist.gov/cyberframework' },
  { name: `Digital Identity Guidelines SP 800-63-4 — NIST — ${checked}`, url: 'https://pages.nist.gov/800-63-4/' },
  { name: `Standards for Internal Control in the Federal Government (2025 Green Book) — U.S. GAO — ${checked}`, url: 'https://www.gao.gov/greenbook' },
  { name: `Recordkeeping Requirements — U.S. EEOC — ${checked}`, url: 'https://www.eeoc.gov/employers/recordkeeping-requirements' },
  { name: `Fact Sheet 21: Recordkeeping Requirements — U.S. Department of Labor — ${checked}`, url: 'https://www.dol.gov/agencies/whd/fact-sheets/21-flsa-recordkeeping' },
  { name: `Cybersecurity Program Best Practices — U.S. Department of Labor EBSA — ${checked}`, url: 'https://www.dol.gov/agencies/ebsa/key-topics/retirement-benefits/cybersecurity/best-practices' },
  { name: `Records Management — U.S. National Archives — ${checked}`, url: 'https://www.archives.gov/records-mgmt' },
] as const;

type Spec = {
  slug: string; title: string; excerpt: string; service: string;
  question: string; method: string; findings: string; population: string;
  workflow: string; challenge: string; evidence: string; measures: string;
  boundaries: string; implementation: string; conclusion: string;
};

const specs: readonly Spec[] = [
  {
    slug: 'hr-knowledge-base-answer-provenance-control',
    title: 'HR Knowledge-Base Answers: Prove Which Source Authorized the Reply',
    excerpt: 'A buyer-focused control model for keeping routine HR help-desk answers tied to approved, current source material without letting administrators invent policy.',
    service: 'hr-help-desk-support',
    question: 'When an outsourced HR help desk answers a recurring question, what proves that the response was authorized rather than merely plausible? The buyer needs more than a polished template. Each answer should trace to a named policy, plan document, system notice, approved script, or employer instruction; identify the version and effective date; state the audience and permitted channel; and show who approved the knowledge item. Search rank, prior use, or a coworker’s confidence cannot substitute for provenance. This distinction matters because a routine question can become consequential when facts differ, a document changes, or an employee asks for an interpretation.',
    method: 'We modeled a knowledge item as a controlled record, then walked it through drafting, approval, publication, retrieval, use, correction, retirement, and audit. The analysis compared NIST governance and privacy concepts, GAO internal-control principles, and federal employment-record guidance with the operational reality of a shared HR inbox. We tested ordinary requests alongside ambiguous identity, conflicting sources, future-effective changes, expired plans, missing language, inaccessible formats, and sensitive follow-up. No employee records or company performance data were used. The result is a control-design inference for buyers, not a claim that an agency prescribes a specific help-desk platform.',
    findings: 'Authoritative sources support several durable ideas: management defines responsibility; useful information must be reliable and communicated to the people who need it; access should reflect purpose and risk; and records must remain available under applicable rules. Applied to a help desk, those ideas favor a versioned answer register rather than an ungoverned folder of snippets. The register should distinguish verbatim approved language from an administrator’s routing note. It should also expose uncertainty. A source can be authentic yet inapplicable to the requester, location, worker class, plan year, or event. Provenance narrows the decision; it does not eliminate contextual review.',
    population: 'The inventory should include canned replies, macros, chatbot passages, intranet pages, email templates, call scripts, links, attachments, decision trees, translations, accessibility variants, and locally saved copies. Include draft, active, scheduled, superseded, suspended, and retired states. Reconcile what the platform displays with what agents can actually insert. Segment items by topic, audience, jurisdiction specified by the employer, source owner, effective window, sensitivity, permitted channel, and escalation trigger. Unknown-owner and no-source items stay visible as exceptions; deleting them from the inventory would make the apparent control stronger while leaving real exposure untouched.',
    workflow: 'At intake, verify the requester only to the level required for the requested information. Classify the question without copying unnecessary personal detail. Retrieve an active item using topic and audience, then compare the request with its assumptions and stop rules. Record the item identifier and version in the case, not a pasted private policy. If the fit is exact, send the approved language through the allowed channel and preserve delivery evidence. If facts are missing or the employee asks what a rule means for them, route a concise packet to the employer owner. Closure requires the sent version, destination, timestamp, and any unresolved follow-up.',
    challenge: 'Challenge tests should include two policies with similar names, a future-effective update, a retroactive correction, a broken source link, an employee outside the defined audience, a translation lag, a macro cached after retirement, and an answer that is correct generally but wrong for a particular plan. Test a compromised or mistakenly privileged account attempting to publish content. Test an urgent requester pressuring staff to improvise. The desired behavior is not always an answer; it is reliable recognition of the boundary. Reviewers should also search using common misspellings and employee language because a control that works only with the official title will fail in ordinary service.',
    evidence: 'Evidence should show the stable item ID, title, source title and owner, source location, version, effective and review dates, approver, audience, allowed channels, sensitivity, exact approved text or controlled link, related items, retirement reason, and change history. A usage record needs the case reference, chosen item version, actor, delivery channel, timestamp, exception state, and escalation owner. Keep the minimum case metadata in broad workflow tools and restricted source content in its approved repository. A screenshot can help diagnose a display problem but should not become the authoritative version. Preserve rejected drafts when they explain why a risky formulation was not released.',
    measures: 'Useful measures include the percentage of active items with a reachable authoritative source, overdue reviews, searches returning no approved result, stopped responses, uses of soon-to-expire items, retired-item insertion attempts, source-owner response time, corrections by root cause, and independently reconstructed samples. Measure by question family and risk, not only as a portfolio average. A high deflection rate can conceal wrong answers; a low response time can reward guessing. Pair speed with source fit and exception quality. For each metric publish its population, observation window, exclusions, unknowns, and definition version so trend claims remain reproducible.',
    boundaries: 'A Philippines-based coordinator can classify a request, retrieve controlled content, verify visible applicability fields, send approved wording, record evidence, and route exceptions. The coordinator should not interpret policy, decide eligibility, promise an outcome, modify plan language, select a jurisdiction, infer consent, diagnose a sensitive situation, or turn an owner’s one-off message into reusable guidance. Employer HR, benefits, legal, privacy, security, and system owners retain content approval, applicability, exceptions, investigations, and consequential communication. Cross-border delivery increases the importance of approved systems, minimum access, documented coverage windows, and a reachable employer decision owner.',
    implementation: 'Start with one high-volume, low-judgment question family. Name the content owner and backup; inventory every answer path; retire unsourced copies; and define required metadata. Configure read-only access for responders and separate publishing authority. Run synthetic cases across ordinary, missing-input, conflicting-source, wrong-audience, unavailable-owner, and sensitive-event paths. Observe a short pilot, then have a second reviewer reconstruct a stratified sample from source through sent reply. Expand only after retirement propagates to every insertion surface and stopped cases reach qualified owners. Re-test after policy, plan, platform, integration, access, staffing, or service-scope changes.',
    conclusion: 'Buyers should treat knowledge-base provenance as an operating control, not a documentation project. The test is whether another authorized reviewer can connect a real reply to the exact approved source and context without relying on private memory. Human Resources Outsourced can maintain the register, apply approved answers, preserve usage evidence, and surface exceptions. The employer remains accountable for what the source means, whom it covers, when it changes, and how sensitive cases are decided.'
  },
  {
    slug: 'outsourced-hr-data-deletion-request-evidence',
    title: 'Outsourced HR Data Deletion: Distinguish a Request From Verified Disposition',
    excerpt: 'A research model for tracking HR data disposition across systems, copies, holds, vendors, and exceptions without letting support staff decide what must be deleted.',
    service: 'employee-records-administration',
    question: 'What evidence should a buyer expect when an HR record reaches an approved disposition event? A ticket marked complete is insufficient. The process must distinguish the owner’s instruction, the record population, legal or operational holds, authoritative copies, working copies, backups, exports, vendor-held data, deletion or destruction method, system result, and residual exceptions. The central buyer decision is whether outsourced support can execute a bounded disposition workflow without deciding retention obligations. The answer depends on a precise inventory and explicit authorization, not on file age, storage pressure, or a requester’s informal message.',
    method: 'We treated disposition as a lifecycle control and traced records from collection through use, replication, retention review, authorization, execution, verification, and exception closure. NIST’s privacy materials describe processing as including retention, disclosure, and disposal; records authorities emphasize deliberate management; employment agencies publish retention requirements that vary by record and event. We mapped those principles to outsourced administration and tested normal expiry, litigation or charge-related preservation, unknown ownership, duplicate copies, vendor platforms, immutable backups, failed jobs, and restored data. This is operational research and not a retention schedule or legal conclusion for any employer.',
    findings: 'The sources establish why a universal delete-after period would be unreliable. Employment records can be subject to different preservation rules and event-based extensions. Privacy risk management calls for understanding data actions and ecosystem relationships. Internal control emphasizes documented responsibility, quality information, monitoring, and remediation. Our inference is that a safe support lane begins only after qualified owners approve the governing rule and specific population. Deletion success reported by one application does not prove that exports, synchronized folders, downstream vendors, archives, or recovery copies were handled. Conversely, a retained backup is not automatically a defect when the approved design restricts restoration and ages it out.',
    population: 'Build the population from systems of record, case platforms, file repositories, email and collaboration locations, managed transfers, analytics stores, local working areas, vendor portals, integrations, logs, archives, and backup classes that the employer identifies. Include active and former workers, applicants, dependents, beneficiaries, duplicates, corrupt items, rejected uploads, attachments, generated reports, derived fields, and failed deletion attempts. Segment by record class, subject, purpose, source, owner, location, copy type, retention trigger, approved rule, hold state, vendor, and technical method. Keep unknown locations and unclassified records in the denominator; absence from a register is not evidence of absence.',
    workflow: 'The workflow begins with an approved rule and a candidate population report, not immediate deletion. A coordinator assembles identifiers and locations without opening content unnecessarily. The record owner confirms scope; legal, HR, privacy, security, or other designated owners resolve holds and conflicts. A second authorized person reviews the execution list when consequence warrants it. The executor records tool, command or approved interface, timestamp, result, and exceptions. Verification re-queries the target and reconciles counts. Downstream owners acknowledge their portions. Closure separates confirmed disposition, scheduled backup aging, lawful retention, technical failure, missing owner, and disputed classification rather than collapsing all states into done.',
    challenge: 'Use synthetic records to test an active hold, a hold added after population creation, the same file under two names, a report containing several employees, an export created during the review window, a vendor record with no deletion API, a failed batch job, a restored backup, an inaccessible former administrator folder, and an item whose retention trigger was recorded incorrectly. Test that a worker cannot approve and execute their own high-risk batch. Test rollback only with non-sensitive synthetic data because real deletion should not be treated as casually reversible. The control passes when exceptions remain visible and unauthorized destruction is blocked.',
    evidence: 'The durable package should include policy or schedule identifier and version, approving owner, scope query, snapshot time, expected count, exclusions, hold checks, reviewer, executor, system-specific results, hashes or identifiers where appropriate, vendor acknowledgments, failures, retry linkage, backup treatment, exception owners, and closure approval. Do not copy whole records into the evidence packet. Hashes can help show file identity but do not prove authority, completeness, or secure destruction. System logs are stronger when tied to the approved population and independently reconciled. Preserve superseded instructions because they explain why an item moved from eligible to held or vice versa.',
    measures: 'Report eligible, approved, executed, verified, held, failed, unknown, and overdue counts separately. Track time in owner review, execution, vendor response, and exception resolution. Sample false inclusion and false exclusion risk rather than celebrating volume deleted. A high completion percentage is dangerous if the denominator excludes shadow copies; a low number may be appropriate when holds are common. Publish the as-of time, systems covered, backup assumptions, retention-rule version, and unresolved locations. Trend recurring failure causes and restored-data detections. Require a reviewer to reproduce selected counts from source inventories without relying on the executor’s spreadsheet.',
    boundaries: 'Support staff may prepare an inventory, run an approved query, execute a specifically authorized disposition step, preserve results, and monitor acknowledgments. They must not invent a retention period, interpret a legal hold, decide that a record is no longer needed, broaden a batch, delete to resolve a privacy complaint, waive vendor evidence, or promise complete erasure across unknown systems. Employer legal, HR, privacy, security, records, application, and vendor owners decide obligations, holds, methods, residual risk, employee communication, and closure. Access should be temporary and minimum necessary, with named accounts and a protected channel for any sensitive identifiers.',
    implementation: 'Pilot one well-defined record class in one system after owners approve the rule. Reconcile the population twice, seed synthetic edge cases, require dual review, and document safe stop conditions. Verify that exports and integrations do not recreate disposed data. Establish a vendor acknowledgment path before including vendor-hosted records. Conduct a post-run query and a later restoration check aligned with the approved backup design. Expand only when counts reconcile, exceptions have real owners, and the team can explain every state. Reassess after migrations, acquisitions, new integrations, policy changes, claims, investigations, or changes to backup and archival architecture.',
    conclusion: 'A deletion request is an instruction entering a governed process; it is not proof of disposition. Buyers need evidence that the right records were considered, protected holds were respected, authorized actions ran, and residual copies or failures remained visible. Human Resources Outsourced can support inventory, controlled execution, reconciliation, and exception tracking. The employer retains every legal, policy, privacy, security, and risk decision that determines whether disposition is permitted and complete.'
  },
  {
    slug: 'hr-work-queue-sampling-bias-control',
    title: 'HR Queue Quality Sampling: Detect the Cases Your Review Method Misses',
    excerpt: 'A decision-grade sampling design for HR support buyers who need evidence beyond easy closed tickets and average quality scores.',
    service: 'reporting-and-qa',
    question: 'Can a small quality sample support a decision about outsourced HR administration? Only if the buyer knows which cases had a chance to be selected and which did not. Convenience samples of recently closed, easily readable, or manager-selected tickets systematically miss stopped work, long-running cases, sensitive routes, reopened items, deleted spam classifications, transfers, and work completed outside the main platform. A quality percentage without a documented population, selection method, nonresponse treatment, and uncertainty is not decision-grade. The goal is not statistical theater; it is a repeatable review that exposes both ordinary execution and consequential tail cases.',
    method: 'We translated GAO concepts of reliable information, control activities, monitoring, and remediation into an operational sampling protocol, then used privacy and records principles to limit reviewer access and preserve selection evidence. The model compares probability-based selection for routine estimation with deliberate risk strata for rare or consequential cases. We challenged it using incomplete exports, changed classifications, excluded channels, tiny strata, reviewer disagreement, and cases that cannot be opened by a general reviewer. No employer dataset was analyzed, so the paper does not estimate an industry defect rate. It proposes a buyer test for whether a reported result can be reproduced and interpreted.',
    findings: 'Official frameworks do not prescribe one HR ticket sample size, and that absence is important. Sample design depends on the decision, population size, expected variation, tolerable uncertainty, risk, and available evidence. Internal-control guidance supports management responsibility for useful information and ongoing evaluation; privacy guidance supports purpose-limited processing. Our inference is that one sample should not serve every question. A random routine sample can estimate common execution attributes, while a separate risk sample can investigate sensitive, overdue, reopened, manually overridden, or cross-client cases. Combining those results into one percentage without weighting would misrepresent the population.',
    population: 'Define the unit before extraction: request, task, interaction, employee event, or closure. Fix the cohort and observation window. Include open-at-start, received, closed, reopened, merged, split, transferred, canceled, spam-classified, inaccessible, sensitive, and still-open items as the question requires. Reconcile platform counts with approved side channels and automation logs. Create strata by service lane, consequence, age, status, client boundary, sensitivity, worker, shift, system, exception type, and whether support controlled the outcome. Record exclusions with counts and reasons. If sensitive items require a qualified reviewer, keep them in the population and route their review rather than silently removing them.',
    workflow: 'Freeze a population extract and hash or otherwise identify it. Document selection code or steps, random seed when used, replacement rules, and the sample frame. Apply a versioned rubric that separates factual completeness, authority, privacy handling, execution accuracy, escalation, communication, and closure evidence. Reviewers mark not-applicable and insufficient-evidence rather than forcing pass or fail. A second reviewer independently scores a subset and resolves disagreements through rubric clarification, not quiet overwriting. Link corrections to the source case while minimizing copied personal information. Report routine and risk-stratum results separately, plus population coverage and cases unavailable for review.',
    challenge: 'Seed known conditions in synthetic cases: perfect easy closures, long blocked work, a fast unauthorized answer, a correct escalation with no closure, a reopened error, a duplicate, a cross-channel handoff, missing attachments, restricted content, an automation-created closure, and a high-volume worker. Confirm each has the intended selection probability or risk-stratum inclusion. Re-run selection to verify reproducibility. Have two reviewers score the same cases in a different order to detect ambiguity and fatigue. Test whether managers can substitute favorable cases after selection. Finally, trace sampled corrections into remediation and later retesting; finding defects without repair is observation, not control.',
    evidence: 'Retain the decision question, unit, cohort dates, source systems, extract timestamp, population reconciliation, fields used for stratification, exclusions, selection method, seed, sample IDs, rubric version, reviewer assignments, access restrictions, scores, evidence references, disagreements, adjudication, corrections, and retest results. Avoid exporting narrative or attachments unless the approved reviewer needs them. Store sensitive review notes in the protected case location and use neutral references in aggregate reports. Preserve the original score alongside any corrected score. A dashboard should link to the definition package so a later reviewer can determine whether a trend reflects quality change or merely a new population or rubric.',
    measures: 'Show population coverage, selection rates by stratum, unavailable-case rate, attribute results with denominators, reviewer agreement, correction aging, repeat defects, and retest outcomes. Use intervals or plain-language uncertainty when estimating from a random sample; do not present a point estimate as exact. Risk samples should report findings and coverage, not be mislabeled as population prevalence. Compare workers or clients only after examining case mix and sample balance. Publish small denominators and suppress breakdowns that create privacy or re-identification risk. The most valuable signal may be a cluster of unclear instructions rather than an individual score.',
    boundaries: 'An outsourced analyst can assemble the approved population, execute documented selection, prepare restricted review packets, apply objective rubric fields, record disagreements, and produce reproducible counts. They should not redefine quality after seeing results, infer misconduct, access sensitive narratives without authorization, rank employees from unbalanced samples, decide discipline, waive errors, or claim statistical significance without an appropriate design. Employer HR, legal, privacy, security, process, and people leaders own the review purpose, sensitive access, rubric judgments, remediation priority, employment consequences, and communication of results.',
    implementation: 'Begin with a single service lane and one decision, such as whether required approvals are present. Build the full frame, compare it with operational counts, and disclose gaps. Run a routine random sample and a separate risk sample. Calibrate reviewers on synthetic cases before real review, then double-score an initial subset. Present results with denominators, unknowns, disagreement, and examples stripped of personal detail. Repair the rubric or data pipeline when reviewers cannot reproduce outcomes. Expand only after remediation closes and retesting works. Rebaseline when channels, workflow states, automation, scope, staffing, or classification rules change.',
    conclusion: 'A quality sample earns trust through coverage and reproducibility, not through a reassuring score. Buyers should be able to see what could be selected, how cases were chosen, which evidence was unavailable, and how uncertainty affects the decision. Human Resources Outsourced can operate the mechanics of extraction, selection, evidence preparation, and reporting. The employer retains the judgments about acceptable quality, sensitive review, corrective action, and any consequence for people or vendors.'
  },
  {
    slug: 'outsourced-hr-service-continuity-recovery-test',
    title: 'Outsourced HR Service Continuity: Test Recovery With Real Queue States',
    excerpt: 'A practical research framework for proving that HR support can resume safely after platform, identity, connectivity, or staffing disruption.',
    service: 'operations-support',
    question: 'What does continuity mean for an outsourced HR support lane? It is not simply that an agent can log in after an outage. Safe recovery must preserve the last trustworthy queue state, protect sensitive information, identify work received during disruption, restore authorized access, reconcile duplicate or missed actions, reestablish owner communication, and prioritize by consequence rather than arrival alone. Buyers need to define the minimum service, maximum tolerable interruption, recovery dependencies, and decision authority for each lane. A generic vendor continuity statement cannot prove that a particular employer workflow will recover without unauthorized improvisation.',
    method: 'We decomposed service into intake, identity, source access, work state, decision-owner contact, execution, evidence, and closure, then applied NIST cybersecurity governance, identity assurance, privacy, and GAO internal-control principles. We used scenario analysis rather than observed incident data. Scenarios covered platform outage, identity-provider failure, loss of a region or device, unavailable employer owner, corrupted export, backlog surge, integration replay, and a handoff across shifts. The model distinguishes continuity from disaster recovery and incident response while recognizing their dependencies. It is buyer-oriented control research, not a promise of uptime or a substitute for technical testing by system owners.',
    findings: 'The sources support governance, named responsibility, protection, detection, response, recovery, reliable information, and monitoring. Applied to HR support, recovery is a business-state problem as well as a technical one. Restoring an application does not establish which requests were received, which changes committed, or which communications were sent. Strong authentication can fail closed during disruption, but bypassing it can create a larger event. Our inference is that each workflow needs a documented last-safe checkpoint and reconciliation procedure. Manual fallback should be deliberately narrow, time-limited, and capable of later import; an uncontrolled spreadsheet is not continuity.',
    population: 'Map every dependency: intake channels, identity provider, HRIS, case tool, document repository, communications, password or secret systems, integrations, vendor portals, network, managed devices, reporting, employer owners, backups, and time sources. Inventory work states including new, acknowledged, pending input, approved, executing, partially committed, sent, failed, reopened, and closed. Include scheduled jobs, webhooks, queued mail, offline notes, after-hours messages, and work spanning shifts. Segment lanes by consequence, data sensitivity, deadline source, reversibility, manual fallback eligibility, and owner availability. Unknown dependencies remain risks; do not infer resilience from an architecture diagram that omits people and vendors.',
    workflow: 'When disruption begins, record observed symptoms and time, stop actions whose state cannot be proven, and use the approved incident route. Protect the last reliable export or checkpoint. The employer owner activates the relevant continuity level and permitted fallbacks. During degraded work, assign stable IDs and capture minimum facts in the approved alternate system. On restoration, import or reconcile intake, compare before-and-after states, detect duplicates, verify partially executed actions, and route conflicts. Resume consequential steps only after authority and source state are revalidated. Closure requires backlog reconciliation, exception ownership, access rollback, evidence preservation, and a review of whether temporary channels retained data.',
    challenge: 'Run table-top and technical tests with synthetic cases. Interrupt a record update between approval and commit; deliver the same request through two channels; delay an integration acknowledgment; restore a stale queue snapshot; revoke an agent during the outage; make the primary employer owner unavailable; inject a sensitive request into a fallback channel; and recover near a shift boundary. Test clocks and time zones. Verify that staff do not guess whether an action completed. Measure whether every synthetic request lands in exactly one reconciled outcome. Include a test where fallback is correctly refused because privacy, authority, or evidence cannot be maintained.',
    evidence: 'The continuity package should identify service lane, scope, activation authority, dependency status, incident reference, last trustworthy checkpoint, affected interval, work inventory, fallback IDs, access changes, communications, decisions, reconciliation method, duplicates, missing items, partial transactions, restored state, exception owners, and closeout approval. Keep employee details in approved systems and report only minimum routing facts broadly. Logs need consistent time references. Screenshots can supplement but not replace machine state and case history. Preserve test results separately from real incidents, clearly labeled. Link corrective actions to owners, due dates, retests, and the plan version they change.',
    measures: 'Measure detection time, activation time, time to minimum service, time to reconciled service, backlog by consequence, duplicate and missing work, unverifiable transactions, fallback volume, privacy exceptions, owner reachability, access rollback, and corrective-action closure. Do not report uptime alone. A service can be technically available while its queue state is untrustworthy. Report distributions and oldest high-consequence cases rather than one average. State test assumptions, systems included, simulated failures, business hours, and exclusions. Trend repeated dependency failures and plan deviations, while separating a successful safe stop from a failure to process.',
    boundaries: 'Coordinators may observe and record disruption, protect the last safe state, follow an activated fallback, assign temporary references, communicate approved status, reconcile records, and surface conflicts. They may not declare an incident’s legal significance, bypass authentication, create unsanctioned storage, infer an approval, change priority rules, promise recovery times, or execute an irreversible action whose prior state is unknown. Employer HR, IT, security, privacy, legal, business-continuity, system, and vendor owners authorize activation, exceptions, communications, restoration acceptance, and risk decisions. Dedicated named accounts and managed devices remain required during degraded operations.',
    implementation: 'Choose one lane with clear state transitions. Document dependencies and the minimum service; define last-safe checkpoints; prepare synthetic cases; and confirm employer owner coverage. Run a table-top first, repair unclear authority, then conduct a bounded technical exercise in an approved environment. Reconcile every test item and require an independent reviewer to reproduce the outcome. Record gaps without editing history. Test again after remediation. Expand to other lanes only when fallback data can be protected and imported, owners are reachable, and temporary access reliably rolls back. Repeat after material system, vendor, identity, workflow, staffing, or scope change.',
    conclusion: 'Continuity is proven by accurate recovery of work state and authority, not by a plan document or restored login screen. Buyers should require tests that expose duplicates, missing events, partial actions, unsafe fallbacks, and owner dependencies. Human Resources Outsourced can maintain operational checkpoints, execute approved degraded procedures, reconcile queues, and document exceptions. Employer and technical owners retain activation, security, privacy, deadline, prioritization, and recovery-acceptance decisions.'
  },
  {
    slug: 'hr-outsourcing-responsibility-matrix-control-test',
    title: 'HR Outsourcing Responsibility Matrices: Test Decisions, Not Just Task Names',
    excerpt: 'A control test for separating employer authority, provider preparation, execution, review, and escalation in outsourced HR workflows.',
    service: 'admin-support',
    question: 'Why do detailed outsourcing scopes still produce ownership gaps? Task labels such as onboarding support, records administration, or reporting collapse several different acts: receiving facts, checking completeness, interpreting rules, approving a decision, changing a system, communicating with a worker, reviewing evidence, and accepting risk. A responsibility matrix is useful only when it maps those acts to named roles and tells staff what to do when the owner is absent or sources conflict. Buyers should test the matrix against real decision points rather than assume that one responsible-and-accountable table cell governs the whole workflow.',
    method: 'We broke five common HR administration patterns into event-level decisions and examined them through GAO internal-control principles, NIST governance and identity concepts, privacy-risk management, federal recordkeeping guidance, and service-provider security materials. Scenarios included routine onboarding, a payroll-related correction, sensitive inbox intake, employee-record filing, and recurring reporting. We then varied owner availability, requester authority, source conflict, system access, client boundary, and urgency. This qualitative design does not determine legal responsibility or recommend a universal organization chart. It provides a method for buyers to reveal ambiguous delegation before production work begins.',
    findings: 'Authoritative frameworks consistently emphasize management responsibility, appropriate authority, reliable information, access control, communication, monitoring, and remediation. Provider oversight does not erase the organization’s own responsibility. Our inference is that a safe matrix must name preparation, decision, approval, execution, review, communication, exception, and closure separately. Accountable cannot be a ceremonial executive who is unreachable at the moment of action. Consulted cannot mean silent approval, and informed cannot mean that sensitive data is copied widely. Access granted by a system is also not proof that the person is authorized for every action the interface permits.',
    population: 'Inventory recurring tasks, ad hoc requests, scheduled jobs, automations, integrations, reports, file transfers, employee communications, vendor interactions, and exception routes. For each, list triggers, inputs, decisions, systems, data classes, outputs, deadlines supplied by owners, and evidence. Include work currently done through email or personal knowledge. Map primary and backup owners by shift and absence. Segment by client, worker population, consequence, reversibility, sensitivity, location, system, and whether a professional judgment is required. Keep unowned and multi-owned decisions visible. A scope document that lists deliverables but omits exception decisions is not a complete population.',
    workflow: 'Convert each workflow into stages. At intake, verify identity, authority, purpose, and minimum data. During preparation, check completeness against an approved checklist without deciding meaning. At decision, route a concise packet to the authorized employer owner. At execution, apply only the specific approved action in the designated system. At review, compare the result with the instruction and authoritative state. Communication uses approved content and audience. Closure requires evidence and unresolved exceptions. The matrix should specify who may act, who must not, the backup, response expectation, safe holding action, escalation path, and whether silence ever has meaning; ordinarily it does not.',
    challenge: 'Test with a missing primary owner, two owners giving conflicting instructions, a manager outside the authorized population, an urgent request near a cutoff, a coordinator whose system role is broader than scope, a vendor asking for extra fields, a decision delivered in chat, a cross-client attachment, a reversed approval, and a task partially completed before an instruction changes. Ask every participant to state who can act next and what evidence is required. If answers differ, the matrix is not operational. Repeat during a shift handoff and planned absence. Verify backup authority in the real systems, not only on paper.',
    evidence: 'A durable responsibility record should include workflow and version, stage, action, decision type, primary role, named current owner, backup, requester requirements, source authority, allowed systems, access profile, prohibited actions, escalation trigger, response expectation, holding action, evidence required, reviewer, communication owner, and effective date. Link approvals to specific transactions rather than maintaining a generic blanket approval. Preserve changed assignments and temporary delegations with start and end times. Review evidence should show whether actual actors matched the matrix. Store sensitive source details in restricted systems and expose only neutral task references to broad operational dashboards.',
    measures: 'Measure unowned stages, missing backups, owner response by decision type, packets returned incomplete, conflicting instructions, actions attempted outside scope, access-to-scope mismatches, temporary delegations past expiry, rework caused by ownership ambiguity, safe stops, and review exceptions. A low escalation rate is not automatically good; it may indicate guessing. A high stop rate may reveal poor scope or weak owner coverage. Report the population and period, distinguish provider-controlled time from owner waiting, and review the oldest consequential cases. Sample completed work to compare actual actor, approval, system event, and reviewer with the current matrix.',
    boundaries: 'An outsourced coordinator can prepare task packets, apply completeness rules, execute authorized clerical steps, maintain factual states, send approved communications, and preserve evidence. The role should not determine eligibility, interpret law or policy, make employment or compensation decisions, approve its own work, accept privacy or security risk, override an employer owner, or broaden disclosure. Employer leaders must appoint reachable HR, payroll, benefits, recruiting, legal, privacy, security, finance, and system owners appropriate to each lane. Cross-border teams need explicit work windows, holiday coverage, secure channels, and end-of-shift transfers; location never creates or removes decision authority.',
    implementation: 'Start with a consequential but bounded workflow and observe how it actually operates. Interview the people performing each stage, compare their answers with system permissions and artifacts, and draft an event-level matrix. Run synthetic ordinary and exception cases, including absent owners and conflicting sources. Remove unnecessary access and establish time-limited delegation. Pilot with daily review, then have an independent person reconstruct selected cases. Repair ownership gaps before increasing volume. Revisit the matrix after policy, system, vendor, staffing, organizational, client, or service changes, and whenever a real event reveals a decision that the model did not name.',
    conclusion: 'A responsibility matrix controls work only when it resolves the next real decision under pressure. Buyers should expect named, reachable authority; narrow execution permissions; visible exceptions; and evidence that actual behavior matched the model. Human Resources Outsourced can maintain the workflow map, prepare decision packets, perform approved administration, and report ownership gaps. Employer owners remain accountable for rules, consequential decisions, exceptions, sensitive communications, and accepted risk.'
  }
] as const;

const limitations = 'Limitations and uncertainty: the cited public materials provide governance, privacy, security, internal-control, and recordkeeping reference points, but they do not prescribe this exact outsourced workflow. Applicability depends on the employer, workforce, jurisdiction, contracts, plans, systems, facts, and current law. We did not audit an employer or provider, observe outcomes, estimate market prevalence, or test a production environment. Scenario tests can reveal design weaknesses but cannot anticipate every failure. Source pages and agency guidance can change after the checked date. Buyers should obtain qualified legal, privacy, security, benefits, payroll, records, accessibility, labor, and technical review where the decision requires it.';
const buyerChecklist = 'Before launch, the buyer should be able to answer twelve practical questions: What event starts the work? Which source is authoritative? Who may request it? Who decides? Who executes? Who independently reviews it? Which systems and data are permitted? What evidence proves each state? Which conditions require a stop? Who is the reachable backup owner? How are corrections linked without erasing history? What change forces the control to be tested again? Record the answers in the working procedure and compare them with actual permissions, templates, integrations, reports, and staff behavior. A contractual scope alone cannot answer these operating questions. If any answer depends on personal memory, an unnamed manager, a broad shared account, or an undocumented side channel, keep the workflow in pilot and assign an owner to repair the gap. Buyers should also confirm that review access is narrower than production access where practical, that sensitive examples use synthetic data, and that the service can preserve a safe state while awaiting an employer decision.';

export const september28ResearchPosts: readonly ResearchPost[] = specs.map((spec) => ({
  slug: spec.slug,
  title: spec.title,
  excerpt: spec.excerpt,
  published: '2026-09-28',
  sections: [
    { heading: 'Research question and buyer decision', body: spec.question },
    { heading: 'Methodology', body: spec.method },
    { heading: 'What the sources support—and what is our inference', body: spec.findings },
    { heading: 'Population and denominator', body: spec.population },
    { heading: 'Operating workflow', body: spec.workflow },
    { heading: 'Challenge cases', body: spec.challenge },
    { heading: 'Evidence model', body: spec.evidence },
    { heading: 'Measures for buyer review', body: spec.measures },
    { heading: 'Role boundaries and escalation', body: spec.boundaries },
    { heading: 'Implementation sequence', body: spec.implementation },
    { heading: 'Buyer readiness checklist', body: buyerChecklist },
    { heading: 'Limitations and uncertainty', body: limitations },
    { heading: 'Conclusion', body: spec.conclusion },
  ],
  sources,
  serviceLink: {
    title: 'Connect this control to a bounded support scope',
    href: `/services/${spec.service}`,
    body: 'Review the related service lane while keeping employer decisions, sensitive exceptions, and risk ownership explicit.'
  }
}));
